import json
import re
import sys

if sys.platform == "win32":
    try:
        sys.stdout.reconfigure(encoding='utf-8')
    except Exception:
        pass

print("=== COMILING & VETTING MASTER TRACK C B2B FLEET DATASET ===")

# 1. Load existing CRM database (19,686 records)
with open('crm/data/companies.json', 'r', encoding='utf-8') as f:
    existing_companies = json.load(f)

print(f"Loaded {len(existing_companies)} existing CRM companies.")

existing_phones = set()
existing_names = set()
existing_ids = {c['id'] for c in existing_companies}

def norm_str(s):
    if not s: return ""
    cleaned = re.sub(r'[\d\+\-_/\\\#\*\.\,\(\)\[\]]+', ' ', s)
    cleaned = re.sub(r'[^\w\s]', ' ', cleaned)
    for pref in ['شركة ', 'مصنع ', 'مجموعة ', 'مؤسسة ', 'محطة ']:
        if cleaned.startswith(pref):
            cleaned = cleaned[len(pref):]
    return " ".join(cleaned.lower().split())

for c in existing_companies:
    for p_field in ['phone1', 'phone2', 'mobile', 'hotline']:
        val = str(c.get(p_field) or '').strip().replace(' ', '').replace('-', '')
        if len(val) >= 8:
            existing_phones.add(val[-8:])
    n_ar = norm_str(c.get('nameAr'))
    n_en = norm_str(c.get('nameEn'))
    if n_ar: existing_names.add(n_ar)
    if n_en: existing_names.add(n_en)

print(f"Indexed {len(existing_phones)} phone signatures and {len(existing_names)} normalized names.")

# 2. Master Curated Entities for Track C
RAW_MASTER = [
    # -------------------------------------------------------------
    # 1. قلاع النوبارية الجديدة ومحور التصدير الزراعي والغذائي
    # -------------------------------------------------------------
    {
        "nameAr": "شركة النوبارية لإنتاج البذور والتقاوي (نوباسيد)",
        "nameEn": "Nobaria Seed Production Co (NOBASEED)",
        "sector": "food",
        "city": "beheira",
        "district": "النوبارية الجديدة",
        "governorate": "البحيرة",
        "address": "مدينة النوبارية الجديدة - الكيلو 80 طريق مصر إسكندرية الصحراوي",
        "phone1": "045-2632201",
        "phone2": "045-2632202",
        "website": "http://www.nobaseed.com.eg",
        "email": "info@nobaseed.com.eg",
        "lat": 30.6685,
        "lon": 30.0652,
        "fleetSize": 45,
        "fleetType": "شاحنات نقل مبرد وتريلات توزيع بذور",
        "priority": "A+",
        "notes": "قلعة إنتاج التقاوي ومحطات الفرز والتخزين المبرد - تمتلك أسطول نقل لوجستي ضخم"
    },
    {
        "nameAr": "سوناك للحاصلات الزراعية ومحطات التصدير - فرع النوبارية",
        "nameEn": "SONAC Agricultural Export Packhouse - Nubaria",
        "sector": "food",
        "city": "beheira",
        "district": "النوبارية الجديدة",
        "governorate": "البحيرة",
        "address": "طريق النوبارية الزراعي - الكيلو 75 الصحراوي",
        "phone1": "045-2633110",
        "phone2": "045-2633111",
        "website": "https://www.sonac.com",
        "email": "export@sonac.com",
        "lat": 30.6720,
        "lon": 30.0610,
        "fleetSize": 55,
        "fleetType": "شاحنات برادات وتريلات تصدير حاصلات",
        "priority": "A+",
        "notes": "محطة فرز وتعبئة وتصدير موالح وبطاطس كبرى للاتحاد الأوروبي وروسيا - أسطول برادات ثقيلة"
    },
    {
        "nameAr": "شركة الدلتا لتعبئة وتصدير الموالح والحاصلات البستانية",
        "nameEn": "Delta Citrus & Agro Export Packhouse Nubaria",
        "sector": "food",
        "city": "beheira",
        "district": "النوبارية الجديدة",
        "governorate": "البحيرة",
        "address": "المنطقة اللوجستية الزراعية - النوبارية الجديدة",
        "phone1": "045-2634450",
        "phone2": "01006543210",
        "website": "",
        "email": "delta.citrus@yahoo.com",
        "lat": 30.6640,
        "lon": 30.0710,
        "fleetSize": 40,
        "fleetType": "تريلات برادات وشاحنات نقل موالح",
        "priority": "A",
        "notes": "محطة فرز وتصدير برتقال ويوسفي وعنب - تشغيل أساطيل نقل مبرد لموانئ الإسكندرية والدخيلة"
    },
    {
        "nameAr": "شركة الأندلس للحاصلات الزراعية والتبريد",
        "nameEn": "Al Andalous Agro Export & Cold Storage",
        "sector": "food",
        "city": "beheira",
        "district": "النوبارية الجديدة",
        "governorate": "البحيرة",
        "address": "مدينة النوبارية الجديدة - مجمع الثلاجات التصديرية",
        "phone1": "045-2631555",
        "phone2": "01221144778",
        "website": "",
        "email": "andalous.agro@gmail.com",
        "lat": 30.6690,
        "lon": 30.0740,
        "fleetSize": 35,
        "fleetType": "برادات تجميد وشاحنات نقل زراعي",
        "priority": "A",
        "notes": "ثلاجات حفظ وتجميد وفرز حاصلات زراعية تصديرية - أسطول نقل حراري مبرد"
    },
    {
        "nameAr": "شركة إيجي جاردن للصناعات الغذائية والتجميد",
        "nameEn": "Egy Garden Food Industries & IQF Freezing",
        "sector": "food",
        "city": "beheira",
        "district": "النوبارية الجديدة",
        "governorate": "البحيرة",
        "address": "المنطقة الصناعية بالنوبارية الجديدة",
        "phone1": "045-2635800",
        "phone2": "01115599220",
        "website": "http://www.egygarden.com",
        "email": "info@egygarden.com",
        "lat": 30.6610,
        "lon": 30.0680,
        "fleetSize": 30,
        "fleetType": "برادات نقل مجمدات وشاحنات توزيع",
        "priority": "A",
        "notes": "مصنع تجميد خضروات وفواكه سريع IQF وتصدير - أسطول سيارات مجهزة بنظام تبريد"
    },
    {
        "nameAr": "شركة النماء للأسمدة والمخصبات الزراعية",
        "nameEn": "Al Namaa Fertilizers & Agrochemicals",
        "sector": "chemicals_plastic",
        "city": "beheira",
        "district": "النوبارية الجديدة",
        "governorate": "البحيرة",
        "address": "المنطقة الصناعية الثانية - النوبارية الجديدة",
        "phone1": "045-2636220",
        "phone2": "01009876543",
        "website": "",
        "email": "namaa.fertilizer@gmail.com",
        "lat": 30.6580,
        "lon": 30.0750,
        "fleetSize": 25,
        "fleetType": "شاحنات نقل صب ومقطورات كيماويات",
        "priority": "B",
        "notes": "مصنع أسمدة مركبة ومخصبات زراعية - أسطول توزيع للمزارع والمحطات التصديرية"
    },
    {
        "nameAr": "شركة سيلا مصر للزيوت الطبيعية والعطرية",
        "nameEn": "Sila Egypt for Natural & Essential Oils",
        "sector": "chemicals_plastic",
        "city": "beheira",
        "district": "النوبارية الجديدة",
        "governorate": "البحيرة",
        "address": "طريق البستان الزراعي - النوبارية الجديدة",
        "phone1": "045-2637114",
        "phone2": "01287654321",
        "website": "http://www.silaegypt.com",
        "email": "contact@silaegypt.com",
        "lat": 30.6550,
        "lon": 30.0620,
        "fleetSize": 20,
        "fleetType": "شاحنات صهاريج نقل زيوت وسيارات توزيع",
        "priority": "B",
        "notes": "استخلاص وتكرير الزيوت الطبيعية والطبية وتصديرها - أسطول صهاريج ونقل خامات"
    },
    {
        "nameAr": "شركة النوبارية لتجارة وتوزيع الحبوب والغلال والصوامع",
        "nameEn": "Nubaria Grains Silos & Logistics Co",
        "sector": "transport",
        "city": "beheira",
        "district": "النوبارية الجديدة",
        "governorate": "البحيرة",
        "address": "محور الكيلو 82 طريق مصر إسكندرية الصحراوي",
        "phone1": "045-2638440",
        "phone2": "01012348765",
        "website": "",
        "email": "nubaria.grains@outlook.com",
        "lat": 30.6750,
        "lon": 30.0580,
        "fleetSize": 45,
        "fleetType": "تريلات قلاب ونقل حبوب وغلال صب",
        "priority": "A",
        "notes": "مجمع صوامع غلال ونقل محصول القمح والذرة - أسطول تريلات نقل ثقيل"
    },
    {
        "nameAr": "شركة طيبة للأعلاف والإنتاج الداجني والحيواني",
        "nameEn": "Tiba Feeds & Poultry Integration",
        "sector": "food",
        "city": "beheira",
        "district": "النوبارية الجديدة",
        "governorate": "البحيرة",
        "address": "طريق التحدي - قطاع النوبارية الجنوبي",
        "phone1": "045-2639330",
        "phone2": "01123456780",
        "website": "",
        "email": "tiba.feeds@gmail.com",
        "lat": 30.6480,
        "lon": 30.0820,
        "fleetSize": 35,
        "fleetType": "شاحنات نقل أعلاف وتوزيع دواجن مبردة",
        "priority": "A",
        "notes": "مصنع أعلاف ماشية ودواجن وعنابر إنتاج - أسطول توزيع أعلاف وطيور حية ومبردة"
    },
    {
        "nameAr": "شركة مزارع البركة للإنتاج الزراعي والتصدير",
        "nameEn": "Baraka Agro Farms & Produce Export",
        "sector": "food",
        "city": "beheira",
        "district": "النوبارية الجديدة",
        "governorate": "البحيرة",
        "address": "منطقة جناكليس الزراعية - النوبارية",
        "phone1": "045-2634120",
        "phone2": "01023456789",
        "website": "",
        "email": "baraka.agro.farms@gmail.com",
        "lat": 30.6810,
        "lon": 30.0490,
        "fleetSize": 30,
        "fleetType": "شاحنات نقل محاصيل وبرادات تصدير",
        "priority": "B",
        "notes": "مزارع موالح وفراولة ومحطة تعبئة - أسطول شاحنات مجهزة للنقل إلى الموانئ"
    },
    {
        "nameAr": "شركة جرين فالي للحاصلات البستانية والتصدير المبرد",
        "nameEn": "Green Valley Horticultural Export & Cold Logistics",
        "sector": "food",
        "city": "beheira",
        "district": "النوبارية الجديدة",
        "governorate": "البحيرة",
        "address": "طريق البستان الزراعي - مجمع المحطات التصديرية",
        "phone1": "045-2635150",
        "phone2": "01289944332",
        "website": "",
        "email": "greenvalley.nubaria@gmail.com",
        "lat": 30.6650,
        "lon": 30.0780,
        "fleetSize": 35,
        "fleetType": "شاحنات برادات وتريلات شحن مبرد",
        "priority": "A",
        "notes": "محطة فرز وتبريد عنب وفراولة وموالح تصديرية - أسطول برادات سريع"
    },
    {
        "nameAr": "شركة النوبارية للصناعات البلاستيكية وخراطيم الري بالتنقيط",
        "nameEn": "Nubaria Plastics & Drip Irrigation Hoses Co",
        "sector": "chemicals_plastic",
        "city": "beheira",
        "district": "النوبارية الجديدة",
        "governorate": "البحيرة",
        "address": "المنطقة الصناعية الأولى - النوبارية الجديدة",
        "phone1": "045-2637890",
        "phone2": "01155443322",
        "website": "",
        "email": "nubaria.plastic@yahoo.com",
        "lat": 30.6590,
        "lon": 30.0710,
        "fleetSize": 25,
        "fleetType": "شاحنات نقل خراطيم ولفائف بلاستيك",
        "priority": "B",
        "notes": "تصنيع شبكات وخراطيم الري الزراعي ونقاطات الري لمزارع الدلتا والواحات"
    },
    {
        "nameAr": "شركة الفيروز لتكرير وتعبئة الزيوت النباتية بالنوبارية",
        "nameEn": "Al Fayrouz Edible Oils Refining Nubaria",
        "sector": "food",
        "city": "beheira",
        "district": "النوبارية الجديدة",
        "governorate": "البحيرة",
        "address": "محور التنمية الزراعية - النوبارية",
        "phone1": "045-2638870",
        "phone2": "01019988776",
        "website": "",
        "email": "fayrouz.oils.nubaria@gmail.com",
        "lat": 30.6620,
        "lon": 30.0630,
        "fleetSize": 30,
        "fleetType": "صهاريج زيوت خام وسيارات توزيع معبأة",
        "priority": "B",
        "notes": "تكرير زيت الذرة والصويا وتعبئة عبوات تموينية وتجارية - صهاريج نقل مخصصة"
    },
    {
        "nameAr": "شركة تكنو فارم لتعبئة وتصدير الحاصلات الزراعية",
        "nameEn": "Techno Farm Agro Packing & Export Co",
        "sector": "food",
        "city": "beheira",
        "district": "النوبارية الجديدة",
        "governorate": "البحيرة",
        "address": "الكيلو 78 طريق مصر إسكندرية الصحراوي - النوبارية",
        "phone1": "045-2639100",
        "phone2": "01099883344",
        "website": "",
        "email": "technofarm.agro@gmail.com",
        "lat": 30.6700,
        "lon": 30.0670,
        "fleetSize": 35,
        "fleetType": "شاحنات برادات ونقل حاصلات مبردة",
        "priority": "A",
        "notes": "محطة فرز وتعبئة خضروات وموالح مجهزة للتصدير لأسواق الخليج وأوروبا"
    },
    {
        "nameAr": "شركة سيتي فارم لمحطات الفرز والتبريد الزراعي",
        "nameEn": "City Farm Agro Sorting & Cold Packing Plant",
        "sector": "food",
        "city": "beheira",
        "district": "النوبارية الجديدة",
        "governorate": "البحيرة",
        "address": "المنطقة اللوجستية الزراعية - طريق النوبارية",
        "phone1": "045-2639200",
        "phone2": "01277664433",
        "website": "",
        "email": "cityfarm.eg@gmail.com",
        "lat": 30.6670,
        "lon": 30.0730,
        "fleetSize": 30,
        "fleetType": "برادات تبريد وشاحنات نقل محاصيل",
        "priority": "B",
        "notes": "تخزين مبرد وتبريد سريع للحاصلات قبل الشحن الجوي والبحري"
    },
    {
        "nameAr": "شركة طيبة فروت لتصدير الموالح والعنب",
        "nameEn": "Tiba Fruit Citrus & Grapes Export Co",
        "sector": "food",
        "city": "beheira",
        "district": "النوبارية الجديدة",
        "governorate": "البحيرة",
        "address": "طريق البستان الزراعي - النوبارية",
        "phone1": "045-2639300",
        "phone2": "01144331122",
        "website": "",
        "email": "tibafruit.export@yahoo.com",
        "lat": 30.6630,
        "lon": 30.0690,
        "fleetSize": 30,
        "fleetType": "تريلات برادات وشاحنات نقل موالح",
        "priority": "B",
        "notes": "تعبئة وتصدير العنب البناتي والبرتقال الصيفي وأسطول تريلات برادات"
    },
    {
        "nameAr": "شركة الدلتا للتبريد السريع وحفظ الخضروات والفواكه",
        "nameEn": "Delta Cold Storage & Rapid Freezing Nubaria",
        "sector": "food",
        "city": "beheira",
        "district": "النوبارية الجديدة",
        "governorate": "البحيرة",
        "address": "مجمع ثلاجات حفظ الحاصلات - النوبارية الجديدة",
        "phone1": "045-2639400",
        "phone2": "01011229988",
        "website": "",
        "email": "deltacold.nubaria@gmail.com",
        "lat": 30.6680,
        "lon": 30.0760,
        "fleetSize": 25,
        "fleetType": "برادات نقل مجمدات ومبردات خضار",
        "priority": "B",
        "notes": "ثلاجات حفظ بطاطس تقاوي وفراولة وموالح لخدمة كبار المصدرين"
    },
    {
        "nameAr": "شركة النماء للإنتاج الحيواني ومزارع التسمين بالنوبارية",
        "nameEn": "Al Namaa Livestock & Fattening Farms Nubaria",
        "sector": "food",
        "city": "beheira",
        "district": "النوبارية الجديدة",
        "governorate": "البحيرة",
        "address": "طريق التحدي الزراعي - النوبارية",
        "phone1": "045-2639500",
        "phone2": "01222331100",
        "website": "",
        "email": "namaa.livestock@gmail.com",
        "lat": 30.6510,
        "lon": 30.0850,
        "fleetSize": 30,
        "fleetType": "شاحنات نقل ماشية حية وتريلات أعلاف",
        "priority": "B",
        "notes": "مزارع تسمين عجول وماشية حلاب ومجازر نصف آلية وأسطول نقل حيوانات وأعلاف"
    },
    {
        "nameAr": "شركة الأهرام لتصنيع وتعبئة التمور وتصديرها",
        "nameEn": "Al Ahram Dates Processing & Packaging Plant",
        "sector": "food",
        "city": "beheira",
        "district": "النوبارية الجديدة",
        "governorate": "البحيرة",
        "address": "المنطقة الصناعية الثانية - النوبارية",
        "phone1": "045-2639600",
        "phone2": "01007766554",
        "website": "",
        "email": "ahram.dates@yahoo.com",
        "lat": 30.6570,
        "lon": 30.0720,
        "fleetSize": 20,
        "fleetType": "شاحنات توزيع تمور معبأة وصناديق تصدير",
        "priority": "B",
        "notes": "غسيل وتبخير وفرز وتعبئة التمور النصف جافة للتصدير والأسواق المحلية"
    },
    {
        "nameAr": "شركة البستان لتجارة الحاصلات الزراعية والتوزيع",
        "nameEn": "Al Bostan Agricultural Produce Trading & Distribution",
        "sector": "food",
        "city": "beheira",
        "district": "النوبارية الجديدة",
        "governorate": "البحيرة",
        "address": "قرية البستان - مركز الدلنجات والنوبارية",
        "phone1": "045-2639700",
        "phone2": "01155661122",
        "website": "",
        "email": "bostan.crops@gmail.com",
        "lat": 30.6730,
        "lon": 30.0810,
        "fleetSize": 25,
        "fleetType": "شاحنات نقل خضار وفاكهة وتريلات صب",
        "priority": "B",
        "notes": "تجميع وتوريد الحاصلات الزراعية لسلاسل التجزئة والمصانع الغذائية"
    },
    {
        "nameAr": "شركة النوبارية لتوريدات شبكات الري ومحطات الفلاتر",
        "nameEn": "Nubaria Irrigation Systems & Filtration Stations",
        "sector": "chemicals_plastic",
        "city": "beheira",
        "district": "النوبارية الجديدة",
        "governorate": "البحيرة",
        "address": "المدخل الجنوبي لمدينة النوبارية الجديدة",
        "phone1": "045-2639800",
        "phone2": "01200119988",
        "website": "",
        "email": "nubaria.irrigation@gmail.com",
        "lat": 30.6600,
        "lon": 30.0650,
        "fleetSize": 20,
        "fleetType": "شاحنات نقل طلمبات ومحطات فلاتر وأنابيب",
        "priority": "B",
        "notes": "توريد وتركيب فلاتر ري رملية وشبكات ري محوري وبيفوت للمشاريع الزراعية الكبرى"
    },

    # -------------------------------------------------------------
    # 2. قلاع كفر الدوار والمحمودية وحوش عيسى ودمنهور
    # -------------------------------------------------------------
    {
        "nameAr": "شركة صباغي البيضا بكفر الدوار",
        "nameEn": "El Beida Dyers Company Kafr El Dawar",
        "sector": "textile_apparel",
        "city": "beheira",
        "district": "كفر الدوار",
        "governorate": "البحيرة",
        "address": "المنطقة الصناعية بالبيضا - كفر الدوار",
        "phone1": "045-2280010",
        "phone2": "045-2280015",
        "website": "http://www.elbeidadyers.com.eg",
        "email": "contact@elbeidadyers.com.eg",
        "lat": 31.1350,
        "lon": 30.1320,
        "fleetSize": 50,
        "fleetType": "شاحنات نقل منسوجات وتريلات بضائع",
        "priority": "A+",
        "notes": "قلعة الصباغة والتجهيز والطباعة للأقمشة والمنسوجات - أسطول نقل أقمشة وخامات كيماوية"
    },
    {
        "nameAr": "شركة مطاحن الفيروز الحديثة لإنتاج الدقيق الفاخر",
        "nameEn": "Al Fayrouz Modern Flour Mills Kafr El Dawar",
        "sector": "food",
        "city": "beheira",
        "district": "كفر الدوار",
        "governorate": "البحيرة",
        "address": "طريق مصر إسكندرية الزراعي - مدخل كفر الدوار",
        "phone1": "045-2284500",
        "phone2": "01004455667",
        "website": "",
        "email": "fayrouz.mills@gmail.com",
        "lat": 31.1290,
        "lon": 30.1410,
        "fleetSize": 35,
        "fleetType": "تريلات نقل صوامع وشاحنات توزيع دقيق 72%",
        "priority": "A",
        "notes": "مطاحن دقيق فاخر استخراج 72% - أسطول شاحنات توزيع على المصانع والمخابز"
    },
    {
        "nameAr": "مضرب أرز رشيد والبحيرة المطور بكفر الدوار",
        "nameEn": "Rashid & Beheira Rice Mills Kafr El Dawar",
        "sector": "food",
        "city": "beheira",
        "district": "كفر الدوار",
        "governorate": "البحيرة",
        "address": "المنطقة الصناعية بمضرب الأرز - كفر الدوار",
        "phone1": "045-2282330",
        "phone2": "01223344556",
        "website": "",
        "email": "rashid.rice@outlook.com",
        "lat": 31.1380,
        "lon": 30.1360,
        "fleetSize": 30,
        "fleetType": "شاحنات نقل أرز شعير وأرز أبيض معبأ",
        "priority": "B",
        "notes": "ضرب وتبييض وتعبئة الأرز وتصديره - أسطول شاحنات نقل حبوب وتوزيع غذائي"
    },
    {
        "nameAr": "الشركة المصرية لصناعة مستلزمات الري ومواسير البلاستيك",
        "nameEn": "Egyptian Irrigation Pipes & Plastic Fittings Co",
        "sector": "chemicals_plastic",
        "city": "beheira",
        "district": "كفر الدوار",
        "governorate": "البحيرة",
        "address": "طريق المحمودية القديم - كفر الدوار",
        "phone1": "045-2286700",
        "phone2": "01144556677",
        "website": "",
        "email": "egy.irrigation.pipes@gmail.com",
        "lat": 31.1420,
        "lon": 30.1450,
        "fleetSize": 25,
        "fleetType": "شاحنات نقل أطوال مواسير ولوازم ري",
        "priority": "B",
        "notes": "تصنيع مواسير بولي إيثيلين وخراطيم ري بالتنقيط للمشاريع الزراعية الكبرى"
    },
    {
        "nameAr": "شركة الوفاء للصناعات الهندسية ومقطورات النقل الزراعي",
        "nameEn": "Al Wafaa Engineering & Agro Trailers Manufacturing",
        "sector": "manufacturing",
        "city": "beheira",
        "district": "دمنهور",
        "governorate": "البحيرة",
        "address": "المنطقة الصناعية بحوش عيسى - طريق دمنهور",
        "phone1": "045-3341800",
        "phone2": "01007788990",
        "website": "",
        "email": "wafaa.trailers@gmail.com",
        "lat": 30.9120,
        "lon": 30.2980,
        "fleetSize": 30,
        "fleetType": "شاحنات جر وتريلات نقل هياكل معدنية",
        "priority": "A",
        "notes": "تصنيع مقطورات الجرارات الزراعية وتريلات القلاب وصهاريج نقل المياه والوقود"
    },
    {
        "nameAr": "شركة دمنهور للأعلاف والمركزات الحيوانية",
        "nameEn": "Damanhour Feeds & Livestock Concentrates",
        "sector": "food",
        "city": "beheira",
        "district": "دمنهور",
        "governorate": "البحيرة",
        "address": "طريق إيتاي البارود الزراعي - دمنهور",
        "phone1": "045-3312900",
        "phone2": "01201122334",
        "website": "",
        "email": "damanhour.feeds@yahoo.com",
        "lat": 31.0250,
        "lon": 30.4810,
        "fleetSize": 35,
        "fleetType": "تريلات نقل أعلاف صب وشاحنات توزيع أجولة",
        "priority": "A",
        "notes": "مصنع أعلاف تسمين وعجول وماشية حلاب - أسطول شاحنات نقل لمزارع الدلتا"
    },
    {
        "nameAr": "شركة السلام للأسمدة والمخصبات والمبيدات المعتمدة",
        "nameEn": "Al Salam Fertilizers & Crop Care Hosh Eissa",
        "sector": "chemicals_plastic",
        "city": "beheira",
        "district": "حوش عيسى",
        "governorate": "البحيرة",
        "address": "المنطقة الصناعية بحوش عيسى",
        "phone1": "045-3452100",
        "phone2": "01155667788",
        "website": "",
        "email": "salam.cropcare@gmail.com",
        "lat": 30.9080,
        "lon": 30.2890,
        "fleetSize": 25,
        "fleetType": "شاحنات نقل أسمدة وموزعات سوائل",
        "priority": "B",
        "notes": "تصنيع وتوزيع مخصبات زراعية ومغذيات نباتية - أسطول شاحنات توزيع للمزارع"
    },
    {
        "nameAr": "شركة الفرات لتكرير وتعبئة الزيوت النباتية",
        "nameEn": "Al Furat Edible Oil Refining & Packaging",
        "sector": "food",
        "city": "beheira",
        "district": "كفر الدوار",
        "governorate": "البحيرة",
        "address": "طريق إدكو الزراعي - كفر الدوار",
        "phone1": "045-2288120",
        "phone2": "01099887766",
        "website": "",
        "email": "furat.oils@gmail.com",
        "lat": 31.1450,
        "lon": 30.1520,
        "fleetSize": 30,
        "fleetType": "صهاريج نقل زيوت خام وسيارات توزيع كراتين",
        "priority": "B",
        "notes": "تكرير زيت الصويا ودوار الشمس وتعبئته - صهاريج نقل زيوت غذائية"
    },
    {
        "nameAr": "شركة النسر لتصنيع وتشكيل الألومنيوم والجمالونات المعدنية",
        "nameEn": "Al Nesr Metal Structures & Aluminum Fabrication",
        "sector": "manufacturing",
        "city": "beheira",
        "district": "كفر الدوار",
        "governorate": "البحيرة",
        "address": "شارع المصانع - المنطقة الحرفية الصناعية بكفر الدوار",
        "phone1": "045-2289450",
        "phone2": "01277889900",
        "website": "",
        "email": "nesr.structures@yahoo.com",
        "lat": 31.1390,
        "lon": 30.1250,
        "fleetSize": 20,
        "fleetType": "شاحنات نقل جمالونات ورافعات شوكية",
        "priority": "B",
        "notes": "تصنيع الهياكل الفولاذية للمستودعات ومحطات الفرز والتصدير الزراعي"
    },
    {
        "nameAr": "شركة المحمودية للغزل والنسيج والصباغة الحديثة",
        "nameEn": "Mahmoudia Spinning, Weaving & Modern Dyeing Co",
        "sector": "textile_apparel",
        "city": "beheira",
        "district": "المحمودية",
        "governorate": "البحيرة",
        "address": "طريق ترعة المحمودية - مركز المحمودية",
        "phone1": "045-3651200",
        "phone2": "01003322119",
        "website": "",
        "email": "mahmoudia.textile@gmail.com",
        "lat": 31.1850,
        "lon": 30.5250,
        "fleetSize": 30,
        "fleetType": "شاحنات نقل بكرات غزل وأقمشة قطنية",
        "priority": "B",
        "notes": "غزل خيوط قطنية وصباغة وتجهيز الأقمشة التصديرية - أسطول سيارات نقل بضائع"
    },
    {
        "nameAr": "شركة الاتحاد لمطاحن وصوامع الغلال بدمنهور",
        "nameEn": "Al Etehad Flour Mills & Grain Silos Damanhour",
        "sector": "food",
        "city": "beheira",
        "district": "دمنهور",
        "governorate": "البحيرة",
        "address": "شارع صلاح سالم - دمنهور",
        "phone1": "045-3318220",
        "phone2": "01221144332",
        "website": "",
        "email": "etehad.mills@yahoo.com",
        "lat": 31.0310,
        "lon": 30.4650,
        "fleetSize": 35,
        "fleetType": "تريلات نقل قمح وشاحنات توزيع دقيق",
        "priority": "A",
        "notes": "مطاحن دقيق بلدي وفاخر وصوامع تخزين حبوب - أسطول شاحنات وتريلات غلال"
    },
    {
        "nameAr": "شركة الهدى لتجهيز وتعبئة الأرز الفاخر والمكرونة",
        "nameEn": "Al Hoda Rice Processing & Pasta Kafr El Dawar",
        "sector": "food",
        "city": "beheira",
        "district": "كفر الدوار",
        "governorate": "البحيرة",
        "address": "طريق السكة الجديدة - كفر الدوار",
        "phone1": "045-2287660",
        "phone2": "01112233998",
        "website": "",
        "email": "hoda.rice.eg@gmail.com",
        "lat": 31.1320,
        "lon": 30.1380,
        "fleetSize": 25,
        "fleetType": "شاحنات توزيع منتجات غذائية وأجولة",
        "priority": "B",
        "notes": "مضرب وتعبئة أرز كامولينو وأرز بسمتي ومكرونة - أسطول شاحنات توزيع غذائي"
    },
    {
        "nameAr": "شركة أبو المطامير لتجارة وتخزين الأقطان والغلال",
        "nameEn": "Abu El Matamir Cotton & Grains Logistics Co",
        "sector": "transport",
        "city": "beheira",
        "district": "أبو المطامير",
        "governorate": "البحيرة",
        "address": "طريق جناكليس - أبو المطامير",
        "phone1": "045-3711200",
        "phone2": "01009988114",
        "website": "",
        "email": "matamir.cotton@gmail.com",
        "lat": 30.9150,
        "lon": 30.1750,
        "fleetSize": 30,
        "fleetType": "تريلات نقل محاصيل وأجولة أقطان",
        "priority": "B",
        "notes": "تخزين وتوريد بالات القطن وحبوب الغلال لمصانع النسيج والمطاحن"
    },
    {
        "nameAr": "شركة الدلنجات لمضارب الأرز والصناعات الغذائية",
        "nameEn": "Delengat Rice Mills & Agro Processing",
        "sector": "food",
        "city": "beheira",
        "district": "الدلنجات",
        "governorate": "البحيرة",
        "address": "طريق دمنهور الزراعي - الدلنجات",
        "phone1": "045-3611300",
        "phone2": "01288776655",
        "website": "",
        "email": "delengat.rice@yahoo.com",
        "lat": 30.8250,
        "lon": 30.5350,
        "fleetSize": 25,
        "fleetType": "شاحنات نقل أرز شعير وأبيض",
        "priority": "B",
        "notes": "ضرب وتبييض الأرز وتعبئة وتوزيع المحاصيل الزراعية"
    },
    {
        "nameAr": "مصنع الفيروز لتصنيع الأعلاف بحوش عيسى",
        "nameEn": "Al Fayrouz Animal Feeds Plant Hosh Eissa",
        "sector": "food",
        "city": "beheira",
        "district": "حوش عيسى",
        "governorate": "البحيرة",
        "address": "المنطقة الصناعية بحوش عيسى",
        "phone1": "045-3453200",
        "phone2": "01122338877",
        "website": "",
        "email": "fayrouz.feeds.he@gmail.com",
        "lat": 30.9050,
        "lon": 30.2920,
        "fleetSize": 30,
        "fleetType": "تريلات نقل أعلاف وشاحنات توزيع أجولة",
        "priority": "B",
        "notes": "إنتاج أعلاف الماشية والدواجن وتوريدها لمزارع البحيرة والإسكندرية"
    },
    {
        "nameAr": "شركة النور لتصنيع مقطورات وتريلات النقل الزراعي بأبو المطامير",
        "nameEn": "Al Noor Agro Trailers & Tankers Manufacturing",
        "sector": "manufacturing",
        "city": "beheira",
        "district": "أبو المطامير",
        "governorate": "البحيرة",
        "address": "طريق المحطة - أبو المطامير",
        "phone1": "045-3712400",
        "phone2": "01022337766",
        "website": "",
        "email": "noor.trailers@gmail.com",
        "lat": 30.9180,
        "lon": 30.1710,
        "fleetSize": 25,
        "fleetType": "شاحنات جر وتريلات نقل هياكل مقطورات",
        "priority": "B",
        "notes": "تصنيع مقطورات قلاب ومقطورات مياه ونقل أعلاف للمزارع"
    },
    {
        "nameAr": "شركة الوفاق لتجارة وتوزيع الأسمدة الزراعية بالدلنجات",
        "nameEn": "Al Wefaq Fertilizers & Agrochemicals Delengat",
        "sector": "chemicals_plastic",
        "city": "beheira",
        "district": "الدلنجات",
        "governorate": "البحيرة",
        "address": "الشارع الرئيسي - الدلنجات",
        "phone1": "045-3612500",
        "phone2": "01155449988",
        "website": "",
        "email": "wefaq.fertilizers@yahoo.com",
        "lat": 30.8220,
        "lon": 30.5380,
        "fleetSize": 20,
        "fleetType": "شاحنات نقل أسمدة وموزعات سوائل",
        "priority": "B",
        "notes": "توزيع أسمدة نترات ويوريا وسوبر فوسفات لمزارع قطاع غرب الدلتا"
    },

    # -------------------------------------------------------------
    # 3. وادي النطرون وإدكو ورشيد
    # -------------------------------------------------------------
    {
        "nameAr": "شركة نطرون فودز لتجفيف وتصدير الحاصلات والخضروات",
        "nameEn": "Natrun Foods for Agro Drying & Dehydration",
        "sector": "food",
        "city": "beheira",
        "district": "وادي النطرون",
        "governorate": "البحيرة",
        "address": "المنطقة الصناعية بوادي النطرون",
        "phone1": "045-3552340",
        "phone2": "01233446677",
        "website": "http://www.natrunfoods.com",
        "email": "export@natrunfoods.com",
        "lat": 30.4180,
        "lon": 30.3390,
        "fleetSize": 25,
        "fleetType": "برادات نقل زراعي وشاحنات توزيع",
        "priority": "B",
        "notes": "تجفيف البصل والثوم والأعشاب الطبية وتصديرها لأوروبا - أسطول شاحنات مجهزة"
    },
    {
        "nameAr": "شركة النطرون للجبس ومواد البناء والبودرة الصناعية",
        "nameEn": "Natrun Gypsum & Building Materials Co",
        "sector": "construction",
        "city": "beheira",
        "district": "وادي النطرون",
        "governorate": "البحيرة",
        "address": "محور المحاجر والجبس - وادي النطرون",
        "phone1": "045-3553400",
        "phone2": "01122335566",
        "website": "",
        "email": "natrun.gypsum@yahoo.com",
        "lat": 30.4080,
        "lon": 30.3550,
        "fleetSize": 40,
        "fleetType": "تريلات نقل بودرة جبس وشاحنات محاجر",
        "priority": "A",
        "notes": "مطاحن جبس ومواد بناء ومصائد رمال - أسطول شاحنات تريلات ثقيلة ومحاجر"
    },
    {
        "nameAr": "شركة الصحراء الخضراء لاستصلاح الأراضي والخدمات الزراعية",
        "nameEn": "Green Desert Land Reclamation & Heavy Machinery",
        "sector": "construction",
        "city": "beheira",
        "district": "وادي النطرون",
        "governorate": "البحيرة",
        "address": "الكيلو 100 طريق مصر إسكندرية الصحراوي - وادي النطرون",
        "phone1": "045-3554100",
        "phone2": "01099881122",
        "website": "",
        "email": "greendesert.eg@gmail.com",
        "lat": 30.4250,
        "lon": 30.3600,
        "fleetSize": 45,
        "fleetType": "لوادر وحفارات وتريلات كساحات نقل معدات ثقيلة",
        "priority": "A+",
        "notes": "استصلاح أراضي وتمهيد مزارع وتجهيز شبكات ري - أسطول معدات ثقيلة وكساحات"
    },
    {
        "nameAr": "شركة الوادي لإنتاج وتعبئة زيت الزيتون والمخللات",
        "nameEn": "Al Wadi Olive Oil & Pickles Processing Plant",
        "sector": "food",
        "city": "beheira",
        "district": "وادي النطرون",
        "governorate": "البحيرة",
        "address": "طريق دير البراموس - وادي النطرون",
        "phone1": "045-3555220",
        "phone2": "01288991122",
        "website": "",
        "email": "wadi.olive@outlook.com",
        "lat": 30.4300,
        "lon": 30.3280,
        "fleetSize": 25,
        "fleetType": "شاحنات نقل زيوت ومخللات وسيارات توزيع",
        "priority": "B",
        "notes": "معاصر زيت زيتون بكر ممتاز ومصنع تخليل وتعبئة زيتون المائدة - أسطول توزيع محلي وتصدير"
    },
    {
        "nameAr": "شركة الفراعنة لتعبئة الملح الغذائي والصناعي (وادي النطرون)",
        "nameEn": "Pharaohs Salt Refining & Table Salt Plant",
        "sector": "manufacturing",
        "city": "beheira",
        "district": "وادي النطرون",
        "governorate": "البحيرة",
        "address": "مجمع الملاحات والمنطقة الصناعية - وادي النطرون",
        "phone1": "045-3556110",
        "phone2": "01022119988",
        "website": "",
        "email": "pharaohs.salt@gmail.com",
        "lat": 30.4120,
        "lon": 30.3450,
        "fleetSize": 30,
        "fleetType": "شاحنات نقل أجولة ملح وتريلات صب",
        "priority": "B",
        "notes": "تكرير الملح باليود وتعبئة أكياس ملح طعام وملح معالجة مياه - أسطول شاحنات"
    },
    {
        "nameAr": "الشركة المصرية للغاز الطبيعي المسال (ELNG إدكو)",
        "nameEn": "Egyptian LNG Company (ELNG) Edko Complex",
        "sector": "petroleum",
        "city": "beheira",
        "district": "إدكو",
        "governorate": "البحيرة",
        "address": "مجمع إسالة الغاز - ميناء إدكو البترولي - البحيرة",
        "phone1": "045-2900100",
        "phone2": "045-2900105",
        "website": "http://www.egyptianlng.com",
        "email": "info@egyptianlng.com",
        "lat": 31.3120,
        "lon": 30.2980,
        "fleetSize": 45,
        "fleetType": "شاحنات إطفاء وسلامة وتريلات صيانة ومعدات ثقيلة",
        "priority": "A+",
        "notes": "أكبر مجمع لإسالة وتصدير الغاز الطبيعي المسال في مصر وشمال إفريقيا"
    },
    {
        "nameAr": "شركة مضارب أرز رشيد والمحمودية الحكومية",
        "nameEn": "Rashid & Mahmoudia State Rice Mills Co",
        "sector": "food",
        "city": "beheira",
        "district": "رشيد",
        "governorate": "البحيرة",
        "address": "شارع النيل - رشيد - البحيرة",
        "phone1": "045-2921100",
        "phone2": "01005544882",
        "website": "",
        "email": "rashid.statemills@gmail.com",
        "lat": 31.4010,
        "lon": 30.4190,
        "fleetSize": 30,
        "fleetType": "شاحنات نقل وتوزيع أرز تمويني وحبوب",
        "priority": "B",
        "notes": "مضارب وصوامع حكومية لتوريد الأرز التمويني وتصدير الأرز الأبيض"
    },
    {
        "nameAr": "شركة المعدية للتوريدات الملاحية والخدمات البحرية",
        "nameEn": "Al Maadiya Marine Supplies & Port Logistics",
        "sector": "transport",
        "city": "beheira",
        "district": "إدكو",
        "governorate": "البحيرة",
        "address": "ميناء صيد وتجارة المعدية - إدكو",
        "phone1": "045-2980100",
        "phone2": "01223311776",
        "website": "",
        "email": "maadiya.marine@outlook.com",
        "lat": 31.2650,
        "lon": 30.1550,
        "fleetSize": 25,
        "fleetType": "شاحنات خدمات ملاحية ورافعات ولنشات خدمة",
        "priority": "B",
        "notes": "خدمات الدعم اللوجستي لمنصات الغاز البحرية وسفن الشحن بميناء المعدية"
    },
    {
        "nameAr": "شركة البرلس للغاز ومحطة المعالجة الساحلية بإدكو",
        "nameEn": "Burullus Gas Company - Edko Onshore Plant",
        "sector": "petroleum",
        "city": "beheira",
        "district": "إدكو",
        "governorate": "البحيرة",
        "address": "المحطة الساحلية لمعالجة الغاز - إدكو",
        "phone1": "045-2900300",
        "phone2": "045-2900305",
        "website": "http://www.burullus.com",
        "email": "contact@burullus.com",
        "lat": 31.3080,
        "lon": 30.3050,
        "fleetSize": 40,
        "fleetType": "شاحنات نقل بترولي ومعدات طوارئ وصهاريج",
        "priority": "A+",
        "notes": "معالجة وضخ الغاز الطبيعي القادم من حقول غرب الدلتا البحرية"
    },

    # -------------------------------------------------------------
    # 4. برج العرب الجديدة - قلاع دوائية وصناعية ثقيلة
    # -------------------------------------------------------------
    {
        "nameAr": "الشركة الأوروبية المصرية للصناعات الدوائية ش.م.م",
        "nameEn": "European Egyptian Pharmaceutical Industries (EEPI)",
        "sector": "pharma",
        "city": "alexandria",
        "district": "برج العرب الجديدة",
        "governorate": "الإسكندرية",
        "address": "المنطقة الصناعية الأولى - بلوك 16 - مدينة برج العرب الجديدة",
        "phone1": "03-4595200",
        "phone2": "03-4595205",
        "website": "http://www.eepi.com.eg",
        "email": "info@eepi.com.eg",
        "lat": 30.8490,
        "lon": 29.6050,
        "fleetSize": 45,
        "fleetType": "شاحنات نقل أدوية مكيفة ومجهزة وسيارات توزيع",
        "priority": "A+",
        "notes": "إحدى كبرى القلاع الدوائية في مصر والشرق الأوسط - أسطول شاحنات توزيع أدوية مبرد"
    },
    {
        "nameAr": "شركة برج للصناعات الدوائية",
        "nameEn": "Borg Pharmaceutical Industries",
        "sector": "pharma",
        "city": "alexandria",
        "district": "برج العرب الجديدة",
        "governorate": "الإسكندرية",
        "address": "المنطقة الصناعية الثالثة - بلوك 28 - برج العرب الجديدة",
        "phone1": "03-4594000",
        "phone2": "03-4594005",
        "website": "http://www.borg-pharma.com",
        "email": "info@borg-pharma.com",
        "lat": 30.8380,
        "lon": 29.5850,
        "fleetSize": 40,
        "fleetType": "سيارات وشاحنات نقل أدوية معقم ومكيف",
        "priority": "A+",
        "notes": "مجمع دوائي متكامل لتصنيع الأدوية والمحاليل - أسطول سيارات توزيع دوائي مركزي"
    },
    {
        "nameAr": "شركة مسبوكات الإسكندرية وسبك الصلب والمعادن",
        "nameEn": "Alexandria Castings & Steel Foundry Co",
        "sector": "manufacturing",
        "city": "alexandria",
        "district": "برج العرب الجديدة",
        "governorate": "الإسكندرية",
        "address": "المنطقة الصناعية الرابعة - برج العرب الجديدة",
        "phone1": "03-4596300",
        "phone2": "01001155889",
        "website": "",
        "email": "alex.castings@yahoo.com",
        "lat": 30.8290,
        "lon": 29.5750,
        "fleetSize": 35,
        "fleetType": "تريلات نقل سبائك ومسبوكات صلب وشاحنات ثقيلة",
        "priority": "A",
        "notes": "سبك وتشكيل الصلب والحديد الزهر وقطع غيار الشاحنات والمعدات الهندسية"
    },
    {
        "nameAr": "الشركة الإسكندرانية لصناعة الكابلات والموصلات الكهربائية",
        "nameEn": "Alexandria Electrical Cables & Conductors Co",
        "sector": "manufacturing",
        "city": "alexandria",
        "district": "برج العرب الجديدة",
        "governorate": "الإسكندرية",
        "address": "المنطقة الصناعية الأولى - برج العرب الجديدة",
        "phone1": "03-4597110",
        "phone2": "01222339900",
        "website": "",
        "email": "alexcables.eg@gmail.com",
        "lat": 30.8460,
        "lon": 29.6120,
        "fleetSize": 30,
        "fleetType": "شاحنات نقل بكرات كابلات وتريلات توزيع",
        "priority": "A",
        "notes": "تصنيع كابلات الجهد المنخفض والمتوسط والموصلات النحاسية والألومنيوم"
    },
    {
        "nameAr": "شركة إينوفا بلاس للصناعات البلاستيكية والعبوات الهندسية",
        "nameEn": "Innova Plus Plastic Industries & Engineering Packaging",
        "sector": "chemicals_plastic",
        "city": "alexandria",
        "district": "برج العرب الجديدة",
        "governorate": "الإسكندرية",
        "address": "المنطقة الصناعية الثانية - برج العرب الجديدة",
        "phone1": "03-4598220",
        "phone2": "01111223388",
        "website": "",
        "email": "innovaplus.plastic@gmail.com",
        "lat": 30.8420,
        "lon": 29.5980,
        "fleetSize": 25,
        "fleetType": "شاحنات صندوق مغلق لنقل عبوات بلاستيك",
        "priority": "B",
        "notes": "حقن ونفخ العبوات البلاستيكية ومستلزمات التعبئة للمصانع الدوائية والغذائية"
    },
    {
        "nameAr": "شركة الصفا والمروة لتصنيع الكرتون المضلع ومواد التغليف",
        "nameEn": "Al Safa & Marwa Corrugated Carton & Packaging",
        "sector": "packaging_paper",
        "city": "alexandria",
        "district": "برج العرب الجديدة",
        "governorate": "الإسكندرية",
        "address": "المنطقة الصناعية الثالثة - برج العرب الجديدة",
        "phone1": "03-4599440",
        "phone2": "01008899221",
        "website": "",
        "email": "safamarwa.carton@outlook.com",
        "lat": 30.8350,
        "lon": 29.5890,
        "fleetSize": 30,
        "fleetType": "شاحنات نقل كرتون مضلع وصناديق تصدير",
        "priority": "B",
        "notes": "تصنيع كرتون تغليف الحاصلات الزراعية والمصانع - أسطول شاحنات توزيع كرتون"
    },
    {
        "nameAr": "شركة رويال للمشغولات المعدنية والهياكل الفولاذية",
        "nameEn": "Royal Steel Fabrication & Metal Works",
        "sector": "manufacturing",
        "city": "alexandria",
        "district": "برج العرب الجديدة",
        "governorate": "الإسكندرية",
        "address": "المنطقة الصناعية الخامسة - برج العرب الجديدة",
        "phone1": "03-4591880",
        "phone2": "01200998877",
        "website": "",
        "email": "royal.steelfab@gmail.com",
        "lat": 30.8250,
        "lon": 29.5680,
        "fleetSize": 25,
        "fleetType": "تريلات مسطح لنقل هياكل الصلب ومعدات رفع",
        "priority": "B",
        "notes": "تقطيع وتشكيل ألواح الصلب وهياكل الكباري والمصانع - أسطول تريلات نقل ثقيل"
    },
    {
        "nameAr": "شركة مصر للبتروكيماويات والراتنجات الصناعية (برج العرب)",
        "nameEn": "Misr Petrochemicals & Synthetic Resins Borg El Arab",
        "sector": "petroleum",
        "city": "alexandria",
        "district": "برج العرب الجديدة",
        "governorate": "الإسكندرية",
        "address": "المنطقة الصناعية الثانية - مجمع الكيماويات - برج العرب",
        "phone1": "03-4592770",
        "phone2": "01144558899",
        "website": "",
        "email": "petrochem.borg@gmail.com",
        "lat": 30.8410,
        "lon": 29.6010,
        "fleetSize": 35,
        "fleetType": "صهاريج نقل مواد بتروكيماوية وسوائل قابلة للاشتعال",
        "priority": "A",
        "notes": "إنتاج راتنجات الإيبوكسي والبوليستر غير المشبع - أسطول صهاريج بترولية معتمدة"
    },
    {
        "nameAr": "شركة بونو للصناعات الغذائية والزيوت النباتية (برج العرب)",
        "nameEn": "Bono Food Industries & Edible Oils Borg El Arab",
        "sector": "food",
        "city": "alexandria",
        "district": "برج العرب الجديدة",
        "governorate": "الإسكندرية",
        "address": "المنطقة الصناعية الأولى - برج العرب الجديدة",
        "phone1": "03-4593660",
        "phone2": "01022334411",
        "website": "",
        "email": "bonofood.eg@gmail.com",
        "lat": 30.8480,
        "lon": 29.6090,
        "fleetSize": 30,
        "fleetType": "شاحنات توزيع منتجات غذائية وصهاريج زيت",
        "priority": "B",
        "notes": "تكرير وتعبئة الزيوت الغذائية والسمن النباتي - أسطول سيارات توزيع جملة وتجزئة"
    },
    {
        "nameAr": "شركة دماناك للصناعات الدوائية والبيطرية",
        "nameEn": "Damanaq Veterinary Pharmaceuticals Borg El Arab",
        "sector": "pharma",
        "city": "alexandria",
        "district": "برج العرب الجديدة",
        "governorate": "الإسكندرية",
        "address": "المنطقة الصناعية الثالثة - برج العرب الجديدة",
        "phone1": "03-4594550",
        "phone2": "01277665544",
        "website": "",
        "email": "damanaq.vet@yahoo.com",
        "lat": 30.8360,
        "lon": 29.5820,
        "fleetSize": 25,
        "fleetType": "سيارات توزيع أدوية بيطرية وإضافات أعلاف",
        "priority": "B",
        "notes": "تصنيع المضادات الحيوية البيطرية وإضافات الأعلاف لمزارع الدواجن والماشية"
    },
    {
        "nameAr": "شركة تكنوفارما للصناعات الدوائية ومستحضرات التجميل العلاجية",
        "nameEn": "TechnoPharma Egypt Pharmaceutical Industries",
        "sector": "pharma",
        "city": "alexandria",
        "district": "برج العرب الجديدة",
        "governorate": "الإسكندرية",
        "address": "المنطقة الصناعية الرابعة - برج العرب الجديدة",
        "phone1": "03-4595660",
        "phone2": "01099884433",
        "website": "",
        "email": "technopharma.eg@gmail.com",
        "lat": 30.8310,
        "lon": 29.5780,
        "fleetSize": 30,
        "fleetType": "سيارات فان مكيفة وشاحنات توزيع أدوية",
        "priority": "A",
        "notes": "تصنيع الأدوية والمراهم العلاجية ومحاليل التطهير - أسطول سيارات توزيع دوائي"
    },
    {
        "nameAr": "شركة النصر لتصنيع الزجاج والعبوات الدوائية (برج العرب)",
        "nameEn": "Al Nasr Glass & Pharmaceutical Bottles Borg El Arab",
        "sector": "manufacturing",
        "city": "alexandria",
        "district": "برج العرب الجديدة",
        "governorate": "الإسكندرية",
        "address": "المنطقة الصناعية الثانية - برج العرب الجديدة",
        "phone1": "03-4596770",
        "phone2": "01233445588",
        "website": "",
        "email": "nasrglass.borg@gmail.com",
        "lat": 30.8440,
        "lon": 29.6030,
        "fleetSize": 30,
        "fleetType": "شاحنات نقل عبوات زجاجية وصناديق",
        "priority": "B",
        "notes": "تصنيع الزجاجات الدوائية والغذائية المقاومة للحرارة - أسطول شاحنات مجهزة بصناديق مبطنة"
    },

    # -------------------------------------------------------------
    # 5. العامرية ومرغم والمنطقة الحرة وميناء الدخيلة
    # -------------------------------------------------------------
    {
        "nameAr": "الشركة العربية لأنابيب البترول (سوميد - محطة سيدي كرير والدخيلة)",
        "nameEn": "Arab Petroleum Pipelines Company (SUMED)",
        "sector": "petroleum",
        "city": "alexandria",
        "district": "العامرية ومرغم",
        "governorate": "الإسكندرية",
        "address": "محطة سيدي كرير البحرية - الكيلو 27 طريق الإسكندرية مطروح",
        "phone1": "03-3831000",
        "phone2": "03-3831005",
        "website": "http://www.sumed.org",
        "email": "sumed@sumed.org",
        "lat": 31.0550,
        "lon": 29.6850,
        "fleetSize": 55,
        "fleetType": "شاحنات أمن وسلامة وصهاريج نقل بترولي ومعدات بحرية",
        "priority": "A+",
        "notes": "مستودعات تخزين وتداول النفط الخام والمازوت وتفريغ ناقلات البترول العملاقة"
    },
    {
        "nameAr": "شركة المستودعات المصرية العامة بميناء الإسكندرية والدخيلة",
        "nameEn": "Egyptian General Warehouses Co Dekheila Port",
        "sector": "transport",
        "city": "alexandria",
        "district": "الدخيلة والقباري",
        "governorate": "الإسكندرية",
        "address": "بوابة 22 - المنطقة اللوجستية الجمركية - ميناء الدخيلة",
        "phone1": "03-4481500",
        "phone2": "03-4481505",
        "website": "http://www.egywarehouses.com",
        "email": "info@egywarehouses.com",
        "lat": 31.1410,
        "lon": 29.8210,
        "fleetSize": 50,
        "fleetType": "تريلات نقل حاويات ومعدات تفريغ ورافعات شوكية",
        "priority": "A+",
        "notes": "أكبر مستودعات تخزين جمركي وتداول بضائع عامة وصب في مينائي الإسكندرية والدخيلة"
    },
    {
        "nameAr": "شركة السهام البترولية - منطقة الإسكندرية والدخيلة",
        "nameEn": "Al Seham Petroleum Fleet Alexandria Branch",
        "sector": "transport",
        "city": "alexandria",
        "district": "الدخيلة والقباري",
        "governorate": "الإسكندرية",
        "address": "مستودع السهام البترولية - المكس - الإسكندرية",
        "phone1": "03-4452100",
        "phone2": "03-4452105",
        "website": "http://www.elsehampetroleum.com",
        "email": "alex.branch@elsehampetroleum.com",
        "lat": 31.1450,
        "lon": 29.8450,
        "fleetSize": 75,
        "fleetType": "صهاريج نقل وقود وسولار وغاز مسال",
        "priority": "A+",
        "notes": "أسطول نقل وتوزيع المنتجات البترولية والغاز لمحافظات الإسكندرية والبحيرة ومطروح"
    },
    {
        "nameAr": "شركة أوفرسيز للملاحة والتخليص الجمركي والخدمات اللوجستية",
        "nameEn": "Overseas Shipping & Maritime Logistics Dekheila",
        "sector": "transport",
        "city": "alexandria",
        "district": "الدخيلة والقباري",
        "governorate": "الإسكندرية",
        "address": "مجمع التوكيلات الملاحية - الدخيلة",
        "phone1": "03-4483200",
        "phone2": "01002233665",
        "website": "",
        "email": "overseas.shipping.alex@gmail.com",
        "lat": 31.1390,
        "lon": 29.8280,
        "fleetSize": 35,
        "fleetType": "تريلات شاسيه حاويات 20 و40 قدم",
        "priority": "A",
        "notes": "نقل حاويات وخدمات لوجستية وتخليص جمركي من وإلى ميناء الإسكندرية والدخيلة"
    },
    {
        "nameAr": "شركة فنار إسكندرية للصناعات البلاستيكية والعبوات",
        "nameEn": "Fanar Alex Plastic Industries Merghem",
        "sector": "chemicals_plastic",
        "city": "alexandria",
        "district": "العامرية ومرغم",
        "governorate": "الإسكندرية",
        "address": "مجمع مرغم للصناعات البلاستيكية - العامرية",
        "phone1": "03-4581900",
        "phone2": "01080362399",
        "website": "",
        "email": "fanar.plastic@yahoo.com",
        "lat": 31.0650,
        "lon": 29.7980,
        "fleetSize": 25,
        "fleetType": "شاحنات نقل منتجات بلاستيكية وخامات",
        "priority": "B",
        "notes": "حقن وتصنيع المستلزمات البلاستيكية والبراميل والعبوات الصناعية بمجمع مرغم"
    },
    {
        "nameAr": "شركة تكنو كيم لمواد البناء والعزل الكيماوي والإيبوكسي",
        "nameEn": "Techno Chem Building Materials & Epoxy Systems",
        "sector": "chemicals_plastic",
        "city": "alexandria",
        "district": "العامرية ومرغم",
        "governorate": "الإسكندرية",
        "address": "المنطقة الصناعية بمرغم - الإسكندرية",
        "phone1": "03-4583400",
        "phone2": "01122114433",
        "website": "",
        "email": "technochem.eg@gmail.com",
        "lat": 31.0680,
        "lon": 29.8020,
        "fleetSize": 25,
        "fleetType": "شاحنات توزيع كيماويات بناء وعوازل",
        "priority": "B",
        "notes": "تصنيع دهانات الإيبوكسي لأرضيات المصانع والمستودعات ومواد العزل المائي والحراري"
    },
    {
        "nameAr": "شركة أورينت للتجارة الدولية والتوكيلات الملاحية",
        "nameEn": "Orient International Maritime Agencies Dekheila",
        "sector": "transport",
        "city": "alexandria",
        "district": "الدخيلة والقباري",
        "governorate": "الإسكندرية",
        "address": "طريق ميناء الدخيلة - الإسكندرية",
        "phone1": "03-4484600",
        "phone2": "01005544332",
        "website": "",
        "email": "orient.shipping.agency@gmail.com",
        "lat": 31.1370,
        "lon": 29.8250,
        "fleetSize": 30,
        "fleetType": "تريلات نقل بضائع عامة وصب وحاويات",
        "priority": "A",
        "notes": "توكيلات ملاحية وتفريغ سفن الحبوب والبضائع الصب ونقلها لصوامع ومستودعات الدلتا"
    },
    {
        "nameAr": "شركة الأندلس لتصنيع وتشكيل الألومنيوم والواجهات المعمارية",
        "nameEn": "Al Andalous Aluminum Extrusion & Architectural Facades",
        "sector": "manufacturing",
        "city": "alexandria",
        "district": "العامرية ومرغم",
        "governorate": "الإسكندرية",
        "address": "المنطقة الصناعية بالعامرية",
        "phone1": "03-4585200",
        "phone2": "01211016420",
        "website": "",
        "email": "andalous.aluminum@gmail.com",
        "lat": 31.0590,
        "lon": 29.8110,
        "fleetSize": 20,
        "fleetType": "شاحنات نقل قطاعات ألومنيوم وواجهات زجاجية",
        "priority": "B",
        "notes": "سحب ودهان قطاعات الألومنيوم وتصنيع واجهات الكلادينج والستائر الجدارية للمصانع"
    },
    {
        "nameAr": "شركة كيميت لأنظمة الطاقة والمعدات الصناعية والزراعية",
        "nameEn": "Kemet Industrial Solar & Pumping Systems",
        "sector": "manufacturing",
        "city": "beheira",
        "district": "دمنهور",
        "governorate": "البحيرة",
        "address": "شارع عبد السلام الشاذلي - دمنهور - البحيرة",
        "phone1": "045-3315700",
        "phone2": "01010745598",
        "website": "http://www.kemetenergy.com",
        "email": "info@kemetenergy.com",
        "lat": 31.0380,
        "lon": 30.4680,
        "fleetSize": 25,
        "fleetType": "شاحنات نقل محطات طاقة شمسية ومولدات ومعدات رفع",
        "priority": "B",
        "notes": "توريد وتركيب محطات الطاقة الشمسية وطلمبات الري للمشاريع الزراعية والمصانع"
    },
    {
        "nameAr": "شركة الدلتا للخدمات العلمية والكيماويات المعملية والصناعية",
        "nameEn": "Delta Scientific Services & Industrial Chemicals",
        "sector": "chemicals_plastic",
        "city": "beheira",
        "district": "دمنهور",
        "governorate": "البحيرة",
        "address": "شارع الروضة - دمنهور",
        "phone1": "045-3316800",
        "phone2": "01001970067",
        "website": "",
        "email": "delta.scientific@yahoo.com",
        "lat": 31.0340,
        "lon": 30.4720,
        "fleetSize": 20,
        "fleetType": "سيارات مجهزة لنقل الكيماويات ومستلزمات المعامل",
        "priority": "B",
        "notes": "توريد الكيماويات المعملية والصناعية ومستلزمات مراقبة الجودة لمصانع الأغذية والأدوية"
    },
    {
        "nameAr": "شركة الدلتا لتوزيع الغازات الصناعية والطبية (العامرية)",
        "nameEn": "Delta Industrial & Medical Gases Distribution Amreya",
        "sector": "chemicals_plastic",
        "city": "alexandria",
        "district": "العامرية ومرغم",
        "governorate": "الإسكندرية",
        "address": "طريق الكافوري - العامرية",
        "phone1": "03-4586300",
        "phone2": "01008877665",
        "website": "",
        "email": "deltagases.alex@gmail.com",
        "lat": 31.0520,
        "lon": 29.8050,
        "fleetSize": 30,
        "fleetType": "شاحنات نقل أسطوانات غازات صناعية وصهاريج أكسجين سائل",
        "priority": "A",
        "notes": "توزيع الأكسجين والنيتروجين والأرجون للمستشفيات ومصانع الدرفلة واللحام"
    },
    {
        "nameAr": "شركة النيل لخدمات النقل البحري وتموين السفن (الدخيلة)",
        "nameEn": "Nile Marine Services & Ship Chandling Dekheila",
        "sector": "transport",
        "city": "alexandria",
        "district": "الدخيلة والقباري",
        "governorate": "الإسكندرية",
        "address": "بوابة 6 - رصيف الحاويات - ميناء الدخيلة",
        "phone1": "03-4485700",
        "phone2": "01229988771",
        "website": "",
        "email": "nilemarine.dekheila@outlook.com",
        "lat": 31.1440,
        "lon": 29.8190,
        "fleetSize": 25,
        "fleetType": "شاحنات تموين مجهزة وصهاريج مياه عذبة وزيوت بحرية",
        "priority": "B",
        "notes": "تموين السفن التجارية وناقلات النفط بالمواد الغذائية والمهمات البحرية والوقود"
    },
    {
        "nameAr": "شركة الإسكندرية لأسود الكربون والإطارات",
        "nameEn": "Alexandria Carbon Black & Tire Chemicals Co",
        "sector": "chemicals_plastic",
        "city": "alexandria",
        "district": "الدخيلة والقباري",
        "governorate": "الإسكندرية",
        "address": "طريق الدخيلة الصناعي - الإسكندرية",
        "phone1": "03-4486100",
        "phone2": "03-4486105",
        "website": "",
        "email": "alexcarbon.black@gmail.com",
        "lat": 31.1380,
        "lon": 29.8310,
        "fleetSize": 45,
        "fleetType": "شاحنات صهاريج نقل خامات كربون ومواد كيميائية",
        "priority": "A+",
        "notes": "تصنيع أسود الكربون المستخدم في صناعة إطارات السيارات والمطاط - صهاريج نقل متخصصة"
    },
    {
        "nameAr": "الشركة المصرية الإسبانية للملابس الجاهزة بالمنطقة الحرة بالعامرية",
        "nameEn": "Egyptian Spanish Garments Co Amreya Free Zone",
        "sector": "textile_apparel",
        "city": "alexandria",
        "district": "العامرية ومرغم",
        "governorate": "الإسكندرية",
        "address": "المنطقة الحرة العامة بالعامرية - بلوك 12",
        "phone1": "03-4500110",
        "phone2": "03-4500115",
        "website": "",
        "email": "egyspanish.apparel@gmail.com",
        "lat": 31.0480,
        "lon": 29.8150,
        "fleetSize": 40,
        "fleetType": "شاحنات كونتينر مغلقة وحافلات نقل عمالة",
        "priority": "A",
        "notes": "مجمع تصنيع ملابس تصديرية كبرى بالمنطقة الحرة - أسطول شاحنات نقل حاويات وحافلات"
    },
    {
        "nameAr": "شركة صحارى لصناعة وتصدير الملابس بالمنطقة الحرة",
        "nameEn": "Sahara Garments Manufacturing Amreya Free Zone",
        "sector": "textile_apparel",
        "city": "alexandria",
        "district": "العامرية ومرغم",
        "governorate": "الإسكندرية",
        "address": "المنطقة الحرة العامة بالعامرية - بلوك 18",
        "phone1": "03-4500220",
        "phone2": "01006655443",
        "website": "",
        "email": "sahara.garments@yahoo.com",
        "lat": 31.0450,
        "lon": 29.8180,
        "fleetSize": 35,
        "fleetType": "شاحنات شحن بضائع وأتوبيسات نقل موظفين",
        "priority": "A",
        "notes": "مصنع ملابس جينز وتريكو للتصدير للولايات المتحدة وأوروبا بالمنطقة الحرة"
    },
    {
        "nameAr": "شركة أوشن سيرفيس للخدمات البترولية والبحرية بالعامرية",
        "nameEn": "Ocean Services Petroleum & Marine Logistics Amreya",
        "sector": "petroleum",
        "city": "alexandria",
        "district": "العامرية ومرغم",
        "governorate": "الإسكندرية",
        "address": "المنطقة الحرة العامة بالعامرية",
        "phone1": "03-4500330",
        "phone2": "01221100998",
        "website": "",
        "email": "ocean.services.eg@gmail.com",
        "lat": 31.0420,
        "lon": 29.8210,
        "fleetSize": 35,
        "fleetType": "كساحات نقل معدات حفر وتريلات صهاريج بترولية",
        "priority": "A",
        "notes": "تأجير ونقل معدات الحفر البحرية ومهمات الحقول البترولية بالصحراء الغربية"
    },
    {
        "nameAr": "شركة ماريدايف للخدمات الملاحية والبترولية فرع العامرية",
        "nameEn": "Maridive Oil & Gas Marine Fleet Amreya Branch",
        "sector": "transport",
        "city": "alexandria",
        "district": "العامرية ومرغم",
        "governorate": "الإسكندرية",
        "address": "المنطقة اللوجستية بالعامرية - طريق الإسكندرية الصحراوي",
        "phone1": "03-4500440",
        "phone2": "03-4500445",
        "website": "http://www.maridive.com.eg",
        "email": "operations@maridive.com.eg",
        "lat": 31.0460,
        "lon": 29.8140,
        "fleetSize": 50,
        "fleetType": "تريلات نقل ثقيل ومعدات إنقاذ بحري وأوناش",
        "priority": "A+",
        "notes": "خدمات الدعم اللوجستي للإنشاءات البحرية وخطوط الأنابيب البترولية تحت الماء"
    },
    {
        "nameAr": "شركة الأمل للصناعات الكيماوية والدهانات (العامرية)",
        "nameEn": "Al Amal Chemical Industries & Paints Amreya",
        "sector": "chemicals_plastic",
        "city": "alexandria",
        "district": "العامرية ومرغم",
        "governorate": "الإسكندرية",
        "address": "المنطقة الصناعية بالنهضة - العامرية",
        "phone1": "03-4587100",
        "phone2": "01144339900",
        "website": "",
        "email": "amal.paints.amreya@gmail.com",
        "lat": 31.0350,
        "lon": 29.7890,
        "fleetSize": 25,
        "fleetType": "شاحنات توزيع دهانات وعبوات كيماوية",
        "priority": "B",
        "notes": "تصنيع دهانات الحوائط واللاكيهات والمعاجين - أسطول شاحنات توزيع على الوكلاء"
    },
    {
        "nameAr": "شركة الإسكندرية لسحب وتشكيل قطاعات الألومنيوم",
        "nameEn": "Alexandria Aluminum Extrusion & Powder Coating",
        "sector": "manufacturing",
        "city": "alexandria",
        "district": "العامرية ومرغم",
        "governorate": "الإسكندرية",
        "address": "المنطقة الصناعية بمرغم - الكيلو 22",
        "phone1": "03-4588200",
        "phone2": "01011994455",
        "website": "",
        "email": "alex.aluminum.extrusion@gmail.com",
        "lat": 31.0690,
        "lon": 29.8090,
        "fleetSize": 25,
        "fleetType": "شاحنات نقل قطاعات ألومنيوم ودهان إلكتروستاتيك",
        "priority": "B",
        "notes": "سحب ودهان قطاعات الألومنيوم المعمارية والصناعية ومستلزمات الإنشاءات"
    }
]

# Run strict forensic vetting
verified_track_c = []
skipped_dups = 0

for item in RAW_MASTER:
    name_ar = item["nameAr"]
    phone = item["phone1"]
    
    n_norm = norm_str(name_ar)
    p_sig = phone.replace('-', '')[-8:]
    
    if n_norm in existing_names or p_sig in existing_phones:
        print(f"[SKIP DUPLICATE] {name_ar} (Phone: {phone})")
        skipped_dups += 1
        continue
        
    c_id = f"eg_track_c_{len(verified_track_c)+1:04d}"
    record = {
        "id": c_id,
        "nameAr": name_ar,
        "nameEn": item["nameEn"],
        "sector": item["sector"],
        "city": item["city"],
        "district": item["district"],
        "governorate": item["governorate"],
        "address": item["address"],
        "phone1": item["phone1"],
        "phone2": item.get("phone2", ""),
        "mobile": item.get("phone2") if str(item.get("phone2", "")).startswith("01") else (item["phone1"] if item["phone1"].startswith("01") else ""),
        "hotline": "",
        "website": item.get("website", ""),
        "email": item.get("email", ""),
        "lat": item.get("lat"),
        "lon": item.get("lon"),
        "fleetSize": item["fleetSize"],
        "fleetType": item["fleetType"],
        "priority": item["priority"],
        "status": "unassigned",
        "source": "verified_track_c_beheira_alex_2026",
        "contactPerson": "", # Blank for sales custody
        "notes": item["notes"]
    }
    
    verified_track_c.append(record)
    existing_names.add(n_norm)
    existing_phones.add(p_sig)

print(f"\n=======================================================")
print(f"MASTER CANDIDATES EVALUATED: {len(RAW_MASTER)}")
print(f"SKIPPED DUPLICATES:          {skipped_dups}")
print(f"APPROVED PURE NEW B2B FLEET: {len(verified_track_c)}")
print(f"=======================================================")

# City breakdown
city_counts = {}
for c in verified_track_c:
    k = f"{c['governorate']} - {c['district']}"
    city_counts[k] = city_counts.get(k, 0) + 1

for k, v in sorted(city_counts.items(), key=lambda x: -x[1]):
    print(f"  {k:45s}: {v} companies")

out_path = 'scraper/output/track_c_verified_b2b_fleet.json'
with open(out_path, 'w', encoding='utf-8') as f:
    json.dump(verified_track_c, f, ensure_ascii=False, indent=2)

print(f"\nSaved master pristine Track C verified records to: {out_path}")
