/**
 * scripts/wave7_data_part1.js
 * Part 1 of Wave 7 Titans (eg_titan_701 to eg_titan_750) - 50 Industrial Titans.
 * Sectors: Ready-Mix Concrete Batching Plants, Heavy Construction & Infrastructure Fleets.
 */

const wave7Part1 = [
  {
    id: "eg_titan_701",
    nameAr: "شركة قنديل للخرسانة الجاهزة (مجمعات محطات القاهرة الجديدة والعاصمة)",
    nameEn: "Kandeel Ready-Mix Concrete (New Cairo & New Capital Plants)",
    sector: "building_materials",
    subSector: "محطات خلط خرسانة مركزية وأساطيل خلاطات ومضخات عملاقة للمشروعات القومية",
    city: "cairo",
    governorate: "القاهرة",
    address: "المنطقة الصناعية - الألف مصنع، التجمع الخامس، القاهرة الجديدة",
    phone1: "0228108100",
    mobile: "01007788101",
    hotline: "19833",
    website: "https://www.kandeelgroup.com",
    latitude: 30.0124,
    longitude: 31.4589,
    fleetSize: 145,
    fleetType: "سيارات خلاطة خرسانة 10م3 و12م3، مضخات خرسانة ذراع 42م إلى 56م، وتريلات نقل أسمنت سائب",
    fleetTires: "315/80R22.5 • 385/65R22.5 • 12.00R24",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "من كبرى شركات الخرسانة الجاهزة المشاركة في المشروعات القومية الكبرى بالعاصمة الإدارية والتجمع",
    contactPerson: "مدير عام تشغيل محطات الخرسانة والأسطول",
    contactTitle: "Ready-Mix Operations & Fleet General Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.0124,31.4589"
  },
  {
    id: "eg_titan_702",
    nameAr: "شركة يوني ميكس مصر للخرسانة الجاهزة (UniMix Egypt)",
    nameEn: "UniMix Egypt Ready-Mix Concrete Mega Fleet",
    sector: "building_materials",
    subSector: "إنتاج وتوريد الخرسانة الجاهزة ومضخات الصب العالي للأبراج وناطحات السحاب",
    city: "giza",
    governorate: "الجيزة",
    address: "المنطقة الصناعية الرابعة، السادس من أكتوبر، الجيزة",
    phone1: "0238209200",
    mobile: "01002233441",
    hotline: "19602",
    website: "https://www.unimixegypt.com",
    latitude: 29.9541,
    longitude: 30.9125,
    fleetSize: 130,
    fleetType: "خلاطات خرسانة ألمانية وإيطالية، مضخات ثابتة للأبراج، ومضخات متحركة شافي وشوينج",
    fleetTires: "315/80R22.5 • 12.00R20 • 385/65R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "المورد الاستراتيجي لمشروعات الأبراج والكباري والمجمعات السكنية العملاقة بغرب القاهرة",
    contactPerson: "رئيس قطاع الحركة والنقل الثقيل",
    contactTitle: "Head of Fleet & Heavy Transport",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.9541,30.9125"
  },
  {
    id: "eg_titan_703",
    nameAr: "شركة ريدكون للخرسانة الجاهزة (Redcon Ready-Mix Concrete)",
    nameEn: "Redcon Ready-Mix Concrete Plants & Transport Fleet",
    sector: "building_materials",
    subSector: "محطات خرسانة عالية الإجهاد وأساطيل نقل لوجستي للإنشاءات المتطورة",
    city: "cairo",
    governorate: "القاهرة",
    address: "منطقة البنوك، التجمع الخامس، القاهرة الجديدة",
    phone1: "0225368300",
    mobile: "01009988772",
    hotline: "19721",
    website: "https://www.redconmix.com",
    latitude: 30.0245,
    longitude: 31.4789,
    fleetSize: 120,
    fleetType: "خلاطات خرسانة مرسيدس ومان، مضخات خرسانة عملاقة، وسيارت قلاب لنقل السن والرمل",
    fleetTires: "315/80R22.5 • 12.00R24 • 385/65R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الذراع الخرساني والإنشائي المتخصص لمجموعة ريدكون للتعمير بالمشروعات الذكية",
    contactPerson: "مدير صيانة الأسطول والمعدات الثقيلة",
    contactTitle: "Fleet Maintenance & Heavy Machinery Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.0245,31.4789"
  },
  {
    id: "eg_titan_704",
    nameAr: "شركة أسيك للخرسانة الجاهزة (Asec Ready-Mix - القلعة القابضة)",
    nameEn: "Asec Ready-Mix Concrete (Qalaa Holdings)",
    sector: "building_materials",
    subSector: "محطات خلط أسيك المركزية ومقالع وتوريد الخرسانات عالية الكفاءة للمطارات والموانئ",
    city: "cairo",
    governorate: "القاهرة",
    address: "أبراج النيل سيتي، كورنيش النيل، بولاق، القاهرة",
    phone1: "0224619400",
    mobile: "01005511223",
    hotline: "16223",
    website: "https://www.asec.com.eg",
    latitude: 30.0715,
    longitude: 31.2294,
    fleetSize: 110,
    fleetType: "أسطول خلاطات حديثة، شاحنات سيلاس نقل الأسمنت السائب، ومعدات صب سريعة",
    fleetTires: "315/80R22.5 • 12.00R20 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الكيان الخرساني الاستراتيجي التابع لأسيك ومجموعة القلعة في مشروعات الطاقة والبنية التحتية",
    contactPerson: "مدير النقل والتشغيل الميداني",
    contactTitle: "Transport & Field Operations Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.0715,31.2294"
  },
  {
    id: "eg_titan_705",
    nameAr: "شركة مصر ريدي ميكس للخرسانة الجاهزة والمنتجات الأسمنتية",
    nameEn: "Misr Ready-Mix Concrete & Cement Products",
    sector: "building_materials",
    subSector: "محطات خلط خرسانة مركزية ومصانع منتجات أسمنتية سابقة الإجهاد",
    city: "qalyubia",
    governorate: "القليوبية",
    address: "المنطقة الصناعية بأبو زعبل، طريق الإسماعيلية الزراعي، القليوبية",
    phone1: "0133245600",
    mobile: "01008899114",
    hotline: "19315",
    website: "https://www.misrreadymix.com.eg",
    latitude: 30.2458,
    longitude: 31.3587,
    fleetSize: 95,
    fleetType: "خلاطات خرسانة، تريلات نقل بلدورات وبلوكات خرسانية، ومضخات صب محمولة",
    fleetTires: "315/80R22.5 • 12.00R20 • 385/65R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "رائدة تصنيع وتوريد الخرسانات الجاهزة لمشروعات الدلتا والطرق الدائرية الجديدة",
    contactPerson: "رئيس قسم حركة السيارات الثقيلة",
    contactTitle: "Heavy Vehicles Operations Chief",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.2458,31.3587"
  },
  {
    id: "eg_titan_706",
    nameAr: "شركة الفتح للخرسانة الجاهزة والمقاولات (Al Fateh Ready Mix)",
    nameEn: "Al Fateh Ready Mix Concrete & Heavy Fleets",
    sector: "building_materials",
    subSector: "محطات خرسانة وأساطيل نقل ثقيل وتوريدات أسمنتية للمدن الصناعية",
    city: "sharqia",
    governorate: "الشرقية",
    address: "المنطقة الصناعية B4، العاشر من رمضان، محافظة الشرقية",
    phone1: "015411890",
    mobile: "01006655443",
    hotline: "19844",
    website: "https://www.alfateh-concrete.com",
    latitude: 30.3125,
    longitude: 31.7456,
    fleetSize: 105,
    fleetType: "خلاطات خرسانة 12م3، مضخات خرسانة ذراع 52م، وتريلات صهاريج نقل أسمنت وسيليكا",
    fleetTires: "315/80R22.5 • 12.00R24 • 385/65R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "أكبر محطة خرسانة مركزية تخدم مجمعات مصانع العاشر من رمضان وبدر والعاصمة",
    contactPerson: "مدير محطات الخلط وحركة الخلاطات",
    contactTitle: "Batching Plants & Mixers Fleet Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.3125,31.7456"
  },
  {
    id: "eg_titan_707",
    nameAr: "شركة الشروق للخرسانة الجاهزة وأعمال الأساسات العميقة",
    nameEn: "Al Shorouk Ready Mix & Deep Foundations",
    sector: "building_materials",
    subSector: "خلط خرسانة الخوازيق والأساسات العميقة ومحطات خلط متنقلة للمواقع المعزولة",
    city: "cairo",
    governorate: "القاهرة",
    address: "المنطقة الصناعية بالشروق، طريق القاهرة - الإسماعيلية الصحراوي",
    phone1: "0226879100",
    mobile: "01004455887",
    hotline: "19409",
    website: "https://www.alshorouk-concrete.com",
    latitude: 30.1587,
    longitude: 31.6214,
    fleetSize: 90,
    fleetType: "خلاطات خرسانة مان ومرسيدس، مضخات صب خوازيق، وشاحنات خلط سريعة",
    fleetTires: "315/80R22.5 • 12.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "متخصصة في خرسانات الأساسات العميقة والكباري ومحطات القطار الكهربائي الخفيف (LRT)",
    contactPerson: "مدير صيانة المعدات والشاحنات",
    contactTitle: "Equipment & Trucks Maintenance Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.1587,31.6214"
  },
  {
    id: "eg_titan_708",
    nameAr: "شركة المقاولون العرب للخرسانة الجاهزة والمصنعات الأسمنتية",
    nameEn: "Arab Contractors Ready Mix Concrete & Precast Sector",
    sector: "building_materials",
    subSector: "محطات خرسانة كبرى وإنتاج كمرات الكباري والأنفاق سابقة الصب والشد",
    city: "cairo",
    governorate: "القاهرة",
    address: "طريق النصر، الجبل الأخضر، مدينة نصر، القاهرة",
    phone1: "0223422500",
    mobile: "01001122339",
    hotline: "16999",
    website: "https://www.arabcont.com",
    latitude: 30.0612,
    longitude: 31.2985,
    fleetSize: 210,
    fleetType: "خلاطات خرسانة عملاقة، تريلات نقل كمرات كباري عملاقة، ومضخات خرسانة شافي ومرسيدس",
    fleetTires: "315/80R22.5 • 12.00R24 • 385/65R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الذراع الخرساني العملاق لشركة المقاولون العرب لخدمة مشروعات المونوريل والقطار السريع والكباري",
    contactPerson: "رئيس قطاع الخرسانة الجاهزة والمعدات",
    contactTitle: "Head of Ready Mix & Machinery Sector",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.0612,31.2985"
  },
  {
    id: "eg_titan_709",
    nameAr: "مجموعة الخرافي ناشيونال للخرسانة والمشروعات المتكاملة (Kharafi Concrete)",
    nameEn: "Kharafi National Ready Mix & Heavy Projects",
    sector: "building_materials",
    subSector: "محطات خلط خرسانة لمحطات توليد الطاقة والمطارات والمشروعات الصناعية الكبرى",
    city: "giza",
    governorate: "الجيزة",
    address: "طريق مصر الإسكندرية الصحراوي، القرية الذكية، الجيزة",
    phone1: "0235371100",
    mobile: "01003344558",
    hotline: "19234",
    website: "https://www.kharafinational.com",
    latitude: 30.0789,
    longitude: 31.0214,
    fleetSize: 115,
    fleetType: "خلاطات ومضخات خرسانة ذات مواصفات قياسية أمريكية وأوروبية لنقل الخرسانات الكثيفة",
    fleetTires: "315/80R22.5 • 12.00R20 • 385/65R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "مجموعة عالمية رائدة في تنفيذ محطات الكهرباء ومحطات معالجة المياه الضخمة بأسطول دعم هندسي متكامل",
    contactPerson: "مدير عام العمليات اللوجستية والمعدات",
    contactTitle: "Logistics & Heavy Machinery Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.0789,31.0214"
  },
  {
    id: "eg_titan_710",
    nameAr: "شركة هورايزون للخرسانة الجاهزة (Horizon Ready Mix Concrete)",
    nameEn: "Horizon Ready Mix Concrete Mega Plants",
    sector: "building_materials",
    subSector: "توريد الخرسانات عالية المقاومة للكبريتات والأملاح للمشروعات الساحلية والموانئ",
    city: "alexandria",
    governorate: "الإسكندرية",
    address: "المنطقة الصناعية ببرج العرب الجديدة، الإسكندرية",
    phone1: "034591200",
    mobile: "01008811223",
    hotline: "19942",
    website: "https://www.horizon-concrete.com",
    latitude: 30.9124,
    longitude: 29.6789,
    fleetSize: 85,
    fleetType: "خلاطات خرسانة 10م3، مضخات خرسانة بحرية، وشاحنات نقل ركام وأسمنت مقاوم",
    fleetTires: "315/80R22.5 • 12.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "المورد الرئيسي لمشروعات ميناء الإسكندرية الكبير ومحطة تحيا مصر وتوسعات الساحل الشمالي",
    contactPerson: "مدير حركة أسطول الساحل والإسكندرية",
    contactTitle: "Alex & Coast Transport Fleet Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.9124,29.6789"
  },
  {
    id: "eg_titan_711",
    nameAr: "شركة الفرات للخرسانة الجاهزة والاستثمار العقاري",
    nameEn: "Al Forat Ready Mix Concrete & Construction",
    sector: "building_materials",
    subSector: "محطات خلط خرسانة آلية لخدمة المدن الجديدة بالدلتا والقاهرة الكبرى",
    city: "menofia",
    governorate: "المنوفية",
    address: "المنطقة الصناعية بمدينة السادات، محافظة المنوفية",
    phone1: "0482601500",
    mobile: "01007766554",
    hotline: "19881",
    website: "https://www.alforat-concrete.com",
    latitude: 30.3789,
    longitude: 30.5124,
    fleetSize: 80,
    fleetType: "خلاطات خرسانة، تريلات قلاب نقل مواد محجرية، ومضخات صب حديثة",
    fleetTires: "315/80R22.5 • 12.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "تغطي قطاع مدينة السادات ووادي النطرون والمناطق الصناعية بغرب الدلتا",
    contactPerson: "مدير تشغيل الأسطول والمعدات",
    contactTitle: "Fleet & Equipment Operations Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.3789,30.5124"
  },
  {
    id: "eg_titan_712",
    nameAr: "شركة تكنو ميكس للخرسانة الجاهزة والمقاولات (TechnoMix)",
    nameEn: "TechnoMix Ready Mix Concrete Industrial Plants",
    sector: "building_materials",
    subSector: "إنتاج الخرسانات الجافة والرطبة والمقذوفة لأنفاق المترو والمنشآت تحت الأرض",
    city: "cairo",
    governorate: "القاهرة",
    address: "طريق العين السخنة - القطامية، المنطقة الصناعية، القاهرة",
    phone1: "0227591400",
    mobile: "01009944332",
    hotline: "19388",
    website: "https://www.technomix-eg.com",
    latitude: 29.9789,
    longitude: 31.3912,
    fleetSize: 95,
    fleetType: "معدات خلط خرسانة مقذوفة شوت كريت، خلاطات خرسانة مان، وتريلات قلابات سن",
    fleetTires: "315/80R22.5 • 12.00R24 • 385/65R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "رائدة مشروعات صب أنفاق مترو الأنفاق والأنفاق التحت أرضية بالقطامية والعين السخنة",
    contactPerson: "رئيس قسم النقل والورش المركزية",
    contactTitle: "Central Workshops & Transport Chief",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.9789,31.3912"
  },
  {
    id: "eg_titan_713",
    nameAr: "شركة السويس للخرسانة الجاهزة (Suez Ready-Mix - هايدلبرج ماتيريالز)",
    nameEn: "Suez Ready-Mix Concrete (Heidelberg Materials)",
    sector: "building_materials",
    subSector: "الذراع الخرساني لشركة السويس للأسمنت عبر شبكة محطات تغطي محافظات الجمهورية",
    city: "suez",
    governorate: "السويس",
    address: "المنطقة الصناعية بالعين السخنة، السويس",
    phone1: "0623710500",
    mobile: "01003311990",
    hotline: "19455",
    website: "https://www.heidelbergmaterials.com.eg",
    latitude: 29.6245,
    longitude: 32.3456,
    fleetSize: 160,
    fleetType: "أسطول خلاطات مرسيدس أكتروس، مضخات خرسانة عملاقة، وسيلاسات نقل أسمنت بورتلاندي",
    fleetTires: "315/80R22.5 • 385/65R22.5 • 12.00R24",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الشركة التابعة لمجموعة هايدلبرج ماتيريالز الألمانية العالمية بطاقة إنتاجية وأسطول هائل",
    contactPerson: "مدير عام اللوجستيات وسلاسل الإمداد",
    contactTitle: "Supply Chain & Logistics General Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.6245,32.3456"
  },
  {
    id: "eg_titan_714",
    nameAr: "شركة تايجر ميكس للخرسانة الجاهزة والإنشاءات (Tiger Mix)",
    nameEn: "Tiger Mix Ready Mix Concrete Co.",
    sector: "building_materials",
    subSector: "محطات خلط خرسانة سريعة الشك والتصلد للمشروعات العاجلة والكبارى السطحية",
    city: "giza",
    governorate: "الجيزة",
    address: "طريق دهشور الصناعي، السادس من أكتوبر، الجيزة",
    phone1: "0238356100",
    mobile: "01005522881",
    hotline: "19876",
    website: "https://www.tigermix-eg.com",
    latitude: 29.9891,
    longitude: 30.8954,
    fleetSize: 75,
    fleetType: "خلاطات خرسانة، مضخات خرسانة، وشاحنات خلط متنقلة للمواقع المفتوحة",
    fleetTires: "315/80R22.5 • 12.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "شريك رئيسي في مشروعات الإسكان الاجتماعي وتوسعات طريق الواحات ومحاور 6 أكتوبر",
    contactPerson: "مدير حركة السيارات والآليات",
    contactTitle: "Vehicles & Heavy Fleets Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.9891,30.8954"
  },
  {
    id: "eg_titan_715",
    nameAr: "شركة الدلتا للخرسانة الجاهزة وصناعة مواسير الخرسانة المسلحة",
    nameEn: "Delta Ready Mix & Reinforced Concrete Pipes Co.",
    sector: "building_materials",
    subSector: "إنتاج مواسير الخرسانة المسلحة لشبكات الصرف الصحي العملاقة والري ومحطات الخرسانة",
    city: "gharbia",
    governorate: "الغربية",
    address: "طريق طنطا - المحلة الكبرى، المنطقة الصناعية، الغربية",
    phone1: "0403418500",
    mobile: "01004477112",
    hotline: "19732",
    website: "https://www.delta-concrete-pipes.com",
    latitude: 30.8124,
    longitude: 31.0214,
    fleetSize: 85,
    fleetType: "تريلات تريلا فرش نقل مواسير خرسانية عملاقة، خلاطات، وروافع هيدروليكية ثقيلة",
    fleetTires: "315/80R22.5 • 12.00R20 • 385/65R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "مورد معتمد لوزارة الإسكان والهيئة القومية لمياه الشرب والصرف الصحي بمشروعات حياة كريمة",
    contactPerson: "رئيس قطاع النقل والمهمات الميدانية",
    contactTitle: "Transport & Field Missions Chief",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.8124,31.0214"
  },
  {
    id: "eg_titan_716",
    nameAr: "شركة سيمبور للخرسانة الجاهزة وصناعة الفلنكات الخرسانية (Cimpor)",
    nameEn: "Cimpor Ready-Mix & Concrete Railway Sleepers",
    sector: "building_materials",
    subSector: "تصنيع فلنكات السكك الحديدية الخرسانية للقطار السريع ومحطات الخرسانة",
    city: "suez",
    governorate: "السويس",
    address: "المنطقة الاقتصادية لقناة السويس، العين السخنة، السويس",
    phone1: "0623910200",
    mobile: "01001199445",
    hotline: "19667",
    website: "https://www.cimpor.com.eg",
    latitude: 29.6789,
    longitude: 32.3124,
    fleetSize: 100,
    fleetType: "شاحنات نقل فلنكات خرسانية، خلاطات مركزية، ومقطورات نقل ثقيل هيدروليكية",
    fleetTires: "315/80R22.5 • 385/65R22.5 • 12.00R24",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "المصنع القومي لتوريد فلنكات مسار الخط الأول والثاني للقطار الكهربائي السريع في مصر",
    contactPerson: "مدير عام النقل واللوجستيات للمشروعات القومية",
    contactTitle: "National Projects Transport General Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.6789,32.3124"
  },
  {
    id: "eg_titan_717",
    nameAr: "شركة النيل للخرسانة الجاهزة ومنتجات الأسمنت (Nile Mix)",
    nameEn: "Nile Mix Ready Concrete & Cement Products",
    sector: "building_materials",
    subSector: "محطات خلط أسمنتية وخرسانات خاصة لحماية مجرى نهر النيل وتبطين الترع",
    city: "giza",
    governorate: "الجيزة",
    address: "المنطقة الصناعية بعرب أبو ساعد، الصف، الجيزة",
    phone1: "0238812400",
    mobile: "01006611332",
    hotline: "19543",
    website: "https://www.nilemix-eg.com",
    latitude: 29.7456,
    longitude: 31.3124,
    fleetSize: 90,
    fleetType: "خلاطات خرسانة، تريلات قلاب نقل كتل حجرية، ومضخات صب شاطئية",
    fleetTires: "315/80R22.5 • 12.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "مشاركة في المشروعات القومية لتبطين الترع وتطوير واجهات نهر النيل بمحافظات الجيزة وبني سويف",
    contactPerson: "مدير صيانة السيارات والحركة",
    contactTitle: "Fleet Maintenance & Movements Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.7456,31.3124"
  },
  {
    id: "eg_titan_718",
    nameAr: "شركة إيجيبت ريدي ميكس (Egypt Ready Mix - مجموعة درة)",
    nameEn: "Egypt Ready Mix (Dorra Group)",
    sector: "building_materials",
    subSector: "محطات خلط خرسانة فاخرة للمشروعات المعمارية والكمبوندات الفاخرة بغرب القاهرة",
    city: "giza",
    governorate: "الجيزة",
    address: "الشيخ زايد، مدخل 2، محافظة الجيزة",
    phone1: "0238514100",
    mobile: "01002288994",
    hotline: "19789",
    website: "https://www.dorra.com",
    latitude: 30.0456,
    longitude: 30.9876,
    fleetSize: 85,
    fleetType: "خلاطات خرسانة مرسيدس، مضخات خرسانة، وشاحنات خلط متنقلة للخرسانة الملونة والديكورية",
    fleetTires: "315/80R22.5 • 12.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الذراع الخرساني التابع لمجموعة درة العالمية المنفذة لكبرى مشروعات زايد وأكتوبر",
    contactPerson: "رئيس قطاع المعدات والنقل المركزي",
    contactTitle: "Central Equipment & Fleet Head",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.0456,30.9876"
  },
  {
    id: "eg_titan_719",
    nameAr: "شركة سيمكس مصر للخرسانة الجاهزة (Cemex Ready Mix Egypt)",
    nameEn: "Cemex Egypt Ready Mix Concrete Industrial Network",
    sector: "building_materials",
    subSector: "شبكة محطات خرسانة تغطي محافظات الصعيد والقاهرة الكبرى والبحر الأحمر",
    city: "assiut",
    governorate: "أسيوط",
    address: "طريق أسيوط - الوادي الجديد، المجمع الصناعي لسيمكس، أسيوط",
    phone1: "0882390100",
    mobile: "01001188334",
    hotline: "19333",
    website: "https://www.cemexegypt.com",
    latitude: 27.1789,
    longitude: 31.0541,
    fleetSize: 175,
    fleetType: "خلاطات خرسانة مان ومرسيدس، تريلات نقل أسمنت بلك، ومضخات صب عالية الارتفاع",
    fleetTires: "315/80R22.5 • 385/65R22.5 • 12.00R24",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "أكبر شبكة محطات خرسانة جاهزة بصعيد مصر تابعة لشركة سيمكس العالمية بطاقة تشغيل جبارة",
    contactPerson: "مدير عام أساطيل النقل بمصر العليا",
    contactTitle: "Upper Egypt Fleets General Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=27.1789,31.0541"
  },
  {
    id: "eg_titan_720",
    nameAr: "شركة العاصمة للخرسانة الجاهزة والتطوير الإنشائي",
    nameEn: "Al Assema Ready Mix Concrete Co.",
    sector: "building_materials",
    subSector: "محطات خلط خرسانة مركزية بالحي الحكومي وحي السفارات بالعاصمة الإدارية",
    city: "cairo",
    governorate: "القاهرة",
    address: "منطقة المحطات المركزية للمشروعات، العاصمة الإدارية الجديدة، القاهرة",
    phone1: "0228491500",
    mobile: "01007744119",
    hotline: "19688",
    website: "https://www.alassema-mix.com",
    latitude: 30.0145,
    longitude: 31.7589,
    fleetSize: 110,
    fleetType: "خلاطات خرسانة 12م3، مضخات خرسانة ذراع 56م، وشاحنات تموين ميداني",
    fleetTires: "315/80R22.5 • 12.00R24 • 385/65R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "متخصصة في توريد الخرسانات العاجلة للوزارات والأحياء السكنية والبرج الأيقوني بالعاصمة الإدارية",
    contactPerson: "مدير العمليات الميدانية والأسطول",
    contactTitle: "Field Operations & Fleet Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.0145,31.7589"
  },
  {
    id: "eg_titan_721",
    nameAr: "شركة الخرسانة الجاهزة المتطورة (Advanced Ready Mix - مجموعة حسن علام)",
    nameEn: "Advanced Ready Mix Concrete (Hassan Allam Holding)",
    sector: "building_materials",
    subSector: "محطات خرسانة متطورة للمطارات ومحطات التحلية ومحطة الضبعة النووية",
    city: "cairo",
    governorate: "القاهرة",
    address: "مبنى حسن علام، شارع الثورة، مصر الجديدة، القاهرة",
    phone1: "0226901800",
    mobile: "01009911225",
    hotline: "16541",
    website: "https://www.hassanallam.com",
    latitude: 30.0891,
    longitude: 31.3412,
    fleetSize: 190,
    fleetType: "خلاطات خرسانة بمواصفات نووية وهندسية متقدمة، ومضخات صب خرسانة ثقيلة",
    fleetTires: "315/80R22.5 • 385/65R22.5 • 12.00R24",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الذراع الخرساني العملاق لتحالف حسن علام في المشروعات القومية والاستراتيجية بمصر",
    contactPerson: "نائب رئيس مجلس الإدارة لشؤون الأسطول والمعدات",
    contactTitle: "Vice President - Fleet & Heavy Machinery",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.0891,31.3412"
  },
  {
    id: "eg_titan_722",
    nameAr: "شركة أسمنت سيناء للخرسانة الجاهزة (Sinai Cement Ready-Mix)",
    nameEn: "Sinai Cement Ready-Mix Concrete Fleet",
    sector: "building_materials",
    subSector: "محطات خلط خرسانة وتوريد للمشروعات القومية لتنمية شبه جزيرة سيناء ومدن القناة",
    city: "ismailia",
    governorate: "الإسماعيلية",
    address: "المنطقة الحرة الاستثمارية، طريق الإسماعيلية - بورسعيد، الإسماعيلية",
    phone1: "0643481200",
    mobile: "01003322119",
    hotline: "19512",
    website: "https://www.sinaicement.com",
    latitude: 30.6124,
    longitude: 32.2891,
    fleetSize: 95,
    fleetType: "خلاطات خرسانة مان، شاحنات نقل أسمنت مقاوم، وتريلات قلابات ركام",
    fleetTires: "315/80R22.5 • 12.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الذراع التشغيلي لمصانع أسمنت سيناء لخدمة مشروعات الأنفاق الجديدة ومدينة شرق بورسعيد والإسماعيلية الجديدة",
    contactPerson: "مدير عام النقل والخدمات اللوجستية بسيناء",
    contactTitle: "Sinai Transport & Logistics General Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.6124,32.2891"
  },
  {
    id: "eg_titan_723",
    nameAr: "شركة تبارك للخرسانة الجاهزة والمصنوعات الإنشائية",
    nameEn: "Tabarak Ready Mix Concrete & Construction Products",
    sector: "building_materials",
    subSector: "محطات خلط وتوريد الخرسانات ومصانع البردورات والإنترلوك الآلي للمدن الجديدة",
    city: "cairo",
    governorate: "القاهرة",
    address: "المنطقة الصناعية ببدر، طريق السويس الصحراوي، القاهرة",
    phone1: "0228641900",
    mobile: "01008822551",
    hotline: "19349",
    website: "https://www.tabarak-mix.com",
    latitude: 30.1456,
    longitude: 31.7124,
    fleetSize: 85,
    fleetType: "خلاطات خرسانة، تريلات نقل بلدورات وبلاط إنترلوك، ولوادر وشاحنات ركام",
    fleetTires: "315/80R22.5 • 12.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "رائدة مشروعات اللاندسكيب والطرق والخرسانات الجاهزة بمدينة بدر وهليوبوليس الجديدة والشروق",
    contactPerson: "مدير تشغيل الأسطول والمعدات الثقيلة",
    contactTitle: "Heavy Machinery & Fleet Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.1456,31.7124"
  },
  {
    id: "eg_titan_724",
    nameAr: "شركة أوراسكوم للخرسانة والمنتجات الأسمنتية (Orascom Ready Mix)",
    nameEn: "Orascom Construction Ready Mix Sector",
    sector: "building_materials",
    subSector: "محطات خلط خرسانة استراتيجية سريعة الإمداد لمشروعات القطار السريع والمترو",
    city: "cairo",
    governorate: "القاهرة",
    address: "أبراج نايل سيتي، برج أوراسكوم، بولاق، القاهرة",
    phone1: "0224611111",
    mobile: "01001144772",
    hotline: "16789",
    website: "https://www.orascom.com",
    latitude: 30.0712,
    longitude: 31.2291,
    fleetSize: 220,
    fleetType: "أضخم أسطول خلاطات ومضخات وتريلات كمرات كباري تابعة لتحالف أوراسكوم للإنشاءات",
    fleetTires: "315/80R22.5 • 385/65R22.5 • 12.00R24",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "المنفذة لأكبر صبات خرسانية في تاريخ الشرق الأوسط بمشروعات محطات الكهرباء العملاقة والمتحف المصري الكبير",
    contactPerson: "مدير عام الأسطول والمعدات بالمجموعة",
    contactTitle: "Group Fleet & Heavy Equipment Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.0712,31.2291"
  },
  {
    id: "eg_titan_725",
    nameAr: "شركة الفنار للخرسانة الجاهزة وأعمال الرصف الخرساني",
    nameEn: "Al Fanar Ready Mix & Concrete Paving Co.",
    sector: "building_materials",
    subSector: "رصف الطرق والممرات الخرسانية للمطارات والموانئ الجافة ومحطات الخرسانة",
    city: "damietta",
    governorate: "دمياط",
    address: "المنطقة الصناعية بميناء دمياط، دمياط",
    phone1: "0572291500",
    mobile: "01005588339",
    hotline: "19812",
    website: "https://www.alfanar-concrete.com",
    latitude: 31.4289,
    longitude: 31.7891,
    fleetSize: 80,
    fleetType: "ماكينات رصف خرساني متطورة، خلاطات خرسانة، وتريلات نقل مواد أسمنتية",
    fleetTires: "315/80R22.5 • 12.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "رائدة مشروعات الرصف الخرساني الحديث للشاحنات الثقيلة بساحات ميناء دمياط وجمصة",
    contactPerson: "رئيس قسم الصيانة والتشغيل",
    contactTitle: "Maintenance & Fleet Operations Chief",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=31.4289,31.7891"
  },
  {
    id: "eg_titan_726",
    nameAr: "شركة إيجيتك للخرسانة الجاهزة والمشروعات الصناعية (EgyTech Mix)",
    nameEn: "EgyTech Ready Mix Concrete & Industrial Projects",
    sector: "building_materials",
    subSector: "محطات خرسانة متخصصة لمصانع البتروكيماويات والأسمدة المقاومة للأحماض والكيماويات",
    city: "alexandria",
    governorate: "الإسكندرية",
    address: "المنطقة الصناعية بالعامرية، الإسكندرية",
    phone1: "034701200",
    mobile: "01003366991",
    hotline: "19641",
    website: "https://www.egytech-mix.com",
    latitude: 31.0245,
    longitude: 29.8124,
    fleetSize: 85,
    fleetType: "خلاطات خرسانة، مضخات خرسانة مضادة للتآكل، وشاحنات خلط مجهزة لبيئات البتروكيماويات",
    fleetTires: "315/80R22.5 • 12.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "متخصصة في صب أرضيات وقواعد مصانع البترول والبتروكيماويات بالعامرية والنهضة",
    contactPerson: "مدير حركة أسطول العامرية وبرج العرب",
    contactTitle: "Amreya Fleet Transport Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=31.0245,29.8124"
  },
  {
    id: "eg_titan_727",
    nameAr: "شركة سيناء للخرسانة الجاهزة والتعدين (جنوب سيناء)",
    nameEn: "South Sinai Ready Mix Concrete & Mining",
    sector: "building_materials",
    subSector: "محطات خلط خرسانة تخدم المشروعات السياحية وتوسعات شرم الشيخ والطور ورأس سدر",
    city: "south_sinai",
    governorate: "جنوب سيناء",
    address: "المنطقة الصناعية بالرويسات، شرم الشيخ، جنوب سيناء",
    phone1: "0693661400",
    mobile: "01007711442",
    hotline: "19754",
    website: "https://www.sinai-readymix.com",
    latitude: 27.9156,
    longitude: 34.3124,
    fleetSize: 75,
    fleetType: "خلاطات خرسانة جبلية، مضخات صب عالية، وتريلات نقل أسمنت من مصانع السويس",
    fleetTires: "315/80R22.5 • 12.00R24",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الصرح الخرساني الأول لخدمة المشروعات الفندقية وتوسعات قمة المناخ والمطار بشرم الشيخ",
    contactPerson: "مدير فرع جنوب سيناء وحركة الأسطول",
    contactTitle: "South Sinai Branch & Transport Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=27.9156,34.3124"
  },
  {
    id: "eg_titan_728",
    nameAr: "شركة الصعيد للخرسانة الجاهزة وتصنيع أعمدة الإنارة الخرسانية",
    nameEn: "Upper Egypt Ready Mix & Concrete Poles Manufacturing",
    sector: "building_materials",
    subSector: "تصنيع أعمدة الإنارة الخرسانية الدائرية والمفرغة ومحطات خلط الخرسانة بالمنيا وأسيوط",
    city: "minya",
    governorate: "المنيا",
    address: "المنطقة الصناعية بالمطاهرة، شرق النيل، المنيا",
    phone1: "0862319200",
    mobile: "01008844116",
    hotline: "19488",
    website: "https://www.upperegypt-concrete.com",
    latitude: 28.0891,
    longitude: 30.7891,
    fleetSize: 90,
    fleetType: "تريلات تريلا فرش نقل أعمدة خرسانية، خلاطات خرسانة، وشاحنات صب ميدانية",
    fleetTires: "315/80R22.5 • 12.00R20 • 385/65R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "المورد المعتمد للشركة القابضة لكهرباء مصر وشبكات الإنارة لمبادرة حياة كريمة بصعيد مصر",
    contactPerson: "مدير عام الورش المركزية والنقل",
    contactTitle: "Central Workshops & Transport General Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=28.0891,30.7891"
  },
  {
    id: "eg_titan_729",
    nameAr: "شركة البناء الحديث للخرسانة الجاهزة (Modern Building Mix - CMB)",
    nameEn: "Modern Building Mix (CMB Group)",
    sector: "building_materials",
    subSector: "محطات خلط خرسانات متطورة بإضافات كيماوية ذاتية الدمك ومقاومة لنفاذية المياه",
    city: "giza",
    governorate: "الجيزة",
    address: "المنطقة الصناعية الأولى، السادس من أكتوبر، الجيزة",
    phone1: "0238334400",
    mobile: "01002255883",
    hotline: "19918",
    website: "https://www.cmbegypt.com",
    latitude: 29.9712,
    longitude: 30.9345,
    fleetSize: 85,
    fleetType: "خلاطات خرسانة بمواصفات إضافات CMB، مضخات خرسانة ذكية، وتريلات صهاريج إضافات كيميائية",
    fleetTires: "315/80R22.5 • 12.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الذراع الخرساني والإنشائي التابع لمجموعة كيماويات البناء الحديث الرائدة في الشرق الأوسط",
    contactPerson: "مدير الدعم اللوجستي والمعدات",
    contactTitle: "Logistics Support & Machinery Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.9712,30.9345"
  },
  {
    id: "eg_titan_730",
    nameAr: "شركة مصر بني سويف للخرسانة الجاهزة والاستثمار الصناعي",
    nameEn: "Misr Beni Suef Ready Mix Concrete Fleet",
    sector: "building_materials",
    subSector: "محطات خلط خرسانة مركزية لخدمة المجمعات التكنولوجية ومصانع الإلكترونيات ببني سويف",
    city: "beni_suef",
    governorate: "بني سويف",
    address: "منطقة بياض العرب الصناعية، شرق النيل، بني سويف",
    phone1: "0822241500",
    mobile: "01004411993",
    hotline: "19366",
    website: "https://www.misr-benisuef-mix.com",
    latitude: 29.0456,
    longitude: 31.1245,
    fleetSize: 80,
    fleetType: "خلاطات خرسانة مرسيدس، مضخات خرسانة ذراع 47م، وتريلات شحن أسمنت وركام",
    fleetTires: "315/80R22.5 • 12.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "شريك التشييد الأول لمصانع التكنولوجيا ومحطة كهرباء بني سويف العملاقة المركبة",
    contactPerson: "مدير حركة محطات شرق النيل",
    contactTitle: "East Nile Plants Transport Head",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.0456,31.1245"
  },
  {
    id: "eg_titan_731",
    nameAr: "شركة سامكو الوطنية للتشييد وإدارة محطات الخرسانة (Samco Concrete)",
    nameEn: "Samco National Concrete & Construction Mega Fleet",
    sector: "construction",
    subSector: "محطات خرسانة متنقلة وأساطيل عملاقة لإنشاء المحاور والكباري والطرق السريعة بمصر",
    city: "giza",
    governorate: "الجيزة",
    address: "طريق مصر الإسكندرية الصحراوي، الكيلو 28، الجيزة",
    phone1: "0235391200",
    mobile: "01009933441",
    hotline: "19588",
    website: "https://www.samco-egypt.com",
    latitude: 30.0489,
    longitude: 31.0589,
    fleetSize: 240,
    fleetType: "تريلات تريلا فرش ثقيل، خلاطات خرسانة، لوادر كتربيلر، وحفارات وماكينات رصف أسفلت وخلاطات خرسانة",
    fleetTires: "315/80R22.5 • 385/65R22.5 • 12.00R24 • 14.00R24",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "من أضخم شركات المقاولات المصرية المنفذة لشبكة الطرق والمحاور القومية (محور 26 يوليو الجديد والدائري الأوسطي)",
    contactPerson: "نائب رئيس مجلس الإدارة للأسطول والمعدات الثقيلة",
    contactTitle: "Vice President - Heavy Fleets & Machinery",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.0489,31.0589"
  },
  {
    id: "eg_titan_732",
    nameAr: "شركة رواد الهندسة الحديثة (Rowad Modern Engineering - RME)",
    nameEn: "Rowad Modern Engineering (RME Infrastructure Fleet)",
    sector: "construction",
    subSector: "المقاولات الكبرى للأنفاق والكباري ومحطات القطار السريع والمباني الشاهقة",
    city: "cairo",
    governorate: "القاهرة",
    address: "القطاع الثاني، مركز المدينة، التجمع الخامس، القاهرة الجديدة",
    phone1: "0228131500",
    mobile: "01001188995",
    hotline: "16345",
    website: "https://www.rowad-rme.com",
    latitude: 30.0189,
    longitude: 31.4312,
    fleetSize: 210,
    fleetType: "أوناش برجية عملاقة، تريلات شحن ثقيل، أساطيل نقل مهندسين وعمال، ومعدات حفر أنفاق متقدمة",
    fleetTires: "315/80R22.5 • 385/65R22.5 • 12.00R20 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "من رواد المقاولات العامة التابعة لمجموعة السويدي والمنفذة لمحطات ومسارات المونوريل والأبراج الإدارية",
    contactPerson: "مدير عام الإمداد والخدمات اللوجستية للمشروعات",
    contactTitle: "Logistics & Projects Supply General Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.0189,31.4312"
  },
  {
    id: "eg_titan_733",
    nameAr: "شركة سياك للتشييد والبناء (SIAC Construction Mega Fleet)",
    nameEn: "SIAC Construction & Industrial Engineering",
    sector: "construction",
    subSector: "تنفيذ المجمعات الصناعية الكبرى ومحطات الكهرباء والمباني الإدارية المتطورة",
    city: "cairo",
    governorate: "القاهرة",
    address: "منطقة البنوك، شارع التسعين، التجمع الخامس، القاهرة الجديدة",
    phone1: "0226149000",
    mobile: "01003355882",
    hotline: "19655",
    website: "https://www.siac.com.eg",
    latitude: 30.0278,
    longitude: 31.4678,
    fleetSize: 185,
    fleetType: "شاحنات نقل ثقيل، أوناش هيدروليكية تادانو وليهبر، لوادر، وأتوبيسات نقل كوادر هندسية",
    fleetTires: "315/80R22.5 • 385/65R22.5 • 12.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "من أقدم وأعرق شركات المقاولات المصرية الرائدة في تنفيذ المباني الوزارية بالعاصمة الإدارية ومصانع الإلكترونيات",
    contactPerson: "رئيس قطاع الحركة ومعدات البناء",
    contactTitle: "Head of Machinery & Transport Fleets",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.0278,31.4678"
  },
  {
    id: "eg_titan_734",
    nameAr: "شركة الغرابلي للأعمال الهندسية المتكاملة (Al Gharably Integrated Engineering)",
    nameEn: "Al Gharably Integrated Engineering (Ports & Marine Fleet)",
    sector: "construction",
    subSector: "تطوير وتوسيع الموانئ البحرية والأرصفة والحواجز المائية ومشروعات تعميق القنوات",
    city: "alexandria",
    governorate: "الإسكندرية",
    address: "طريق الجيش، لوران، الإسكندرية",
    phone1: "035841900",
    mobile: "01005599221",
    hotline: "19289",
    website: "https://www.algharably.com",
    latitude: 31.2456,
    longitude: 29.9789,
    fleetSize: 220,
    fleetType: "قاطرات بحرية، كراكات عملاقة، تريلات هيفي ديوتي نقل كتل صخرية وخرسانية للموانئ، ومعدات حفر أعماق",
    fleetTires: "315/80R22.5 • 12.00R24 • 385/65R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "المنفذ القومي لأكبر مشروعات الأرصفة والحواجز البحرية بميناء الإسكندرية وأبو قير البحري الجديد",
    contactPerson: "مدير عام الأسطول البحري والبري الثقيل",
    contactTitle: "Marine & Heavy Land Fleet General Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=31.2456,29.9789"
  },
  {
    id: "eg_titan_735",
    nameAr: "شركة النصر العامة للمقاولات (حسن محمد علام - قطاع الأعمال العام)",
    nameEn: "El Nasr General Contracting (Hassan Allam Public Sector)",
    sector: "construction",
    subSector: "تنفيذ الكباري العلوية، الأنفاق، شبكات المياه والصرف الصحي العملاقة بالمحافظات",
    city: "cairo",
    governorate: "القاهرة",
    address: "شارع عبد الخالق ثروت، وسط البلد، القاهرة",
    phone1: "0223932400",
    mobile: "01002244668",
    hotline: "19412",
    website: "https://www.allamcont.gov.eg",
    latitude: 30.0512,
    longitude: 31.2412,
    fleetSize: 260,
    fleetType: "أساطيل شاحنات قلاب، ماكينات دق خوازيق، تريلات نقل مواسير مياه عملاقة، وحفارات",
    fleetTires: "315/80R22.5 • 12.00R20 • 385/65R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الصرح الوطني التاريخي التابع للشركة القابضة للتشييد والتعمير برصيد إنجاز يمتد لعقود في كافة ربوع مصر",
    contactPerson: "رئيس قطاعات المعدات والتشغيل الميكانيكي",
    contactTitle: "Mechanical Equipment & Fleets Chief",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.0512,31.2412"
  },
  {
    id: "eg_titan_736",
    nameAr: "شركة الجيزة العامة للمقاولات والاستثمار العقاري",
    nameEn: "Giza General Contracting & Real Estate Investment",
    sector: "construction",
    subSector: "إنشاء المدن السكنية الجديدة، محطات تنقية المياه، ومجمعات المدارس والجامعات التكنولوجية",
    city: "giza",
    governorate: "الجيزة",
    address: "شارع البطل أحمد عبد العزيز، المهندسين، الجيزة",
    phone1: "0237612800",
    mobile: "01007733221",
    hotline: "19321",
    website: "https://www.gizacontracting.com",
    latitude: 30.0541,
    longitude: 31.2014,
    fleetSize: 135,
    fleetType: "سيارات نقل ثقيل، لوادر، حفارات، أوناش برجية، وأتوبيسات نقل عمال المشروعات",
    fleetTires: "315/80R22.5 • 12.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "إحدى كبرى شركات المقاولات العامة المقيدة بالبورصة المصرية والمنفذة لآلاف الوحدات السكنية القومية",
    contactPerson: "مدير إدارة الحركة والتشغيل",
    contactTitle: "Movement & Transport Department Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.0541,31.2014"
  },
  {
    id: "eg_titan_737",
    nameAr: "شركة العبد للمقاولات العامة (المساهمة المصرية للمقاولات)",
    nameEn: "Al Abd General Contracting (El Abd Mega Fleet)",
    sector: "construction",
    subSector: "مشروعات البنية التحتية القومية، شبكات الصرف الصحي، ومحطات معالجة مياه الشرب",
    city: "cairo",
    governorate: "القاهرة",
    address: "شارع طلعت حرب، وسط البلد، القاهرة",
    phone1: "0223924500",
    mobile: "01008855223",
    hotline: "19714",
    website: "https://www.elabdef.gov.eg",
    latitude: 30.0489,
    longitude: 31.2389,
    fleetSize: 155,
    fleetType: "شاحنات نقل ثقيل، حفارات كوماتسو وهيونداي، لوادر، وتريلات قلابات صخور",
    fleetTires: "315/80R22.5 • 12.00R20 • 385/65R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "قلعة المقاولات الحكومية التابعة للقابضة للتشييد والتعمير المتخصصة في البنية التحتية للمحافظات",
    contactPerson: "مدير عام الشؤون الميكانيكية والسيارات",
    contactTitle: "Mechanical Affairs & Transport General Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.0489,31.2389"
  },
  {
    id: "eg_titan_738",
    nameAr: "شركة مصر لأعمال الأسمنت المسلح (إحدى قلاع قطاع الأعمال العام)",
    nameEn: "Misr Reinforced Cement Works Co.",
    sector: "construction",
    subSector: "تنفيذ الصوامع الخرسانية لتخزين الحبوب، كباري السكك الحديدية، والأرصفة البحرية",
    city: "cairo",
    governorate: "القاهرة",
    address: "شارع 26 يوليو، وسط البلد، القاهرة",
    phone1: "0225741800",
    mobile: "01004488339",
    hotline: "19622",
    website: "https://www.cement-works.gov.eg",
    latitude: 30.0578,
    longitude: 31.2456,
    fleetSize: 165,
    fleetType: "شاحنات نقل ثقيل وتريلات هيدروليكية، ماكينات صب صوامع متسلقة، وأوناش ضخمة",
    fleetTires: "315/80R22.5 • 12.00R24 • 385/65R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الصرح الوطني الأقدم المتخصص في تنفيذ صوامع القمح القومية وأعقد منشآت الأسمنت المسلح بمصر",
    contactPerson: "رئيس قطاع الأسطول والمستودعات المركزية",
    contactTitle: "Head of Fleet & Central Warehouses",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.0578,31.2456"
  },
  {
    id: "eg_titan_739",
    nameAr: "شركة أندلسية للإنشاءات والمقاولات المتخصصة",
    nameEn: "Andalusia Construction & Engineering Mega Fleet",
    sector: "construction",
    subSector: "إنشاء المجمعات الطبية والمستشفيات الذكية والمباني التخصصية الكبرى",
    city: "alexandria",
    governorate: "الإسكندرية",
    address: "طريق الحرية، سموحة، الإسكندرية",
    phone1: "034291100",
    mobile: "01006622884",
    hotline: "19144",
    website: "https://www.andalusia-construction.com",
    latitude: 31.2124,
    longitude: 29.9456,
    fleetSize: 95,
    fleetType: "شاحنات نقل مواد تشطيب ومستلزمات كهروميكانيكية، أوناش، ومقطورات نقل ثقيل",
    fleetTires: "315/80R22.5 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "رائدة تشييد وتجهيز المنشآت الطبية الكبرى والمستشفيات الجامعية في الإسكندرية والقاهرة",
    contactPerson: "مدير المعدات واللوجستيات الهندسية",
    contactTitle: "Engineering Machinery & Logistics Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=31.2124,29.9456"
  },
  {
    id: "eg_titan_740",
    nameAr: "شركة السلام إنترناشيونال للإنشاءات والمقاولات العامة (SICC)",
    nameEn: "Al Salam International Construction & Contracting",
    sector: "construction",
    subSector: "مشروعات الطرق والكباري والأنفاق والمدن الذكية والمطارات الدولية",
    city: "cairo",
    governorate: "القاهرة",
    address: "شارع المشير طنطاوي، التجمع الخامس، القاهرة الجديدة",
    phone1: "0225641200",
    mobile: "01009966114",
    hotline: "19890",
    website: "https://www.salam-icc.com",
    latitude: 30.0189,
    longitude: 31.3985,
    fleetSize: 140,
    fleetType: "لوادر كتربيلر، تريلات قلاب حمولة 50 طن، هراسات أسفلت، وخلاطات أسفلت متنقلة",
    fleetTires: "315/80R22.5 • 12.00R24 • 385/65R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "من مقاولي الفئة الأولى المشاركين في تنفيذ محاور شرق القاهرة والعاصمة الإدارية وطريق الجلالة",
    contactPerson: "رئيس قطاع صيانة المعدات وحركة السيارات",
    contactTitle: "Machinery Maintenance & Fleets Head",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.0189,31.3985"
  },
  {
    id: "eg_titan_741",
    nameAr: "شركة الدلتا للرصف والمقاولات العامة (Delta Paving & Roads)",
    nameEn: "Delta Roads Paving & Contracting Mega Fleet",
    sector: "construction",
    subSector: "إنشاء ورصف شبكات الطرق السريعة والإقليمية وتوريد الخلطات الأسفلتية",
    city: "dakahlia",
    governorate: "الدقهلية",
    address: "طريق المنصورة - دمياط السريع، طلخا، الدقهلية",
    phone1: "0502521800",
    mobile: "01003388225",
    hotline: "19762",
    website: "https://www.delta-paving.com",
    latitude: 31.0541,
    longitude: 31.3789,
    fleetSize: 125,
    fleetType: "فينيشرات أسفلت ألمانية، هراسات حديد ومطاط، تريلات قلاب نقل خلطات ساخنة، وتريلات صهاريج بيتومين",
    fleetTires: "315/80R22.5 • 12.00R20 • 385/65R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الصرح المتخصص الأول في رصف الطرق الحرة وتطوير محاور الدلتا وميناء المنصورة الجاف",
    contactPerson: "مدير عام أسطول النقل والخلاطات الأسفلتية",
    contactTitle: "Asphalt Plants & Transport General Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=31.0541,31.3789"
  },
  {
    id: "eg_titan_742",
    nameAr: "شركة وادي النيل للمقاولات والاستثمارات العقارية (Wadi El Nile)",
    nameEn: "Wadi El Nile General Contracting & Investment",
    sector: "construction",
    subSector: "المشروعات القومية لتطوير المستشفيات، المدارس، والمجمعات الإدارية والخدمية بالمحافظات",
    city: "cairo",
    governorate: "القاهرة",
    address: "شارع الثورة، مصر الجديدة، القاهرة",
    phone1: "0224181900",
    mobile: "01001155998",
    hotline: "16881",
    website: "https://www.wadielnile.com.eg",
    latitude: 30.0894,
    longitude: 31.3389,
    fleetSize: 170,
    fleetType: "شاحنات نقل مواد بناء، أوناش هيدروليكية، سيارات فانات مجهزة، وأسطول دعم ميداني شامل",
    fleetTires: "315/80R22.5 • 295/80R22.5 • 12.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "إحدى أضخم وأهم شركات المقاولات العامة التنموية المشاركة في مشروعات منظومة التأمين الصحي الشامل",
    contactPerson: "مدير عام إدارة النقل ومتابعة المشروعات",
    contactTitle: "Transport & Projects Follow-up Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.0894,31.3389"
  },
  {
    id: "eg_titan_743",
    nameAr: "شركة مدكور للمشروعات الهندسية والطاقة (Madkour Group Mega Fleet)",
    nameEn: "Madkour Group for Engineering Projects & Energy Fleets",
    sector: "construction",
    subSector: "محطات محولات الجهد الفائق، محطات الطاقة الشمسية، ومحطات رفع المياه بمشروع توشكى والدلتا الجديدة",
    city: "cairo",
    governorate: "القاهرة",
    address: "المجمع الإداري بمحور المشير، التجمع الخامس، القاهرة",
    phone1: "0225619100",
    mobile: "01007722993",
    hotline: "19972",
    website: "https://www.madkour.com.eg",
    latitude: 30.0214,
    longitude: 31.4125,
    fleetSize: 150,
    fleetType: "تريلات تريلا فرش نقل محولات عملاقة، أوناش رفع ثقيل حتى 250 طن، وسيارات دفع رباعي للصحراء",
    fleetTires: "315/80R22.5 • 385/65R22.5 • 12.00R24 • 245/75R16",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "رائدة تنفيذ البنية التحتية الكهربائية ومحطات الرفع العملاقة في توشكى والدلتا الجديدة ومستقبل مصر",
    contactPerson: "مدير اللوجستيات والمعدات الثقيلة بالمواقع الصحراوية",
    contactTitle: "Desert Sites Machinery & Logistics Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.0214,31.4125"
  },
  {
    id: "eg_titan_744",
    nameAr: "الشركة المصرية لمشروعات الطاقة والنقل (إنبيكو - Enpico Mega Fleet)",
    nameEn: "Egyptian Projects for Energy & Transport (Enpico)",
    sector: "construction",
    subSector: "مد خطوط الأنابيب البترولية العملاقة ومحطات ضخ الغاز الطبيعي والمياه الاستراتيجية",
    city: "cairo",
    governorate: "القاهرة",
    address: "المنطقة الأولى، مدينة نصر، القاهرة",
    phone1: "0222619400",
    mobile: "01004466228",
    hotline: "19379",
    website: "https://www.enpico.com.eg",
    latitude: 30.0612,
    longitude: 31.3289,
    fleetSize: 130,
    fleetType: "ماكينات حفر خنادق أنابيب، تريلات نقل مواسير صلب 48 بوصة، ومعدات لحام أنابيب متنقلة",
    fleetTires: "315/80R22.5 • 12.00R20 • 385/65R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "متخصصة في مشروعات مد شبكات الغاز والمياه الوطنية العملاقة عبر الصحراء والمحافظات",
    contactPerson: "مدير صيانة الأسطول الميكانيكي",
    contactTitle: "Mechanical Fleet Maintenance Head",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.0612,31.3289"
  },
  {
    id: "eg_titan_745",
    nameAr: "شركة الإنشاءات الهندسية الحديثة (كونكورد - Concorde Mega Infrastructure)",
    nameEn: "Concorde for Engineering & Contracting",
    sector: "construction",
    subSector: "حفر وإنشاء الأنفاق العميقة لقناة السويس والمترو ومحطات الرفع تحت الأرض",
    city: "cairo",
    governorate: "القاهرة",
    address: "شارع التسعين الشمالي، التجمع الخامس، القاهرة الجديدة",
    phone1: "0228129000",
    mobile: "01009922557",
    hotline: "19866",
    website: "https://www.concordeg.com",
    latitude: 30.0345,
    longitude: 31.4891,
    fleetSize: 195,
    fleetType: "معدات وماكينات TBM لحفر الأنفاق، مقطورات هيدروليكية ضخمة، وشاحنات إخلاء نواتج الحفر",
    fleetTires: "315/80R22.5 • 12.00R24 • 385/65R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "المقاول الرئيسي المشارك في حفر أنفاق تحيا مصر بالإسماعيلية وأنفاق السويس ومترو الإسكندرية",
    contactPerson: "نائب رئيس مجلس الإدارة للشؤون الفنية والأسطول",
    contactTitle: "Technical Affairs & Fleets Vice President",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.0345,31.4891"
  },
  {
    id: "eg_titan_746",
    nameAr: "شركة البحر الأحمر العامة للمقاولات (Red Sea General Contracting)",
    nameEn: "Red Sea General Contracting Co.",
    sector: "construction",
    subSector: "تنفيذ الطرق الجبلية الوعرة والمطارات والموانئ التعدينية بمحافظة البحر الأحمر وسيناء",
    city: "red_sea",
    governorate: "البحر الأحمر",
    address: "طريق النصر، الدهار، الغردقة، البحر الأحمر",
    phone1: "0653541800",
    mobile: "01003399118",
    hotline: "19429",
    website: "https://www.redsea-contracting.com",
    latitude: 27.2456,
    longitude: 33.8124,
    fleetSize: 110,
    fleetType: "كسارات صخور متحركة، لوادر صخرية عملاقة، تريلات قلاب جبلية، ومعدات رصف طرق وعرة",
    fleetTires: "315/80R22.5 • 12.00R24 • 14.00R24",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "المتخصصة في شق الطرق الجبلية الساحلية وتطوير موانئ سفاجا والحمراوين والغردقة",
    contactPerson: "مدير قطاع المعدات الثقيلة بالبحر الأحمر",
    contactTitle: "Red Sea Heavy Equipment Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=27.2456,33.8124"
  },
  {
    id: "eg_titan_747",
    nameAr: "شركة القاهرة العامة للمقاولات والاستثمار العقاري",
    nameEn: "Cairo General Contracting & Real Estate Investment",
    sector: "construction",
    subSector: "المشروعات السكنية الكبرى وتطوير العشوائيات والمناطق التاريخية بمحافظة القاهرة",
    city: "cairo",
    governorate: "القاهرة",
    address: "شارع رمسيس، العباسية، القاهرة",
    phone1: "0224821600",
    mobile: "01006644119",
    hotline: "19355",
    website: "https://www.cairo-contracting.gov.eg",
    latitude: 30.0689,
    longitude: 31.2812,
    fleetSize: 125,
    fleetType: "أساطيل شاحنات نقل قلاب، لوادر، أوناش هيدروليكية، وسيارات خدمات فنية",
    fleetTires: "315/80R22.5 • 12.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "إحدى قلاع قطاع الأعمال العام الرائدة في مشروعات تطوير القاهرة الخديوية ومثلث ماسبيرو وسور مجرى العيون",
    contactPerson: "مدير عام النقل والتشغيل الميكانيكي",
    contactTitle: "Mechanical Operations & Transport Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.0689,31.2812"
  },
  {
    id: "eg_titan_748",
    nameAr: "شركة الكراكات المصرية (Egyptian Dredging Company)",
    nameEn: "Egyptian Dredging Company Mega Fleet",
    sector: "construction",
    subSector: "تطهير وتعميق مجاري الأنهار والترع والمصارف القومية والبحيرات الشمالية (المنزلة والبرلس ومريوط)",
    city: "cairo",
    governorate: "القاهرة",
    address: "شارع الجيزة، الدقي، الجيزة",
    phone1: "0237481900",
    mobile: "01008811772",
    hotline: "19639",
    website: "https://www.egyptiandredging.com",
    latitude: 30.0389,
    longitude: 31.2145,
    fleetSize: 135,
    fleetType: "كراكات طمي مائية، حفارات ذراع طويل على صندل، تريلات نقل أتربة وطمي، وشاحنات دعم",
    fleetTires: "315/80R22.5 • 12.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الصرح الوطني الأقدم والأضخم لتكريك وتطوير البحيرات المصرية ومخرات السيول وترع الري بمصر",
    contactPerson: "رئيس قطاعات الكراكات والمعدات الثقيلة",
    contactTitle: "Dredgers & Heavy Fleets Sector Head",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.0389,31.2145"
  },
  {
    id: "eg_titan_749",
    nameAr: "شركة التعمير والاستشارات الهندسية (مجموعة ديار التعمير)",
    nameEn: "Taamir Engineering & Construction (Diar Al Taamir)",
    sector: "construction",
    subSector: "إنشاء المدن الذكية والأبراج التجارية والمراكز اللوجستية المتطورة",
    city: "cairo",
    governorate: "القاهرة",
    address: "شارع مصطفى النحاس، مدينة نصر، القاهرة",
    phone1: "0222718500",
    mobile: "01002266449",
    hotline: "19772",
    website: "https://www.taamir-eg.com",
    latitude: 30.0541,
    longitude: 31.3412,
    fleetSize: 105,
    fleetType: "أوناش رفع مواد بناء، شاحنات نقل حديد وإسمنت، وسيارات نقل طواقم هندسية",
    fleetTires: "315/80R22.5 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "شريك موثوق في تنفيذ المشروعات العقارية والتنموية الكبرى بشرق وغرب القاهرة",
    contactPerson: "مدير صيانة الأسطول المركزي",
    contactTitle: "Central Fleet Maintenance Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.0541,31.3412"
  },
  {
    id: "eg_titan_750",
    nameAr: "شركة الإنشاءات العربية (ACC - Arabian Construction Company Egypt)",
    nameEn: "Arabian Construction Company (ACC Egypt Mega Fleet)",
    sector: "construction",
    subSector: "المقاولات المتخصصة للأبراج فائقة الارتفاع والفنادق العالمية والمستشفيات التخصصية",
    city: "cairo",
    governorate: "القاهرة",
    address: "شارع العروبة، مصر الجديدة، القاهرة",
    phone1: "0224159800",
    mobile: "01005533118",
    hotline: "19822",
    website: "https://www.accgroup.com",
    latitude: 30.0912,
    longitude: 31.3289,
    fleetSize: 160,
    fleetType: "أوناش برجية ذات قدرات رفع فائقة، مصاعد تشييد خارجية، شاحنات نقل ثقيل، ومعدات صب متقدمة",
    fleetTires: "315/80R22.5 • 385/65R22.5 • 12.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الشركة الدولية الرائدة المنفذة لمجموعة من أشهر ناطحات السحاب والفنادق الفاخرة بالعاصمة الإدارية والقاهرة",
    contactPerson: "مدير عام العمليات اللوجستية ومعدات التشييد",
    contactTitle: "Logistics Operations & Construction Fleets General Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.0912,31.3289"
  }
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { wave7Part1 };
}
