/**
 * Wave 7 Titans - Part 4 (Titans 851 to 900)
 * Sector Focus: Agri-Business, Mega Poultry Fleets, Sugar Mills, Edible Oils, Mills & Food FMCG Fleets
 */

const wave7Part4 = [
  {
    id: "eg_titan_851",
    nameAr: "مجموعة الدقهلية للدواجن والإنتاج الداجني والزراعي (Dakahlia Poultry Group)",
    nameEn: "Dakahlia Poultry & Agri-Business Mega Group",
    sector: "food",
    subSector: "أضخم مجمعات أمهات التسمين، مصانع الأعلاف النباتية، ومجازر الدواجن الآلية المتكاملة",
    city: "dakahlia",
    governorate: "الدقهلية",
    address: "طريق المنصورة - دكرنس، المنصورة، الدقهلية",
    phone1: "0502315000",
    mobile: "01001188331",
    hotline: "19884",
    website: "https://www.dakahlia.net",
    latitude: 31.0423,
    longitude: 31.3912,
    fleetSize: 260,
    fleetType: "شاحنات نقل دواجن حية مهواة، تريلات نقل كتاكيت مكيفة بحساسات حرارة، وبرادات شحن مصنعات دواجن",
    fleetTires: "315/80R22.5 • 295/80R22.5 • 11.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "رائدة صناعة الدواجن في الدلتا ومصر وأحد أكبر منتجي الأعلاف الحيوانية والداجنة ومفرخات الكتاكيت",
    contactPerson: "مدير عام النقل والأسطول الميداني",
    contactTitle: "Live Poultry Fleets & Transport General Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=31.0423,31.3912"
  },
  {
    id: "eg_titan_852",
    nameAr: "شركة دواجن الوطنية مصر (Al Watania Poultry Egypt - مجمع وادي النطرون)",
    nameEn: "Al Watania Poultry Egypt Mega Bio-Complex (Wadi El Natrun)",
    sector: "food",
    subSector: "مجمع الدواجن الحيوي المتكامل الأكبر في الشرق الأوسط (مزارع، مصانع أعلاف، ومجازر آلية)",
    city: "beheira",
    governorate: "البحيرة",
    address: "الكيلو 105، طريق القاهرة - الإسكندرية الصحراوي، وادي النطرون، البحيرة",
    phone1: "0453551000",
    mobile: "01003366992",
    hotline: "19661",
    website: "https://www.alwataniaegypt.com",
    latitude: 30.4124,
    longitude: 30.3456,
    fleetSize: 310,
    fleetType: "أضخم أسطول مبردات ونقل حيوي، شاحنات صهاريج نقل حبوب وأعلاف سائبة (Bulk Feeds)، وتريلات تصدير",
    fleetTires: "315/80R22.5 • 385/65R22.5 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "المشروع القومي الاستثماري العملاق لإنتاج الدواجن بطاقة تتجاوز 100 مليون طائر سنوياً في قلب الصحراء",
    contactPerson: "رئيس قطاعات اللوجستيات والحركة المركزية",
    contactTitle: "Central Fleets & Bio-Logistics Sector Head",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.4124,30.3456"
  },
  {
    id: "eg_titan_853",
    nameAr: "مجموعة الوادي القابضة للدواجن والأعلاف (Wadi Holding - مجمع السادات)",
    nameEn: "Wadi Holding Poultry & Agri-Feed Mega Hub",
    sector: "food",
    subSector: "تربية أمهات الدواجن، إنتاج الأعلاف المتطورة، التجهيزات الغذائية، والتنمية الزراعية",
    city: "monufia",
    governorate: "المنوفية",
    address: "المنطقة الصناعية السابعة، مدينة السادات، المنوفية",
    phone1: "0482601100",
    mobile: "01005577224",
    hotline: "19889",
    website: "https://www.wadiholding.com",
    latitude: 30.3789,
    longitude: 30.5124,
    fleetSize: 220,
    fleetType: "تريلات هوابر نقل خامات أعلاف وصويا، شاحنات نقل دواجن مجهزة، وبرادات شحن منتجات وادي فود",
    fleetTires: "315/80R22.5 • 385/65R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "المجموعة الرائدة والمتكاملة في صناعة الثروة الداجنة والأعلاف والزيتون والصناعات الزراعية التصديرية",
    contactPerson: "مدير عام النقل وسلاسل الإمداد الزراعية",
    contactTitle: "Agri-Supply Chain & Fleets Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.3789,30.5124"
  },
  {
    id: "eg_titan_854",
    nameAr: "مجموعة القاهرة ثري إيه للدواجن والأعلاف (Cairo 3A Poultry & Agri-Complex)",
    nameEn: "Cairo 3A Poultry & Feed Mega Integrated Complex",
    sector: "food",
    subSector: "تفريخ الدواجن، مجازر أهرام للدواجن، تصنيع أعلاف كابو، واستيراد الحبوب وتفريغ الصوامع",
    city: "giza",
    governorate: "الجيزة",
    address: "طريق الواحات البحرية، السادس من أكتوبر، الجيزة",
    phone1: "0238514100",
    mobile: "01007799443",
    hotline: "19318",
    website: "https://www.cairo3a.com",
    latitude: 29.8912,
    longitude: 30.8245,
    fleetSize: 280,
    fleetType: "تريلات تريلا هوابر حبوب حمولة 70 م3، شاحنات نقل أعلاف سائبة، وسيارات مبردة لتوزيع دواجن شهد",
    fleetTires: "315/80R22.5 • 385/65R22.5 • 12.00R24",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الكيان التجاري والزراعي الأكبر في مصر المستحوذ على حصة حاكمة في استيراد الذرة والصويا وسلاسل الدواجن (شهد)",
    contactPerson: "نائب رئيس مجلس الإدارة لقطاع النقل والأسطول التجاري",
    contactTitle: "Executive Vice President - Logistics & Fleets",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.8912,30.8245"
  },
  {
    id: "eg_titan_855",
    nameAr: "شركة القاهرة للدواجن (CPC - مجمع مصانع العاشر والشرقية)",
    nameEn: "Cairo Poultry Company (CPC Americana Agro-Hub)",
    sector: "food",
    subSector: "أقدم وأكبر شركة دواجن مدرجة بالبورصة لإنتاج كتاكيت التسمين، الأعلاف، ومنتجات كوكي المقرمشة",
    city: "sharqia",
    governorate: "الشرقية",
    address: "المنطقة الصناعية B1، العاشر من رمضان، الشرقية",
    phone1: "015412200",
    mobile: "01009911885",
    hotline: "16024",
    website: "https://www.cpc.com.eg",
    latitude: 30.2989,
    longitude: 31.7345,
    fleetSize: 240,
    fleetType: "أساطيل برادات كوكي حمولة 5 إلى 20 طن، تريلات نقل أمهات، وتريلات صهاريج نقل أعلاف",
    fleetTires: "315/80R22.5 • 295/80R22.5 • 225/75R17.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الصرح المؤسس لصناعة الدواجن الحديثة في مصر ومنتج مصنعات كوكي الشهيرة التابعة لمجموعة أمريكانا",
    contactPerson: "مدير عام النقل والتوزيع المبرد",
    contactTitle: "Cold-Chain Transport & Logistics General Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.2989,31.7345"
  },
  {
    id: "eg_titan_856",
    nameAr: "شركة الدلتا للسكر (Delta Sugar Mega Refineries - مصانع الحامول)",
    nameEn: "Delta Sugar Company Mega Beet Processing Refineries (Hamool)",
    sector: "food",
    subSector: "أكبر منتج لسكر البنجر في مصر والشرق الأوسط، إنتاج علف البنجر والمولاس للتصدير",
    city: "kafr_el_sheikh",
    governorate: "كفر الشيخ",
    address: "مجمع مصانع السكر بالحامول، كفر الشيخ",
    phone1: "0473801200",
    mobile: "01002244778",
    hotline: "19742",
    website: "https://www.deltasugar.com",
    latitude: 31.3124,
    longitude: 31.1456,
    fleetSize: 290,
    fleetType: "تريلات قلابات عملاقة لتوريد محصول البنجر، تريلات شحن سكر أبيض معبأ، وتريلات صهاريج مولاس",
    fleetTires: "315/80R22.5 • 12.00R24 • 385/65R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "القلعة الصناعية القومية الرائدة في تكرير سكر البنجر بطاقة استيعابية تتجاوز 2.5 مليون طن بنجر سنوياً",
    contactPerson: "رئيس قطاعات النقل وتوريدات محصول البنجر",
    contactTitle: "Sugar Beet Supply & Inbound Transport Head",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=31.3124,31.1456"
  },
  {
    id: "eg_titan_857",
    nameAr: "شركة النوبارية لصناعة وتكرير السكر (Nubaria Sugar Refining Co.)",
    nameEn: "Nubaria Sugar Refining Company Mega Complex",
    sector: "food",
    subSector: "تكرير سكر البنجر، تكرير السكر الخام المستورد، وتصنيع الأعلاف ومولاس التصدير",
    city: "beheira",
    governorate: "البحيرة",
    address: "الكيلو 75، طريق الإسكندرية - القاهرة الصحراوي، غرب النوبارية، البحيرة",
    phone1: "0452631500",
    mobile: "01004466119",
    hotline: "19835",
    website: "https://www.nubariasugar.com",
    latitude: 30.6512,
    longitude: 30.0789,
    fleetSize: 210,
    fleetType: "شاحنات قلابات نقل بنجر من المزارع، تريلات تريلا فرش سكر، وتريلات صهاريج تريلات عسل أسود ومولاس",
    fleetTires: "315/80R22.5 • 12.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "صرح استراتيجي لتوفير السكر التمويني والحر وتكرير الشحنات التصديرية بمحافظات الدلتا والإسكندرية",
    contactPerson: "مدير عام النقل والتوزيع المركزي",
    contactTitle: "Central Transport & Dispatch General Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.6512,30.0789"
  },
  {
    id: "eg_titan_858",
    nameAr: "شركة الدقهلية لصناعة وتكرير السكر (Dakahlia Sugar Company - بلقاس)",
    nameEn: "Dakahlia Sugar Company Mega Beet Processing Complex (Belqas)",
    sector: "food",
    subSector: "عصر وتكرير بنجر السكر، إنتاج السكر الأبيض عالي النقاوة، ومخلفات البنجر العلفية",
    city: "dakahlia",
    governorate: "الدقهلية",
    address: "مجمع مصانع بلقاس، طريق المنصورة - جمصة، الدقهلية",
    phone1: "0502781000",
    mobile: "01006688334",
    hotline: "19941",
    website: "https://www.dak sugar.com.eg",
    latitude: 31.2345,
    longitude: 31.3567,
    fleetSize: 230,
    fleetType: "قلابات شحن بنجر زراعي، تريلات نقل شكائر سكر زنة 50 كجم، وتريلات صهاريج مولاس تصديري",
    fleetTires: "315/80R22.5 • 12.00R24",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "أحد أضخم قلاع إنتاج السكر الأبيض في مصر بطاقة تكرير تتعدى 18 ألف طن بنجر يومياً في موسم الحصاد",
    contactPerson: "مدير عام الحركة والتشغيل اللوجستي",
    contactTitle: "Logistics Movement & Fleet Operations Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=31.2345,31.3567"
  },
  {
    id: "eg_titan_859",
    nameAr: "شركة القناة للسكر (Canal Sugar Mega Agro-Industrial Complex - غرب المنيا)",
    nameEn: "Canal Sugar Mega Agro-Industrial Complex (West Minya)",
    sector: "food",
    subSector: "أضخم مصنع لسكر البنجر في العالم واستصلاح 181 ألف فدان بالظهير الصحراوي لغرب المنيا",
    city: "minya",
    governorate: "المنيا",
    address: "المشروع القومي لغرب غرب المنيا، طريق المنيا - الواحات، المنيا",
    phone1: "0862391000",
    mobile: "01008811556",
    hotline: "19875",
    website: "https://www.canalsugar.com",
    latitude: 28.0891,
    longitude: 30.4124,
    fleetSize: 340,
    fleetType: "معدات حصاد زراعية ثقيلة، تريلات قلابات ذات سعة فائقة لنقل البنجر، وشاحنات شحن سكر لموانئ التصدير",
    fleetTires: "385/65R22.5 • 315/80R22.5 • 12.00R24",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "المشروع الاستثماري الإماراتي المصري الأضخم عالمياً بطاقة إنتاج 900 ألف طن سكر أبيض سنوياً",
    contactPerson: "رئيس قطاعات الأسطول الثقيل وسلاسل الإمداد الزراعية",
    contactTitle: "Heavy Fleet & Agricultural Supply Chain Head",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=28.0891,30.4124"
  },
  {
    id: "eg_titan_860",
    nameAr: "شركة السكر والصناعات التكاملية المصرية (مجمع مصانع الحوامدية والمصانع الجنوبية)",
    nameEn: "Egyptian Sugar and Integrated Industries Co. (ESIIC Hawamdia)",
    sector: "food",
    subSector: "الصرح الوطني الأم لتكرير قصب وسكر البنجر، الكحول النقي، الخل، والمنتجات الكيماوية العضوية",
    city: "giza",
    governorate: "الجيزة",
    address: "شارع الجمهورية، الحوامدية، الجيزة",
    phone1: "0238120000",
    mobile: "01001133772",
    hotline: "19420",
    website: "https://www.siic.com.eg",
    latitude: 29.8978,
    longitude: 31.2589,
    fleetSize: 320,
    fleetType: "تريلات شحن سكر تمويني، صهاريج كحول نقي معتمد، تريلات صهاريج مولاس، وشاحنات ورش الصيانة الثقيلة",
    fleetTires: "315/80R22.5 • 12.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "عميد الصناعة السكرية الوطنية التابع للشركة القابضة للصناعات الغذائية والمشرف على مصانع الصعيد",
    contactPerson: "رئيس قطاعات النقل والتشغيل الميكانيكي",
    contactTitle: "Mechanical Operations & Transport Sector Head",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.8978,31.2589"
  },
  {
    id: "eg_titan_861",
    nameAr: "شركة صافولا إيجيبت لزيوت الطعام والسمن (Savola Foods Egypt - عافية وروابي)",
    nameEn: "Savola Foods Egypt Mega Refineries (Afia, Rawaby, Shams)",
    sector: "food",
    subSector: "تكرير وتعبئة زيوت الذرة، عباد الشمس، زيوت النخيل، وسمن روابي وجنة الأكثر مبيعاً",
    city: "suez",
    governorate: "السويس",
    address: "المنطقة الصناعية بالأدبية، عتاقة، السويس",
    phone1: "0623391500",
    mobile: "01003355998",
    hotline: "19330",
    website: "https://www.savolafoods.com",
    latitude: 29.8456,
    longitude: 32.4891,
    fleetSize: 260,
    fleetType: "تريلات صهاريج نقل زيوت غذائية صلب معتمد Food-Grade، شاحنات توزيع كراتين زيوت وسمن، وتريلات تصدير",
    fleetTires: "315/80R22.5 • 295/80R22.5 • 385/65R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الشركة المتصدرة لسوق الزيوت النباتية والسمن في مصر والشرق الأوسط بمنتجاتها عافية وروابي وجنة",
    contactPerson: "مدير عام النقل والتوزيع الإقليمي",
    contactTitle: "Regional Logistics & Fleet Transport General Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.8456,32.4891"
  },
  {
    id: "eg_titan_862",
    nameAr: "مجموعة أرما للصناعات الغذائية (Arma Food Industries - كريستال والهَانِم)",
    nameEn: "Arma Food Industries Mega Plants (Crystal, El Hanem)",
    sector: "food",
    subSector: "مجمعات تكرير وإنتاج زيوت الذرة وعباد الشمس كريستال، السمن النباتي الهانم، والمسلى الطبيعي",
    city: "sharqia",
    governorate: "الشرقية",
    address: "المنطقة الصناعية الثالثة A1، العاشر من رمضان، الشرقية",
    phone1: "015413100",
    mobile: "01005577441",
    hotline: "19070",
    website: "https://www.arma.com.eg",
    latitude: 30.3012,
    longitude: 31.7589,
    fleetSize: 250,
    fleetType: "شاحنات تريلات صندوقية لنقل الزيوت المعبأة، صهاريج نقل زيوت نباتية ستانلس ستيل، وتريلات توزيع",
    fleetTires: "315/80R22.5 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "رائدة صناعة الزيوت الفاخرة كريستال والهَانِم بأسطول توزيع يغطي كل سلاسل التجزئة والمحافظات",
    contactPerson: "مدير عام الحركة والأسطول المركزي",
    contactTitle: "Central Fleet & Movement General Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.3012,31.7589"
  },
  {
    id: "eg_titan_863",
    nameAr: "شركة مصر للزيوت والصابون (Misr Oil and Soap Mega Complex)",
    nameEn: "Misr Oil and Soap Historic Industrial Complex",
    sector: "food",
    subSector: "عصر بذور القطن والصويا، تكرير الزيوت التموينية، وإنتاج الصابون الطبي والتواليت والمنظفات",
    city: "dakahlia",
    governorate: "الدقهلية",
    address: "مجمع مصانع سندوب، المنصورة، الدقهلية",
    phone1: "0502241600",
    mobile: "01007799225",
    hotline: "19782",
    website: "https://www.misroilsoap.com.eg",
    latitude: 31.0214,
    longitude: 31.3789,
    fleetSize: 180,
    fleetType: "تريلات صهاريج نقل زيوت خام ومكررة، شاحنات توزيع زيوت تموينية وصابون، وتريلات نقل كسب قطن",
    fleetTires: "315/80R22.5 • 11.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "أعرق القلاع الصناعية التابعة لوزارة التموين لتأمين الزيوت التموينية والصناعات الصابونية بمصر",
    contactPerson: "رئيس قطاعات النقل والورش الإنتاجية",
    contactTitle: "Production Fleets & Transport Sector Head",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=31.0214,31.3789"
  },
  {
    id: "eg_titan_864",
    nameAr: "شركة طنطا للزيوت والصابون والمياه الطبيعية (Tanta Oil and Soap Co.)",
    nameEn: "Tanta Oil and Soap Industrial Mega Complex",
    sector: "food",
    subSector: "عصر وتكرير الزيوت النباتية، صابون الغسيل والتواليت، تعبئة مياه نقية، وإنتاج الأعلاف المركزة",
    city: "gharbia",
    governorate: "الغربية",
    address: "شارع مصطفى كامل، طنطا، الغربية",
    phone1: "0403332400",
    mobile: "01009922668",
    hotline: "19637",
    website: "https://www.tantaoil.com.eg",
    latitude: 30.7912,
    longitude: 31.0012,
    fleetSize: 165,
    fleetType: "تريلات شحن سلع تموينية، صهاريج زيوت طعام، شاحنات توزيع مياه طبيعية ومياه معبأة",
    fleetTires: "315/80R22.5 • 12.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "أحد الأعمدة الصناعية التاريخية لوسط الدلتا في تكرير الزيوت وإنتاج وتوزيع السلع الاستراتيجية التموينية",
    contactPerson: "مدير عام النقل وسلاسل التوزيع",
    contactTitle: "Distribution Chains & Transport Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.7912,31.0012"
  },
  {
    id: "eg_titan_865",
    nameAr: "شركة مطاحن خمس نجوم بالسويس (Five Star Flour Mills - السويس)",
    nameEn: "Five Star Flour Mills Mega Port Silos & Industrial Complex",
    sector: "food",
    subSector: "أكبر مجمع مطاحن دقيق فاخر 72%، استيراد القمح وصوامع ميناء الأدبية بطاقة تخزين عملاقة",
    city: "suez",
    governorate: "السويس",
    address: "منطقة ميناء الأدبية، عتاقة، السويس",
    phone1: "0623392000",
    mobile: "01001144889",
    hotline: "19844",
    website: "https://www.fivestaregypt.com",
    latitude: 29.8512,
    longitude: 32.4912,
    fleetSize: 220,
    fleetType: "تريلات صهاريج نقل دقيق سائب (Flour Tankers)، تريلات جامبو نقل شكائر دقيق 50 كجم، وتريلات صوامع",
    fleetTires: "315/80R22.5 • 385/65R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "المورد الحصري للدقيق الفاخر لكبرى شركات المكرونة والبسكويت والمخابز السياحية ومصانع الأغذية بمصر",
    contactPerson: "مدير عام الأسطول وشحن الدقيق الفاخر",
    contactTitle: "Bulk Flour Shipping & Fleets General Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.8512,32.4912"
  },
  {
    id: "eg_titan_866",
    nameAr: "شركة مطاحن شمال القاهرة (North Cairo Flour Mills Mega Complex)",
    nameEn: "North Cairo Flour Mills & Bakeries Public Mega Complex",
    sector: "food",
    subSector: "طحن الأقماح التموينية وإنتاج الدقيق البلدي 87.5%، الدقيق الفاخر، صوامع الغلال، والمخابز الآلية",
    city: "cairo",
    governorate: "القاهرة",
    address: "شارع معهد ناصر، الساحل، شبرا، القاهرة",
    phone1: "0222026500",
    mobile: "01003366114",
    hotline: "19755",
    website: "https://www.northcairomills.com",
    latitude: 30.0891,
    longitude: 31.2456,
    fleetSize: 195,
    fleetType: "شاحنات شحن دقيق للمخابز البلدية، تريلات نقل قمح من الصوامع والموانئ، وتريلات نقل ردة خشنة",
    fleetTires: "315/80R22.5 • 12.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الصرح الأكبر المسؤول عن تأمين رغيف الخبز المدعم لملايين المواطنين في نطاق القاهرة الكبرى",
    contactPerson: "رئيس قطاعات النقل والصيانة الميكانيكية",
    contactTitle: "Transport & Mechanical Maintenance Head",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.0891,31.2456"
  },
  {
    id: "eg_titan_867",
    nameAr: "شركة مطاحن شرق الدلتا (East Delta Flour Mills Mega Network)",
    nameEn: "East Delta Flour Mills Mega Storage & Milling Complex",
    sector: "food",
    subSector: "مطاحن وصوامع تخزين الأقماح وتوزيع الدقيق عبر محافظات الشرقية والإسماعيلية والسويس وبورسعيد",
    city: "sharqia",
    governorate: "الشرقية",
    address: "شارع الشهيد طيار، الزقازيق، الشرقية",
    phone1: "0552303500",
    mobile: "01005588337",
    hotline: "19830",
    website: "https://www.eastdeltamills.com",
    latitude: 30.5891,
    longitude: 31.5012,
    fleetSize: 175,
    fleetType: "تريلات تريلا فرش نقل شكائر، شاحنات توزيع دقيق، وتريلات قلابات تفريغ قمح محلي ومستورد",
    fleetTires: "315/80R22.5 • 11.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "العمود الفقري للأمن الغذائي وطحن الحبوب لقطاع مدن القناة والشرقية وشمال سيناء",
    contactPerson: "مدير عام النقل والحركة",
    contactTitle: "Transport Fleet Operations Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.5891,31.5012"
  },
  {
    id: "eg_titan_868",
    nameAr: "مجموعة إيجيبت فودز للصناعات الغذائية (Egypt Foods Group - تايجر وبيليه)",
    nameEn: "Egypt Foods Group Mega Snacks & Confectionery Plants (Tiger Chips)",
    sector: "food",
    subSector: "مجمعات تصنيع رقائق البطاطس المقرمشة تايجر وشيبسي تايجر، السناكس، الشوكولاتة، والحلويات",
    city: "monufia",
    governorate: "المنوفية",
    address: "المنطقة الصناعية بقويسنا، طريق مصر إسكندرية الزراعي، المنوفية",
    phone1: "0482574100",
    mobile: "01007711993",
    hotline: "19660",
    website: "https://www.egyptfoodsgroup.com",
    latitude: 30.5214,
    longitude: 31.1345,
    fleetSize: 330,
    fleetType: "أضخم أسطول شاحنات جامبو وفانات مغلقة لتوزيع المقرمشات، تريلات نقل بطاطس تصنيع مجهزة، وتريلات تصدير",
    fleetTires: "295/80R22.5 • 225/75R17.5 • 315/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الشركة الوطنية الأولى المنافسة للشركات العالمية في سوق المقرمشات وتصدير السناكس لأكثر من 40 دولة",
    contactPerson: "رئيس قطاعات الأسطول والتوزيع القومي",
    contactTitle: "National Fleet & Distribution Sector Head",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.5214,31.1345"
  },
  {
    id: "eg_titan_869",
    nameAr: "شركة ريتش فود للصناعات الغذائية (Rich Food - ريتش بيك ومصنعات اللحوم)",
    nameEn: "Rich Food Industries Mega Complex (Rich Bake & Processed Meats)",
    sector: "food",
    subSector: "أكبر مخابز آلية للمخبوزات الأوروبية ريتش بيك، ومصانع منتجات اللحوم المبردة والمجمدة المصنعة",
    city: "giza",
    governorate: "الجيزة",
    address: "المنطقة الصناعية الثالثة، السادس من أكتوبر، الجيزة",
    phone1: "0238334400",
    mobile: "01009933551",
    hotline: "19973",
    website: "https://www.richfood.com",
    latitude: 29.9624,
    longitude: 30.9245,
    fleetSize: 250,
    fleetType: "أساطيل شاحنات توزيع مخبوزات يومية سريعة، برادات نقل لحوم مجمدة ومبردة، وتريلات تصدير",
    fleetTires: "225/75R17.5 • 295/80R22.5 • 315/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "رائدة المخبوزات الصحية والتوست في مصر ومورد سلاسل المطاعم العالمية والهايبر ماركت",
    contactPerson: "مدير عام النقل السريع والتوزيع اليومي",
    contactTitle: "Daily Distribution & Fleet Transport Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.9624,30.9245"
  },
  {
    id: "eg_titan_870",
    nameAr: "مجموعة مزارع دينا للصناعات الغذائية والألبان (Dina Farms Mega Agro-Dairy)",
    nameEn: "Dina Farms Mega Integrated Agro & Dairy Complex",
    sector: "food",
    subSector: "أكبر مزرعة ألبان متكاملة حرة في إفريقيا (أكثر من 17 ألف رأس قطيع هولشتاين)، وتصنيع الحليب والعصائر",
    city: "beheira",
    governorate: "البحيرة",
    address: "الكيلو 80، طريق القاهرة - الإسكندرية الصحراوي، البحيرة",
    phone1: "0452632200",
    mobile: "01002255887",
    hotline: "19033",
    website: "https://www.dinafarms.com",
    latitude: 30.5678,
    longitude: 30.1891,
    fleetSize: 230,
    fleetType: "فنطاس صهاريج نقل حليب طازج معزولة ومبردة، برادات توزيع ألبان وعصائر، ومعدات زراعية وحصاد علف",
    fleetTires: "315/80R22.5 • 295/80R22.5 • 385/65R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "مزرعة الألبان النموذجية الأضخم في مصر التابعة لشركة القلعة لتوفير الحليب الطازج الطبيعي 100%",
    contactPerson: "مدير اللوجستيات والنقل المبرد وسلاسل التوريد",
    contactTitle: "Cold-Chain Logistics & Dairy Fleets Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.5678,30.1891"
  },
  {
    id: "eg_titan_871",
    nameAr: "شركة وادي فود للصناعات الغذائية التصديرية (Wadi Food Mega Industrial Plants)",
    nameEn: "Wadi Food Agro-Industrial & Export Mega Complex",
    sector: "food",
    subSector: "عصر وتعبئة زيت الزيتون البكر الممتاز، مخللات وزيتون مائدة للتصدير، ومصنعات صلصة الطماطم",
    city: "monufia",
    governorate: "المنوفية",
    address: "المنطقة الصناعية الأولى، مدينة السادات، المنوفية",
    phone1: "0482602200",
    mobile: "01004477112",
    hotline: "19923",
    website: "https://www.wadifood.com",
    latitude: 30.3812,
    longitude: 30.5214,
    fleetSize: 140,
    fleetType: "تريلات شحن صادرات للموانئ، شاحنات توزيع تجزئة، وتريلات صهاريج زيت زيتون غذائي",
    fleetTires: "315/80R22.5 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "سفيرة زيت الزيتون المصري عالمياً والحاصلة على أرفع جوائز الجودة العالمية في أمريكا وأوروبا واليابان",
    contactPerson: "مدير الشحن والأسطول التجاري",
    contactTitle: "Commercial Shipping & Fleets Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.3812,30.5214"
  },
  {
    id: "eg_titan_872",
    nameAr: "شركة إندومي مصر للصناعات الغذائية (Indomie Egypt - سالم وزران أبو العطا)",
    nameEn: "Indomie Egypt Mega Industrial Hub (Salim Wazaran Abu Elata)",
    sector: "food",
    subSector: "مجمعات تصنيع النودلز والشعرية سريعة التحضير وتصنيع بهارات النكهات وخطوط التعبئة الآلية",
    city: "beheira",
    governorate: "البحيرة",
    address: "المنطقة الصناعية بحوش عيسى، البحيرة / مصانع بدر بالمنطقة الصناعية",
    phone1: "0452381200",
    mobile: "01006699335",
    hotline: "19447",
    website: "https://www.indomie.com.eg",
    latitude: 30.9124,
    longitude: 30.2891,
    fleetSize: 220,
    fleetType: "أساطيل شاحنات جامبو مغلقة خفيفة وعالية السعة، تريلات شحن دقيق فاخر، وتريلات شحن للمحافظات",
    fleetTires: "295/80R22.5 • 225/75R17.5 • 315/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "المصنع الأكبر للشعرية سريعة التحضير في إفريقيا المغطي للسوق المصري والتصدير للدول الإفريقية والعربية",
    contactPerson: "مدير عام النقل والتوزيع اللوجستي",
    contactTitle: "Logistics Transport & Supply Chain Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.9124,30.2891"
  },
  {
    id: "eg_titan_873",
    nameAr: "شركة ريجينا للمكرونة والصناعات الغذائية (Regina Pasta & Food Industries)",
    nameEn: "Regina Pasta & Food Industries Mega Plants (Sadat City)",
    sector: "food",
    subSector: "تصنيع المكرونة الفاخرة من سيمولينا القمح الصلب 100%، صلصة الطماطم، ومطاحن السيمولينا المدمجة",
    city: "monufia",
    governorate: "المنوفية",
    address: "المنطقة الصناعية الثانية، مدينة السادات، المنوفية",
    phone1: "0482604500",
    mobile: "01008822557",
    hotline: "19239",
    website: "https://www.reginapasta.com",
    latitude: 30.3745,
    longitude: 30.5089,
    fleetSize: 185,
    fleetType: "تريلات تريلا صندوقية لشحن المكرونة، صهاريج نقل دقيق وسيمولينا سائبة، وشاحنات توزيع تجزئة",
    fleetTires: "315/80R22.5 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "رائدة صناعة المكرونة الفاخرة في مصر والمصدرة لمنتجات القمح الصلب لأكثر من 35 دولة",
    contactPerson: "مدير عام النقل والمبيعات اللوجستية",
    contactTitle: "Transport & Sales Logistics General Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.3745,30.5089"
  },
  {
    id: "eg_titan_874",
    nameAr: "شركة حلواني إخوان مصر للصناعات الغذائية (Halwani Bros Egypt)",
    nameEn: "Halwani Bros Egypt Mega Food Processing Plants (10th of Ramadan)",
    sector: "food",
    subSector: "تصنيع الحلاوة الطحينية، المربيات، اللحوم المصنعة والدواجن، والمخللات وتجهيز الأغذية",
    city: "sharqia",
    governorate: "الشرقية",
    address: "المنطقة الصناعية B2، العاشر من رمضان، الشرقية",
    phone1: "015414000",
    mobile: "01001155994",
    hotline: "19098",
    website: "https://www.halwani.com",
    latitude: 30.3067,
    longitude: 31.7489,
    fleetSize: 200,
    fleetType: "برادات نقل لحوم ودواجن معتمدة، شاحنات توزيع حلاوة وطحينة، وفانات توزيع سوبر ماركت",
    fleetTires: "295/80R22.5 • 225/75R17.5 • 315/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "العلامة التاريخية الشهيرة في صناعة الأغذية واللحوم المصنعة والحلاوة ذات الحصة السوقية البارزة",
    contactPerson: "مدير عام الأسطول والتوزيع المبرد",
    contactTitle: "Cold Fleet & Distribution General Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.3067,31.7489"
  },
  {
    id: "eg_titan_875",
    nameAr: "شركة الصناعات الغذائية دومتي (Domty Mega Cheese & Bakery Plants)",
    nameEn: "Domty Mega Cheese, Juice & Bakery Complex (6th of October)",
    sector: "food",
    subSector: "أكبر منتج للجبن الأبيض المعبأ، الجبن المطبوخ، العصائر الطبيعية، والمخبوزات الآلية وسندوتشات دومتي",
    city: "giza",
    governorate: "الجيزة",
    address: "المنطقة الصناعية الثانية، السادس من أكتوبر، الجيزة",
    phone1: "0238202000",
    mobile: "01003377228",
    hotline: "16886",
    website: "https://www.domty.org",
    latitude: 29.9545,
    longitude: 30.9167,
    fleetSize: 310,
    fleetType: "أضخم أساطيل الفانات والشاحنات المبردة المجهزة لتوزيع الألبان والمخبوزات اليومية لآلاف المحال",
    fleetTires: "225/75R17.5 • 295/80R22.5 • 315/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "رائدة سوق الجبن الأبيض في مصر المدرجة بالبورصة بأسطول توزيع مباشر هو الأكفأ والأوسع انتشاراً",
    contactPerson: "رئيس قطاعات اللوجستيات والحركة والتوزيع المباشر",
    contactTitle: "Direct Distribution & Fleets Sector Head",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.9545,30.9167"
  },
  {
    id: "eg_titan_876",
    nameAr: "مجموعة فرج الله للصناعات الغذائية (Faragalla Group - مجمع مصانع برج العرب)",
    nameEn: "Faragalla Group Mega Food Processing Complex (Borg El Arab)",
    sector: "food",
    subSector: "أضخم مجمع غذائي متكامل لإنتاج العصائر، الخضروات المجمدة، اللحوم المصنعة، المربى، والصلصة",
    city: "alexandria",
    governorate: "الإسكندرية",
    address: "المنطقة الصناعية الأولى، برج العرب الجديدة، الإسكندرية",
    phone1: "034592000",
    mobile: "01005599442",
    hotline: "19947",
    website: "https://www.faragalla.com",
    latitude: 30.9189,
    longitude: 29.6124,
    fleetSize: 320,
    fleetType: "أساطيل شاحنات تبريد وتجميد ثقيلة، تريلات شحن صادرات لميناء الإسكندرية، وفانات توزيع تجزئة",
    fleetTires: "315/80R22.5 • 295/80R22.5 • 385/65R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "القلعة التصديرية الغذائية الأكبر في الإسكندرية التي تضم عشرات المصانع التخصصية في موقع موحد",
    contactPerson: "نائب رئيس مجلس الإدارة للوجستيات والأسطول",
    contactTitle: "Vice President - Logistics & Fleets",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.9189,29.6124"
  },
  {
    id: "eg_titan_877",
    nameAr: "شركة بيبسيكو مصر للمشروبات والأغذية (PepsiCo Egypt - مصانع مدينة نصر ومدينة السادس من أكتوبر)",
    nameEn: "PepsiCo Egypt Mega Beverages & Snacks Plants",
    sector: "food",
    subSector: "مجمعات تعبئة المشروبات الغازية بيبسي وسفن أب وميراندا وأكوافينا، وشيبسي مصر للبطاطس",
    city: "cairo",
    governorate: "القاهرة",
    address: "المنطقة الحرة العامة، مدينة نصر، القاهرة",
    phone1: "0222765000",
    mobile: "01007722665",
    hotline: "19737",
    website: "https://www.pepsico.com",
    latitude: 30.0512,
    longitude: 31.3456,
    fleetSize: 450,
    fleetType: "أضخم أساطيل شاحنات نقل صناديق المياه الغازية المفتوحة (Beverage Bay Trucks)، وبرادات شيبسي، وتريلات",
    fleetTires: "295/80R22.5 • 315/80R22.5 • 225/75R17.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "العملاق العالمي للمشروبات والأغذية الخفيفة الممتلك لواحد من أضخم 3 أساطيل نقل تجاري في مصر",
    contactPerson: "مدير عام النقل والأسطول القومي لمصر وشمال إفريقيا",
    contactTitle: "Country Fleet & Logistics General Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.0512,31.3456"
  },
  {
    id: "eg_titan_878",
    nameAr: "شركة كوكاكولا هيلينيك مصر للمشروبات (Coca-Cola HBC Egypt)",
    nameEn: "Coca-Cola HBC Egypt Mega Bottling Plants & Distribution",
    sector: "food",
    subSector: "مجمعات تعبئة كوكاكولا وسبرايت وفانتا وشويبس ومياه دساني، ومستودعات التوزيع الإقليمية",
    city: "giza",
    governorate: "الجيزة",
    address: "المنطقة الصناعية الثانية، السادس من أكتوبر، الجيزة",
    phone1: "0238289000",
    mobile: "01009944883",
    hotline: "19262",
    website: "https://eg.coca-colahellenic.com",
    latitude: 29.9489,
    longitude: 30.9112,
    fleetSize: 420,
    fleetType: "شاحنات توزيع مشروبات هيدروليكية ذات ستائر منزلقة (Curtainsider)، تريلات نقل خامات مركزات، وفانات صيانة",
    fleetTires: "295/80R22.5 • 315/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الموزع والتعبئة الدولي المعتمد لشركة كوكاكولا بمصر بعد الاستحواذ عليها من مجموعة هيلينيك العالمية",
    contactPerson: "رئيس قطاعات اللوجستيات والنقل المستدام",
    contactTitle: "Sustainable Logistics & Fleet Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.9489,30.9112"
  },
  {
    id: "eg_titan_879",
    nameAr: "شركة نستله مصر للصناعات الغذائية والمياه (Nestlé Egypt - مصانع السادس من أكتوبر وقها)",
    nameEn: "Nestlé Egypt Mega Nutrition, Dairy & Waters Plants",
    sector: "food",
    subSector: "تصنيع أغذية الأطفال سيريلاك، شوكولاتة كيت كات، مرقة ماجي، وتعبئة مياه نستله بيور لايف وبركة",
    city: "giza",
    governorate: "الجيزة",
    address: "المنطقة الصناعية الأولى، السادس من أكتوبر، الجيزة",
    phone1: "0238284000",
    mobile: "01001166447",
    hotline: "16180",
    website: "https://www.nestle.com.eg",
    latitude: 29.9678,
    longitude: 30.9289,
    fleetSize: 290,
    fleetType: "شاحنات شحن مياه طبيعية قوارير 5 جالون وكراتين، تريلات شحن أغذية جافة، وبرادات توزيع آيس كريم",
    fleetTires: "295/80R22.5 • 315/80R22.5 • 225/75R17.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الفرع المصري لأكبر شركة أغذية في العالم المتصدرة لسوق المياه المعبأة وأغذية الطفولة والطهي",
    contactPerson: "مدير عام النقل وسلاسل الإمداد بمصر",
    contactTitle: "Supply Chain & Physical Logistics Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.9678,30.9289"
  },
  {
    id: "eg_titan_880",
    nameAr: "شركة دانون مصر للألبان وأغذية الرضع (Danone Egypt - مصانع العبور)",
    nameEn: "Danone Egypt Mega Fresh Dairy & Early Life Nutrition Plants",
    sector: "food",
    subSector: "مجمعات تصنيع الزبادي الطازج دانون ودانيت، المشروبات اللبنية أكتيفيا، وأغذية الأطفال ابتاميل وبيبيلاك",
    city: "qalyubia",
    governorate: "القليوبية",
    address: "المنطقة الصناعية الأولى، مدينة العبور، القليوبية",
    phone1: "0244813000",
    mobile: "01003388775",
    hotline: "19326",
    website: "https://www.danone.eg",
    latitude: 30.2234,
    longitude: 31.4689,
    fleetSize: 260,
    fleetType: "أسطول متطور من شاحنات التبريد المتصل بحساسات إنترنت الأشياء لضبط درجات الحرارة بدقة، وفانات توزيع",
    fleetTires: "225/75R17.5 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "رائدة منتجات الألبان الصحية والزبادي العالمي المعتمدة على سلاسل إمداد تبريد صارمة ومزارع مصرية معتمدة",
    contactPerson: "مدير عام النقل والأسطول المبرد",
    contactTitle: "Cold-Chain Transport & Logistics Lead",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.2234,31.4689"
  },
  {
    id: "eg_titan_881",
    nameAr: "شركة جهينة للصناعات الغذائية (Juhayna - مجمع مصانع السادس من أكتوبر)",
    nameEn: "Juhayna Food Industries Mega Industrial Hub (6th of October)",
    sector: "food",
    subSector: "المجمع الصناعي الأكبر للألبان المعقمة، الزبادي، العصائر الطبيعية، ومصنعات الفواكه المركزة",
    city: "giza",
    governorate: "الجيزة",
    address: "المنطقة الصناعية الأولى، السادس من أكتوبر، الجيزة",
    phone1: "0238286000",
    mobile: "01005511229",
    hotline: "16630",
    website: "https://www.juhayna.com",
    latitude: 29.9656,
    longitude: 30.9312,
    fleetSize: 480,
    fleetType: "أضخم أسطول توزيع برادات وفانات نقل ألبان وعصائر في مصر يتجاوز 1000 سيارة توزيع وتريلات شحن ثقيل",
    fleetTires: "225/75R17.5 • 295/80R22.5 • 315/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "العلامة الوطنية رقم 1 في الألبان والعصائر بمصر والمالكة لأضخم شبكة لوجستية لخدمة التجزئة والجملة",
    contactPerson: "رئيس قطاعات الأسطول والنقل المركزي",
    contactTitle: "Central Fleet & Outbound Logistics Sector Head",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.9656,30.9312"
  },
  {
    id: "eg_titan_882",
    nameAr: "شركة المراعي مصر (بيتي للألبان والعصائر - مجمع مصانع النوبارية)",
    nameEn: "Beyti (Almarai Egypt Joint Venture Mega Complex - Nubaria)",
    sector: "food",
    subSector: "أحدث مجمع لتصنيع وتعبئة الحليب المعقم، الزبادي، الجبن الأبيض، وعصائر كل يوم وتروبيكانا",
    city: "beheira",
    governorate: "البحيرة",
    address: "الكيلو 72، طريق القاهرة - الإسكندرية الصحراوي، غرب النوبارية، البحيرة",
    phone1: "0452633000",
    mobile: "01007733554",
    hotline: "16335",
    website: "https://www.beyti.com",
    latitude: 30.6389,
    longitude: 30.1012,
    fleetSize: 390,
    fleetType: "تريلات تبريد ونقل حليب خام، أساطيل شاحنات وفانات توزيع مبردة يومية تغطي كافة محافظات الجمهورية",
    fleetTires: "225/75R17.5 • 295/80R22.5 • 315/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الشراكة الاستراتيجية بين المراعي السعودية وبيبسيكو العالمية المالكة لأكبر مصانع الألبان بالنوبارية",
    contactPerson: "مدير عام النقل والأسطول والتوزيع اللوجستي",
    contactTitle: "Logistics, Distribution & Fleet Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.6389,30.1012"
  },
  {
    id: "eg_titan_883",
    nameAr: "شركة هيرو للصناعات الغذائية مصر Hero الشرق الأوسط (Hero Middle East - مصانع قها)",
    nameEn: "Hero Middle East & Africa Mega Food Processing (Qaha)",
    sector: "food",
    subSector: "تصنيع مربيات هيرو السويسرية، أغذية الأطفال بروتين هيرو بيبي، زبدة الفول السوداني ومشروبات الفواكه",
    city: "qalyubia",
    governorate: "القليوبية",
    address: "طريق مصر إسكندرية الزراعي، قها، القليوبية",
    phone1: "0132561500",
    mobile: "01009955776",
    hotline: "19376",
    website: "https://www.hero.ch",
    latitude: 30.2845,
    longitude: 31.2012,
    fleetSize: 170,
    fleetType: "شاحنات شحن أغذية أطفال معقمة، تريلات نقل عبوات زجاجية، وشاحنات توزيع لسلاسل الصيدليات والتجزئة",
    fleetTires: "295/80R22.5 • 315/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "المركز الإقليمي لتصنيع وتصدير منتجات مجموعة هيرو السويسرية للشرق الأوسط وإفريقيا من مصانع قها التاريخية",
    contactPerson: "مدير عام العمليات اللوجستية والأسطول",
    contactTitle: "Logistics Operations & Fleet Head",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.2845,31.2012"
  },
  {
    id: "eg_titan_884",
    nameAr: "شركة بيل إيجيبت لتصنيع الجبن والألبان (Bel Egypt - لافاش كيري وأبو الولد)",
    nameEn: "Bel Egypt Mega Cheese Processing Plants (La Vache Qui Rit, Kiri)",
    sector: "food",
    subSector: "تصنيع الجبن المثلثات لافاش كيري، كيري، أبو الولد، والجبن المربعات والمطبوخ للشرق الأوسط",
    city: "sharqia",
    governorate: "الشرقية",
    address: "المنطقة الصناعية الثالثة A2، العاشر من رمضان، الشرقية",
    phone1: "015415500",
    mobile: "01001177998",
    hotline: "19235",
    website: "https://www.groupe-bel.com",
    latitude: 30.3089,
    longitude: 31.7512,
    fleetSize: 180,
    fleetType: "برادات شحن أجبان مبردة بدرجات حرارة مسيطر عليها، تريلات شحن حاويات موانئ، وفانات توزيع تجزئة",
    fleetTires: "295/80R22.5 • 315/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "المصنع الأكبر لمجموعة بيل الفرنسية في إفريقيا والشرق الأوسط لإنتاج أشهر أنواع الجبن المطبوخ",
    contactPerson: "مدير عام النقل وسلاسل التوريد المبردة",
    contactTitle: "Cold Supply Chain & Transport Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.3089,31.7512"
  },
  {
    id: "eg_titan_885",
    nameAr: "شركة موندليز إيجيبت للصناعات الغذائية (Mondelez Egypt - كادبوري وبسكويت وكيك)",
    nameEn: "Mondelez Egypt Mega Confectionery Plants (Cadbury, Oreo, Tuc)",
    sector: "food",
    subSector: "مجمعات تصنيع شوكولاتة كادبوري ديري ميلك، بسكويت أوريو وتوك، كيك هوز وتوينكيز وكليرتس وترايدنت",
    city: "sharqia",
    governorate: "الشرقية",
    address: "المنطقة الصناعية B3، العاشر من رمضان، الشرقية",
    phone1: "015416000",
    mobile: "01003399113",
    hotline: "19838",
    website: "https://www.mondelezinternational.com",
    latitude: 30.3112,
    longitude: 31.7612,
    fleetSize: 220,
    fleetType: "برادات نقل شوكولاتة مكيفة بنظم حماية ذوبان، تريلات شحن حلويات للموانئ، وشاحنات توزيع للمتاجر",
    fleetTires: "295/80R22.5 • 315/80R22.5 • 225/75R17.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الصرح العالمي الأول في تصنيع الشوكولاتة والبسكويت المعتمد كمركز تصدير إقليمي لأكثر من 20 دولة",
    contactPerson: "مدير عام الأسطول والشحن الدولي",
    contactTitle: "Fleet & International Logistics Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.3112,31.7612"
  },
  {
    id: "eg_titan_886",
    nameAr: "مجموعة إيديتا للصناعات الغذائية (Edita Mega Bakeries & Snack Foods - بني سويف وأكتوبر)",
    nameEn: "Edita Food Industries Mega Bakery Plants (Molto, Todo, Bake Rolz)",
    sector: "food",
    subSector: "أكبر منتج للمخبوزات المعبأة آلياً؛ كرواسون مولتو، كيك تودو، خبز بيك رولز، مقرمشات بيك ستيكس وميميكس",
    city: "giza",
    governorate: "الجيزة",
    address: "المنطقة الصناعية الرابعة، السادس من أكتوبر، الجيزة / كوم أبو راضي، بني سويف",
    phone1: "0238204000",
    mobile: "01005522881",
    hotline: "19940",
    website: "https://www.edita.com.eg",
    latitude: 29.9412,
    longitude: 30.9189,
    fleetSize: 340,
    fleetType: "أضخم أسطول شاحنات مغلقة خفيفة ومتوسطة لتوزيع المخبوزات الطازجة يومياً على أكثر من 70 ألف نقطة بيع",
    fleetTires: "225/75R17.5 • 295/80R22.5 • 315/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "رائدة المخبوزات الخفيفة والكيك المحشو في مصر والشرق الأوسط بأسطول توزيع يومي عالي الكفاءة والسرعة",
    contactPerson: "رئيس قطاعات النقل وسلاسل الإمداد المركزية",
    contactTitle: "Central Fleets & Supply Chain Head",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.9412,30.9189"
  },
  {
    id: "eg_titan_887",
    nameAr: "شركة مارس إيجيبت لتصنيع الشوكولاتة والحلويات (Mars Egypt - مجمع مصانع السادس من أكتوبر)",
    nameEn: "Mars Egypt Mega Confectionery Plants (Galaxy, Twix, M&Ms)",
    sector: "food",
    subSector: "مجمعات تصنيع شوكولاتة جالاكسي، تويكس، سنيكرز، باونتي، وإم آند إمز والتصدير لأفريقيا والشرق الأوسط",
    city: "giza",
    governorate: "الجيزة",
    address: "المنطقة الصناعية الثالثة، السادس من أكتوبر، الجيزة",
    phone1: "0238287000",
    mobile: "01007744113",
    hotline: "19329",
    website: "https://www.mars.com",
    latitude: 29.9578,
    longitude: 30.9212,
    fleetSize: 190,
    fleetType: "برادات شحن شوكولاتة بمواصفات أيزو معتمدة، تريلات شحن لحاويات التصدير بموانئ السخنة والإسكندرية",
    fleetTires: "315/80R22.5 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "المقر الإقليمي الأول لمجموعة مارس العالمية في شمال إفريقيا والمصدر لنحو 30 سوقاً دولياً من مصر",
    contactPerson: "مدير اللوجستيات الإقليمي والأسطول",
    contactTitle: "Regional Fleet & Logistics Lead",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.9578,30.9212"
  },
  {
    id: "eg_titan_888",
    nameAr: "شركة يونيليفر مشرق للصناعات الغذائية والشاي (Unilever Mashreq - شاي ليبتون وكنور)",
    nameEn: "Unilever Mashreq Foods & Tea Mega Processing Plants (Lipton & Knorr)",
    sector: "food",
    subSector: "أكبر مصنع لتعبئة وخلط وتصدير شاي ليبتون في العالم، ومصانع منتجات الشوربة والصلصات كنور",
    city: "alexandria",
    governorate: "الإسكندرية",
    address: "المنطقة الصناعية ببرج العرب الجديدة، الإسكندرية / 6 أكتوبر",
    phone1: "034593500",
    mobile: "01009966337",
    hotline: "19058",
    website: "https://www.unilever.com",
    latitude: 30.9212,
    longitude: 29.6245,
    fleetSize: 240,
    fleetType: "تريلات شحن صادرات شاي لموانئ العالم، شاحنات توزيع منتجات كنور وليبتون لقطاعات التجزئة والفنادق",
    fleetTires: "315/80R22.5 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "مجمع برج العرب هو مركز تصدير شاي ليبتون الأول عالمياً الذي يصدر إنتاجه لملايين المستهلكين حول الأرض",
    contactPerson: "مدير عام النقل والأسطول والشحن الدولي",
    contactTitle: "Outbound Logistics & Fleet Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.9212,29.6245"
  },
  {
    id: "eg_titan_889",
    nameAr: "مجموعة أغذية مصر (Agthia Egypt - أطياب للحوم المصنعة والدواجن)",
    nameEn: "Agthia Egypt (Atyab Processed Meats & Poultry Mega Hub)",
    sector: "food",
    subSector: "أكبر مجمعات تصنيع اللحوم المفرومة، البرجر، السجق، ومصنعات الدواجن المتبلة والجاهزة للطهي أطياب",
    city: "qalyubia",
    governorate: "القليوبية",
    address: "المنطقة الصناعية بالخانكة، القليوبية",
    phone1: "0133245000",
    mobile: "01002288449",
    hotline: "19909",
    website: "https://www.atyabfoods.com",
    latitude: 30.2289,
    longitude: 31.3689,
    fleetSize: 270,
    fleetType: "برادات مجمدة لحوم ودواجن حديثة -18 درجة مئوية، تريلات شحن خامات لحوم مستوردة، وفانات توزيع مطاعم",
    fleetTires: "295/80R22.5 • 225/75R17.5 • 315/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "رائدة مصنعات اللحوم الفاخرة أطياب التابعة لمجموعة أغذية الإماراتية والمورد المعتمد لسلاسل الفنادق والمطاعم",
    contactPerson: "مدير عام الأسطول المبرد والنقل المركزي",
    contactTitle: "Reefer Fleet & Logistics General Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.2289,31.3689"
  },
  {
    id: "eg_titan_890",
    nameAr: "شركة أطياب المرشدي لتجهيز وتعبئة اللحوم وتجارة المواشي (El Morshedy Meat Mega Complex)",
    nameEn: "El Morshedy Mega Livestock & Meat Processing Complex",
    sector: "food",
    subSector: "مزارع تسمين وتجارة العجول الحية، مجازر آلية متطورة، وتعبئة اللحوم المبردة والمجمدة للسوق المحلي",
    city: "giza",
    governorate: "الجيزة",
    address: "طريق الفيوم الصحراوي، بالقرب من دهشور، الجيزة",
    phone1: "0238914000",
    mobile: "01004411663",
    hotline: "19894",
    website: "https://www.elmorshedymeat.com",
    latitude: 29.8124,
    longitude: 31.0245,
    fleetSize: 160,
    fleetType: "تريلات تريلا ذات طابقين لنقل الماشية الحية، شاحنات مجمدة لنقل الذبائح ولحوم الكندوز والبتلو",
    fleetTires: "315/80R22.5 • 12.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الصرح الرائد في استيراد وتسمين الثروة الحيوانية وتأمين اللحوم الطازجة لمنافذ التوزيع والهايبر ماركت",
    contactPerson: "مدير عام نقل المواشي واللحوم المبردة",
    contactTitle: "Livestock & Cold Transport Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.8124,31.0245"
  },
  {
    id: "eg_titan_891",
    nameAr: "شركة سكر الفيوم (Fayoum Sugar Works & Refining Mega Plants)",
    nameEn: "Fayoum Sugar Refining & Beet Processing Mega Complex",
    sector: "food",
    subSector: "تكرير سكر البنجر، إنتاج السكر الأبيض، العلف الحيواني، وتغذية مزارع محافظات شمال الصعيد",
    city: "fayoum",
    governorate: "الفيوم",
    address: "مجمع مصانع السكر بقصر الباسل، إطسا، الفيوم",
    phone1: "0846831000",
    mobile: "01006633991",
    hotline: "19746",
    website: "https://www.fayoumsugar.com",
    latitude: 29.2145,
    longitude: 30.7891,
    fleetSize: 220,
    fleetType: "قلابات شحن محصول البنجر، تريلات نقل شكائر سكر، وتريلات صهاريج نقل مولاس للتصدير والمصانع",
    fleetTires: "315/80R22.5 • 12.00R24",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "القلعة الصناعية الأولى للسكر بمحافظة الفيوم التي تخدم مساحات زراعية شاسعة وتنتج أكثر من 160 ألف طن سكر سنوياً",
    contactPerson: "مدير عام النقل والحركة الميدانية",
    contactTitle: "Field Movement & Fleets General Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.2145,30.7891"
  },
  {
    id: "eg_titan_892",
    nameAr: "شركة سكر الإسكندرية (Alexandria Sugar Company - مجمع صافولا ببنجر السكر)",
    nameEn: "Alexandria Sugar Company Mega Complex (Savola Beet Plant)",
    sector: "food",
    subSector: "أحدث مجمعات استخلاص وتكرير السكر من البنجر، السكر السائل للصناعات الغذائية، والمولاس",
    city: "alexandria",
    governorate: "الإسكندرية",
    address: "منطقة بنجر السكر، الكيلو 45 طريق الإسكندرية - مطروح، الإسكندرية",
    phone1: "034571000",
    mobile: "01008855227",
    hotline: "19833",
    website: "https://www.alexandriasugar.com",
    latitude: 30.9891,
    longitude: 29.4124,
    fleetSize: 240,
    fleetType: "تريلات قلابات تفريغ بنجر سريع، تريلات نقل سكر أبيض معبأ، وتريلات صهاريج لنقل السكر السائل للصناعات",
    fleetTires: "315/80R22.5 • 385/65R22.5 • 12.00R24",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الصرح المتطور التابع لمجموعة صافولا للأغذية لسد الفجوة السكرية وتغذية كبرى مصانع الأغذية والمشروبات",
    contactPerson: "رئيس قطاعات الأسطول وتوريد الحاصلات الزراعية",
    contactTitle: "Agri-Harvest & Fleets Sector Head",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.9891,29.4124"
  },
  {
    id: "eg_titan_893",
    nameAr: "شركة النيل للزيوت والمنظفات (Nile Vegetable Oils & Detergents Mega Complex)",
    nameEn: "Nile Vegetable Oils & Detergents Public Industrial Complex",
    sector: "food",
    subSector: "عصر بذرة الصويا والقطن، تكرير الزيوت التموينية، مصانع المسلى الصناعي، والمنظفات الصناعية السائلة",
    city: "cairo",
    governorate: "القاهرة",
    address: "شارع كورنيش النيل، المعادي، القاهرة / مصانع مسطرد وبنها",
    phone1: "0225251100",
    mobile: "01001199446",
    hotline: "19725",
    website: "https://www.nileoils.com.eg",
    latitude: 29.9678,
    longitude: 31.2512,
    fleetSize: 175,
    fleetType: "تريلات صهاريج نقل زيوت نباتية خام ومكررة، شاحنات توزيع سلع تموينية، وتريلات شحن مساحيق غسيل",
    fleetTires: "315/80R22.5 • 11.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "أحد الصروح القومية العريقة لتوفير السلع الأساسية ومساحيق الغسيل وسمن الطبخ التمويني",
    contactPerson: "مدير عام النقل والورش الميكانيكية",
    contactTitle: "Mechanical Workshops & Fleet Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.9678,31.2512"
  },
  {
    id: "eg_titan_894",
    nameAr: "شركة الزيوت المستخلصة ومنتجاتها (Extracted Oils & Products Mega Complex)",
    nameEn: "Extracted Oils & Derivatives Public Company (Alexandria)",
    sector: "food",
    subSector: "استخلاص الزيوت بالمذيبات العضوية، تكرير زيت الصويا ودوار الشمس، وإنتاج الكسب النباتي للأعلاف",
    city: "alexandria",
    governorate: "الإسكندرية",
    address: "شارع قنال المحمودية، محرم بك، الإسكندرية",
    phone1: "033924000",
    mobile: "01003311664",
    hotline: "19831",
    website: "https://www.extractedoils.com.eg",
    latitude: 31.1891,
    longitude: 29.9124,
    fleetSize: 155,
    fleetType: "تريلات صهاريج نقل زيوت غذائية، تريلات نقل كسب أعلاف للمزارع، وشاحنات توزيع زيوت معبأة",
    fleetTires: "315/80R22.5 • 12.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "القلعة التاريخية لاستخلاص الزيوت النباتية وتوفير الأعلاف ومساندة البطاقات التموينية بالإسكندرية والبحيرة",
    contactPerson: "مدير عام اللوجستيات والنقل",
    contactTitle: "Logistics & Transport General Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=31.1891,29.9124"
  },
  {
    id: "eg_titan_895",
    nameAr: "مجموعة سيكام للتنمية الحيوية والزراعة العضوية (SEKEM Group & ISIS Organic)",
    nameEn: "SEKEM Group for Sustainable Development & ISIS Organic Foods",
    sector: "food",
    subSector: "الزراعة الحيوية، تصنيع شاي الأعشاب والأغذية العضوية إيزيس، العسل الطبيعي، والأدوية العشبية أتوس",
    city: "sharqia",
    governorate: "الشرقية",
    address: "طريق بلبيس الصحراوي، الكيلو 3، بلبيس، الشرقية",
    phone1: "0552650000",
    mobile: "01005533882",
    hotline: "19792",
    website: "https://www.sekem.com",
    latitude: 30.4124,
    longitude: 31.5678,
    fleetSize: 140,
    fleetType: "شاحنات شحن أغذية عضوية معقمة، تريلات نقل صادرات للأعشاب الطبية لأوروبا، وسيارات توزيع صيدليات",
    fleetTires: "295/80R22.5 • 225/75R17.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "رائدة التنمية المستدامة والزراعة الحيوية في مصر والعالم والحائزة على جائزة نوبل البديلة للاستدامة",
    contactPerson: "مدير سلاسل الإمداد والشحن التصديري",
    contactTitle: "Supply Chain & Export Shipping Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.4124,31.5678"
  },
  {
    id: "eg_titan_896",
    nameAr: "شركة أروما للمشروبات والصناعات الغذائية (Aroma Food & Beverage - سي بيبسي وجهينة)",
    nameEn: "Aroma Food & Beverage Mega Processing Plants",
    sector: "food",
    subSector: "تعبئة العصائر المركزة والصلصة، وتجفيف وتجميد الفواكه والخضروات للتصدير الدولي",
    city: "beheira",
    governorate: "البحيرة",
    address: "المنطقة الصناعية بكفر الدوار، البحيرة",
    phone1: "0452214500",
    mobile: "01007755119",
    hotline: "19688",
    website: "https://www.aromafoods.com",
    latitude: 31.1345,
    longitude: 30.1245,
    fleetSize: 130,
    fleetType: "تريلات تبريد ونقل حاصلات بستانية، شاحنات تصدير حاويات لموانئ الإسكندرية والدخيلة، وفانات توزيع",
    fleetTires: "315/80R22.5 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "شريك التوريد والتعبئة للعلامات الغذائية الكبرى ومصدر معتمد للفواكه المجمدة للأسواق الأوروبية",
    contactPerson: "مدير عام النقل والأسطول الزراعي",
    contactTitle: "Agricultural Logistics & Fleets Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=31.1345,30.1245"
  },
  {
    id: "eg_titan_897",
    nameAr: "مجموعة مطاحن ومخابز شمال الجيزة (Giza Flour Mills Mega Public Network)",
    nameEn: "Giza & Haram Flour Mills & Public Bakeries Network",
    sector: "food",
    subSector: "طحن الأقماح، توزيع الدقيق البلدي على مخابز الجيزة والهرم وأكتوبر، وإنتاج الردة العلفية",
    city: "giza",
    governorate: "الجيزة",
    address: "شارع فيصل الرئيسي، الجيزة",
    phone1: "0235851200",
    mobile: "01009977334",
    hotline: "19837",
    website: "https://www.gizafilmills.com",
    latitude: 29.9912,
    longitude: 31.1891,
    fleetSize: 170,
    fleetType: "شاحنات شحن دقيق بلدي 50 كجم، تريلات نقل قمح من صوامع إمبابة وأكتوبر، وتريلات هوابر ردة",
    fleetTires: "315/80R22.5 • 12.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "المسؤول عن توفير الدقيق لملايين المواطنين بمحافظة الجيزة ومناطق الهرم والعمرانية وأكتوبر",
    contactPerson: "مدير عام الحركة والنقل التمويني",
    contactTitle: "Supply Fleets & Movement General Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.9912,31.1891"
  },
  {
    id: "eg_titan_898",
    nameAr: "شركة سكر النوبارية الجديدة الزراعية التصديرية (Green Valley Agricultural Sugar)",
    nameEn: "Green Valley Agro-Industrial Sugar Refining & Farms",
    sector: "food",
    subSector: "زراعة وتوريد بنجر السكر، محطات فرز وتعبئة الحاصلات التصديرية، وتكرير السكر العضوي",
    city: "alexandria",
    governorate: "الإسكندرية",
    address: "طريق النوبارية الجديدة، الكيلو 85، الإسكندرية الصحراوي",
    phone1: "034581100",
    mobile: "01001133556",
    hotline: "19943",
    website: "https://www.greenvalley-sugar.com",
    latitude: 30.7124,
    longitude: 30.0456,
    fleetSize: 185,
    fleetType: "قلابات شحن بنجر، تريلات نقل حاصلات زراعية مبردة للتصدير الجوي والبحري، وتريلات حبوب",
    fleetTires: "315/80R22.5 • 385/65R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "مجمع زراعي تصديري يجمع بين تكرير سكر البنجر وفرز محاصيل الموالح والبطاطس للأسواق الروسية والأوروبية",
    contactPerson: "مدير عام النقل وسلاسل الإمداد التصديرية",
    contactTitle: "Export Supply Chain & Fleet Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.7124,30.0456"
  },
  {
    id: "eg_titan_899",
    nameAr: "مجموعة الصعيدي للأعلاف والثروة الداجنة (El Saidy Feeds & Poultry Mega Hub)",
    nameEn: "El Saidy Feeds & Mega Poultry Integrated Complex",
    sector: "food",
    subSector: "أضخم مصانع إنتاج أعلاف التسمين والبياض، صوامع تفريغ الذرة والصويا، ومجازر الدواجن المبردة",
    city: "gharbia",
    governorate: "الغربية",
    address: "المنطقة الصناعية بالمحلة الكبرى، طريق طنطا، الغربية",
    phone1: "0402251000",
    mobile: "01003355778",
    hotline: "19836",
    website: "https://www.elsaidygroup.com",
    latitude: 30.9678,
    longitude: 31.1678,
    fleetSize: 195,
    fleetType: "تريلات صهاريج أعلاف سائبة، تريلات شحن ذرة صفراء وصويا من الموانئ، وشاحنات نقل كتاكيت ودواجن",
    fleetTires: "315/80R22.5 • 385/65R22.5 • 11.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "المورد الأكبر لأعلاف الدواجن ومزارع التسمين في قطاع الدلتا بطاقة إنتاج تتجاوز 4000 طن علف يومياً",
    contactPerson: "رئيس قطاعات الأسطول واللوجستيات الميدانية",
    contactTitle: "Field Fleets & Logistics Sector Head",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.9678,31.1678"
  },
  {
    id: "eg_titan_900",
    nameAr: "شركة سكر أبو قرقاص التاريخية (Abu Qurqas Sugar Mill - مصانع المنيا القديمة)",
    nameEn: "Abu Qurqas Historic Sugar Mills & Distillery Complex",
    sector: "food",
    subSector: "عصر قصب وبنجر السكر، إنتاج السكر الأبيض، تقطير الكحول الطبي والإيثانول والمولاس والخل العضوي",
    city: "minya",
    governorate: "المنيا",
    address: "أبو قرقاص، جنوب محافظة المنيا",
    phone1: "0862420500",
    mobile: "01005577991",
    hotline: "19421",
    website: "https://www.siic.com.eg/abuqurqas",
    latitude: 27.9345,
    longitude: 30.8245,
    fleetSize: 250,
    fleetType: "قطارات وقاطرات ديزل ومقطورات نقل محصول القصب والبنجر، تريلات شحن سكر، وصهاريج كحول طبي نقي",
    fleetTires: "315/80R22.5 • 12.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "أعرق مصانع السكر في مصر وأفريقيا والمؤسس لصناعة الكحول والتقطير الحيوي منذ أكثر من 150 عاماً",
    contactPerson: "رئيس قطاعات النقل والتشغيل وخطوط الديكوفيل",
    contactTitle: "Transport Lines & Plant Fleet General Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=27.9345,30.8245"
  }
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { wave7Part4 };
}
