/**
 * scripts/wave6_data_part4.js
 * Part 4 of Wave 6 Titans (eg_titan_591 to eg_titan_630) - 40 Industrial Titans.
 * Sectors: Oils, Soaps, Chemicals, Fertilizers & Petroleum Refineries & Gas Haulage.
 */

const wave6Part4 = [
  // 5. Oil, Soap, Starch, Detergents & Fertilizers (20)
  {
    id: "eg_titan_591",
    nameAr: "شركة مصر للزيوت والصابون ومصانع الأعلاف (ميت غمر ودكرنس ودمياط)",
    nameEn: "Misr Oil, Soap & Fodder Co. (Mit Ghamr, Dekernes & Damietta)",
    sector: "food",
    subSector: "تكرير الزيوت النباتية، إنتاج السمن الصناعي، المنظفات، وتصنيع أعلاف الدواجن والماشية",
    city: "dakahlia",
    governorate: "الدقهلية",
    address: "شارع مصنع الزيت، ميت غمر، محافظة الدقهلية / مجمع دكرنس ومصنع دمياط",
    phone1: "0506901200",
    mobile: "01002244771",
    hotline: "16191",
    website: "https://www.misroilsoap.com.eg",
    latitude: 30.7189,
    longitude: 31.2589,
    fleetSize: 85,
    fleetType: "صهاريج نقل زيوت نباتية ستانلس ستيل، تريلات كسب وأعلاف، سيارات توزيع سمن وزيت، وأتوبيسات",
    fleetTires: "315/80R22.5 • 295/80R22.5 • 11.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الصرح الغذائي والصناعي الأكبر بالدقهلية ودمياط لتوريد الزيوت التموينية لوزارة التموين",
    contactPerson: "مدير عام النقل والأسطول المركزي",
    contactTitle: "Central Fleet & Transport Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.7189,31.2589"
  },
  {
    id: "eg_titan_592",
    nameAr: "شركة النيل للزيوت والمنظفات ومستودعات التوزيع (مسطرد وسوهاج وأسيوط)",
    nameEn: "The Nile Oil & Detergents Co. (Mostorod, Sohag & Assiut)",
    sector: "food",
    subSector: "تكرير الزيوت، إنتاج المنظفات الصناعية وسوائل الغسيل، وتوريد السمن النباتي لكافة المحافظات",
    city: "qalyubia",
    governorate: "القليوبية",
    address: "شارع ترعة الإسماعيلية، مسطرد، القليوبية / مصانع سوهاج وأسيوط",
    phone1: "0242202100",
    mobile: "01118844335",
    hotline: "16192",
    website: "https://www.nileoil.com.eg",
    latitude: 30.1345,
    longitude: 31.3189,
    fleetSize: 95,
    fleetType: "صهاريج نقل زيوت غذائية، شاحنات توزيع سلع تموينية، تريلات نقل خامات، وأتوبيسات عمال",
    fleetTires: "315/80R22.5 • 295/80R22.5 • 12.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "شركة عريقة تمتلك شبكة مصانع بالقاهرة والصعيد وتدير أسطول صهاريج نقل زيوت ضخم",
    contactPerson: "رئيس قطاع الحركة والنقل والتوزيع",
    contactTitle: "Head of Fleet Transport & Distribution",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.1345,31.3189"
  },
  {
    id: "eg_titan_593",
    nameAr: "شركة الإسكندرية للزيوت والصابون (كرموز وكفر الزيات)",
    nameEn: "Alexandria Oil & Soap Co. (Karmouz & Kafr El Zayat)",
    sector: "food",
    subSector: "استخلاص الزيوت من البذور وتكريرها، صناعة الصابون الفاخر، والمسال البترولي المساعد",
    city: "alexandria",
    governorate: "الإسكندرية",
    address: "شارع قنال المحمودية، راغب باشا، كرموز، الإسكندرية",
    phone1: "033921500",
    mobile: "01229955224",
    hotline: "16193",
    website: "https://www.alexoilsoap.com",
    latitude: 31.1789,
    longitude: 29.8945,
    fleetSize: 75,
    fleetType: "صهاريج شحن زيوت، شاحنات توزيع صابون ومسحوق، وحافلات ركاب",
    fleetTires: "315/80R22.5 • 295/80R22.5 • 11.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "إحدى كبرى شركات الزيوت والصابون بالإسكندرية بأسطول نقل يغطي غرب الدلتا والإسكندرية ومطروح",
    contactPerson: "مدير حركة النقل",
    contactTitle: "Transport Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=31.1789,29.8945"
  },
  {
    id: "eg_titan_594",
    nameAr: "شركة الزيوت المستخلصة ومنتجاتها (محرم بك والقباري بالإسكندرية)",
    nameEn: "Extracted Oils & Derivatives Co. (Alexandria)",
    sector: "food",
    subSector: "استخلاص الزيوت من كسب الصويا والقطن بالمذيبات وإنتاج خامات الأعلاف المركزة والصابون",
    city: "alexandria",
    governorate: "الإسكندرية",
    address: "شارع قنال السويس، محرم بك، الإسكندرية / مجمع القباري",
    phone1: "034954100",
    mobile: "01007733221",
    hotline: "16194",
    website: "https://www.extractedoils.com.eg",
    latitude: 31.1845,
    longitude: 29.9045,
    fleetSize: 70,
    fleetType: "صهاريج كيماويات وزيوت، تريلات تيبار شحن كسب وفول صويا، وأتوبيسات ركاب",
    fleetTires: "315/80R22.5 • 12.00R20 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "مصنع استخلاص بالبذور الزيتية عريق يرتبط بحركة شحن خام الصويا من ميناء الإسكندرية والدخيلة",
    contactPerson: "مدير الحركة والصيانة الميدانية",
    contactTitle: "Maintenance & Transport Supervisor",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=31.1845,29.9045"
  },
  {
    id: "eg_titan_595",
    nameAr: "الشركة المصرية للنشا والخميرة والمنظفات (محرم بك - الإسكندرية)",
    nameEn: "Egyptian Starch, Yeast & Detergents Co. (Alexandria)",
    sector: "food",
    subSector: "تصنيع الخميرة الطازجة والمجففة للمخابز والمستخلصات الحيوية والنشا الغذائي والصناعي",
    city: "alexandria",
    governorate: "الإسكندرية",
    address: "شارع أحمد أبو سليمان، السيوف / مصانع محرم بك، الإسكندرية",
    phone1: "035014100",
    mobile: "01114422883",
    hotline: "16195",
    website: "https://www.starchyeeast.com",
    latitude: 31.2289,
    longitude: 29.9812,
    fleetSize: 80,
    fleetType: "سيارات برادات مبردة لتوزيع الخميرة الحية على المخابز يومياً، شاحنات نقل نشا، وأتوبيسات",
    fleetTires: "225/75R17.5 • 295/80R22.5 • 315/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "المورد الاستراتيجي للخميرة الحية لكافة مخابز الإسكندرية والدلتا والقاهرة بأسطول برادات سريع الحركة",
    contactPerson: "مدير عام النقل والتوزيع المبرد",
    contactTitle: "Refrigerated Transport & Distribution Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=31.2289,29.9812"
  },
  {
    id: "eg_titan_596",
    nameAr: "الشركة العامة لمصانع النشا والجلوكوز (طرة ومسطرد)",
    nameEn: "Egyptian Starch & Glucose Co. (Tora & Mostorod Plants)",
    sector: "food",
    subSector: "معالجة الذرة الرطبة لإنتاج الجلوكوز، الفركتوز، النشا المعدل، وزيت الذرة لمصانع الحلويات",
    city: "cairo",
    governorate: "القاهرة",
    address: "كورنيش النيل، طرة البلد، المعادي، القاهرة / مجمع مسطرد",
    phone1: "0225251400",
    mobile: "01228811775",
    hotline: "16196",
    website: "https://www.starchglucose.com",
    latitude: 29.9412,
    longitude: 31.2789,
    fleetSize: 85,
    fleetType: "صهاريج نقل شراب الجلوكوز والفركتوز السائل، تريلات نقل ذرة صفراء، شاحنات نشا، وأتوبيسات",
    fleetTires: "315/80R22.5 • 385/65R22.5 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "المورد الرئيسي لشراب الجلوكوز والفركتوز لكبرى مصانع الأغذية والحلويات والمشروبات الغازية في مصر",
    contactPerson: "مدير عام الأسطول وحركة الصهاريج",
    contactTitle: "Tankers Fleet & Transport Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.9412,31.2789"
  },
  {
    id: "eg_titan_597",
    nameAr: "شركة الدلتا لتصنيع الخميرة والمستخلصات الحيوية (مدينة السادات)",
    nameEn: "Delta Yeast & Bio-Extracts Industries (Sadat City)",
    sector: "food",
    subSector: "أحدث مجمع لتصنيع الخميرة الجافة الفورية وخميرة الخبز وتصديرها للدول الإفريقية والعربية",
    city: "menofia",
    governorate: "المنوفية",
    address: "المنطقة الصناعية الخامسة، مدينة السادات، محافظة المنوفية",
    phone1: "0482616200",
    mobile: "01003388114",
    hotline: "16197",
    website: "https://www.deltayeast.com",
    latitude: 30.3812,
    longitude: 30.5012,
    fleetSize: 65,
    fleetType: "شاحنات شحن موانئ، فانات توزيع خميرة فورية، تريلات نقل مولاس، وأتوبيسات ركاب",
    fleetTires: "315/80R22.5 • 295/80R22.5 • 225/75R17.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "مصنع تكنولوجي متطور لتصنيع وتصدير الخميرة الفورية بأسطول شحن موانئ وتوزيع محلي",
    contactPerson: "مدير اللوجستيات والحركة",
    contactTitle: "Logistics Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.3812,30.5012"
  },
  {
    id: "eg_titan_598",
    nameAr: "مجموعة عافية الدولية للزيوت والسمن النباتي (السويس والعاشر من رمضان)",
    nameEn: "Afia International Egypt - Edible Oils & Ghee (Savola Group)",
    sector: "food",
    subSector: "تكرير وتعبئة زيوت الذرة وعباد الشمس والسمن النباتي (عافية، سلايت، حلوة)",
    city: "suez",
    governorate: "السويس",
    address: "المنطقة الحرة للأدبية، السويس / مجمع مصانع العاشر من رمضان",
    phone1: "0623691200",
    mobile: "01115599442",
    hotline: "16198",
    website: "https://www.afia.com.eg",
    latitude: 29.8512,
    longitude: 32.4889,
    fleetSize: 110,
    fleetType: "شاحنات مرسيدس أكتروس توزيع، صهاريج نقل زيوت خام من ميناء الأدبية، وفانات توزيع تجزئة",
    fleetTires: "315/80R22.5 • 295/80R22.5 • 385/65R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "إحدى كبرى مجموعات تصنيع وتوزيع زيوت الطعام الفاخرة بمصر التابعة لمجموعة صافولا بأسطول شحن وتوزيع ضخم",
    contactPerson: "مدير عام أسطول التوزيع الوطني",
    contactTitle: "National Distribution Fleet Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.8512,32.4889"
  },
  {
    id: "eg_titan_599",
    nameAr: "شركة أرما للصابون والمنظفات الصناعية (العاشر من رمضان)",
    nameEn: "Arma Soap & Detergent Mega Industries (10th of Ramadan)",
    sector: "manufacturing",
    subSector: "تصنيع مساحيق الغسيل الأوتوماتيك والعادي، الصابون، والمنظفات السائلة (أوكسي Oxi وسباركل)",
    city: "sharqia",
    governorate: "الشرقية",
    address: "المنطقة الصناعية B3، مدينة العاشر من رمضان، محافظة الشرقية",
    phone1: "015418800",
    mobile: "01224433887",
    hotline: "16199",
    website: "https://www.armagroup.com",
    latitude: 30.2912,
    longitude: 31.7489,
    fleetSize: 115,
    fleetType: "تريلات شحن مساحيق غسيل للمحافظات، شاحنات صندوقية، صهاريج كيماويات، وأسطول حافلات ركاب",
    fleetTires: "315/80R22.5 • 295/80R22.5 • 385/65R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "عملاق تصنيع المنظفات والصابون بمصر (أوكسي) بأسطول شحن لوجستي يغطي كافة سلاسل الإمداد ومنافذ البيع",
    contactPerson: "مدير عام النقل واللوجستيات الميدانية",
    contactTitle: "General Logistics & Transport Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.2912,31.7489"
  },
  {
    id: "eg_titan_600",
    nameAr: "شركة هينكل مصر لصناعة المنظفات الصناعية (برسيل وبريل - بورسعيد و6 أكتوبر)",
    nameEn: "Henkel Egypt for Detergents (Persil & Pril - Port Said & 6th of October)",
    sector: "manufacturing",
    subSector: "صناعة المنظفات المنزلية ومساحيق الغسيل وسوائل الأطباق ومستحضرات العناية وفق معايير ألمانية",
    city: "port_said",
    governorate: "بورسعيد",
    address: "المنطقة الصناعية C2، بورسعيد / مكاتب ومصانع 6 أكتوبر، الجيزة",
    phone1: "0663733100",
    mobile: "01007799443",
    hotline: "16200",
    website: "https://www.henkel.com.eg",
    latitude: 31.2489,
    longitude: 32.2789,
    fleetSize: 105,
    fleetType: "تريلات نقل مساحيق ومنظفات معتمدة، فانات توزيع، صهاريج خامات، وأتوبيسات مرسيدس عمال",
    fleetTires: "315/80R22.5 • 295/80R22.5 • 225/75R17.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الشركة الألمانية العالمية الرائدة في المنظفات (برسيل، بريل) بأسطول شحن ضخم يربط مصانع بورسعيد بمستودعات الجمهورية",
    contactPerson: "مدير العمليات اللوجستية وسلاسل الإمداد",
    contactTitle: "Supply Chain & Logistics Operations Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=31.2489,32.2789"
  },
  {
    id: "eg_titan_601",
    nameAr: "شركة بروكتر آند جامبل مصر للمنظفات والعناية (مدينة 6 أكتوبر)",
    nameEn: "Procter & Gamble Egypt (P&G - Ariel, Tide & Pampers - 6th of October)",
    sector: "manufacturing",
    subSector: "تصنيع مساحيق الغسيل (إريال وتايد)، حفاضات بامبرز، ومستحضرات العناية الشخصية التصديرية",
    city: "giza",
    governorate: "الجيزة",
    address: "المنطقة الصناعية الرابعة، مدينة السادس من أكتوبر، الجيزة",
    phone1: "0238339100",
    mobile: "01112277443",
    hotline: "16201",
    website: "https://www.pg.com.eg",
    latitude: 29.9412,
    longitude: 30.9145,
    fleetSize: 125,
    fleetType: "تريلات شحن ثقيل، شاحنات توزيع معتمدة دولياً، حاويات تصدير موانئ، وحافلات ركاب راقية",
    fleetTires: "315/80R22.5 • 385/65R22.5 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "أكبر مركز تصنيع وتصدير إقليمي لشركة P&G لمنطقة الشرق الأوسط وإفريقيا بأسطول لوجستي عالمي",
    contactPerson: "مدير النقل والشحن الخارجي لمنطقة إفريقيا",
    contactTitle: "Inbound & Outbound Transport Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.9412,30.9145"
  },
  {
    id: "eg_titan_602",
    nameAr: "شركة يونيلفر مشرق لصناعة الصابون والمنظفات (مجمع مصانع 6 أكتوبر)",
    nameEn: "Unilever Mashreq for Soaps & Home Care (6th of October)",
    sector: "manufacturing",
    subSector: "تصنيع صابون دوف ولوكس ومساحيق أومو وشاي ليبتون ومنتجات العناية المنزلية والشخصية",
    city: "giza",
    governorate: "الجيزة",
    address: "المنطقة الصناعية الثالثة، مدينة 6 أكتوبر، محافظة الجيزة",
    phone1: "0238342100",
    mobile: "01223388116",
    hotline: "16202",
    website: "https://www.unilever.com.eg",
    latitude: 29.9289,
    longitude: 30.9289,
    fleetSize: 110,
    fleetType: "شاحنات شحن بضائع، تريلات لنقل الخامات، فانات توزيع، وأتوبيسات ركاب",
    fleetTires: "315/80R22.5 • 295/80R22.5 • 225/75R17.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "المجمع الصناعي الرائد لشركة يونيليفر لمنطقة المشرق العربي بأسطول شحن وتوزيع استراتيجي",
    contactPerson: "مدير عام النقل والأسطول",
    contactTitle: "Transport Logistics Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.9289,30.9289"
  },
  {
    id: "eg_titan_603",
    nameAr: "شركة كفر الزيات للمبيدات والكيماويات الزراعية (كفر الزيات - الغربية)",
    nameEn: "Kafr El Zayat Pesticides & Chemicals Co. (KZ Chemicals)",
    sector: "manufacturing",
    subSector: "تصنيع المبيدات الحشرية والفطرية، الأسمدة الورقية، والمطهرات البيطرية والصحية العامة",
    city: "gharbia",
    governorate: "الغربية",
    address: "طريق الدلتا الزراعي، كفر الزيات، محافظة الغربية",
    phone1: "0402541200",
    mobile: "01004499228",
    hotline: "16203",
    website: "https://www.kzchem.com",
    latitude: 30.8212,
    longitude: 30.8145,
    fleetSize: 75,
    fleetType: "شاحنات نقل مواد كيماوية مجهزة ومعتمدة للسلامة، صهاريج سوائل، وأتوبيسات ركاب",
    fleetTires: "315/80R22.5 • 295/80R22.5 • 11.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الصرح الكيماوي العريق في مصر والشرق الأوسط لإنتاج المبيدات الزراعية بأسطول نقل معتمد للمواد الخطرة",
    contactPerson: "مدير إدارة السلامة والنقل الكيماوي",
    contactTitle: "Safety & Chemical Transport Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.8212,30.8145"
  },
  {
    id: "eg_titan_604",
    nameAr: "الشركة المالية والصناعية بأسيوط (مصانع سماد منقباد)",
    nameEn: "EFIC Manqabad Superphosphate Mega Fertilizer Plant (Assiut)",
    sector: "manufacturing",
    subSector: "إنتاج سماد السوبر فوسفات الأحادي والمحبب وحمض الكبريتيك لتسميد أراضي الصعيد ومصر",
    city: "assiut",
    governorate: "أسيوط",
    address: "منطقة منقباد الصناعية، مركز أسيوط، محافظة أسيوط",
    phone1: "0882381200",
    mobile: "01118855331",
    hotline: "16204",
    website: "https://www.efic-assiut.com",
    latitude: 27.2412,
    longitude: 31.1145,
    fleetSize: 90,
    fleetType: "تريلات تيبار نقل صخور الفوسفات، صهاريج حمض كبريتيك مبطنة، شاحنات أسمدة، وأتوبيسات ورديات",
    fleetTires: "12.00R24 • 315/80R22.5 • 12.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "أكبر مصنع لإنتاج الأسمدة الفوسفاتية في صعيد مصر التابع للشركة المالية والصناعية المصرية (EFIC)",
    contactPerson: "مدير عام النقل والمهمات الثقيلة بأسيوط",
    contactTitle: "General Transport & Heavy Fleet Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=27.2412,31.1145"
  },
  {
    id: "eg_titan_605",
    nameAr: "شركة الإسكندرية للأسمدة (أبو قير سماد 3 وأبو قير)",
    nameEn: "Alexandria Fertilizers Co. (AlexFert - Abu Qir Industrial Zone)",
    sector: "manufacturing",
    subSector: "إنتاج سماد اليوريا المحببة والأمونيا السائلة وتصديرها لمختلف قارات العالم",
    city: "alexandria",
    governorate: "الإسكندرية",
    address: "منطقة الطابية، خليج أبو قير، الإسكندرية",
    phone1: "035603100",
    mobile: "01221188449",
    hotline: "16205",
    website: "https://www.alexfert.com",
    latitude: 31.3112,
    longitude: 30.1289,
    fleetSize: 100,
    fleetType: "تريلات شحن يوريا سائبة، صهاريج نقل أمونيا مبردة، تريلات نقل أكياس لموانئ الإسكندرية، وأتوبيسات",
    fleetTires: "315/80R22.5 • 385/65R22.5 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "إحدى كبرى قلاع صناعة الأسمدة النيتروجينية في مصر المطلة على البحر المتوسط بأسطول نقل وتصدير ثقيل",
    contactPerson: "رئيس قطاع الحركة والنقل الميداني",
    contactTitle: "Head of Fleet Operations & Shipping",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=31.3112,30.1289"
  },
  {
    id: "eg_titan_606",
    nameAr: "شركة إيفرجرو للأسمدة المتخصصة والبوتاسيوم (السادات وأبو رواش)",
    nameEn: "Evergrow for Specialty Fertilizers & Potassium Sulfate Mega Plants",
    sector: "manufacturing",
    subSector: "أكبر منتج لسلفات البوتاسيوم وكلوريد الكالسيوم وحامض الفوسفوريك النقي في الشرق الأوسط",
    city: "menofia",
    governorate: "المنوفية",
    address: "المنطقة الصناعية السابعة، مدينة السادات / مجمع أبو رواش بالجيزة",
    phone1: "0482618100",
    mobile: "01008833119",
    hotline: "16206",
    website: "https://www.evergrowfertegypt.com",
    latitude: 30.3689,
    longitude: 30.5189,
    fleetSize: 110,
    fleetType: "صهاريج أحماض كيماوية متخصصة، تريلات شحن سلفات بوتاسيوم، شاحنات تصدير، وأتوبيسات ركاب",
    fleetTires: "315/80R22.5 • 385/65R22.5 • 12.00R24",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "صرح صناعي عملاق في إنتاج الأسمدة المتخصصة بالسادات يمتلك أسطول صهاريج نقل أحماض ضخم",
    contactPerson: "مدير عام اللوجستيات والنقل الكيماوي",
    contactTitle: "Chemical Logistics & Fleet Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.3689,30.5189"
  },
  {
    id: "eg_titan_607",
    nameAr: "شركة حلوان للأسمدة (التبين - حلوان)",
    nameEn: "Helwan Fertilizers Co. (HFC - El Tebeen, Helwan)",
    sector: "manufacturing",
    subSector: "إنتاج اليوريا والأمونيا ونترات النشادر المخصصة للمشروعات الزراعية القومية الكبرى",
    city: "helwan",
    governorate: "القاهرة",
    address: "منطقة التبين الصناعية، حلوان، محافظة القاهرة",
    phone1: "0225012400",
    mobile: "01115533887",
    hotline: "16207",
    website: "https://www.helwanfert.com",
    latitude: 29.7789,
    longitude: 31.3112,
    fleetSize: 95,
    fleetType: "تريلات تيبار شحن أسمدة، صهاريج غازات صناعية، شاحنات نقل ثقيل، وحافلات ورديات",
    fleetTires: "315/80R22.5 • 385/65R22.5 • 12.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "قلعة الأسمدة النيتروجينية بجنوب القاهرة بأسطول شحن مباشر لمشروعات استصلاح الأراضي",
    contactPerson: "مدير عام النقل والأسطول",
    contactTitle: "General Fleet Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.7789,31.3112"
  },
  {
    id: "eg_titan_608",
    nameAr: "الشركة المصرية لإنتاج الإيثيلين ومشتقاته (إيثيدكو - الإسكندرية)",
    nameEn: "Egyptian Ethylene & Derivatives Co. (ETHYDCO - Alexandria)",
    sector: "petroleum",
    subSector: "أحدث وأضخم مجمع لإنتاج البولي إيثيلين عالي ومنخفض الكثافة والبوتادين بالشرق الأوسط",
    city: "alexandria",
    governorate: "الإسكندرية",
    address: "مجمع البتروكيماويات، النهضة، العامرية، الإسكندرية",
    phone1: "034770100",
    mobile: "01229911883",
    hotline: "16208",
    website: "https://www.ethydco-eg.com",
    latitude: 31.0512,
    longitude: 29.8412,
    fleetSize: 105,
    fleetType: "شاحنات شحن حبيبات البولي إيثيلين، صهاريج نقل غاز البوتادين المضغوط، وتريلات حاويات تصدير",
    fleetTires: "315/80R22.5 • 385/65R22.5 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الصرح البتروكيماوي القومي الأضخم بالإسكندرية المغذي لصناعة البلاستيك في مصر وإفريقيا وأوروبا",
    contactPerson: "مدير عام النقل والعمليات اللوجستية للبتروكيماويات",
    contactTitle: "Petrochemical Logistics & Fleet Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=31.0512,29.8412"
  },
  {
    id: "eg_titan_609",
    nameAr: "شركة البتروكيماويات المصرية (العامرية - الإسكندرية)",
    nameEn: "Egyptian Petrochemicals Co. (EPC - Amreya, Alexandria)",
    sector: "petroleum",
    subSector: "إنتاج البولي فينيل كلوريد (PVC)، الصودا الكاوية، والكلور السائل لمصانع المواسير والكيماويات",
    city: "alexandria",
    governorate: "الإسكندرية",
    address: "الكيلو 36 طريق الإسكندرية - القاهرة الصحراوي، العامرية، الإسكندرية",
    phone1: "034771200",
    mobile: "01002299554",
    hotline: "16209",
    website: "https://www.petrochem.com.eg",
    latitude: 31.0412,
    longitude: 29.8312,
    fleetSize: 90,
    fleetType: "صهاريج كلور وصودا كاوية معتمدة، شاحنات شحن بودرة PVC، وأسطول حافلات ركاب",
    fleetTires: "315/80R22.5 • 295/80R22.5 • 12.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "رائد صناعة الـ PVC والصودا الكاوية في مصر التابع للهيئة المصرية العامة للبترول",
    contactPerson: "مدير الحركة والنقل الميداني",
    contactTitle: "Field Transport Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=31.0412,29.8312"
  },
  {
    id: "eg_titan_610",
    nameAr: "الشركة المصرية لإنتاج البروبيلين والبولى بروبيلين (EPP - بورسعيد)",
    nameEn: "Egyptian Propylene & Polypropylene Co. (EPP - Port Said)",
    sector: "petroleum",
    subSector: "إنتاج خام البولي بروبيلين المستخدم في صناعة السجاد والأجولة المنسوجة وقطع غيار السيارات",
    city: "port_said",
    governorate: "بورسعيد",
    address: "المنطقة الصناعية بالرسوة، طريق الإسماعيلية بورسعيد، بورسعيد",
    phone1: "0663771500",
    mobile: "01116688332",
    hotline: "16210",
    website: "https://www.epp-eg.com",
    latitude: 31.2212,
    longitude: 32.2612,
    fleetSize: 85,
    fleetType: "تريلات شحن رولات وحبيبات بولي بروبيلين، شاحنات حاويات موانئ، وحافلات ركاب",
    fleetTires: "315/80R22.5 • 385/65R22.5 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "مجمع بتروكيماوي عالمي ببورسعيد يغذي كبرى مصانع السجاد واللدائن بأسطول شحن وتصدير متميز",
    contactPerson: "مدير الشحن والخدمات اللوجستية",
    contactTitle: "Logistics & Shipping Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=31.2212,32.2612"
  },

  // 6. Petroleum Refineries, Fuel Haulage & Gas Networks (20)
  {
    id: "eg_titan_611",
    nameAr: "الشركة العامة للبترول (رأس غارب والواحات والصحراء الشرقية)",
    nameEn: "General Petroleum Co. (GPC - Ras Gharib, Red Sea & Western Oases)",
    sector: "petroleum",
    subSector: "أول شركة وطنية مصرية 100% لاستكشاف وإنتاج وتكرير النفط الخام والغاز بالصحاري المصرية",
    city: "red_sea",
    governorate: "البحر الأحمر",
    address: "مدينة رأس غارب، محافظة البحر الأحمر / المقر الإداري بمدينة نصر، القاهرة",
    phone1: "0653621400",
    mobile: "01001177992",
    hotline: "16211",
    website: "https://www.gpc.com.eg",
    latitude: 28.3589,
    longitude: 33.0812,
    fleetSize: 140,
    fleetType: "شاحنات صهاريج بترول ثقيل 6x6، كاسحات رمال، حفارات وأبراج صيانة آبار، وأسطول حافلات دفع رباعي صحراوي",
    fleetTires: "14.00R20 • 12.00R24 • 315/80R22.5 • 12.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "رائدة شركات البترول الوطنية في مصر بأسطول صحراوي عملاق يجوب حقول رأس غارب وسدر وأبو سنان",
    contactPerson: "مدير عام النقل والأسطول الصحراوي الثقيل",
    contactTitle: "General Manager of Desert Fleet Operations",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=28.3589,33.0812"
  },
  {
    id: "eg_titan_612",
    nameAr: "شركة السويس لتصنيع البترول (السويس)",
    nameEn: "Suez Oil Processing Co. (SOPC - Suez Refinery)",
    sector: "petroleum",
    subSector: "تكرير البترول الخام، إنتاج المازوت، السولار، البنزين عالي الأوكتين، والأسفلت لرصف الطرق",
    city: "suez",
    governorate: "السويس",
    address: "شارع صلاح نسيم، الزيتية، محافظة السويس",
    phone1: "0623321500",
    mobile: "01228844116",
    hotline: "16212",
    website: "https://www.sopc.com.eg",
    latitude: 29.9545,
    longitude: 32.5312,
    fleetSize: 110,
    fleetType: "صهاريج نقل أسفلت ساخن معزولة حرارياً، صهاريج وقود، سيارات إطفاء ومكافحة حريق بترولية، وأتوبيسات",
    fleetTires: "315/80R22.5 • 295/80R22.5 • 12.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "أقدم معمل تكرير بترول في الشرق الأوسط (تأسس 1921) يخضع لمشروع التحديث والتوسعات القومية الكبرى",
    contactPerson: "مدير عام إدارة النقل والورش المركزية",
    contactTitle: "General Transport & Central Workshops Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.9545,32.5312"
  },
  {
    id: "eg_titan_613",
    nameAr: "شركة النصر للبترول ومعامل التكرير (الزيتية - السويس)",
    nameEn: "El Nasr Petroleum Co. (NPC - El Zayteya Refinery, Suez)",
    sector: "petroleum",
    subSector: "تكرير النفط الخام وإنتاج وقود الطائرات (Jet Fuel)، غاز البوتاجاز، والمنتجات البترولية الخفيفة",
    city: "suez",
    governorate: "السويس",
    address: "منطقة الزيتية، السويس / مستودعات حوض الدرس وميناء الزيتيات",
    phone1: "0623331200",
    mobile: "01113355998",
    hotline: "16213",
    website: "https://www.nasrpetroleum.com",
    latitude: 29.9612,
    longitude: 32.5412,
    fleetSize: 115,
    fleetType: "شاحنات صهريجية لنقل وقود الطائرات للمطارات، صهاريج بوتاجاز مسال، وأسطول حافلات ورديات",
    fleetTires: "315/80R22.5 • 385/65R22.5 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "صرح تكرير وطني استراتيجي يغذي مطارات وموانئ مصر بالوقود المتخصص بأسطول صهاريج نقل دقيق",
    contactPerson: "مدير حركة النقل والشحن البترولي",
    contactTitle: "Petroleum Transport & Fleet Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.9612,32.5412"
  },
  {
    id: "eg_titan_614",
    nameAr: "شركة أسيوط لتكرير البترول ومعمل جحدم (أسيوط)",
    nameEn: "Assiut Oil Refining Co. (ASORC - Gahdam Refinery, Assiut)",
    sector: "petroleum",
    subSector: "معمل التكرير الرئيسي في صعيد مصر ومجمع التكسير الهيدروجيني للمازوت (أنوبك)",
    city: "assiut",
    governorate: "أسيوط",
    address: "منطقة جحدم، مركز منفلوط، محافظة أسيوط",
    phone1: "0882411200",
    mobile: "01006688224",
    hotline: "16214",
    website: "https://www.asorc.com",
    latitude: 27.2912,
    longitude: 31.0212,
    fleetSize: 125,
    fleetType: "صهاريج نقل مشتقات بترولية، سيارات إطفاء متطورة، شاحنات صيانة، وأسطول حافلات ركاب مرسيدس",
    fleetTires: "315/80R22.5 • 295/80R22.5 • 12.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "شريان الطاقة والوقود لمحافظات الصعيد بأكملها مع مشروع مجمع أنوبك لإنتاج السولار عالي الجودة",
    contactPerson: "رئيس قطاع النقل والخدمات الميكانيكية",
    contactTitle: "Head of Mechanical Services & Fleet Transport",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=27.2912,31.0212"
  },
  {
    id: "eg_titan_615",
    nameAr: "شركة العامرية لتكرير البترول ومجمع الزيوت الخاصة (الإسكندرية)",
    nameEn: "Amreya Petroleum Refining Co. (APRC - Alexandria)",
    sector: "petroleum",
    subSector: "تكرير البترول وإنتاج الزيوت الأساسية، الشموع البرافينية، والألكيل بنزين الخطي (LAB)",
    city: "alexandria",
    governorate: "الإسكندرية",
    address: "مرغم، الكيلو 20 طريق الإسكندرية - القاهرة الصحراوي، الإسكندرية",
    phone1: "034772100",
    mobile: "01224488339",
    hotline: "16215",
    website: "https://www.aprc.com.eg",
    latitude: 31.0812,
    longitude: 29.8112,
    fleetSize: 110,
    fleetType: "صهاريج نقل زيوت بترولية خاصة، صهاريج وقود، شاحنات شموع برافين، وأتوبيسات ركاب",
    fleetTires: "315/80R22.5 • 295/80R22.5 • 12.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "القلعة البترولية المتخصصة في إنتاج الزيوت الأساسية والشموع البرافينية بالإسكندرية بأسطول شحن معتمد",
    contactPerson: "مدير عام النقل والورش",
    contactTitle: "General Fleet & Transport Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=31.0812,29.8112"
  },
  {
    id: "eg_titan_616",
    nameAr: "شركة القاهرة لتكرير البترول (مسطرد وطنطا)",
    nameEn: "Cairo Oil Refining Co. (CORC - Mostorod & Tanta Refineries)",
    sector: "petroleum",
    subSector: "تكرير النفط لتغذية استهلاك القاهرة الكبرى والدلتا بالبنزين والسولار والمازوت والبوتاجاز",
    city: "qalyubia",
    governorate: "القليوبية",
    address: "طريق ترعة الإسماعيلية، مسطرد، محافظة القليوبية / معمل تكرير طنطا",
    phone1: "0242203100",
    mobile: "01119955227",
    hotline: "16216",
    website: "https://www.corc-eg.com",
    latitude: 30.1389,
    longitude: 31.3212,
    fleetSize: 130,
    fleetType: "صهاريج وقود عملاقة، سيارات طوارئ وإطفاء بترولية، شاحنات صيانة، وأسطول حافلات نقل عمال ضخم",
    fleetTires: "315/80R22.5 • 295/80R22.5 • 12.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "أكبر طاقة تكريرية في مصر تغذي العاصمة ومحافظات الدلتا بأسطول صهاريج وسيارات خدمة عملاق",
    contactPerson: "مدير عام النقل والمهمات",
    contactTitle: "Transport & Equipment General Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.1389,31.3212"
  },
  {
    id: "eg_titan_617",
    nameAr: "شركة بوتاجاسكو لنقل وتوصيل أسطوانات الغاز (أسطول 850 شاحنة نقل)",
    nameEn: "Butagasco - National Bottled Gas Transport & Distribution Fleet",
    sector: "petroleum",
    subSector: "النقل والتوزيع القومي لأسطوانات البوتاجاز المنزلية والتجارية لكافة ربوع الجمهورية",
    city: "cairo",
    governorate: "القاهرة",
    address: "شارع الطيران، مدينة نصر، القاهرة / مستودعات مركزية بجميع المحافظات",
    phone1: "0222621400",
    mobile: "01002244118",
    hotline: "16217",
    website: "https://www.butagasco.com",
    latitude: 30.0612,
    longitude: 31.3312,
    fleetSize: 220,
    fleetType: "تريلات تريلا نقل أسطوانات متعددة الطوابق، شاحنات جامبو توزيع للمستودعات، وسيارات صيانة طوارئ",
    fleetTires: "315/80R22.5 • 295/80R22.5 • 8.25R16 • 7.50R16",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "أضخم أسطول شاحنات مخصص لنقل أسطوانات الغاز في مصر يعمل يومياً لتأمين الطاقة لكافة قرى ومراكز الجمهورية",
    contactPerson: "مدير عام الأسطول والنقل المركزي بالجمهورية",
    contactTitle: "General Fleet & National Transport Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.0612,31.3312"
  },
  {
    id: "eg_titan_618",
    nameAr: "شركة السهام البترولية لنقل وتوزيع المنتجات البترولية (450 تريلا صهريج)",
    nameEn: "Petroleum Arrows Co. - Fuel Haulage & Tanker Fleet (El Seham)",
    sector: "petroleum",
    subSector: "نقل المشتقات البترولية السائلة والغازات الصب عبر أضخم أسطول صهاريج نقل ثقيل في مصر",
    city: "cairo",
    governorate: "القاهرة",
    address: "الكيلو 4.5 طريق السويس الصحراوي، ألماظة، القاهرة / جراجات القطامية والإسكندرية والسويس وأسيوط",
    phone1: "0222912400",
    mobile: "01227744331",
    hotline: "16218",
    website: "https://www.elseham.com.eg",
    latitude: 30.0912,
    longitude: 31.3812,
    fleetSize: 250,
    fleetType: "تريلات صهريج وقود مرسيدس أكتروس وفولفو، صهاريج غاز صب، صهاريج كيماويات، وأطقم صيانة متنقلة",
    fleetTires: "315/80R22.5 • 385/65R22.5 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الصرح الوطني الأضخم على الإطلاق لنقل وتوزيع الوقود السائل والغاز الصب التابع لقطاع البترول المصري",
    contactPerson: "مساعد رئيس الشركة للعمليات وحركة الأسطول",
    contactTitle: "Vice President for Fleet Operations & Logistics",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.0912,31.3812"
  },
  {
    id: "eg_titan_619",
    nameAr: "شركة بترول بلاعيم (بتروبل - حقول أبو رديس وبورسعيد)",
    nameEn: "Belayim Petroleum Co. (PETROBEL - Abu Rudeis & Port Said)",
    sector: "petroleum",
    subSector: "إنتاج الزيت الخام من حقول سيناء البرية والبحرية وحقل ظهر العملاق للغاز ببورسعيد",
    city: "south_sinai",
    governorate: "جنوب سيناء",
    address: "مدينة أبو رديس، جنوب سيناء / مجمع حقل ظهر، الجميل، بورسعيد / المقر بمدينة نصر",
    phone1: "0693501200",
    mobile: "01004411776",
    hotline: "16219",
    website: "https://www.petrobel.org",
    latitude: 28.9112,
    longitude: 33.1812,
    fleetSize: 135,
    fleetType: "شاحنات دعم حقول البترول، شاحنات صحراوية مجهزة، كاسحات، أوناش هيدروليكية، وأتوبيسات ركاب مكيفة",
    fleetTires: "14.00R20 • 12.00R24 • 315/80R22.5 • 11.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "المشغل الرئيسي لأكبر حقل غاز في البحر المتوسط (حقل ظهر) وحقول بلاعيم بسيناء بأسطول دعم وتوزيع ضخم",
    contactPerson: "مدير عام النقل والخدمات الميدانية البحرية والبرية",
    contactTitle: "General Manager of Field Fleet & Logistics",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=28.9112,33.1812"
  },
  {
    id: "eg_titan_620",
    nameAr: "شركة بدر الدين للبترول (بابيتكو - حقول الصحراء الغربية)",
    nameEn: "Badr Petroleum Co. (BAPETCO - Western Desert Oil & Gas Fields)",
    sector: "petroleum",
    subSector: "استكشاف وإنتاج الغاز الطبيعي والنفط الخام بحقول بدر الدين والأبيض وسترا بالصحراء الغربية",
    city: "matrouh",
    governorate: "مطروح",
    address: "حقول بدر الدين بالصحراء الغربية / المقر الإداري بالمعادي، القاهرة",
    phone1: "0225191200",
    mobile: "01118822441",
    hotline: "16220",
    website: "https://www.bapetco.net",
    latitude: 29.8512,
    longitude: 27.9112,
    fleetSize: 120,
    fleetType: "شاحنات دفع رباعي 6x6 مجهزة للرمال العميقة، شاحنات صهاريج مياه ووقود صحراوية، وأتوبيسات فرق الحقول",
    fleetTires: "14.00R20 • 12.00R24 • 315/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "عملاق إنتاج الغاز والنفط بالصحراء الغربية بأسطول مركبات صحراوية ومعدات شاقة عالي الاعتمادية",
    contactPerson: "مدير العمليات اللوجستية والنقل الصحراوي",
    contactTitle: "Western Desert Logistics & Transport Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.8512,27.9112"
  },
  {
    id: "eg_titan_621",
    nameAr: "شركة شقير البحرية للزيت (أوسوكو - رأس شقير بالبحر الأحمر)",
    nameEn: "Offshore Shukheir Oil Co. (OSOCO - Ras Shukheir, Red Sea)",
    sector: "petroleum",
    subSector: "إنتاج الزيت الخام والغاز من الحقول البحرية والبرية بمنطقة خليج السويس ورأس شقير",
    city: "red_sea",
    governorate: "البحر الأحمر",
    address: "منطقة رأس شقير، طريق الغردقة السويس، البحر الأحمر",
    phone1: "0653551200",
    mobile: "01223366992",
    hotline: "16221",
    website: "https://www.osoco.com.eg",
    latitude: 28.1412,
    longitude: 33.2812,
    fleetSize: 75,
    fleetType: "شاحنات خدمات حقول، صهاريج نقل نفط، سيارات طوارئ، وأتوبيسات نقل مهندسين",
    fleetTires: "12.00R24 • 315/80R22.5 • 11.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "شركة بترولية رائدة في منطقة خليج السويس ذات أسطول نقل ميداني متخصص",
    contactPerson: "مدير حركة النقل",
    contactTitle: "Transport Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=28.1412,33.2812"
  },
  {
    id: "eg_titan_622",
    nameAr: "شركة بترول خليج السويس (جابكو - أساطيل رأس شقير والقاهرة)",
    nameEn: "Gulf of Suez Petroleum Co. (GUPCO - Ras Shukheir & Cairo)",
    sector: "petroleum",
    subSector: "أقدم وأكبر منتج للنفط في خليج السويس مع أسطول دعم حقول ومعدات ثقيلة برية وبحرية",
    city: "cairo",
    governorate: "القاهرة",
    address: "شارع فلسطين، المعادي الجديدة، القاهرة / حقول رأس شقير بالبحر الأحمر",
    phone1: "0227061200",
    mobile: "01007788339",
    hotline: "16222",
    website: "https://www.gupco.net",
    latitude: 29.9789,
    longitude: 31.2889,
    fleetSize: 130,
    fleetType: "شاحنات ثقيلة 6x6، أوناش تلسكوبية، صهاريج بترولية، وأسطول حافلات ركاب حديثة لنقل العاملين",
    fleetTires: "14.00R20 • 12.00R24 • 315/80R22.5 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "شريك تاريخي في استخراج نفط خليج السويس بأسطول معدات ونقل عملاق بين القاهرة ومواقع الحقول بالبحر الأحمر",
    contactPerson: "مدير عام النقل والخدمات الميدانية",
    contactTitle: "General Field Fleet & Transport Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.9789,31.2889"
  },
  {
    id: "eg_titan_623",
    nameAr: "شركة شمال البحرية للبترول (نوربيتكو - الصحراء الغربية)",
    nameEn: "North Bahariya Petroleum Co. (NORPETCO - Western Desert)",
    sector: "petroleum",
    subSector: "استكشاف وتنمية حقول البترول في حوض البحرية والواحات البحرية بالصحراء الغربية",
    city: "giza",
    governorate: "الجيزة",
    address: "حقول الواحات البحرية، الصحراء الغربية / المقر الإداري بالمعادي، القاهرة",
    phone1: "0225171400",
    mobile: "01114499118",
    hotline: "16223",
    website: "https://www.norpetco.com",
    latitude: 28.3412,
    longitude: 29.0145,
    fleetSize: 80,
    fleetType: "شاحنات نقل خام من الآبار لمستودعات التجميع، سيارات دفع رباعي، وأتوبيسات فرق الحفر",
    fleetTires: "14.00R20 • 12.00R24 • 315/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "إحدى كبرى شركات إنتاج الزيت بالواحات البحرية بأسطول شاحنات وسيارات صحراوية نشط",
    contactPerson: "مدير حركة النقل الصحراوي",
    contactTitle: "Desert Fleet Supervisor",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=28.3412,29.0145"
  },
  {
    id: "eg_titan_624",
    nameAr: "شركة تاون جاس لتوزيع الغاز الطبيعي للمدن (أسطول 650 سيارة صيانة وطوارئ)",
    nameEn: "Town Gas - Town Gas Mega Distribution Fleet (Cairo, Giza & Alex)",
    sector: "petroleum",
    subSector: "توصيل شبكات الغاز الطبيعي للمنازل والمصانع وتشغيل أضخم أسطول طوارئ وصيانة شبكات غاز بمصر",
    city: "cairo",
    governorate: "القاهرة",
    address: "شارع كورنيش النيل، الوراق / مكاتب مدينة نصر والإسكندرية",
    phone1: "0223801200",
    mobile: "01229977553",
    hotline: "16224",
    website: "https://www.towngas.com.eg",
    latitude: 30.1112,
    longitude: 31.2289,
    fleetSize: 180,
    fleetType: "شاحنات حفر وتمديد خطوط الغاز، سيارات فانات طوارئ مجهزة 24 ساعة، وشاحنات نقل مواسير البولي إيثيلين",
    fleetTires: "225/75R17.5 • 295/80R22.5 • 315/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الشركة الرائدة في توصيل شبكات الغاز الطبيعي بالقاهرة الكبرى والإسكندرية بأكبر أسطول سيارات خدمة وطوارئ سريع",
    contactPerson: "مدير عام أسطول السيارات والحركة المركزية",
    contactTitle: "General Manager of Central Fleet & Emergency Operations",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.1112,31.2289"
  },
  {
    id: "eg_titan_625",
    nameAr: "شركة غاز الشرق لنقل وتوزيع الغاز الطبيعي المضغوط",
    nameEn: "East Gas Co. - Strategic Natural Gas Transmission Pipeline",
    sector: "petroleum",
    subSector: "تشغيل وصيانة خطوط الغاز الطبيعي الإقليمية والدولية ومحطات الضغط الكبرى بسيناء والسويس",
    city: "cairo",
    governorate: "القاهرة",
    address: "شارع التسعين الشمالي، التجمع الخامس، القاهرة الجديدة",
    phone1: "0228114100",
    mobile: "01003366882",
    hotline: "16225",
    website: "https://www.eastgas.com.eg",
    latitude: 30.0289,
    longitude: 31.4412,
    fleetSize: 75,
    fleetType: "شاحنات صيانة خطوط الغاز، سيارات مراقبة أمنية ودوريات خطوط 4x4، وأتوبيسات فرق فنية",
    fleetTires: "245/75R16 • 315/80R22.5 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الشركة الاستراتيجية المسؤولة عن شبكات وخطوط نقل الغاز الإقليمية بسيناء والبحر الأحمر",
    contactPerson: "مدير عام الخدمات اللوجستية والأسطول",
    contactTitle: "Logistics & Transport General Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.0289,31.4412"
  },
  {
    id: "eg_titan_626",
    nameAr: "شركة صيانكو لصيانة الأجهزة والشبكات البترولية (أسطول 400 سيارة متنقلة)",
    nameEn: "SIYANCO - Petroleum Maintenance & Customer Care Mobile Fleet",
    sector: "petroleum",
    subSector: "خدمات الصيانة الدورية للأجهزة المنزلية والصناعية التي تعمل بالغاز الطبيعي وشبكات الوقود",
    city: "cairo",
    governorate: "القاهرة",
    address: "شارع مصطفى النحاس، مدينة نصر، القاهرة / فروع بكافة محافظات مصر",
    phone1: "0222751200",
    mobile: "01115588772",
    hotline: "16226",
    website: "https://www.siyanco.com",
    latitude: 30.0512,
    longitude: 31.3545,
    fleetSize: 150,
    fleetType: "سيارات فانات صيانة مجهزة، شاحنات نقل مهمات، وسيارات خدمة عملاء ميدانية سريعة",
    fleetTires: "195/70R15C • 225/75R17.5 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "شركة خدمات بترولية كبرى تمتلك أسطول سيارات متنقلة لصيانة شبكات وأجهزة الغاز في جميع محافظات مصر",
    contactPerson: "مدير عام الحركة والنقل المركزي",
    contactTitle: "Central Transport & Field Services Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.0512,31.3545"
  },
  {
    id: "eg_titan_627",
    nameAr: "شركة بتروسيلتك لخدمات آبار البترول والنقل الثقيل",
    nameEn: "Petroceltic Egypt - Oilfield Services & Heavy Haulage",
    sector: "petroleum",
    subSector: "خدمات الحفر والإنتاج ونقل المهمات البترولية الثقيلة بين الحقول والموانئ",
    city: "cairo",
    governorate: "القاهرة",
    address: "منطقة المعادي الجديدة، القاهرة / قواعد العمليات بالسويس ورأس شقير",
    phone1: "0225161400",
    mobile: "01228833445",
    hotline: "16227",
    website: "https://www.petroceltic-eg.com",
    latitude: 29.9689,
    longitude: 31.2945,
    fleetSize: 70,
    fleetType: "لوابد نقل حفارات ومواسير حفر، تريلات شحن معدات، وسيارات دعم ميداني صحراوية",
    fleetTires: "12.00R24 • 315/80R22.5 • 385/65R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "شركة خدمات بترولية متخصصة في نقل وتجهيز أبراج الحفر والمهمات الثقيلة للحقول الصحراوية",
    contactPerson: "مدير حركة المعدات واللوجستيات",
    contactTitle: "Equipment Movement & Logistics Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.9689,31.2945"
  },
  {
    id: "eg_titan_628",
    nameAr: "شركة سينوثروة للحفر والمعدات الثقيلة (المعادي وحقول البترول)",
    nameEn: "SinoTharwa Mega Drilling Co. (Cairo & Western Desert)",
    sector: "petroleum",
    subSector: "أعمال حفر وصيانة آبار البترول والغاز عبر أسطول من أحدث الحفارات البرية التكنولوجية",
    city: "cairo",
    governorate: "القاهرة",
    address: "القطاع السابع، المعادي الجديدة، القاهرة / قواعد مطروح والصحراء الشرقية",
    phone1: "0227541200",
    mobile: "01009944118",
    hotline: "16228",
    website: "https://www.sinotharwa.com",
    latitude: 29.9712,
    longitude: 31.2912,
    fleetSize: 95,
    fleetType: "تريلات تريلا ثقيلة نقل أبراج حفر (Rig Movers)، أوناش رافعة، شاحنات دعم آبار، وأتوبيسات ركاب",
    fleetTires: "12.00R24 • 14.00R20 • 315/80R22.5 • 385/65R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "شراكة مصرية صينية عملاقة في حفر آبار النفط والغاز بأسطول معدات ثقيلة فائق القدرة لنقل الحفارات",
    contactPerson: "مدير عام النقل ونقل أبراج الحفر",
    contactTitle: "Rig Moving & Heavy Fleet Operations Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.9712,31.2912"
  },
  {
    id: "eg_titan_629",
    nameAr: "شركة الحفر الوطنية (شاحنات نقل أبراج الحفر والرافعات)",
    nameEn: "National Drilling Co. (NDC - Land Rig Transport & Mobile Cranes)",
    sector: "petroleum",
    subSector: "حفر آبار النفط والغاز الاستكشافية والتنموية بالصحراء الغربية وخليج السويس والدلتا",
    city: "cairo",
    governorate: "القاهرة",
    address: "شارع مكرم عبيد، مدينة نصر، القاهرة / قواعد السويس ومطروح",
    phone1: "0222731500",
    mobile: "01112288339",
    hotline: "16229",
    website: "https://www.ndcegypt.com",
    latitude: 30.0645,
    longitude: 31.3412,
    fleetSize: 85,
    fleetType: "شاحنات صحراوية عملاقة (أكتروس تيتان)، لوابد متعددة المحاور، أوناش هيدروليكية، وأتوبيسات ورديات",
    fleetTires: "14.00R20 • 12.00R24 • 315/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "من أقدم شركات الحفر الوطنية بمصر تمتلك شاحنات نقل ثقيل متخصصة لنقل مكونات الحفارات العملاقة",
    contactPerson: "مدير اللوجستيات والنقل الثقيل",
    contactTitle: "Heavy Logistics & Haulage Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.0645,31.3412"
  },
  {
    id: "eg_titan_630",
    nameAr: "شركة النقل المباشر للمنتجات البترولية (الإسكندرية والسويس)",
    nameEn: "Direct Petroleum Haulage & Tankers Logistics Co.",
    sector: "transport",
    subSector: "النقل المتخصص للوقود السائل، المازوت الصناعي للمصانع، وزيوت التزليق البحرية بالموانئ",
    city: "alexandria",
    governorate: "الإسكندرية",
    address: "الكيلو 21 طريق الإسكندرية مطروح، العجمي، الإسكندرية / فرع السويس",
    phone1: "034381200",
    mobile: "01223399881",
    hotline: "16230",
    website: "https://www.directpetrohaulage.com",
    latitude: 31.0912,
    longitude: 29.7412,
    fleetSize: 90,
    fleetType: "صهاريج نقل وقود مرسيدس ومان، صهاريج نقل مازوت معزولة حرارياً، وسيارات خدمة سريعة",
    fleetTires: "315/80R22.5 • 385/65R22.5 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "شركة نقل بترولي خاصة معتمدة تخدم مصانع الأسمنت والسيراميك والصلب والسفن بموانئ الإسكندرية والسويس",
    contactPerson: "مدير حركة أسطول الصهاريج",
    contactTitle: "Tanker Fleet Operations Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=31.0912,29.7412"
  }
];

module.exports = { wave6Part4 };
