/**
 * Wave 7 Titans - Part 6 (Titans 951 to 1000)
 * Sector Focus: Pharmaceuticals & Biotech, Marine Logistics, Ports & Terminals, Glass & Building Materials
 */

const wave7Part6 = [
  {
    id: "eg_titan_951",
    nameAr: "شركة راميدا للصناعات الدوائية (Rameda Pharmaceuticals - مجمع مصانع السادس من أكتوبر)",
    nameEn: "Rameda Pharmaceuticals Mega Manufacturing Plants (6th of October)",
    sector: "pharma",
    subSector: "مجمعات تصنيع المضادات الحيوية، المحاليل الوريدية، القطرات المعقمة، والمستحضرات الدوائية الصلبة",
    city: "giza",
    governorate: "الجيزة",
    address: "المنطقة الصناعية الثانية، السادس من أكتوبر، الجيزة",
    phone1: "0238203000",
    mobile: "01001144882",
    hotline: "19632",
    website: "https://www.rameda.com",
    latitude: 29.9512,
    longitude: 30.9245,
    fleetSize: 135,
    fleetType: "برادات مجهزة ومراقبة حرارياً لنقل وتوزيع الأدوية، فانات توزيع صيدليات، وتريلات تصدير منتجات دوائية",
    fleetTires: "225/75R17.5 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "إحدى أسرع شركات الأدوية نمواً في البورصة المصرية والمصدرة لأكثر من 25 دولة في إفريقيا والشرق الأوسط",
    contactPerson: "مدير عام النقل والأسطول المبرد الدوائي",
    contactTitle: "Pharma Cold-Chain Transport Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.9512,30.9245"
  },
  {
    id: "eg_titan_952",
    nameAr: "شركة سانوفي مصر للصناعات الدوائية (Sanofi Egypt - مجمع مصانع الزيتون)",
    nameEn: "Sanofi Egypt Mega Sterile Pharmaceutical Plants (El Zaytoun)",
    sector: "pharma",
    subSector: "المجمع الدوائي العالمي لإنتاج الإنسولين، أدوية القلب والأوعية الدموية، مسكنات الألم، واللقاحات الحيوية",
    city: "cairo",
    governorate: "القاهرة",
    address: "شارع المسلة، المطرية / الزيتون، القاهرة",
    phone1: "0222861000",
    mobile: "01003366119",
    hotline: "16763",
    website: "https://www.sanofi.com.eg",
    latitude: 30.1245,
    longitude: 31.3124,
    fleetSize: 155,
    fleetType: "شاحنات تبريد دوائية متطورة (Cold-Chain)، فانات توزيع سريعة للمستشفيات، وتريلات شحن صادرات للموانئ",
    fleetTires: "225/75R17.5 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الفرع المصري لكبرى مجموعات الدواء الفرنسية الرائدة في تأمين أدوية الأمراض المزمنة في مصر",
    contactPerson: "مدير عام اللوجستيات وسلاسل الإمداد الدوائية",
    contactTitle: "Pharma Supply Chain & Fleets Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.1245,31.3124"
  },
  {
    id: "eg_titan_953",
    nameAr: "شركة جلاكسو سميث كلاين مصر (GSK Egypt - مصانع مدينة السلام والجيزة)",
    nameEn: "GlaxoSmithKline Egypt Mega Plants (GSK El Salam & Giza)",
    sector: "pharma",
    subSector: "تصنيع المضادات الحيوية واسعة المجال أوجمنتين، أدوية الجهاز التنفسي، اللقاحات، ومسكنات بنادول",
    city: "cairo",
    governorate: "القاهرة",
    address: "طريق مصر - الإسماعيلية الصحراوي، مدينة السلام، القاهرة",
    phone1: "0226960000",
    mobile: "01005588334",
    hotline: "16260",
    website: "https://www.gsk.com/en-eg",
    latitude: 30.1678,
    longitude: 31.4289,
    fleetSize: 180,
    fleetType: "أسطول برادات توزيع معتمد، فانات نقل أدوية طارئة للمستشفيات والمراكز الطبية، وتريلات تصدير دولي",
    fleetTires: "225/75R17.5 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الكيان الدوائي البريطاني الأكبر في مصر الممتلك لثلاثة مصانع أدوية كبرى وشبكة توزيع تغطي كافة المحافظات",
    contactPerson: "رئيس قطاعات اللوجستيات والأسطول القومي",
    contactTitle: "Country Logistics & Fleets Head",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.1678,31.4289"
  },
  {
    id: "eg_titan_954",
    nameAr: "شركة المهن الطبية للأدوية (MUP - مجمع مصانع أبو سلطان بالإسماعيلية)",
    nameEn: "Medical Union Pharmaceuticals (MUP Abu Sultan Mega Sterile Complex)",
    sector: "pharma",
    subSector: "أكبر صرح لإنتاج البنسلين المعقم، مضادات حيوية السيفالوسبورين، أمبولات الحقن، ومحاليل الكلى",
    city: "ismailia",
    governorate: "الإسماعيلية",
    address: "منطقة أبو سلطان، فايد، الإسماعيلية",
    phone1: "0643400500",
    mobile: "01007711558",
    hotline: "19835",
    website: "https://www.mupegypt.com",
    latitude: 30.4124,
    longitude: 32.2891,
    fleetSize: 165,
    fleetType: "برادات شحن أدوية معقمة، تريلات نقل مواد خام صيدلانية ومستلزمات تغليف، وشاحنات توزيع على الفروع",
    fleetTires: "295/80R22.5 • 225/75R17.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "القلعة الدوائية القومية التابعة لاتحاد نقابات المهن الطبية لتأمين المضادات الحيوية الحساسة ومحاليل الغسيل الكلوي",
    contactPerson: "مدير عام النقل والأسطول المركزي",
    contactTitle: "Central Transport & Cold Fleet Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.4124,32.2891"
  },
  {
    id: "eg_titan_955",
    nameAr: "شركة جلوبال نابي للأدوية (Global Napi Pharmaceuticals - مصانع السادس من أكتوبر)",
    nameEn: "Global Napi Pharmaceuticals Mega Complex (6th of October)",
    sector: "pharma",
    subSector: "مجمعات تصنيع الأدوية الحيوية، أدوية الأورام، الكبسولات الرخوة، والمنتجات الصيدلانية عالية الدقة",
    city: "giza",
    governorate: "الجيزة",
    address: "المنطقة الصناعية الثانية، السادس من أكتوبر، الجيزة",
    phone1: "0238200500",
    mobile: "01009933772",
    hotline: "19631",
    website: "https://www.globalnapi.com",
    latitude: 29.9545,
    longitude: 30.9189,
    fleetSize: 145,
    fleetType: "شاحنات نقل أدوية مزودة بحساسات درجات حرارة ورطوبة، فانات توزيع، وتريلات تصدير للشرق الأوسط وأفريقيا",
    fleetTires: "225/75R17.5 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "رائدة تصنيع الأدوية الحديثة وشركاء الإنتاج المحلي لكبرى الشركات العالمية مثل ميرك وسيرفييه",
    contactPerson: "مدير عام اللوجستيات وسلاسل الإمداد",
    contactTitle: "Supply Chain & Transport Lead",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.9545,30.9189"
  },
  {
    id: "eg_titan_956",
    nameAr: "شركة سيديكو للأدوية (SEDICO Pharmaceuticals - مجمع السادس من أكتوبر)",
    nameEn: "SEDICO Pharmaceuticals Mega Industrial Complex (6th of October)",
    sector: "pharma",
    subSector: "تصنيع أدوية الإنسولين البشري، أمبولات ومجففات التجميد (Lyophilized)، ومضادات الالتهاب غير الستيرويدية",
    city: "giza",
    governorate: "الجيزة",
    address: "المنطقة الصناعية الأولى، السادس من أكتوبر، الجيزة",
    phone1: "0238333500",
    mobile: "01001166994",
    hotline: "19832",
    website: "https://www.sedico.net",
    latitude: 29.9678,
    longitude: 30.9312,
    fleetSize: 150,
    fleetType: "شاحنات تبريد فائقة الدقة لنقل الإنسولين ومنتجات التبريد، فانات توزيع مستشفيات، وتريلات تصدير دولي",
    fleetTires: "225/75R17.5 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "إحدى كبرى قلاع إنتاج الإنسولين وأمبولات المضادات الحيوية في مصر والتابعة للشركة العربية للصناعات الدوائية أكديما",
    contactPerson: "مدير عام النقل والأسطول المبرد",
    contactTitle: "Cold-Chain Fleet & Distribution Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.9678,30.9312"
  },
  {
    id: "eg_titan_957",
    nameAr: "شركة ماركيرل للصناعات الدوائية (Marcyrl Pharmaceutical Industries - مصانع العبور)",
    nameEn: "Marcyrl Pharmaceutical Industries Mega Plants (El Obour City)",
    sector: "pharma",
    subSector: "إنتاج أدوية فيروس سي، أدوية الأورام المتطورة، الكبسولات الهلامية، وقطرات العيون المعقمة",
    city: "qalyubia",
    governorate: "القليوبية",
    address: "المنطقة الصناعية الأولى، بلوك 13023، مدينة العبور، القليوبية",
    phone1: "0244812000",
    mobile: "01003388556",
    hotline: "19721",
    website: "https://www.marcyrl.com",
    latitude: 30.2289,
    longitude: 31.4789,
    fleetSize: 140,
    fleetType: "برادات مجهزة لحفظ الأدوية الحساسة، شاحنات شحن مواد فعالة، وفانات توزيع صيدليات ومراكز علاجية",
    fleetTires: "225/75R17.5 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "البطل الوطني في تصنيع أدوية علاج فيروس سي بمصر والمشارك الأكبر في المبادرة الرئاسية 100 مليون صحة",
    contactPerson: "مدير عام اللوجستيات والأسطول الفني",
    contactTitle: "Technical Fleet & Logistics Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.2289,31.4789"
  },
  {
    id: "eg_titan_958",
    nameAr: "شركة دلتا فارما للصناعات الدوائية (Delta Pharma - مجمع العاشر من رمضان)",
    nameEn: "Delta Pharma Mega Pharmaceutical Industrial Plants (10th of Ramadan)",
    sector: "pharma",
    subSector: "مجمعات تصنيع الأقراص المغلفة، الكبسولات، الشرابات الدوائية، ومستحضرات العناية الطبية الفائقة",
    city: "sharqia",
    governorate: "الشرقية",
    address: "المنطقة الصناعية الثالثة A1، العاشر من رمضان، الشرقية",
    phone1: "015413500",
    mobile: "01005511883",
    hotline: "19830",
    website: "https://www.deltapharma.com.eg",
    latitude: 30.3012,
    longitude: 31.7545,
    fleetSize: 130,
    fleetType: "شاحنات شحن أدوية مبردة، فانات توزيع سريع لشركات التوزيع المتحدة وابن سينا، وتريلات تصدير",
    fleetTires: "225/75R17.5 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "إحدى كبرى القلاع الدوائية في مدينة العاشر من رمضان المصدرة لأكثر من 20 دولة عربية وأفريقية",
    contactPerson: "مدير عام النقل وسلاسل الإمداد",
    contactTitle: "Supply Chain & Transport Lead",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.3012,31.7545"
  },
  {
    id: "eg_titan_959",
    nameAr: "الشركة الأوروبية المصرية للصناعات الدوائية (EEPI - مجمع مصانع فاركو بالعامرية)",
    nameEn: "European Egyptian Pharmaceutical Industries (EEPI Pharco Mega Plants)",
    sector: "pharma",
    subSector: "أكبر مصانع إنتاج المضادات الحيوية للسيفالوسبورين، المحاليل المعقمة، وأدوية القلب والكلى",
    city: "alexandria",
    governorate: "الإسكندرية",
    address: "الكيلو 25، طريق الإسكندرية - القاهرة الصحراوي، العامرية، الإسكندرية",
    phone1: "034700000",
    mobile: "01007733441",
    hotline: "19888",
    website: "https://www.eepi.com.eg",
    latitude: 31.0289,
    longitude: 29.8245,
    fleetSize: 160,
    fleetType: "برادات نقل أدوية ومستحضرات معقمة، شاحنات شحن مواد خام كيميائية صيدلانية، وتريلات تصدير للموانئ",
    fleetTires: "295/80R22.5 • 225/75R17.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "إحدى كبرى قلاع مجموعة فاركو الدوائية الحاصلة على شهادات الجودة الأوروبية لتصدير الدواء المصري",
    contactPerson: "مدير عام الأسطول والنقل الدوائي",
    contactTitle: "Pharmaceutical Fleet & Logistics Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=31.0289,29.8245"
  },
  {
    id: "eg_titan_960",
    nameAr: "شركة مينافارم للأدوية والصناعات الحيوية (Minapharm Pharmaceuticals - مجمع العاشر من رمضان)",
    nameEn: "Minapharm Pharmaceuticals & Biopharmaceuticals Mega Complex",
    sector: "pharma",
    subSector: "رائدة التكنولوجيا الحيوية (Biotechnology)، إنتاج أدوية التجلط، المناعة، وأمراض الكبد والمستحضرات البيولوجية",
    city: "sharqia",
    governorate: "الشرقية",
    address: "المنطقة الصناعية الثالثة A2، العاشر من رمضان، الشرقية",
    phone1: "015412500",
    mobile: "01009955117",
    hotline: "19728",
    website: "https://www.minapharm.com",
    latitude: 30.3067,
    longitude: 31.7589,
    fleetSize: 135,
    fleetType: "شاحنات تبريد فائقة الدقة لمنتجات التقنية الحيوية (2-8 درجات مئوية)، فانات توزيع مستشفيات، وتريلات تصدير",
    fleetTires: "225/75R17.5 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الشركة الرائدة إقليمياً في هندسة البروتينات وصناعة الأدوية البيولوجية المعقدة بالشراكة مع بروبيوترانس الألمانية",
    contactPerson: "مدير سلاسل التوريد والخدمات اللوجستية المبردة",
    contactTitle: "Biotech Cold Supply Chain & Fleets Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.3067,31.7589"
  },
  {
    id: "eg_titan_961",
    nameAr: "الشركة القابضة للمستحضرات الحيوية واللقاحات فاكسيرا (VACSERA - مصانع العجوزة والسادس من أكتوبر)",
    nameEn: "VACSERA (The Holding Company for Biological Products & Vaccines)",
    sector: "pharma",
    subSector: "الصرح القومي لتصنيع اللقاحات والأمصال المضادة للسموم، مشتقات الدم، وتعبئة اللقاحات الفيروسية العالمية",
    city: "giza",
    governorate: "الجيزة",
    address: "51 شارع وزارة الزراعة، الدقي / العجوزة، الجيزة ومجمع 6 أكتوبر الصناعي",
    phone1: "0237611111",
    mobile: "01001177663",
    hotline: "19836",
    website: "https://www.vacsera.com",
    latitude: 30.0456,
    longitude: 31.2124,
    fleetSize: 150,
    fleetType: "أسطول سيارات تبريد وتجميد فائق لتوزيع اللقاحات للمديريات الصحية بالمحافظات، وتريلات صهاريج مياه مقطرة",
    fleetTires: "225/75R17.5 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "أقدم وأعرق منتج للأمصال واللقاحات في إفريقيا والشرق الأوسط والضامن للأمن القومي الحيوي المصري",
    contactPerson: "رئيس قطاعات النقل واللوجستيات المبردة القومية",
    contactTitle: "National Bio-Logistics & Fleets Sector Head",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.0456,31.2124"
  },
  {
    id: "eg_titan_962",
    nameAr: "شركة كيميفارم للصناعات الدوائية (Chemipharm Pharmaceutical Industries - مصانع السادس من أكتوبر)",
    nameEn: "Chemipharm Pharmaceutical Industries Mega Plants (6th of October)",
    sector: "pharma",
    subSector: "تصنيع المستحضرات الدوائية للأطفال، أدوية الجهاز الهضمي والقلب، المحاليل، والمضادات الحيوية الحديثة",
    city: "giza",
    governorate: "الجيزة",
    address: "المنطقة الصناعية الثالثة، السادس من أكتوبر، الجيزة",
    phone1: "0238332000",
    mobile: "01003399228",
    hotline: "19848",
    website: "https://www.chemipharm.com",
    latitude: 29.9612,
    longitude: 30.9245,
    fleetSize: 125,
    fleetType: "برادات نقل أدوية معتمدة، فانات توزيع لشركات الأدوية والمخازن، وتريلات شحن صادرات للموانئ",
    fleetTires: "225/75R17.5 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الصرح الدوائي المتطور الحائز على اعتمادات دولية لتصنيع الأدوية وتصديرها لأسواق إفريقيا والخليج",
    contactPerson: "مدير عام النقل والأسطول",
    contactTitle: "Transport & Fleets General Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.9612,30.9245"
  },
  {
    id: "eg_titan_963",
    nameAr: "شركة أوتوبيا للصناعات الدوائية (Utopia Pharmaceuticals - مجمع العاشر من رمضان)",
    nameEn: "Utopia Pharmaceuticals Mega Industrial Complex (10th of Ramadan)",
    sector: "pharma",
    subSector: "مجمعات تصنيع أدوية العظام والمفاصل، أدوية الأعصاب، الأقراص الفوارة، والمكملات الغذائية الطبية المتطورة",
    city: "sharqia",
    governorate: "الشرقية",
    address: "المنطقة الصناعية الثالثة، العاشر من رمضان، الشرقية",
    phone1: "015414800",
    mobile: "01005522774",
    hotline: "19849",
    website: "https://www.utopiapharm.com",
    latitude: 30.3089,
    longitude: 31.7612,
    fleetSize: 115,
    fleetType: "شاحنات شحن أدوية مبردة، فانات مندوبي التوزيع والصيدليات، وتريلات نقل خامات ومستلزمات إنتاج",
    fleetTires: "225/75R17.5 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "إحدى كبرى الشركات الوطنية المتخصصة في أدوية الجهاز الحركي والعصبي بحصة سوقية متميزة",
    contactPerson: "مدير العمليات وسلاسل الإمداد اللوجستية",
    contactTitle: "Supply Chain & Logistics Operations Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.3089,31.7612"
  },
  {
    id: "eg_titan_964",
    nameAr: "شركة برج للصناعات الدوائية (Borg Pharmaceutical Industries - مجمع برج العرب)",
    nameEn: "Borg Pharmaceutical Industries Mega Plants (Borg El Arab)",
    sector: "pharma",
    subSector: "إنتاج قطرات العيون المعقمة بنظم BFS، المستحضرات الهرمونية، أدوية الجلدية، والمضادات الحيوية الفموية",
    city: "alexandria",
    governorate: "الإسكندرية",
    address: "المنطقة الصناعية الثالثة، برج العرب الجديدة، الإسكندرية",
    phone1: "034591500",
    mobile: "01007744339",
    hotline: "19850",
    website: "https://www.borg-pharma.com",
    latitude: 30.9145,
    longitude: 29.6189,
    fleetSize: 120,
    fleetType: "شاحنات تبريد ونقل محاليل معقمة، فانات توزيع مستشفيات ومراكز عيون، وتريلات تصدير لميناء الإسكندرية",
    fleetTires: "225/75R17.5 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "القلعة الدوائية الأبرز في مدينة برج العرب الجديدة الرائدة في تكنولوجيا تصنيع قطرات العيون المعقمة",
    contactPerson: "مدير عام النقل والأسطول الإقليمي",
    contactTitle: "Regional Fleet & Transport Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.9145,29.6189"
  },
  {
    id: "eg_titan_965",
    nameAr: "شركة ممفيس للأدوية والصناعات الكيماوية (Memphis Pharmaceuticals Public Company)",
    nameEn: "Memphis Pharmaceuticals & Chemical Industries Public Mega Complex",
    sector: "pharma",
    subSector: "أعرق القلاع الوطنية لتصنيع مستحضرات الحقن، الكريمات والمراهم الطبية، المهدئات، ومستخلصات الأعشاب",
    city: "cairo",
    governorate: "القاهرة",
    address: "8 شارع السواح، الأميرية، الزيتون، القاهرة",
    phone1: "0222581200",
    mobile: "01009966552",
    hotline: "19851",
    website: "https://www.memphispharma.com",
    latitude: 30.1089,
    longitude: 31.2945,
    fleetSize: 140,
    fleetType: "شاحنات توزيع أدوية للمستشفيات الجامعية وهيئة التأمين الصحي، فانات صيدليات، وتريلات نقل خامات",
    fleetTires: "295/80R22.5 • 225/75R17.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الصرح الدوائي القومي التاريخي التابع لوزارة قطاع الأعمال العام لتوفير الدواء بأسعار في متناول ملايين المواطنين",
    contactPerson: "رئيس قطاعات النقل والورش الميكانيكية",
    contactTitle: "Mechanical Fleet & Transport Sector Head",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.1089,31.2945"
  },
  {
    id: "eg_titan_966",
    nameAr: "شركة النيل للأدوية والصناعات الكيماوية (Nile Pharmaceuticals Public Company)",
    nameEn: "Nile Pharmaceuticals & Chemical Industries Public Mega Complex",
    sector: "pharma",
    subSector: "تصنيع أدوية القلب والسكر ومضادات التجلط، المطهرات الطبية، أدوية الطوارئ، وتوريد صيدليات المستشفيات",
    city: "cairo",
    governorate: "القاهرة",
    address: "ميدان السواح، الأميرية، القاهرة",
    phone1: "0222572500",
    mobile: "01001188448",
    hotline: "19852",
    website: "https://www.nilepharma.com.eg",
    latitude: 30.1045,
    longitude: 31.2989,
    fleetSize: 135,
    fleetType: "شاحنات شحن محاليل وأدوية، سيارات توريد التأمين الصحي والشرطة والقوات المسلحة، وتريلات كيماويات",
    fleetTires: "295/80R22.5 • 225/75R17.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "عميد الصناعة الدوائية القومية وأكبر مورد للأدوية الأساسية ومحاليل التطهير للمستشفيات العامة بمصر",
    contactPerson: "مدير عام النقل والحركة المركزية",
    contactTitle: "Central Transport & Movement Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.1045,31.2989"
  },
  {
    id: "eg_titan_967",
    nameAr: "شركة الإسكندرية للأدوية والصناعات الكيماوية (Alexandria Pharmaceuticals Public Co.)",
    nameEn: "Alexandria Pharmaceuticals & Chemical Industries Mega Plants",
    sector: "pharma",
    subSector: "تصنيع البخاخات التنفسية الاستنشاقية (Aerosols)، الكبسولات الجيلاتينية، الفوارات، ومسكنات الألم",
    city: "alexandria",
    governorate: "الإسكندرية",
    address: "شارع جميلة بوحيرد، العوايد، الإسكندرية",
    phone1: "033303500",
    mobile: "01003311884",
    hotline: "19853",
    website: "https://www.alexp pharma.com",
    latitude: 31.2245,
    longitude: 29.9891,
    fleetSize: 130,
    fleetType: "شاحنات تبريد نقل أدوية وبخاخات، فانات توزيع لصيدليات الوجه البحري، وتريلات تصدير لميناء الإسكندرية",
    fleetTires: "295/80R22.5 • 225/75R17.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "القلعة التاريخية الأولى بالإسكندرية المتخصصة في تكنولوجيا البخاخات التنفسية لمرضى الحساسية والربو الشعبي",
    contactPerson: "مدير عام اللوجستيات والأسطول",
    contactTitle: "Logistics & Fleets General Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=31.2245,29.9891"
  },
  {
    id: "eg_titan_968",
    nameAr: "شركة القاهرة للأدوية والصناعات الكيماوية (Cairo Pharmaceuticals Public Company)",
    nameEn: "Cairo Pharmaceuticals & Chemical Industries Public Mega Complex",
    sector: "pharma",
    subSector: "مجمعات تصنيع الأدوية الفموية، أدوية الجهاز الهضمي، مستحضرات التخدير الموضعي، والمضادات الحيوية",
    city: "cairo",
    governorate: "القاهرة",
    address: "شارع عبد الحميد الديب، شبرا، القاهرة",
    phone1: "0222024500",
    mobile: "01005533116",
    hotline: "19854",
    website: "https://www.cairopharma.com.eg",
    latitude: 30.0812,
    longitude: 31.2412,
    fleetSize: 120,
    fleetType: "شاحنات نقل أدوية ومستلزمات، فانات توزيع سريعة، وتريلات شحن خامات صيدلانية ومواد تغليف",
    fleetTires: "295/80R22.5 • 225/75R17.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الصرح الوطني التاريخي التابع لقطاع الأعمال لتأمين المستحضرات العلاجية الحيوية للجمهور والمستشفيات",
    contactPerson: "مدير عام النقل والحركة",
    contactTitle: "Transport & Logistics Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.0812,31.2412"
  },
  {
    id: "eg_titan_969",
    nameAr: "شركة أدويا للأدوية (Adwia Pharmaceuticals - مجمع العاشر من رمضان)",
    nameEn: "Adwia Pharmaceuticals Mega Industrial Complex (10th of Ramadan)",
    sector: "pharma",
    subSector: "تصنيع المستحضرات الدوائية البشرية والبيطرية، أدوية المضادات الحيوية، وأدوية الجهاز التنفسي والمسكنات",
    city: "sharqia",
    governorate: "الشرقية",
    address: "المنطقة الصناعية الثالثة B1، العاشر من رمضان، الشرقية",
    phone1: "015411500",
    mobile: "01007755992",
    hotline: "19855",
    website: "https://www.adwia.com",
    latitude: 30.3045,
    longitude: 31.7589,
    fleetSize: 125,
    fleetType: "شاحنات شحن أدوية بشرية وبيطرية مجهزة، فانات توزيع مستودعات وصيدليات، وتريلات تصدير دولي",
    fleetTires: "225/75R17.5 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "رائدة تصنيع الأدوية البشرية والبيطرية في مصر ذات الحضور القوي في مزارع الثروة الحيوانية والداجنة والطب البشري",
    contactPerson: "مدير عام اللوجستيات والأسطول",
    contactTitle: "Fleet & Logistics General Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.3045,31.7589"
  },
  {
    id: "eg_titan_970",
    nameAr: "شركة الأندلس الطبية للأدوية (Al Andalus Medical Company - مصانع السادس من أكتوبر)",
    nameEn: "Al Andalus Medical Company Mega Pharmaceutical Complex",
    sector: "pharma",
    subSector: "مجمعات تصنيع أدوية القلب والأوعية الدموية، أدوية المسالك البولية، المضادات الحيوية، والمكملات العلاجية",
    city: "giza",
    governorate: "الجيزة",
    address: "المنطقة الصناعية الرابعة، السادس من أكتوبر، الجيزة",
    phone1: "0238206500",
    mobile: "01009977224",
    hotline: "19856",
    website: "https://www.alandalus.com.eg",
    latitude: 29.9412,
    longitude: 30.9124,
    fleetSize: 110,
    fleetType: "برادات مجهزة ومراقبة حرارياً لنقل وتوزيع الأدوية، فانات توزيع صيدليات، وتريلات شحن صادرات للموانئ",
    fleetTires: "225/75R17.5 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "إحدى أسرع الشركات الدوائية نمواً في سوق الدواء المصري ومصدر بارز للأدوية للدول العربية والأفريقية",
    contactPerson: "مدير عام سلاسل الإمداد والأسطول",
    contactTitle: "Supply Chain & Fleet Lead",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.9412,30.9124"
  },
  {
    id: "eg_titan_971",
    nameAr: "شركة الملاحة الوطنية (National Navigation Company - NNC أسطول الحبوب والصب الجاف القومي)",
    nameEn: "National Navigation Company (NNC Egypt Bulk Fleet Carrier)",
    sector: "transport",
    subSector: "الناقل البحري الوطني الأول للحبوب والأقماح والبضائع الصب الجاف على متن أسطول سفن وادي النيل والصب العملاق",
    city: "cairo",
    governorate: "القاهرة",
    address: "شارع عبد المنعم رياض، المهندسين، الجيزة / مكاتب ميناء الإسكندرية وبورسعيد",
    phone1: "0233471000",
    mobile: "01001199553",
    hotline: "19857",
    website: "https://www.nnc.com.eg",
    latitude: 30.0545,
    longitude: 31.2089,
    fleetSize: 220,
    fleetType: "أسطول سفن صب جاف عملاقة (Panamax & Kamsarmax)، تريلات نقل ثقيل وشاحنات هوابر حبوب من الموانئ للصوامع",
    fleetTires: "315/80R22.5 • 385/65R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الناقل الاستراتيجي القومي لتأمين الأقماح والسلع التموينية المستوردة إلى مصر عبر أعالي البحار والموانئ",
    contactPerson: "رئيس قطاعات النقل البري والخدمات اللوجستية البحرية",
    contactTitle: "Marine & Land Logistics Sector Head",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.0545,31.2089"
  },
  {
    id: "eg_titan_972",
    nameAr: "شركة الإسكندرية لتداول الحاويات والبضائع (Alexandria Container & Cargo Handling Co. - ACCHC)",
    nameEn: "Alexandria Container and Cargo Handling Co. (ACCHC Terminals)",
    sector: "transport",
    subSector: "إدارة وتشغيل محطتي حاويات الإسكندرية والدخيلة، تفريغ وشحن الحاويات، الساحات اللوجستية، والأوناش العملاقة",
    city: "alexandria",
    governorate: "الإسكندرية",
    address: "رصيف 22 إلى 24، ميناء الإسكندرية البحري، الإسكندرية",
    phone1: "034800200",
    mobile: "01003311997",
    hotline: "19858",
    website: "https://www.acchc.com",
    latitude: 31.1891,
    longitude: 29.8789,
    fleetSize: 240,
    fleetType: "جرارات موانئ (Terminal Tractors)، أوناش ساحات عملاقة (RTG & STS)، وشاحنات تريلات نقل حاويات داخلية",
    fleetTires: "315/80R22.5 • 18.00R25 • 12.00R24",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "المشغل الوطني التاريخي الأول لمحطات الحاويات في مصر المتداول لأكثر من مليون حاوية مكافئة سنوياً",
    contactPerson: "نائب رئيس مجلس الإدارة للتشغيل ومعدات الموانئ",
    contactTitle: "Terminal Operations & Port Fleets Vice President",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=31.1891,29.8789"
  },
  {
    id: "eg_titan_973",
    nameAr: "شركة بورسعيد لتداول الحاويات والبضائع (PSCCHC - محطة غرب بورسعيد للحاويات)",
    nameEn: "Port Said Container & Cargo Handling Co. (West Port Said Terminal)",
    sector: "transport",
    subSector: "محطة غرب بورسعيد لتداول وترانزيت الحاويات، الروافع الشاطئية العملاقة، ومخازن البضائع اللوجستية العامة",
    city: "port_said",
    governorate: "بورسعيد",
    address: "ميناء غرب بورسعيد، شارع مصطفى كامل، بورسعيد",
    phone1: "0663341000",
    mobile: "01005533221",
    hotline: "19859",
    website: "https://www.port-said-containers.com",
    latitude: 31.2589,
    longitude: 32.3012,
    fleetSize: 190,
    fleetType: "شاحنات جرارات موانئ تيرمينال، أوناش ريتش ستاكر (Reach Stackers)، وأساطيل نقل حاويات البضائع",
    fleetTires: "315/80R22.5 • 18.00R25",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "إحدى كبرى شركات تداول الحاويات والترانزيت التابعة للشركة القابضة للنقل البحري والبري على مدخل قناة السويس",
    contactPerson: "مدير عام المعدات والحركة الميدانية",
    contactTitle: "Port Equipment & Fleets General Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=31.2589,32.3012"
  },
  {
    id: "eg_titan_974",
    nameAr: "شركة دمياط لتداول الحاويات والبضائع (Damietta Container & Cargo Handling Co. - DCHC)",
    nameEn: "Damietta Container and Cargo Handling Company (DCHC Terminal)",
    sector: "transport",
    subSector: "محطة حاويات ميناء دمياط العملاقة، خدمات الترانزيت الدولي للبحر المتوسط، والتفريغ السريع لسفن الحاويات العملاقة",
    city: "damietta",
    governorate: "دمياط",
    address: "ميناء دمياط، كفر البطيخ، دمياط",
    phone1: "0572291500",
    mobile: "01007755442",
    hotline: "19860",
    website: "https://www.dchc-damietta.com",
    latitude: 31.4589,
    longitude: 31.7512,
    fleetSize: 210,
    fleetType: "جرارات أرصفة موانئ ثقيلة، أوناش ساحة هيدروليكية، تريلات نقل حاويات ترانزيت، وشاحنات ورش صيانة",
    fleetTires: "315/80R22.5 • 18.00R25 • 385/65R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "رائدة الترانزيت البحري في حوض البحر المتوسط ومركز العمليات اللوجستية التنافسي على الساحل المصري",
    contactPerson: "رئيس قطاعات الأسطول والمعدات الثقيلة",
    contactTitle: "Port Fleets & Heavy Equipment Sector Head",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=31.4589,31.7512"
  },
  {
    id: "eg_titan_975",
    nameAr: "مجموعة كادمار للملاحة والنقل والخدمات اللوجستية (Kadmar Shipping & Logistics Group)",
    nameEn: "Kadmar Shipping & Mega Logistics Fleets Group (Alexandria & Sokhna)",
    sector: "transport",
    subSector: "التوكيلات الملاحية الدولية، شحن الحاويات، النقل المتعدد الوسائط، محطات المستودعات الجافة، والخدمات اللوجستية",
    city: "alexandria",
    governorate: "الإسكندرية",
    address: "شارع الفردوس، سموحة، الإسكندرية / مكاتب السخنة وبورسعيد والقاهرة",
    phone1: "034299000",
    mobile: "01009977665",
    hotline: "19861",
    website: "https://www.kadmar.com",
    latitude: 31.2189,
    longitude: 29.9456,
    fleetSize: 185,
    fleetType: "تريلات نقل حاويات 40 و20 قدم، شاحنات مبردة لنقل البضائع الحساسة، ولوابد نقل معدات ثقيلة للمشروعات",
    fleetTires: "315/80R22.5 • 385/65R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "إحدى كبرى مجموعات الملاحة واللوجستيات الخاصة في مصر والشرق الأوسط الوكيل لخطوط ملاحية عالمية",
    contactPerson: "مدير عام النقل والأسطول البري الميداني",
    contactTitle: "Land Fleets & Transport Operations Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=31.2189,29.9456"
  },
  {
    id: "eg_titan_976",
    nameAr: "مجموعة بان مارين للخدمات البحرية واللوجستية وخدمات البترول (Pan Marine Group)",
    nameEn: "Pan Marine Shipping, Logistics & Offshore Mega Operations",
    sector: "transport",
    subSector: "سفن الإمداد والخدمات البترولية البحرية (Offshore Supply Vessels)، النقل الثقيل المتخصص، والمستودعات الحرة",
    city: "alexandria",
    governorate: "الإسكندرية",
    address: "شارع سيزوستريس، محطة الرمل، الإسكندرية / العين السخنة",
    phone1: "034870000",
    mobile: "01001144337",
    hotline: "19862",
    website: "https://www.pan-marine.net",
    latitude: 31.1989,
    longitude: 29.9012,
    fleetSize: 175,
    fleetType: "تريلات نقل ثقيل للمعدات البترولية، لوابد متعددة المحاور، شاحنات نقل حاويات، وقوارب خدمات بحرية سريعة",
    fleetTires: "385/65R22.5 • 315/80R22.5 • 12.00R24",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "المجموعة المصرية المتكاملة الرائدة في دعم منصات البترول والغاز في البحر المتوسط وخليج السويس واللوجستيات البرية",
    contactPerson: "نائب رئيس مجلس الإدارة للعمليات والأسطول البري",
    contactTitle: "Land Fleets & Operations Vice President",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=31.1989,29.9012"
  },
  {
    id: "eg_titan_977",
    nameAr: "شركة أوفيرسيز للملاحة والخدمات البحرية والتجارة (Overseas Group for Marine & Shipping)",
    nameEn: "Overseas Group for Shipping, Marine Services & Port Logistics",
    sector: "transport",
    subSector: "تفريغ وشحن السفن بالموانئ، إدارة أساطيل النقل الثقيل، خدمات المستودعات التخزينية المفتوحة والمغلقة",
    city: "suez",
    governorate: "السويس",
    address: "شارع بورسعيد، بورتوفيق، السويس",
    phone1: "0623331000",
    mobile: "01003366881",
    hotline: "19863",
    website: "https://www.overseas-shipping.com",
    latitude: 29.9545,
    longitude: 32.5589,
    fleetSize: 160,
    fleetType: "تريلات تريلا فرش نقل بضائع عامة، تريلات نقل حاويات، أوناش شوكية حمولات ثقيلة، وشاحنات تفريغ موانئ",
    fleetTires: "315/80R22.5 • 385/65R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الصرح البحري المتميز في تقديم الحلول المتكاملة للشحن والتفريغ وخدمة سفن العبور في قناة السويس وموانئ البحر الأحمر",
    contactPerson: "مدير عام النقل والأسطول اللوجستي",
    contactTitle: "Logistics Fleets & Transport Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.9545,32.5589"
  },
  {
    id: "eg_titan_978",
    nameAr: "الشركة المصرية لخدمات النقل والتجارة إيجيترانس (Egytrans Heavy Lift & Mega Logistics)",
    nameEn: "Egytrans (Egyptian Transport & Commercial Services - Mega Heavy Lift)",
    sector: "transport",
    subSector: "أكبر مقاول نقل متخصص للأحمال فائقة الضخامة (Heavy Lift & Project Cargo) وتوربينات ومحولات الطاقة العملاقة",
    city: "cairo",
    governorate: "القاهرة",
    address: "شارع قصر النيل، وسط البلد، القاهرة / مكاتب الإسكندرية والسخنة",
    phone1: "0223932000",
    mobile: "01005588772",
    hotline: "19864",
    website: "https://www.egytrans.com",
    latitude: 30.0489,
    longitude: 31.2412,
    fleetSize: 195,
    fleetType: "مقطورات هيدروليكية نمطية (SPMT & Modular Hydraulic Trailers) حتى 1000 طن، رؤوس جرارات فائقة القدرة",
    fleetTires: "385/65R22.5 • 315/80R22.5 • 12.00R24",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "رائدة النقل الثقيل والاستثنائي في مصر منذ عام 1973 والمسؤولة عن نقل المعدات الأضخم في تاريخ المشروعات القومية",
    contactPerson: "مدير عام النقل الثقيل والمشاريع الهندسية",
    contactTitle: "Heavy Lift & Engineering Projects Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.0489,31.2412"
  },
  {
    id: "eg_titan_979",
    nameAr: "شركة ترسانة الإسكندرية البحرية (Alexandria Shipyard Mega Dry Docks & Fleets)",
    nameEn: "Alexandria Shipyard Mega Marine Construction & Heavy Workshops",
    sector: "manufacturing",
    subSector: "بناء وإصلاح السفن الحربية والمدنية وناقلات البترول، الأحواض الجافة العملاقة، وتصنيع الهياكل المعدنية الثقيلة",
    city: "alexandria",
    governorate: "الإسكندرية",
    address: "رأس التين، الميناء الغربي، الإسكندرية",
    phone1: "034453000",
    mobile: "01007711228",
    hotline: "19865",
    website: "https://www.alexshipyard.com.eg",
    latitude: 31.2012,
    longitude: 29.8645,
    fleetSize: 180,
    fleetType: "أوناش ترسانة عملاقة حمولة حتى 300 طن، تريلات لنقل الألواح الفولاذية والقطاعات البحرية، وشاحنات ورش",
    fleetTires: "315/80R22.5 • 12.00R24",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "القلعة الصناعية البحرية الأكبر في إفريقيا والشرق الأوسط التابعة لجهاز الصناعات والخدمات البحرية",
    contactPerson: "رئيس قطاعات النقل الداخلي والمعدات الثقيلة",
    contactTitle: "Heavy Equipment & Plant Logistics Sector Head",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=31.2012,29.8645"
  },
  {
    id: "eg_titan_980",
    nameAr: "شركة القناة لرباط وأنوار السفن (Canal Mooring & Lights Co. - هيئة قناة السويس)",
    nameEn: "Canal Mooring & Lights Company (Suez Canal Authority)",
    sector: "transport",
    subSector: "تأمين ورباط وإضاءة كافة السفن وقوافل العبور بقناة السويس، صيانة الكشافات العملاقة، وأساطيل اللنشات السريعة",
    city: "port_said",
    governorate: "بورسعيد",
    address: "شارع مصطفى كامل، مبنى هيئة قناة السويس، بورسعيد / السويس والإسماعيلية",
    phone1: "0663223000",
    mobile: "01009933446",
    hotline: "19866",
    website: "https://www.canalmooring.com.eg",
    latitude: 31.2612,
    longitude: 32.3089,
    fleetSize: 150,
    fleetType: "لنشات بحرية سريعة لرباط السفن، شاحنات نقل مهمات إضاءة وكابلات بحرية، وسيارات صيانة أجهزة ملاحة",
    fleetTires: "295/80R22.5 • 225/75R16",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الذراع التشغيلي الحيوي لهيئة قناة السويس المسؤول عن سلامة وعبور أضخم سفن العالم في القناة الملاحية على مدار الساعة",
    contactPerson: "مدير عام العمليات والحركة البحرية والبرية",
    contactTitle: "Marine & Land Operations General Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=31.2612,32.3089"
  },
  {
    id: "eg_titan_981",
    nameAr: "شركة التمساح لبناء السفن والخدمات البحرية (Timsah Shipbuilding - هيئة قناة السويس)",
    nameEn: "Timsah Shipbuilding & Offshore Marine Services (SCA)",
    sector: "manufacturing",
    subSector: "بناء قاطرات الشد البحرية العملاقة، لنشات الإرشاد، صيانة المنصات البترولية، وتصنيع الكباري العائمة على القناة",
    city: "ismailia",
    governorate: "الإسماعيلية",
    address: "ميدان التمساح، الإسماعيلية / ورش السويس والإسكندرية",
    phone1: "0643391000",
    mobile: "01001155883",
    hotline: "19867",
    website: "https://www.timsahship.com.eg",
    latitude: 30.5912,
    longitude: 32.2789,
    fleetSize: 140,
    fleetType: "قاطرات بحرية ثقيلة (Bollard Pull)، تريلات نقل صاج وحديد تسليح بحري، وشاحنات ورش ميكانيكية متنقلة",
    fleetTires: "315/80R22.5 • 12.00R24",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الشركة التابعة لهيئة قناة السويس المتخصصة في بناء وتطوير أسطول القاطرات البحرية وسفن الأبحاث وخدمات الغاز والنفط",
    contactPerson: "مدير عام النقل والورش الترسانية",
    contactTitle: "Shipyard Workshops & Transport Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.5912,32.2789"
  },
  {
    id: "eg_titan_982",
    nameAr: "شركة سان جوبان مصر للزجاج المسطح (Saint-Gobain Glass Egypt - مجمع العين السخنة)",
    nameEn: "Saint-Gobain Glass Egypt Mega Float Glass Complex (Ain Sokhna)",
    sector: "building_materials",
    subSector: "أضخم مصنع زجاج مسطح عائم (Float Glass) في الشرق الأوسط وإفريقيا لزجاج المباني والواجهات والسيارات",
    city: "suez",
    governorate: "السويس",
    address: "المنطقة الاقتصادية الخاصة، العين السخنة، السويس",
    phone1: "0623394000",
    mobile: "01003377114",
    hotline: "19868",
    website: "https://www.saint-gobain-glass.com.eg",
    latitude: 29.6389,
    longitude: 32.3312,
    fleetSize: 195,
    fleetType: "تريلات إينلوادر المتخصصة (Glass Inloaders) لنقل ألواح الزجاج الجامبو، تريلات نقل رمال السيليكا، وشاحنات تصدير",
    fleetTires: "385/65R22.5 • 315/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الصرح الفرنسي العالمي بطاقة إنتاج 900 طن زجاج مسطح يومياً المصدر لأكثر من 40 دولة عبر ميناء السخنة",
    contactPerson: "مدير عام أسطول نقل الزجاج وسلاسل الإمداد",
    contactTitle: "Glass Transport Fleets & Supply Chain Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.6389,32.3312"
  },
  {
    id: "eg_titan_983",
    nameAr: "شركة سفنكس للزجاج المسطح (Sphinx Glass Mega Industrial Plants - مدينة السادات)",
    nameEn: "Sphinx Glass Mega Float Glass Manufacturing Complex (Sadat City)",
    sector: "building_materials",
    subSector: "إنتاج الزجاج الشفاف، الملون، العاكس، والزجاج منخفض الانبعاثات الحرارية (Low-E) للواجهات المعمارية الحديثة",
    city: "monufia",
    governorate: "المنوفية",
    address: "المنطقة الصناعية السادسة، مدينة السادات، المنوفية",
    phone1: "0482607000",
    mobile: "01005599338",
    hotline: "19869",
    website: "https://www.sphinxglass.com",
    latitude: 30.3645,
    longitude: 30.5289,
    fleetSize: 170,
    fleetType: "شاحنات تريلات مجهزة بحوامل زجاج رأسية A-Frames، تريلات شحن صادرات للموانئ، وقلابات نقل خامات كوارتز",
    fleetTires: "385/65R22.5 • 315/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "رائدة تكنولوجيا الزجاج المعماري عالي المواصفات التابعة لمجموعة مواد الإعمار القابضة (CPC)",
    contactPerson: "مدير عام النقل والأسطول اللوجستي",
    contactTitle: "Logistics Fleet & Transport General Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.3645,30.5289"
  },
  {
    id: "eg_titan_984",
    nameAr: "شركة سيناء للأسمنت الأبيض (Sinai White Portland Cement - العريش وأبو زنيمة)",
    nameEn: "Sinai White Portland Cement Mega Complex (Aalborg Cement)",
    sector: "building_materials",
    subSector: "أكبر مصنع للأسمنت الأبيض في العالم لإنتاج الأسمنت الأبيض البورتلاندي فائق البياض عالي المقاومة",
    city: "north_sinai",
    governorate: "شمال سيناء",
    address: "منطقة الصناعات الثقيلة، لحفن، جنوب العريش، شمال سيناء",
    phone1: "0683351000",
    mobile: "01007722559",
    hotline: "19870",
    website: "https://www.sinaiwhitecement.com",
    latitude: 31.0891,
    longitude: 33.7891,
    fleetSize: 250,
    fleetType: "تريلات تريلا سيلو لنقل الأسمنت الأبيض السائب، تريلات نقل شكائر معبأة، وقلابات صخور الحجر الجيري النقي",
    fleetTires: "315/80R22.5 • 385/65R22.5 • 12.00R24",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الصرح العالمي التابع لمجموعة ألبورج بورتلاند الإيطالية الدنماركية المصدر للأسمنت الأبيض إلى كافة قارات العالم",
    contactPerson: "رئيس قطاعات الأسطول وتوزيع الأسمنت القومي",
    contactTitle: "White Cement Distribution & Fleets Head",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=31.0891,33.7891"
  },
  {
    id: "eg_titan_985",
    nameAr: "شركة سيناء للجبس وبلاكو سان جوبان (Sinai Gypsum & Placo Saint-Gobain)",
    nameEn: "Sinai Gypsum & Placo Saint-Gobain Mega Plaster Plants (Suez)",
    sector: "building_materials",
    subSector: "استخراج خام الجبس من مناجم رأس ملعب بسيناء، تصنيع جبس البناء والتشطيبات الفاخرة، وألواح الجبس بورد",
    city: "suez",
    governorate: "السويس",
    address: "المنطقة الصناعية بعتاقة، السويس / مناجم رأس ملعب جنوب سيناء",
    phone1: "0623231000",
    mobile: "01009944771",
    hotline: "19871",
    website: "https://www.placo.saint-gobain.eg",
    latitude: 29.9124,
    longitude: 32.4891,
    fleetSize: 185,
    fleetType: "تريلات قلابات صخور جبس خامة، تريلات فرش لنقل ألواح الجبس بورد، وتريلات شحن شكائر جبس مصيص وتشطيبات",
    fleetTires: "315/80R22.5 • 12.00R24 • 385/65R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "أشهر وأنقى خامات الجبس الطبيعي في العالم المعتمدة في كبرى المشروعات المعمارية والتشطيبات الفندقية",
    contactPerson: "مدير عام النقل والأسطول المنجمي والبري",
    contactTitle: "Mining & Land Fleets General Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.9124,32.4891"
  },
  {
    id: "eg_titan_986",
    nameAr: "شركة كناوف مصر لأنظمة الجبس بورد والبناء الجاف (Knauf Egypt Mega Industrial Complex)",
    nameEn: "Knauf Egypt Mega Gypsum Board & Drywall Systems Plants (Attaka)",
    sector: "building_materials",
    subSector: "مجمعات تصنيع ألواح الجبس المقاوم للرطوبة والحرائق، القطاعات المعدنية، المعاجين الجاهزة، وأسقف البناء الحديثة",
    city: "suez",
    governorate: "السويس",
    address: "المنطقة الصناعية بعتاقة، السويس",
    phone1: "0623232500",
    mobile: "01001166338",
    hotline: "19872",
    website: "https://www.knauf.com.eg",
    latitude: 29.9245,
    longitude: 32.4789,
    fleetSize: 165,
    fleetType: "تريلات شحن ألواح جبس بورد مجهزة بحماية حواف، شاحنات توزيع معاجين، وتريلات تصدير منتجات للدول العربية",
    fleetTires: "315/80R22.5 • 385/65R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الفرع المصري للعملاق الألماني كناوف المصنع والمصدر الرائد لأنظمة البناء الجاف والتشطيبات الذكية بمصر",
    contactPerson: "مدير عام سلاسل الإمداد والشحن للمشروعات",
    contactTitle: "Supply Chain & Project Shipping Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.9245,32.4789"
  },
  {
    id: "eg_titan_987",
    nameAr: "الشركة المصرية للجبس (جبس سينايت - مصانع مدينة السادات وعتاقة)",
    nameEn: "Egyptian Gypsum Company (Gips Sinait Mega Plants)",
    sector: "building_materials",
    subSector: "تصنيع الجبس الطبيعي المعماري، جبس المصيص سينايت، جبس التشكيل والديكور، وبودرة الجبس الطبية للجبائر",
    city: "monufia",
    governorate: "المنوفية",
    address: "المنطقة الصناعية الرابعة، مدينة السادات، المنوفية",
    phone1: "0482608000",
    mobile: "01003388662",
    hotline: "19873",
    website: "https://www.egyptiangypsum.com",
    latitude: 30.3712,
    longitude: 30.5012,
    fleetSize: 155,
    fleetType: "تريلات تريلا فرش شكائر جبس، قلابات نقل خامات حجرية من المحاجر، وشاحنات توزيع على كبرى مخازن البناء",
    fleetTires: "315/80R22.5 • 12.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "العلامة التراثية الأولى والأشهر في مصر لجبس المصيص والديكور سينايت بانتشار لا يضاهى لدى مقاولي التشطيبات",
    contactPerson: "مدير عام النقل والتوزيع المركزي",
    contactTitle: "Central Transport & Distribution Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.3712,30.5012"
  },
  {
    id: "eg_titan_988",
    nameAr: "شركة أسمنت مصر بني سويف (Misr Beni Suef Cement Mega Complex)",
    nameEn: "Misr Beni Suef Cement Mega Industrial Complex",
    sector: "building_materials",
    subSector: "إنتاج الأسمنت البورتلاندي العادي والمقاوم للكبريتات، أسمنت التشطيبات، والكلنكر عالي الجودة للتصدير",
    city: "beni_suef",
    governorate: "بني سويف",
    address: "منطقة بياض العرب الصناعية، شرق النيل، بني سويف",
    phone1: "0822241000",
    mobile: "01005511447",
    hotline: "19874",
    website: "https://www.mbscement.com",
    latitude: 29.0456,
    longitude: 31.1412,
    fleetSize: 240,
    fleetType: "تريلات سيلو لنقل الأسمنت السائب لمشروعات الخرسانة الجاهزة، تريلات شكائر، وقلابات صخور المحاجر الثقيلة",
    fleetTires: "315/80R22.5 • 12.00R24 • 385/65R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "إحدى كبرى القلاع الصناعية للأسمنت في صعيد مصر التي تدعم مشروعات البنية التحتية والمدن الجديدة بملايين الأطنان",
    contactPerson: "رئيس قطاعات الأسطول وحركة النقل الميداني",
    contactTitle: "Cement Transport & Field Fleet Sector Head",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.0456,31.1412"
  },
  {
    id: "eg_titan_989",
    nameAr: "شركة ليسيكو مصر للأدوات الصحية والسيراميك (Lecico Egypt - مجمع مصانع خورشيد وبرج العرب)",
    nameEn: "Lecico Egypt Mega Sanitary Ware & Ceramic Complex",
    sector: "building_materials",
    subSector: "أكبر منتج للأطقم الصحية الخزفية الفاخرة، بلاط السيراميك والبورسلين، والتصدير لأكثر من 50 دولة أوروبية",
    city: "alexandria",
    governorate: "الإسكندرية",
    address: "طريق قناة المحمودية، خورشيد، الإسكندرية / برج العرب الجديدة",
    phone1: "035180000",
    mobile: "01007733665",
    hotline: "19876",
    website: "https://www.lecico.com",
    latitude: 31.1789,
    longitude: 30.0124,
    fleetSize: 260,
    fleetType: "تريلات تريلا صندوقية مبطنة لشحن الأطقم الصحية، شاحنات نقل سيراميك، وتريلات شحن حاويات لميناء الإسكندرية",
    fleetTires: "315/80R22.5 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "رائدة صناعة الأدوات الصحية والسيراميك في الشرق الأوسط وإحدى كبرى الشركات المصدرة لأسواق المملكة المتحدة وفرنسا",
    contactPerson: "مدير عام النقل والأسطول التصديري",
    contactTitle: "Export Fleet & Shipping General Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=31.1789,30.0124"
  },
  {
    id: "eg_titan_990",
    nameAr: "مجموعة سيراميكا الجوهرة (Al Jawhara - مصانع إكما للقيشاني والسيراميك بالسادس من أكتوبر)",
    nameEn: "Al Jawhara Ceramics & Porcelain Mega Industrial Plants (ECMA)",
    sector: "building_materials",
    subSector: "تصنيع سيراميك وبورسلين الأرضيات والحوائط الفاخر عالي المقاومة والوزن النوعي، الديكورات المعمارية والليزر",
    city: "giza",
    governorate: "الجيزة",
    address: "المنطقة الصناعية الثالثة، السادس من أكتوبر، الجيزة",
    phone1: "0238331100",
    mobile: "01009955883",
    hotline: "19878",
    website: "https://www.aljawharaceramics.com",
    latitude: 29.9645,
    longitude: 30.9189,
    fleetSize: 220,
    fleetType: "شاحنات نقل سيراميك وبورسلين ثقيل، تريلات شحن صادرات للموانئ البحرية، وشاحنات توزيع معارض الجمهورية",
    fleetTires: "315/80R22.5 • 12.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "العلامة الفاخرة الرائدة في تصميم وتصنيع البورسلين والسيراميك فائق الجودة المعادل لأفخر المواصفات الإيطالية",
    contactPerson: "رئيس قطاعات الأسطول والتوزيع القومي",
    contactTitle: "National Fleet & Distribution Sector Head",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.9645,30.9189"
  },
  {
    id: "eg_titan_991",
    nameAr: "شركة سيراميكا بريما (Ceramica Prima - مجمع مصانع مدينة السادات)",
    nameEn: "Ceramica Prima Mega Porcelain & Ceramic Complex (Sadat City)",
    sector: "building_materials",
    subSector: "مجمعات تصنيع السيراميك، البورسلين كامل الكتلة، وبلاط المشاريع الكبرى والمطارات والمولات التجارية",
    city: "monufia",
    governorate: "المنوفية",
    address: "المنطقة الصناعية السابعة، مدينة السادات، المنوفية",
    phone1: "0482609000",
    mobile: "01001177339",
    hotline: "19879",
    website: "https://www.ceramicaprima.com",
    latitude: 30.3689,
    longitude: 30.5156,
    fleetSize: 210,
    fleetType: "تريلات تريلا ثقيلة لشحن السيراميك، قلابات نقل الطفلة والصلصال والفلسبار، وشاحنات شحن موانئ التصدير",
    fleetTires: "315/80R22.5 • 12.00R24",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "إحدى كبرى القلاع المصنعة للسيراميك والبورسلين بمصر بطاقة تتجاوز 100 ألف متر مربع يومياً وشبكة توزيع واسعة",
    contactPerson: "مدير عام الحركة والأسطول الثقيل",
    contactTitle: "Heavy Fleets & Movement General Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.3689,30.5156"
  },
  {
    id: "eg_titan_992",
    nameAr: "شركة سيراميكا فينيسيا (Venisia Ceramics - مجمع مصانع العاشر من رمضان)",
    nameEn: "Venisia Ceramics Mega Industrial Plants (10th of Ramadan)",
    sector: "building_materials",
    subSector: "تصنيع السيراميك الديكوري، بلاط الحوائط الرقمي Digital، والبورسلين المعالج لامتصاص الصدمات والأحمال",
    city: "sharqia",
    governorate: "الشرقية",
    address: "المنطقة الصناعية B3، العاشر من رمضان، الشرقية",
    phone1: "015415800",
    mobile: "01003399551",
    hotline: "19880",
    website: "https://www.venisiaceramics.com",
    latitude: 30.3124,
    longitude: 31.7589,
    fleetSize: 185,
    fleetType: "شاحنات شحن باليتات سيراميك، تريلات نقل خامات من محاجر أسوان وسينا، وتريلات تصدير منتجات للدول العربية",
    fleetTires: "315/80R22.5 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الاسم اللامع في عالم السيراميك العصري والتشطيبات الفاخرة بأسطول شحن وتوزيع يغطي كافة المعارض بالمحافظات",
    contactPerson: "مدير عام النقل وسلاسل التوريد",
    contactTitle: "Supply Chain & Transport Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.3124,31.7589"
  },
  {
    id: "eg_titan_993",
    nameAr: "مجموعة سيراميكا رويال (Ceramica Royal - مجمعات سيراميكا كليوباترا جروب)",
    nameEn: "Ceramica Royal Mega Plants (Cleopatra Group 10th of Ramadan)",
    sector: "building_materials",
    subSector: "مجمعات إنتاج البورسلين المزجج الفاخر، السيراميك ثلاثي الأبعاد، وأطقم الحمامات الملكية المصدرة للخارج",
    city: "sharqia",
    governorate: "الشرقية",
    address: "المنطقة الصناعية الثالثة، العاشر من رمضان، الشرقية",
    phone1: "015416500",
    mobile: "01005522993",
    hotline: "19881",
    website: "https://www.ceramicaroyal.com",
    latitude: 30.3089,
    longitude: 31.7645,
    fleetSize: 230,
    fleetType: "تريلات تريلا ثقيلة لشحن السيراميك والبورسلين، شاحنات تصدير حاويات للموانئ، وفانات خدمات العملاء",
    fleetTires: "315/80R22.5 • 12.00R24",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "أحد الصروح الفاخرة التابعة لمجموعة كليوباترا الرائدة عالمياً في تصنيع السيراميك وتصديره لأكثر من 100 دولة",
    contactPerson: "رئيس قطاعات الأسطول والشحن الدولي",
    contactTitle: "International Shipping & Fleets Sector Head",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.3089,31.7645"
  },
  {
    id: "eg_titan_994",
    nameAr: "شركة سيراميكا ألفا (Ceramica Alfa - مجمع مصانع مدينة العبور)",
    nameEn: "Ceramica Alfa Mega Industrial Plants (El Obour City)",
    sector: "building_materials",
    subSector: "تصنيع سيراميك الأرضيات والحوائط المقاوم للانزلاق والمستحضرات الخزفية لمشروعات الإسكان والتشييد القومية",
    city: "qalyubia",
    governorate: "القليوبية",
    address: "المنطقة الصناعية الأولى، مدينة العبور، القليوبية",
    phone1: "0244815000",
    mobile: "01007744116",
    hotline: "19882",
    website: "https://www.ceramica-alfa.com",
    latitude: 30.2245,
    longitude: 31.4712,
    fleetSize: 175,
    fleetType: "شاحنات نقل سيراميك، تريلات شحن خامات صلبة، وتريلات توريد مباشر لمواقع مشروعات الإسكان الجديدة",
    fleetTires: "315/80R22.5 • 12.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "المورد المعتمد لأكبر مشروعات التطوير العقاري والإسكان الاجتماعي بمصر لتميز منتجاتها بالمتانة العالية",
    contactPerson: "مدير عام النقل والمبيعات المركزية",
    contactTitle: "Central Transport & Sales Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.2245,31.4712"
  },
  {
    id: "eg_titan_995",
    nameAr: "شركة جلوريا للسيراميك والبورسلين (Gloria Ceramics - مجمع مصانع العاشر من رمضان)",
    nameEn: "Gloria Ceramics & Porcelain Mega Manufacturing Complex",
    sector: "building_materials",
    subSector: "تصنيع البورسلين اللامع والمطفي، السيراميك الخارجي للحدائق والواجهات، وبلاط الأرصفة المقاوم للأحمال",
    city: "sharqia",
    governorate: "الشرقية",
    address: "المنطقة الصناعية A3، العاشر من رمضان، الشرقية",
    phone1: "015417200",
    mobile: "01009966334",
    hotline: "19883",
    website: "https://www.gloriaceramics.com",
    latitude: 30.3156,
    longitude: 31.7512,
    fleetSize: 180,
    fleetType: "تريلات تريلا فرش حمولات ثقيلة، قلابات نقل خامات صخور محجرية، وتريلات تصدير منتجات للموانئ البحرية",
    fleetTires: "315/80R22.5 • 12.00R24",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "إحدى كبرى القلاع المصنعة للبورسلين المعماري عالي الكفاءة والمشارك في تبليط محطات القطار الكهربائي والمونوريل",
    contactPerson: "مدير عام اللوجستيات والحركة",
    contactTitle: "Logistics & Fleet Operations Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.3156,31.7512"
  },
  {
    id: "eg_titan_996",
    nameAr: "شركة أركان ستيل للصلب والحديد الخاص (Arkan Steel Mega Rebar & Profiles Plants)",
    nameEn: "Arkan Steel Mega Rolling Mills & Structural Profiles Complex",
    sector: "manufacturing",
    subSector: "درفلة حديد التسليح عالي المقاومة B500DWR، الزوايا، الكمرات، والقطاعات الهيكلية للإنشاءات الثقيلة والكباري",
    city: "suez",
    governorate: "السويس",
    address: "المنطقة الصناعية بعتاقة، السويس",
    phone1: "0623233500",
    mobile: "01001188557",
    hotline: "19885",
    website: "https://www.arkansteel.com",
    latitude: 29.9312,
    longitude: 32.4712,
    fleetSize: 220,
    fleetType: "تريلات تريلا أطوال لنقل أطوال حديد التسليح والكمرات حتى 18 متراً، تريلات نقل بليت صلب، وأوناش تحميل علوية",
    fleetTires: "315/80R22.5 • 385/65R22.5 • 12.00R24",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "المورد الاستراتيجي لقطاعات الصلب وحديد التسليح لمشروعات الأنفاق والجسور العملاقة والمدن الذكية الجديدة",
    contactPerson: "مدير عام النقل الثقيل والأطوال الخاصة",
    contactTitle: "Heavy Steel Transport & Fleets General Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.9312,32.4712"
  },
  {
    id: "eg_titan_997",
    nameAr: "مجموعة ميتالكو للإنشاءات والكباري المعدنية (Metalco Public Mega Industrial Plants)",
    nameEn: "Metalco (Egyptian Co. for Metallic Construction Public Mega Plants)",
    sector: "construction",
    subSector: "أعرق صرح لتصنيع وتركيب الكباري الفولاذية المعلقة، جمالونات المطارات، خزانات الوقود، والهياكل المعدنية العملاقة",
    city: "qalyubia",
    governorate: "القليوبية",
    address: "شارع ترعة الإسماعيلية، مسطرد، شبرا الخيمة، القليوبية",
    phone1: "0242201000",
    mobile: "01003311779",
    hotline: "19886",
    website: "https://www.metalco.com.eg",
    latitude: 30.1345,
    longitude: 31.3124,
    fleetSize: 190,
    fleetType: "تريلات تريلا تلسكوبية لنقل كمرات الكباري الفولاذية العملاقة، أوناش هيدروليكية عملاقة حمولة 200 طن، وتريلات",
    fleetTires: "385/65R22.5 • 315/80R22.5 • 12.00R24",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الشركة التابعة للشركة القابضة للصناعات المعدنية والمنفذة لأغلب كباري النيل ومحطات الكهرباء التاريخية في مصر",
    contactPerson: "رئيس قطاعات النقل الثقيل والأوناش المركزية",
    contactTitle: "Heavy Cranes & Transport Sector Head",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.1345,31.3124"
  },
  {
    id: "eg_titan_998",
    nameAr: "شركة حديد العشري للدرفلة والصلب (El Ashry Steel Mega Industrial Plants - قليوب والعاشر)",
    nameEn: "El Ashry Steel Mega Rolling Mills & Rebar Complex",
    sector: "manufacturing",
    subSector: "مجمعات صهر ودرفلة حديد التسليح، الصاج المدرفل على الساخن والبارد، المواسير الفولاذية، واللفائف المجلفنة",
    city: "qalyubia",
    governorate: "القليوبية",
    address: "طريق مصر - الإسكندرية الزراعي، قليوب، القليوبية / العاشر من رمضان",
    phone1: "0132149000",
    mobile: "01005533112",
    hotline: "19887",
    website: "https://www.elashrysteel.com",
    latitude: 30.1989,
    longitude: 31.2145,
    fleetSize: 230,
    fleetType: "تريلات نقل أطوال حديد تسليح، تريلات نقل لفائف صاج مجلفن (Coils) بحوامل أمان خاصة، وأوناش شوكية ثقيلة",
    fleetTires: "315/80R22.5 • 385/65R22.5 • 12.00R24",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "إحدى أسرع قلاع الصلب نمواً في مصر المتخصصة في درفلة حديد التسليح وتصنيع قطاعات ومواسير الصاج المجلفن",
    contactPerson: "مدير عام النقل والأسطول المركزي",
    contactTitle: "Central Transport & Steel Fleets Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.1989,31.2145"
  },
  {
    id: "eg_titan_999",
    nameAr: "شركة حديد عنتر لدرفلة وتجارة الصلب (Antar Steel Mega Rolling Mills - الجيزة والسادات)",
    nameEn: "Antar Steel Mega Rolling Mills & Commercial Logistics",
    sector: "manufacturing",
    subSector: "درفلة وإنتاج حديد التسليح عالي المقاومة، لفائف أسلاك الصلب، وشبكات المستودعات المركزية لتوزيع الصلب",
    city: "giza",
    governorate: "الجيزة",
    address: "طريق الواحات، المنطقة الصناعية، السادس من أكتوبر، الجيزة",
    phone1: "0238208000",
    mobile: "01007755335",
    hotline: "19888",
    website: "https://www.antarsteel.com",
    latitude: 29.9345,
    longitude: 30.9089,
    fleetSize: 210,
    fleetType: "تريلات تريلا ثقيلة لنقل حديد التسليح ولفائف الصلب، أوناش رافعة هيدروليكية، وتريلات توريد مباشر للمقاولين",
    fleetTires: "315/80R22.5 • 12.00R24",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "رائدة تجارة ودرفلة الصلب وحديد التسليح في مصر بأسطول نقل مباشر يغطي مئات المشروعات الإنشائية الكبرى",
    contactPerson: "مدير عام الأسطول والشحن الميداني",
    contactTitle: "Field Dispatch & Fleets General Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.9345,30.9089"
  },
  {
    id: "eg_titan_1000",
    nameAr: "شركة حديد الدلتا للصلب بمسطرد (Delta Steel Mill - مجمع مسطرد الوطني التاريخي)",
    nameEn: "Delta Steel Mill Public Mega Rolling & Ingot Complex (Mostorod)",
    sector: "manufacturing",
    subSector: "تطوير وإحياء أقدم صرح للصلب بمسطرد لإنتاج 500 ألف طن بليت صلب وسباكة المسبوكات الزهر والصلب سنوياً",
    city: "qalyubia",
    governorate: "القليوبية",
    address: "طريق ترعة الإسماعيلية، مسطرد، القليوبية",
    phone1: "0242202000",
    mobile: "01009977558",
    hotline: "19890",
    website: "https://www.deltasteelmill.com.eg",
    latitude: 30.1389,
    longitude: 31.3145,
    fleetSize: 250,
    fleetType: "تريلات نقل خردة وبليت صلب، مقطورات ثقيلة لنقل مسبوكات المحركات وأجسام الطلمبات، وتريلات حديد تسليح",
    fleetTires: "315/80R22.5 • 12.00R24 • 385/65R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الصرح الوطني الأم المؤسس لصناعة الصلب والسباكة في مصر منذ عام 1947 والذي يكتمل به عملاق مصر الصناعي رقم 1000",
    contactPerson: "رئيس قطاعات النقل والورش التعدينية والأسطول القومي",
    contactTitle: "National Fleet & Mining Transport Sector Head",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.1389,31.3145"
  }
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { wave7Part6 };
}
