/**
 * scripts/wave6_data_part1.js
 * Part 1 of Wave 6 Titans (eg_titan_501 to eg_titan_600) - 100 Industrial Titans.
 * Sectors: Textiles & Garments, Paper & Packaging, Mining & Quarries, Agri-Business & Mills.
 */

const wave6Part1 = [
  // 1. Textiles, Weaving, Dyeing & Carpets (25)
  {
    id: "eg_titan_501",
    nameAr: "شركة مصر للحرير الصناعي وألياف البوليستر (كفر الدوار - البحيرة)",
    nameEn: "Misr Rayon & Polyester Fibers Co. (Kafr El Dawar)",
    sector: "manufacturing",
    subSector: "إنتاج خيوط وألياف الحرير الصناعي والبوليستر وأقمشة النايلون للصناعات النسيجية",
    city: "beheira",
    governorate: "البحيرة",
    address: "المجمع الصناعي الكيماوي والنسيجي، كفر الدوار، محافظة البحيرة",
    phone1: "0452281200",
    mobile: "01003445561",
    hotline: "19181",
    website: "https://www.misr-rayon.com.eg",
    latitude: 31.1345,
    longitude: 30.1289,
    fleetSize: 85,
    fleetType: "شاحنات نقل ألياف وبكر بوليستر، صهاريج نقل مواد كيماوية، وأتوبيسات نقل ورديات",
    fleetTires: "315/80R22.5 • 295/80R22.5 • 11.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "قلعة إنتاج خيوط البوليستر والحرير الصناعي التابعة للشركة القابضة للغزل والنسيج بأسطول شحن وتوزيع ضخم",
    contactPerson: "رئيس قطاع الحركة والنقل والخدمات الميدانية",
    contactTitle: "Head of Fleet & Transport Operations",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=31.1345,30.1289"
  },
  {
    id: "eg_titan_502",
    nameAr: "شركة مصر للغزل والنسيج وصباغة الأقطان بكفر الدوار (البحيرة)",
    nameEn: "Misr Spinning & Weaving Co. - Kafr El Dawar Complex",
    sector: "manufacturing",
    subSector: "صناعة غزل القطن الرفيع والسميك والأقمشة القطنية المصبوغة والمنسوجات التصديرية",
    city: "beheira",
    governorate: "البحيرة",
    address: "شارع بورسعيد، المجمع الصناعي للغزل، كفر الدوار، محافظة البحيرة",
    phone1: "0452282400",
    mobile: "01221199882",
    hotline: "19282",
    website: "https://www.misrkd.com",
    latitude: 31.1312,
    longitude: 30.1345,
    fleetSize: 110,
    fleetType: "تريلات نقل بالات القطن الخام، سيارات شحن الأقمشة للموانئ، وأسطول أتوبيسات ورديات العمال",
    fleetTires: "315/80R22.5 • 385/65R22.5 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "أحد أقدم وأكبر مجمعات الغزل والنسيج في الدلتا يخضع لبرنامج التطوير القومي الحديث بأسطول حافلات وشاحنات ضخم",
    contactPerson: "مدير عام النقل البري وتوزيع المنتجات",
    contactTitle: "Director of Land Logistics & Product Distribution",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=31.1312,30.1345"
  },
  {
    id: "eg_titan_503",
    nameAr: "شركة النصر للأصواف والمنسوجات الممتازة (ستيا - الإسكندرية)",
    nameEn: "El Nasr Wool & Selected Textiles Co. (STIA - Alexandria)",
    sector: "manufacturing",
    subSector: "صناعة خيوط الصوف والمنسوجات والبطاطين والأقمشة الصوفية الفاخرة للأسواق المحلية والدولية",
    city: "alexandria",
    governorate: "الإسكندرية",
    address: "شارع مسجد القصبجي، السيوف شماعة، الرمل، الإسكندرية",
    phone1: "035012300",
    mobile: "01112288443",
    hotline: "19383",
    website: "https://www.stia-textile.com",
    latitude: 31.2389,
    longitude: 29.9912,
    fleetSize: 70,
    fleetType: "شاحنات مغلقة لنقل البطاطين والأقمشة، تريلات نقل خام الصوف، وأتوبيسات ركاب",
    fleetTires: "295/80R22.5 • 315/80R22.5 • 11.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الصرح الرائد في تصنيع الصوف والأقمشة المخلوطة بالإسكندرية بأسطول نقل بضائع وحافلات عمال نشط",
    contactPerson: "مدير إدارة الحركة واللوجستيات",
    contactTitle: "Fleet & Logistics Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=31.2389,29.9912"
  },
  {
    id: "eg_titan_504",
    nameAr: "شركة النصر للغزل والنسيج والتريكو (شوربجي - الجيزة)",
    nameEn: "El Nasr Clothing & Textiles Co. (El Shourbagy - Giza)",
    sector: "manufacturing",
    subSector: "إنتاج الملابس الداخلية والتريكو والأقمشة المجهزة والمنسوجات القطنية عالية الجودة",
    city: "giza",
    governorate: "الجيزة",
    address: "شارع ترعة السواحل، الوراق - إمبابة، محافظة الجيزة",
    phone1: "0235401500",
    mobile: "01004455882",
    hotline: "19484",
    website: "https://www.elshourbagy.com.eg",
    latitude: 30.0789,
    longitude: 31.2145,
    fleetSize: 65,
    fleetType: "شاحنات نقل بضائع مغلقة، سيارات توزيع فانات، وأتوبيسات نقل العاملين",
    fleetTires: "295/80R22.5 • 225/75R17.5 • 11.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "شركة تاريخية كبرى في تصنيع التريكو والملابس القطنية الجاهزة بأسطول سيارات توزيع وشاحنات شحن معتمد",
    contactPerson: "مدير الشؤون الفنية والنقل والمتابعة",
    contactTitle: "Technical Affairs & Transport Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.0789,31.2145"
  },
  {
    id: "eg_titan_505",
    nameAr: "شركة مصر لصباغة وتجهيز المنسوجات بالمحلة الكبرى (الغربية)",
    nameEn: "Misr Textile Dyeing & Processing Co. - El Mahalla El Kubra",
    sector: "manufacturing",
    subSector: "عمليات الصباغة الصناعية الكبرى والتجهيز والطباعة على الأقمشة لشركات التصدير",
    city: "gharbia",
    governorate: "الغربية",
    address: "المنطقة الصناعية لشركات النسيج، المحلة الكبرى، محافظة الغربية",
    phone1: "0402234500",
    mobile: "01227766331",
    hotline: "19585",
    website: "https://www.mahalla-dyeing.com",
    latitude: 30.9712,
    longitude: 31.1645,
    fleetSize: 60,
    fleetType: "شاحنات نقل أقمشة مجهزة، صهاريج نقل الصبغات والكيماويات، وميكروباصات وأتوبيسات",
    fleetTires: "315/80R22.5 • 295/80R22.5 • 8.25R16",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "مجمع الصباغة والتجهيز المركزي لخدمة صناعة الغزل والمنسوجات بالمحلة الكبرى والدلتا",
    contactPerson: "مدير النقل والمهمات",
    contactTitle: "Transport & Logistics Officer",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.9712,31.1645"
  },
  {
    id: "eg_titan_506",
    nameAr: "مجموعة دايس للملابس الجاهزة والتريكو (برج العرب وقليوب)",
    nameEn: "Dice Sport & Casual Wear Mega Factories (Dice Group)",
    sector: "manufacturing",
    subSector: "صناعة الملابس الرياضية والتريكو والملابس القطنية وتصديرها لكبرى الماركات العالمية",
    city: "alexandria",
    governorate: "الإسكندرية",
    address: "المنطقة الصناعية الثانية، برج العرب الجديدة، الإسكندرية / مجمع قليوب",
    phone1: "034591500",
    mobile: "01007788991",
    hotline: "19686",
    website: "https://www.dicefactory.net",
    latitude: 30.9145,
    longitude: 29.6212,
    fleetSize: 95,
    fleetType: "شاحنات نقل مغلقة، تريلات شحن موانئ، فانات توزيع معارض، وأسطول حافلات ورديات",
    fleetTires: "295/80R22.5 • 315/80R22.5 • 225/75R17.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "أحد أكبر مصنعي ومصدري الملابس والتريكو في مصر بأسطول متكامل لخدمة مجمعات التصنيع وسلسلة الفروع",
    contactPerson: "مدير عام النقل وسلاسل الإمداد",
    contactTitle: "General Manager of Fleet & Supply Chain",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.9145,29.6212"
  },
  {
    id: "eg_titan_507",
    nameAr: "مجموعة جيزة للغزل والنسيج والملابس (كفر الدوار و6 أكتوبر)",
    nameEn: "Giza Spinning, Weaving & Apparel Mega Group",
    sector: "manufacturing",
    subSector: "إنتاج خيوط القطن الرفيعة والملابس الجاهزة وتجهيز الأقمشة التصديرية للأسواق الأمريكية والأوروبية",
    city: "giza",
    governorate: "الجيزة",
    address: "المنطقة الصناعية الرابعة، مدينة السادس من أكتوبر، الجيزة",
    phone1: "0238332100",
    mobile: "01114433221",
    hotline: "19787",
    website: "https://www.gizaspin.com",
    latitude: 29.9312,
    longitude: 30.9189,
    fleetSize: 90,
    fleetType: "شاحنات نقل كونتينرات موانئ، شاحنات توزيع أقمشة، وحافلات مرسيدس لنقل العمال",
    fleetTires: "315/80R22.5 • 385/65R22.5 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "مجموعة رائدة في تصدير المنسوجات والملابس الجاهزة بأسطول شحن ثقيل مباشر لموانئ الإسكندرية والسخنة",
    contactPerson: "مدير حركة الأسطول والنقل الخارجي",
    contactTitle: "Fleet Movement & Outbound Logistics Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.9312,30.9189"
  },
  {
    id: "eg_titan_508",
    nameAr: "مجموعة بولاريس الدولية للملابس الجاهزة (المنطقة الحرة بمدينة نصر)",
    nameEn: "Polaris Garments International (Nasr City Public Free Zone)",
    sector: "manufacturing",
    subSector: "تصنيع وتصدير البنطلونات والملابس الجاهزة وفق أحدث خطوط الإنتاج الآلية",
    city: "cairo",
    governorate: "القاهرة",
    address: "المنطقة الحرة العامة، مدينة نصر، محافظة القاهرة",
    phone1: "0222718100",
    mobile: "01009988112",
    hotline: "19888",
    website: "https://www.polaris-garments.com",
    latitude: 30.0512,
    longitude: 31.3489,
    fleetSize: 55,
    fleetType: "تريلات نقل بضائع معتمدة جمركياً، وسيارات نقل مغلقة، وحافلات ركاب",
    fleetTires: "315/80R22.5 • 295/80R22.5 • 225/75R17.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "صرح تصنيعي تصديري عملاق بالمنطقة الحرة العامة بمدينة نصر بأسطول شحن للمطارات والموانئ",
    contactPerson: "مدير اللوجستيات والشحن الجمركي",
    contactTitle: "Customs Clearance & Logistics Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.0512,31.3489"
  },
  {
    id: "eg_titan_509",
    nameAr: "شركة أليكس لتصنيع وتصدير الملابس الجاهزة (العامرية - الإسكندرية)",
    nameEn: "Alex Apparels for Garments Manufacturing (Amreya - Alexandria)",
    sector: "manufacturing",
    subSector: "إنتاج وتصدير الملابس الجاهزة والقمصان والجينز لكبرى سلاسل التجزئة في العالم",
    city: "alexandria",
    governorate: "الإسكندرية",
    address: "المنطقة الحرة العامة بالعامرية، طريق القاهرة الإسكندرية الصحراوي، الإسكندرية",
    phone1: "034500120",
    mobile: "01223344558",
    hotline: "19989",
    website: "https://www.alexapparels.com",
    latitude: 31.0212,
    longitude: 29.7889,
    fleetSize: 85,
    fleetType: "شاحنات حاويات لنقل الصادرات لميناء الدخيلة والإسكندرية، وأسطول حافلات عمال",
    fleetTires: "315/80R22.5 • 295/80R22.5 • 12R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "من أضخم مصانع تصدير الملابس في المنطقة الحرة بالعامرية بأسطول حافلات ورديات وشاحنات بضائع عملاق",
    contactPerson: "رئيس قطاع الحركة والنقل الميداني",
    contactTitle: "Head of Transportation & Field Operations",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=31.0212,29.7889"
  },
  {
    id: "eg_titan_510",
    nameAr: "شركة إمبريال لصناعة الغزل والنسيج والتريكو (العاشر من رمضان)",
    nameEn: "Imperial Spinning & Textile Mills (10th of Ramadan)",
    sector: "manufacturing",
    subSector: "إنتاج الخيوط القطنية الممشطة والمغزولة وتجهيز الأقمشة الدائرية لمصانع الملابس",
    city: "sharqia",
    governorate: "الشرقية",
    address: "المنطقة الصناعية B4، مدينة العاشر من رمضان، محافظة الشرقية",
    phone1: "015411200",
    mobile: "01002233114",
    hotline: "16110",
    website: "https://www.imperialtextile.com.eg",
    latitude: 30.2912,
    longitude: 31.7589,
    fleetSize: 55,
    fleetType: "شاحنات شحن الغزول والأقمشة، تريلات لنقل القطن، وأتوبيسات ركاب",
    fleetTires: "315/80R22.5 • 295/80R22.5 • 8.25R16",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "مصنع رائد في توريد الغزول القطنية الممتازة لمصانع العاشر من رمضان والعبور بأسطول شحن وتوزيع نشط",
    contactPerson: "مدير المشتريات والحركة والصيانة",
    contactTitle: "Fleet Maintenance & Procurement Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.2912,31.7589"
  },
  {
    id: "eg_titan_511",
    nameAr: "الشركة المصرية لصناعة السجاد والمنسوجات (ماك MAC - العاشر من رمضان)",
    nameEn: "Manufacture & Commercialization of Carpets (MAC - Oriental Weavers)",
    sector: "manufacturing",
    subSector: "صناعة أغطية الأرضيات والموكيت والسجاد المطبوع والمنسوجات غير المغزولة",
    city: "sharqia",
    governorate: "الشرقية",
    address: "المنطقة الصناعية A1، مدينة العاشر من رمضان، الشرقية",
    phone1: "015412400",
    mobile: "01229988771",
    hotline: "16111",
    website: "https://www.mac-carpets.com",
    latitude: 30.3012,
    longitude: 31.7445,
    fleetSize: 120,
    fleetType: "تريلات شحن رولات الموكيت والسجاد، سيارات توزيع للفروع والمعارض، وأسطول حافلات ركاب",
    fleetTires: "315/80R22.5 • 385/65R22.5 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "إحدى قلاع مجموعة النساجون الشرقيون المتخصصة في الموكيت والسجاد المطبوع بأسطول نقل وشحن فائق الضخامة",
    contactPerson: "مدير عام النقل والأسطول المركزي",
    contactTitle: "General Manager of Central Fleet Operations",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.3012,31.7445"
  },
  {
    id: "eg_titan_512",
    nameAr: "مصانع الدلتا للغزل والنسيج والصباغة (طنطا وزفتى - الغربية)",
    nameEn: "Delta Spinning & Weaving Co. (Tanta & Zifta Plants)",
    sector: "manufacturing",
    subSector: "غزل وحلج الأقطان وصناعة الأقمشة وتجهيز المنسوجات لشركات القطاع العام والخاص",
    city: "gharbia",
    governorate: "الغربية",
    address: "شارع مصطفى كامل، طنطا، محافظة الغربية / مجمع زفتى",
    phone1: "0403332100",
    mobile: "01118899223",
    hotline: "16112",
    website: "https://www.deltaspinning.com.eg",
    latitude: 30.7912,
    longitude: 31.0045,
    fleetSize: 75,
    fleetType: "شاحنات نقل أقطان وغزول، تريلات شحن، وأتوبيسات وميكروباصات نقل عمال",
    fleetTires: "315/80R22.5 • 295/80R22.5 • 11.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "صرح تاريخي في محافظة الغربية يخدم قطاع الغزل والحلج بمحافظات الدلتا",
    contactPerson: "مدير حركة النقل والصيانة الدورية",
    contactTitle: "Transport & Fleet Maintenance Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.7912,31.0045"
  },
  {
    id: "eg_titan_513",
    nameAr: "مجموعة لوتس لصناعة وتصدير ملابس الجينز (المنطقة الحرة ببورسعيد)",
    nameEn: "Lotus Garments Co. - Denim & Jeans Manufacturing (Port Said)",
    sector: "manufacturing",
    subSector: "صناعة وتصدير بناطيل وملابس الجينز عالية الجودة للأسواق الأوروبية والأمريكية",
    city: "port_said",
    governorate: "بورسعيد",
    address: "المنطقة الصناعية C3، المنطقة الحرة العامة، بورسعيد",
    phone1: "0663732000",
    mobile: "01001144773",
    hotline: "16113",
    website: "https://www.lotusgarments.com",
    latitude: 31.2512,
    longitude: 32.2889,
    fleetSize: 85,
    fleetType: "تريلات شحن كونتينرات لميناء شرق وغرب بورسعيد، وحافلات كوستر وأتوبيسات عمال",
    fleetTires: "315/80R22.5 • 295/80R22.5 • 7.50R16",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "أكبر مصنع لتصدير ملابس الجينز في محافظة بورسعيد بأسطول نقل بحري وجوي وحافلات لخدمة آلاف العمال",
    contactPerson: "رئيس الشؤون الإدارية والأسطول",
    contactTitle: "Head of Administration & Fleet Transport",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=31.2512,32.2889"
  },
  {
    id: "eg_titan_514",
    nameAr: "شركة النصر للملابس والمنسوجات (كابو - النزهة بالإسكندرية)",
    nameEn: "El Nasr Clothing & Textiles Co. (KABO - Alexandria)",
    sector: "manufacturing",
    subSector: "صناعة الملابس الداخلية الجاهزة والملابس القطنية والتريكو وتوزيعها محلياً ودولياً",
    city: "alexandria",
    governorate: "الإسكندرية",
    address: "شارع قنال المحمودية، النزهة، الإسكندرية",
    phone1: "034251200",
    mobile: "01225544119",
    hotline: "16114",
    website: "https://www.kabo.com.eg",
    latitude: 31.2012,
    longitude: 29.9545,
    fleetSize: 65,
    fleetType: "شاحنات شحن وتوزيع بضائع، فانات نقل داخلي، وأتوبيسات ركاب",
    fleetTires: "295/80R22.5 • 225/75R17.5 • 8.25R16",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "العلامة التجارية المصرية الرائدة (كابو) في الملابس القطنية بأسطول شحن وتوزيع نشط في جميع المحافظات",
    contactPerson: "مدير عام الخدمات اللوجستية والحركة",
    contactTitle: "Logistics & Fleet Transport Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=31.2012,29.9545"
  },
  {
    id: "eg_titan_515",
    nameAr: "شركة دمياط للغزل والنسيج والصباغة (دمياط)",
    nameEn: "Damietta Spinning & Weaving Co.",
    sector: "manufacturing",
    subSector: "غزل القطن وصناعة أقمشة الجينز والمفروشات والصباغة والتجهيز لمصانع الأثاث والملابس",
    city: "damietta",
    governorate: "دمياط",
    address: "طريق المحور، المنطقة الصناعية، دمياط",
    phone1: "0572361200",
    mobile: "01113355662",
    hotline: "16115",
    website: "https://www.damiaspin.com.eg",
    latitude: 31.4112,
    longitude: 31.8145,
    fleetSize: 55,
    fleetType: "شاحنات شحن أقمشة، تريلات نقل خام، وحافلات ركاب",
    fleetTires: "315/80R22.5 • 295/80R22.5 • 11.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الصرح النسيجي الرئيسي بدمياط لتوريد أقمشة المفروشات والملابس",
    contactPerson: "مدير حركة النقل",
    contactTitle: "Transport Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=31.4112,31.8145"
  },
  {
    id: "eg_titan_516",
    nameAr: "شركة الوجه القبلي للغزل والنسيج (قنا وأسيوط والمنيا)",
    nameEn: "Upper Egypt Spinning & Weaving Co.",
    sector: "manufacturing",
    subSector: "غزل الأقطان المصرية بالصعيد وتجهيز الخيوط لمصانع النسيج في الوجهين البحري والقبلي",
    city: "qena",
    governorate: "قنا",
    address: "المجمع الصناعي للغزل، قنا / مصانع أسيوط والمنيا",
    phone1: "0965213400",
    mobile: "01005566881",
    hotline: "16116",
    website: "https://www.upperegypttextile.com",
    latitude: 26.1589,
    longitude: 32.7212,
    fleetSize: 60,
    fleetType: "تريلات نقل بالات القطن وغزول، شاحنات نقل ثقيل، وحافلات عمال",
    fleetTires: "315/80R22.5 • 12.00R20 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "القاعدة الصناعية للغزل والنسيج في صعيد مصر بأسطول شحن ونقل ممتد بطول محافظات الصعيد والقاهرة",
    contactPerson: "رئيس قطاع الحركة والنقل بالصعيد",
    contactTitle: "Head of Upper Egypt Transport",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=26.1589,32.7212"
  },
  {
    id: "eg_titan_517",
    nameAr: "شركة المحمودية العامة للغزل والنسيج (البحيرة)",
    nameEn: "Mahmoudia Spinning & Textile Co. (Beheira)",
    sector: "manufacturing",
    subSector: "إنتاج الغزول القطنية السميكة والممزوجة وتوريدها لمصانع التريكو والمفروشات",
    city: "beheira",
    governorate: "البحيرة",
    address: "شارع المصانع، المحمودية، محافظة البحيرة",
    phone1: "0452611200",
    mobile: "01224455883",
    hotline: "16117",
    website: "https://www.mahmoudiaspin.com",
    latitude: 31.1812,
    longitude: 30.5212,
    fleetSize: 45,
    fleetType: "شاحنات نقل غزول، تريلات نقل خام، وأتوبيسات ركاب",
    fleetTires: "315/80R22.5 • 295/80R22.5 • 11.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "مصنع قطاع أعمال عام عريق في الغزل بالبحيرة",
    contactPerson: "مدير حركة النقل",
    contactTitle: "Fleet Movement Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=31.1812,30.5212"
  },
  {
    id: "eg_titan_518",
    nameAr: "شركة كوم حمادة للغزل والتجهيز (البحيرة)",
    nameEn: "Kom Hamada Spinning & Finishing Mills",
    sector: "manufacturing",
    subSector: "حلج الأقطان وصناعة الخيوط القطنية السميكة وتجهيز أقمشة التنجيد والمفروشات",
    city: "beheira",
    governorate: "البحيرة",
    address: "المنطقة الصناعية، كوم حمادة، محافظة البحيرة",
    phone1: "0453681400",
    mobile: "01117766334",
    hotline: "16118",
    website: "https://www.komhamadaspin.com",
    latitude: 30.7512,
    longitude: 30.6989,
    fleetSize: 40,
    fleetType: "شاحنات نقل غزول، تريلات قطن، وأتوبيسات نقل ورديات",
    fleetTires: "315/80R22.5 • 295/80R22.5 • 9.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "مصنع غزل تاريخي بمركز كوم حمادة بالبحيرة",
    contactPerson: "مدير الشؤون الإدارية والنقل",
    contactTitle: "Admin & Transport Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.7512,30.6989"
  },
  {
    id: "eg_titan_519",
    nameAr: "مصانع أورينت للكتان والمنسوجات والزيوت (طنطا - الغربية)",
    nameEn: "Orient Flax, Textiles & Linseed Oil Mega Plants (Tanta)",
    sector: "manufacturing",
    subSector: "زراعة ومعالجة خيوط الكتان وإنتاج الأقمشة الكتانية وألياف الكتان وزيت بذر الكتان الحار",
    city: "gharbia",
    governorate: "الغربية",
    address: "طريق طنطا - زفتى الزراعي، طنطا، محافظة الغربية",
    phone1: "0403412500",
    mobile: "01008855221",
    hotline: "16119",
    website: "https://www.orientflax.com",
    latitude: 30.8112,
    longitude: 31.0212,
    fleetSize: 55,
    fleetType: "تريلات نقل أعواد الكتان، صهاريج زيت بذر الكتان، شاحنات تصدير، وأتوبيسات عمال",
    fleetTires: "315/80R22.5 • 295/80R22.5 • 11.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "أكبر معالج ومصدر لألياف ومنسوجات الكتان في منطقة الدلتا بأسطول شحن متخصص لموانئ التصدير",
    contactPerson: "مدير عام النقل والتشغيل الزراعي والصناعي",
    contactTitle: "Agro-Industrial Transport Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.8112,31.0212"
  },
  {
    id: "eg_titan_520",
    nameAr: "شركة ميريت للملابس الجاهزة وتصدير التريكو (مدينة العبور)",
    nameEn: "Merit Garments & Apparel Manufacturing (Obour City)",
    sector: "manufacturing",
    subSector: "صناعة الملابس الخارجية والتريكو والملابس الصوفية للأسواق العالمية",
    city: "qalyubia",
    governorate: "القليوبية",
    address: "المنطقة الصناعية ب & ج، مدينة العبور، محافظة القليوبية",
    phone1: "0244812300",
    mobile: "01229911442",
    hotline: "16120",
    website: "https://www.meritgarments.com",
    latitude: 30.2212,
    longitude: 31.4789,
    fleetSize: 50,
    fleetType: "شاحنات شحن موانئ، فانات توزيع، وأتوبيسات ركاب نقل ورديات",
    fleetTires: "295/80R22.5 • 225/75R17.5 • 8.25R16",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "مصنع رائد بالعبور في تصنيع الملابس وتجهيز الشحنات التصديرية",
    contactPerson: "مدير اللوجستيات والحركة",
    contactTitle: "Logistics & Fleet Officer",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.2212,31.4789"
  },
  {
    id: "eg_titan_521",
    nameAr: "شركة هانز إيجيبت للملابس والتريكو (مدينة بدر الصناعية)",
    nameEn: "Hanes Egypt Apparel Manufacturing (Badr City)",
    sector: "manufacturing",
    subSector: "صناعة الملابس الداخلية والقطنية وفق معايير الجودة العالمية ومواصفات التصدير",
    city: "cairo",
    governorate: "القاهرة",
    address: "المنطقة الصناعية الرابعة، مدينة بدر، محافظة القاهرة",
    phone1: "0228607100",
    mobile: "01004411993",
    hotline: "16121",
    website: "https://www.hanesegypt.com",
    latitude: 30.1412,
    longitude: 31.7212,
    fleetSize: 55,
    fleetType: "شاحنات شحن حاويات، فانات نقل بضائع، وحافلات نقل عمال",
    fleetTires: "315/80R22.5 • 295/80R22.5 • 225/75R17.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "مصنع ملابس ضخم بمدينة بدر بأسطول شحن مباشر لميناء السخنة ومطار القاهرة",
    contactPerson: "مدير حركة النقل",
    contactTitle: "Transport Operations Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.1412,31.7212"
  },
  {
    id: "eg_titan_522",
    nameAr: "شركة صحارى لصناعة المنسوجات والسجاد (العاشر من رمضان)",
    nameEn: "Sahara Carpets & Textile Mills (10th of Ramadan)",
    sector: "manufacturing",
    subSector: "صناعة السجاد الآلي وخيوط البولي بروبيلين والمفروشات الأرضية الفاخرة",
    city: "sharqia",
    governorate: "الشرقية",
    address: "المنطقة الصناعية A3، العاشر من رمضان، محافظة الشرقية",
    phone1: "015413500",
    mobile: "01112299884",
    hotline: "16122",
    website: "https://www.saharacarpets.com",
    latitude: 30.3112,
    longitude: 31.7312,
    fleetSize: 60,
    fleetType: "تريلات شحن سجاد، شاحنات جامبو توزيع، وحافلات ركاب",
    fleetTires: "315/80R22.5 • 295/80R22.5 • 8.25R16",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "مصنع سجاد آلي كبير بالعاشر من رمضان بأسطول توزيع يغطي معارض الدلتا والقاهرة والصعيد",
    contactPerson: "مدير الحركة والنقل الداخلي",
    contactTitle: "Domestic Fleet Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.3112,31.7312"
  },
  {
    id: "eg_titan_523",
    nameAr: "مجموعة فيستيا للملابس الجاهزة والبدل (سموحة - الإسكندرية)",
    nameEn: "Vestia Ready Made Garments & Menswear Group (Alexandria)",
    sector: "manufacturing",
    subSector: "تصنيع البدل والملابس الرجالية والزي الموحد للمؤسسات والشركات الكبرى",
    city: "alexandria",
    governorate: "الإسكندرية",
    address: "طريق النصر، سموحة، الإسكندرية",
    phone1: "034271500",
    mobile: "01223366889",
    hotline: "16123",
    website: "https://www.vestia.com.eg",
    latitude: 31.2145,
    longitude: 29.9489,
    fleetSize: 45,
    fleetType: "فانات وشاحنات توزيع مجهزة، وأتوبيسات ركاب",
    fleetTires: "225/75R17.5 • 295/80R22.5 • 7.50R16",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "العلامة المصرية العريقة في صناعة البدل والملابس الرسمية بأسطول توزيع نشط",
    contactPerson: "مسؤول اللوجستيات والمبيعات المؤسسية",
    contactTitle: "Logistics & Corporate Fleet Officer",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=31.2145,29.9489"
  },
  {
    id: "eg_titan_524",
    nameAr: "شركة صباغي البيضا بكفر الدوار (البحيرة)",
    nameEn: "El Beida Dyers Co. (Kafr El Dawar - Beheira)",
    sector: "manufacturing",
    subSector: "أكبر مصانع صباغة وتبييض وتجهيز وطباعة الأقمشة القطنية والمخلوطة في مصر",
    city: "beheira",
    governorate: "البحيرة",
    address: "مدينة البيضا الصناعية، كفر الدوار، محافظة البحيرة",
    phone1: "0452285100",
    mobile: "01007766332",
    hotline: "16124",
    website: "https://www.elbeidadyers.com",
    latitude: 31.1212,
    longitude: 30.1189,
    fleetSize: 65,
    fleetType: "شاحنات شحن أقمشة مصبوغة، صهاريج كيماويات، وأتوبيسات نقل ورديات",
    fleetTires: "315/80R22.5 • 295/80R22.5 • 11.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "مدينة صناعية تاريخية مخصصة للصباغة والتجهيز بالبحيرة بأسطول نقل بضائع وحافلات ضخم",
    contactPerson: "مدير الشؤون العامة والنقل",
    contactTitle: "General Affairs & Fleet Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=31.1212,30.1189"
  },
  {
    id: "eg_titan_525",
    nameAr: "مصانع الشوربجي للأقمشة غير المنسوجة والمفروشات (مدينة 6 أكتوبر)",
    nameEn: "Shourbagy Non-Woven Fabrics & Bedding Industries (6th of October)",
    sector: "manufacturing",
    subSector: "إنتاج الأقمشة غير المنسوجة للأغراض الطبية والصناعية والزراعية والبطائن",
    city: "giza",
    governorate: "الجيزة",
    address: "المنطقة الصناعية الثالثة، مدينة 6 أكتوبر، محافظة الجيزة",
    phone1: "0238205400",
    mobile: "01114422998",
    hotline: "16125",
    website: "https://www.shourbagynonwoven.com",
    latitude: 29.9212,
    longitude: 30.9312,
    fleetSize: 50,
    fleetType: "تريلات رولات الأقمشة، شاحنات صندوقية، وحافلات ركاب",
    fleetTires: "315/80R22.5 • 295/80R22.5 • 8.25R16",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "مصنع متطور في تصنيع الأقمشة غير المنسوجة وتوريدها لمصانع المستلزمات الطبية والسيارات",
    contactPerson: "مدير الحركة والنقل",
    contactTitle: "Fleet Movement Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.9212,30.9312"
  }
];

module.exports = { wave6Part1 };
