/**
 * scripts/wave7_data_part3.js
 * Part 3 of Wave 7 Titans (eg_titan_801 to eg_titan_850) - 50 Industrial Titans.
 * Sectors: Heavy Chemicals, Petrochemicals, Fertilizers, Paints, Industrial Gases & Advanced Manufacturing.
 */

const wave7Part3 = [
  {
    id: "eg_titan_801",
    nameAr: "شركة جوتن للدهانات والبويات الصناعية والبحرية (Jotun Paints Egypt)",
    nameEn: "Jotun Paints Egypt Industrial & Marine Coatings",
    sector: "manufacturing",
    subSector: "تصنيع الدهانات الصناعية الثقيلة والدهانات البحرية للسفن والمنشآت البترولية",
    city: "sharqia",
    governorate: "الشرقية",
    address: "المنطقة الصناعية الثالثة A3، العاشر من رمضان، الشرقية",
    phone1: "015413100",
    mobile: "01002288117",
    hotline: "19141",
    website: "https://www.jotun.com/eg-ar",
    latitude: 30.3089,
    longitude: 31.7589,
    fleetSize: 125,
    fleetType: "شاحنات نقل مجهزة بمواصفات أمان نقل المواد الكيماوية والدهانات سريعة الاشتعال، وتريلات صهاريج",
    fleetTires: "315/80R22.5 • 295/80R22.5 • 225/75R17.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الصرح النرويجي العالمي الرائد لإنتاج الدهانات المعمارية والبحرية والطلاءات الواقية من التآكل بمصر",
    contactPerson: "مدير عام سلاسل الإمداد والخدمات اللوجستية",
    contactTitle: "Supply Chain & Logistics General Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.3089,31.7589"
  },
  {
    id: "eg_titan_802",
    nameAr: "شركة كابسي للدهانات وبويات السيارات (Kapci Coatings - مجمع بورسعيد)",
    nameEn: "Kapci Coatings Mega Industrial Plants (Port Said)",
    sector: "manufacturing",
    subSector: "أكبر صرح لتصنيع بويات السيارات والطلاءات الصناعية والتصدير لأكثر من 70 دولة",
    city: "port_said",
    governorate: "بورسعيد",
    address: "المنطقة الحرة الصناعية، جنوب بورسعيد، الكيلو 7 طريق الإسماعيلية",
    phone1: "0663771500",
    mobile: "01004411992",
    hotline: "19921",
    website: "https://www.kapci.com",
    latitude: 31.2124,
    longitude: 32.2789,
    fleetSize: 180,
    fleetType: "تريلات شحن حاويات تصدير للموانئ، شاحنات توزيع إقليمي للمحافظات، وصهاريج نقل مذيبات كيميائية",
    fleetTires: "315/80R22.5 • 385/65R22.5 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "القلعة المصرية الأولى عالمياً في تصدير دهانات إعادة طلاء السيارات والمنتجات الكيماوية التخصصية",
    contactPerson: "رئيس قطاع الحركة والنقل الدولي والمحلي",
    contactTitle: "International & Local Fleet Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=31.2124,32.2789"
  },
  {
    id: "eg_titan_803",
    nameAr: "شركة أكزو نوبل مصر للدهانات وبويات الحماية (AkzoNobel Egypt - ديلوكس وإنترناشيونال)",
    nameEn: "AkzoNobel Egypt Mega Coatings & Decorative Paints Plants",
    sector: "manufacturing",
    subSector: "تصنيع دهانات ديلوكس الفاخرة، بويات الحماية الصناعية والبحرية International، وبويات البودرة والأخشاب",
    city: "sharqia",
    governorate: "الشرقية",
    address: "المنطقة الصناعية الثالثة A3، العاشر من رمضان، الشرقية",
    phone1: "015418500",
    mobile: "01006633228",
    hotline: "19339",
    website: "https://www.akzonobel.com/en/eg",
    latitude: 30.3089,
    longitude: 31.7612,
    fleetSize: 125,
    fleetType: "شاحنات شحن دهانات مجهزة، تريلات نقل خامات كيماوية، وسيارات توزيع للمراكز التخصصية والمشروعات الكبرى",
    fleetTires: "315/80R22.5 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "العملاق الهولندي العالمي الرائد في بويات الحماية الصناعية لمنصات النفط والسفن ودهانات ديلوكس المعمارية",
    contactPerson: "مدير عام اللوجستيات وسلاسل الإمداد",
    contactTitle: "Supply Chain & Logistics Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.3089,31.7612"
  },
  {
    id: "eg_titan_804",
    nameAr: "شركة سايبس للدهانات والكيماويات الصناعية (Sipes Paints Egypt)",
    nameEn: "Sipes Paints Egypt Industrial Fleets",
    sector: "manufacturing",
    subSector: "تصنيع دهانات المباني، الطلاءات الإيبوكسية للأرضيات، والكيماويات المساعدة للبناء",
    city: "sharqia",
    governorate: "الشرقية",
    address: "المنطقة الصناعية A1، العاشر من رمضان، الشرقية",
    phone1: "015411200",
    mobile: "01008855441",
    hotline: "19875",
    website: "https://www.sipes.net",
    latitude: 30.3012,
    longitude: 31.7412,
    fleetSize: 115,
    fleetType: "شاحنات نقل دهانات مغلقة، تريلات شحن ثقيل، وسيارات توزيع فروع ومنافذ المحافظات",
    fleetTires: "315/80R22.5 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "من أقدم وأعرق علامات الدهانات في مصر والشرق الأوسط بشبكة توزيع ومصانع آلية ضخمة",
    contactPerson: "رئيس قطاع الحركة والشحن الإقليمي",
    contactTitle: "Regional Shipping & Movement Head",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.3012,31.7412"
  },
  {
    id: "eg_titan_805",
    nameAr: "شركة دهانات الجزيرة مصر (Al-Jazeera Paints Egypt)",
    nameEn: "Al-Jazeera Paints Egypt Mega Industrial Complex",
    sector: "manufacturing",
    subSector: "المجمع الصناعي لدهانات الأبراج والمشروعات الكبرى والدهانات الذكية المقاومة للحريق",
    city: "giza",
    governorate: "الجيزة",
    address: "المنطقة الصناعية الرابعة، السادس من أكتوبر، الجيزة",
    phone1: "0238206100",
    mobile: "01002211448",
    hotline: "19941",
    website: "https://www.jazeerapaints.com/egypt",
    latitude: 29.9612,
    longitude: 30.9245,
    fleetSize: 105,
    fleetType: "شاحنات نقل مغلقة مبردة، تريلات نقل مواد كيماوية، وأساطيل فانات توزيع سريع",
    fleetTires: "315/80R22.5 • 225/75R17.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "المجمع الصناعي المتطور للعلامة الرائدة المنفذة لطلاءات كبرى مشروعات الأبراج والقصور والمدن الحديثة",
    contactPerson: "مدير العمليات اللوجستية والأسطول",
    contactTitle: "Logistics Operations & Fleet Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.9612,30.9245"
  },
  {
    id: "eg_titan_806",
    nameAr: "الشركة الألمانية اللبنانية للدهانات (GLC Paints - مجمعات العبور والعاشر)",
    nameEn: "German Lebanese Co. for Paints (GLC Mega Plants)",
    sector: "manufacturing",
    subSector: "تصنيع وتوزيع دهانات الديكور وحماية المنشآت والكيماويات الإنشائية",
    city: "qalyubia",
    governorate: "القليوبية",
    address: "المنطقة الصناعية الأولى، مدينة العبور، القليوبية",
    phone1: "0244812500",
    mobile: "01005577119",
    hotline: "16752",
    website: "https://www.glcpaints.com",
    latitude: 30.2245,
    longitude: 31.4789,
    fleetSize: 160,
    fleetType: "أساطيل شاحنات نقل ثقيل وتوزيع، تريلات شحن خامات كيماوية، ومقطورات مجهزة",
    fleetTires: "315/80R22.5 • 295/80R22.5 • 225/75R17.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "أحد أكبر منتجي الدهانات في مصر والشرق الأوسط بأسطول نقل وشحن يغطي كافة مراكز الجمهورية يومياً",
    contactPerson: "مدير عام النقل واللوجستيات الميدانية",
    contactTitle: "Field Logistics & Fleets Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.2245,31.4789"
  },
  {
    id: "eg_titan_807",
    nameAr: "شركة باسف مصر للصناعات الكيماوية ومضافات البناء (BASF Egypt)",
    nameEn: "BASF Egypt Chemical Industries & Construction Solutions",
    sector: "manufacturing",
    subSector: "إنتاج كيماويات البناء المتطورة، مضافات الخرسانة، والبوليمرات التخصصية للسيارات والصناعة",
    city: "menofia",
    governorate: "المنوفية",
    address: "المنطقة الصناعية السادسة، مدينة السادات، المنوفية",
    phone1: "0482602400",
    mobile: "01007799113",
    hotline: "19662",
    website: "https://www.basf.com/eg",
    latitude: 30.3891,
    longitude: 30.5245,
    fleetSize: 95,
    fleetType: "تريلات صهاريج نقل مواد كيماوية خطرة معتمدة ADR، شاحنات مبردة، وشاحنات خلط مضافات",
    fleetTires: "315/80R22.5 • 385/65R22.5 • 12.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الصرح الألماني العالمي الأضخم للصناعات الكيماوية الموردة لكافة مصانع السيارات والإنشاءات الكبرى بمصر",
    contactPerson: "مدير الأمان وسلاسل الإمداد الكيميائي",
    contactTitle: "Chemical Supply Chain & Safety Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.3891,30.5245"
  },
  {
    id: "eg_titan_808",
    nameAr: "شركة سيكا مصر لكيماويات البناء والتشييد (Sika Egypt)",
    nameEn: "Sika Egypt for Construction Chemicals Mega Fleet",
    sector: "manufacturing",
    subSector: "إنتاج موانع تسرب المياه، ألياف تسليح الخرسانة، ولواصق السيراميك والمباني الشاهقة",
    city: "cairo",
    governorate: "القاهرة",
    address: "المنطقة الصناعية الأولى، مدينة العبور، القليوبية",
    phone1: "0244810500",
    mobile: "01009922883",
    hotline: "19324",
    website: "https://egy.sika.com",
    latitude: 30.2289,
    longitude: 31.4812,
    fleetSize: 90,
    fleetType: "شاحنات شحن كيماويات متخصصة، تريلات صهاريج، وشاحنات توزيع محطات خلط الخرسانة",
    fleetTires: "315/80R22.5 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "القلعة السويسرية العالمية المتخصصة في كيماويات الأنفاق ومحطات التحلية ومشروعات البنية التحتية",
    contactPerson: "رئيس قسم التوزيع والخدمات اللوجستية",
    contactTitle: "Distribution & Logistics Operations Chief",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.2289,31.4812"
  },
  {
    id: "eg_titan_809",
    nameAr: "شركة إير ليكيد مصر للغازات الصناعية والطبية (Air Liquide Egypt)",
    nameEn: "Air Liquide Egypt Mega Industrial & Medical Gases",
    sector: "manufacturing",
    subSector: "إنتاج وتوزيع الأكسجين السائل والنيتروجين والأرجون والهيدروجين للمستشفيات ومصانع الصلب",
    city: "cairo",
    governorate: "القاهرة",
    address: "المجمع الإداري، القطامية هايتس، القاهرة الجديدة",
    phone1: "0227598100",
    mobile: "01001144889",
    hotline: "16388",
    website: "https://www.airliquide.com.eg",
    latitude: 29.9891,
    longitude: 31.3789,
    fleetSize: 175,
    fleetType: "تريلات صهاريج كرايوجينك شديدة البرودة لنقل الغازات المسالة، شاحنات توزيع أسطوانات مضغوطة",
    fleetTires: "315/80R22.5 • 385/65R22.5 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الرائدة الفرنسية العالمية الأولى في تأمين إمدادات الأكسجين الطبي لمستشفيات مصر والغازات لمصانع الصلب",
    contactPerson: "مدير عام أساطيل النقل المبرد والغازات المسالة",
    contactTitle: "Cryogenic Fleet & Transport Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.9891,31.3789"
  },
  {
    id: "eg_titan_810",
    nameAr: "شركة ليندي للغازات الصناعية والطبية مصر (Linde Gas Egypt)",
    nameEn: "Linde Gas Egypt Industrial Cryogenic Fleets",
    sector: "manufacturing",
    subSector: "محطات فصل الهواء وإنتاج الغازات التخصصية وثاني أكسيد الكربون الغذائي",
    city: "suez",
    governorate: "السويس",
    address: "المنطقة الصناعية بعتاقة، السويس",
    phone1: "0623681400",
    mobile: "01003366225",
    hotline: "19544",
    website: "https://www.linde-gas.com.eg",
    latitude: 29.9312,
    longitude: 32.4789,
    fleetSize: 140,
    fleetType: "صهاريج كرايوجينك لنقل النيتروجين وثاني أكسيد الكربون السائل، وشاحنات شحن أسطوانات",
    fleetTires: "315/80R22.5 • 385/65R22.5 • 12.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "المورد الاستراتيجي للغازات الصناعية لشركات الأغذية والمشروبات (الغاز الكربوني) وحقول البترول",
    contactPerson: "رئيس قطاع النقل والسلامة المهنية للأسطول",
    contactTitle: "Fleet Safety & Transport Operations Head",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.9312,32.4789"
  },
  {
    id: "eg_titan_811",
    nameAr: "شركة غازات النيل للغازات الصناعية والطبية (Nile Gases Co.)",
    nameEn: "Nile Industrial & Medical Gases Mega Fleet",
    sector: "manufacturing",
    subSector: "إنتاج الغازات المضغوطة والمسالة وأسيتيلين اللحام لمصانع البناء والترسانات البحرية",
    city: "alexandria",
    governorate: "الإسكندرية",
    address: "طريق السد العالي، المكس، الإسكندرية",
    phone1: "034481900",
    mobile: "01005511337",
    hotline: "19728",
    website: "https://www.nile-gases.com",
    latitude: 31.1456,
    longitude: 29.8412,
    fleetSize: 110,
    fleetType: "شاحنات شحن أسطوانات غازات صناعية، تريلات صهاريج نقل غازات طبية، وسيارات صيانة شبكات",
    fleetTires: "315/80R22.5 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الصرح السكندري العريق المغذي لترسانات الإسكندرية ومصانع الحديد وشركات البترول بالغازات الصناعية",
    contactPerson: "مدير الحركة والنقل التخصصي",
    contactTitle: "Specialized Transport & Fleets Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=31.1456,29.8412"
  },
  {
    id: "eg_titan_812",
    nameAr: "شركة أبو قير للأسمدة والصناعات الكيماوية (مجمعات مصانع أبو قير 1 و 2 و 3)",
    nameEn: "Abu Qir Fertilizers & Chemical Industries (Plants 1, 2 & 3)",
    sector: "manufacturing",
    subSector: "أضخم صرح لإنتاج أسمدة اليوريا ونترات الأمونيوم والسماد السائل والتصدير العالمي",
    city: "alexandria",
    governorate: "الإسكندرية",
    address: "المنطقة الصناعية بالطابية، خط رشيد، أبو قير، الإسكندرية",
    phone1: "035603000",
    mobile: "01007744223",
    hotline: "19199",
    website: "https://www.abuqir.com",
    latitude: 31.3124,
    longitude: 30.0891,
    fleetSize: 260,
    fleetType: "تريلات تريلا فرش وتريلات جوانب نقل شكائر أسمدة، صهاريج نقل أمونيا سائلة مضغوطة، وأتوبيسات ورديات",
    fleetTires: "315/80R22.5 • 385/65R22.5 • 12.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "عملاق صناعة الأسمدة النيتروجينية في مصر وإفريقيا بطاقة إنتاجية تتجاوز 2 مليون طن سنوياً",
    contactPerson: "رئيس قطاعات النقل والخدمات الميدانية والصيانة",
    contactTitle: "Transport, Maintenance & Field Services Sector Head",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=31.3124,30.0891"
  },
  {
    id: "eg_titan_813",
    nameAr: "شركة الإسكندرية للأسمدة (أليكسفيرت - Alexfert)",
    nameEn: "Alexandria Fertilizers Co. (Alexfert Mega Complex)",
    sector: "manufacturing",
    subSector: "إنتاج سماد اليوريا الحبيبي والأمونيا وتصدير الحاويات للأسواق الأوروبية والأمريكية",
    city: "alexandria",
    governorate: "الإسكندرية",
    address: "المجمع الصناعي للأسمدة، الطابية، الإسكندرية",
    phone1: "035624100",
    mobile: "01009988114",
    hotline: "19415",
    website: "https://www.alexfert.com",
    latitude: 31.3156,
    longitude: 30.0945,
    fleetSize: 155,
    fleetType: "تريلات نقل يوريا صب للموانئ، صهاريج نقل أمونيا مبردة، وشاحنات دعم لوجستي",
    fleetTires: "315/80R22.5 • 385/65R22.5 • 12.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "القلعة التصديرية الكبرى لليوريا الحبيبية بأحدث تكنولوجيا تصنيع صديقة للبيئة بمصر",
    contactPerson: "مدير عام الشحن والتسويق اللوجستي",
    contactTitle: "Logistics Shipping & Fleet Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=31.3156,30.0945"
  },
  {
    id: "eg_titan_814",
    nameAr: "شركة الدلتا للأسمدة والصناعات الكيماوية (سماد طلخا - قطاع الأعمال العام)",
    nameEn: "Delta Fertilizers & Chemical Industries (Talkha Plants)",
    sector: "manufacturing",
    subSector: "إنتاج سلفات النشادر والأسمدة النيتروجينية والأمونيا التابعة للقابضة للكيماويات",
    city: "dakahlia",
    governorate: "الدقهلية",
    address: "مجمع مصانع سماد طلخا، طلخا، الدقهلية",
    phone1: "0502528100",
    mobile: "01002233991",
    hotline: "19609",
    website: "https://www.delta-fert.gov.eg",
    latitude: 31.0612,
    longitude: 31.3712,
    fleetSize: 140,
    fleetType: "تريلات نقل أسمدة شكائر، صهاريج أمونيا، أوناش شوكية، وأتوبيسات نقل آلاف العمال",
    fleetTires: "315/80R22.5 • 12.00R20 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الصرح الوطني التاريخي المغذي للرقعة الزراعية في قلب الدلتا التابع لقطاع الأعمال العام",
    contactPerson: "مدير عام الحركة والسيارات والورش",
    contactTitle: "Movement, Fleet & Workshops General Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=31.0612,31.3712"
  },
  {
    id: "eg_titan_815",
    nameAr: "شركة النصر للأسمدة والصناعات الكيماوية (سيمادكو - السويس)",
    nameEn: "El Nasr Fertilizers & Chemical Industries (Semadco Suez)",
    sector: "manufacturing",
    subSector: "إنتاج حامض النيتريك ونترات النشادر والسماد المركب وكبريتات النشادر",
    city: "suez",
    governorate: "السويس",
    address: "طريق صلاح نسيم، عتاقة، السويس",
    phone1: "0623331800",
    mobile: "01004455883",
    hotline: "19374",
    website: "https://www.semadco.gov.eg",
    latitude: 29.9541,
    longitude: 32.5124,
    fleetSize: 130,
    fleetType: "صهاريج نقل أحماض كيميائية مبطنة، تريلات نقل أسمدة، وشاحنات صيانة مجمعات الأمونيا",
    fleetTires: "315/80R22.5 • 12.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "أول مصنع أسمدة أقيم في الشرق الأوسط (تأسس عام 1946) وما زال صرحاً وطنياً استراتيجياً بالسويس",
    contactPerson: "رئيس قطاعات النقل والورش الميكانيكية",
    contactTitle: "Mechanical Workshops & Transport Head",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.9541,32.5124"
  },
  {
    id: "eg_titan_816",
    nameAr: "شركة حلوان للأسمدة (Helwan Fertilizers Company - HFC)",
    nameEn: "Helwan Fertilizers Company (HFC Urea Complex)",
    sector: "manufacturing",
    subSector: "إنتاج اليوريا والأمونيا السائلة وتزويد الجمعيات الزراعية بالسماد المدعم والتصدير",
    city: "cairo",
    governorate: "القاهرة",
    address: "المنطقة الصناعية بجنوب حلوان، التبين، القاهرة",
    phone1: "0225012500",
    mobile: "01006688225",
    hotline: "19788",
    website: "https://www.hfcegypt.com",
    latitude: 29.7789,
    longitude: 31.2891,
    fleetSize: 120,
    fleetType: "تريلات تريلا فرش شحن أسمدة، صهاريج أمونيا معتمدة، وأساطيل نقل لوجستي لموانئ السخنة والإسكندرية",
    fleetTires: "315/80R22.5 • 385/65R22.5 • 12.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "مجمع عملاق لإنتاج اليوريا الحبيبية المتطورة بمواصفات مطابقة لأعلى المعايير العالمية",
    contactPerson: "مدير عام النقل والتشغيل",
    contactTitle: "Transport & Operations General Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.7789,31.2891"
  },
  {
    id: "eg_titan_817",
    nameAr: "مجموعة إيفرجرو للأسمدة المتخصصة (Evergrow - مجمع مدينة السادات)",
    nameEn: "Evergrow for Specialty Fertilizers Mega Complex (Sadat City)",
    sector: "manufacturing",
    subSector: "أكبر منتج في الشرق الأوسط لأسمدة البوتاسيوم وحامض الفوسفوريك وكلوريد الكالسيوم",
    city: "menofia",
    governorate: "المنوفية",
    address: "المنطقة الصناعية السابعة، مدينة السادات، المنوفية",
    phone1: "0482613100",
    mobile: "01008811449",
    hotline: "19638",
    website: "https://www.evergrowfert.com",
    latitude: 30.3956,
    longitude: 30.5412,
    fleetSize: 185,
    fleetType: "تريلات نقل أسمدة بوتاسية، صهاريج نقل أحماض مركزة، تريلات نقل خام الفوسفات، وأتوبيسات",
    fleetTires: "315/80R22.5 • 385/65R22.5 • 12.00R24",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "القلعة الصناعية الثالثة عالمياً في إنتاج سلفات البوتاسيوم بحجم استثمارات وأساطيل عملاقة",
    contactPerson: "نائب رئيس المجموعة للخدمات اللوجستية والأسطول",
    contactTitle: "Group Logistics & Fleet Vice President",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.3956,30.5412"
  },
  {
    id: "eg_titan_818",
    nameAr: "شركة الصناعات الكيماوية المصرية (كيما أسوان - مجمع كيما 2 الجديد)",
    nameEn: "Egyptian Chemical Industries (KIMA 2 Mega Complex Aswan)",
    sector: "manufacturing",
    subSector: "الصرح العملاق لإنتاج نترات الأمونيوم واليوريا والغاز الطبيعي بجنوب مصر",
    city: "aswan",
    governorate: "أسوان",
    address: "منطقة كيما، شرق مدينة أسوان",
    phone1: "0972458100",
    mobile: "01001199332",
    hotline: "19245",
    website: "https://www.kima-eg.com",
    latitude: 24.0612,
    longitude: 32.9124,
    fleetSize: 165,
    fleetType: "تريلات نقل أسمدة مجهزة لدرجات الحرارة العالية، صهاريج غازات صناعية، وأساطيل نقل ثقيل",
    fleetTires: "315/80R22.5 • 12.00R24 • 385/65R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "مجمع كيما 2 الجديد الذي افتتحه رئيس الجمهورية كأحد أضخم قلاع الصناعة وتنمية صعيد مصر",
    contactPerson: "رئيس قطاعات الأسطول والنقل والمستودعات",
    contactTitle: "Fleet, Transport & Warehouses Sector Head",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=24.0612,32.9124"
  },
  {
    id: "eg_titan_819",
    nameAr: "شركة مصر لإنتاج الأسمدة (موبكو - MOPCO بميناء دمياط)",
    nameEn: "Misr Fertilizers Production Company (MOPCO Damietta Port)",
    sector: "manufacturing",
    subSector: "أكبر مجمع لإنتاج الأمونيا واليوريا في مصر والشرق الأوسط للتصدير الملاحي",
    city: "damietta",
    governorate: "دمياط",
    address: "المنطقة الحرة بميناء دمياط، دمياط",
    phone1: "0572292400",
    mobile: "01003355771",
    hotline: "19599",
    website: "https://www.mopco-eg.com",
    latitude: 31.4312,
    longitude: 31.7612,
    fleetSize: 190,
    fleetType: "تريلات شحن يوريا صب للمراكب، صهاريج نقل مواد كيماوية، وأساطيل نقل هندسي ولوجستي متكامل",
    fleetTires: "315/80R22.5 • 385/65R22.5 • 12.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "العملاق البتروكيماوي التابع لقطاع البترول المصري بطاقة تصديرية ضخمة تزيد عن 2 مليون طن سنوياً",
    contactPerson: "مدير عام النقل والعمليات البحرية والبرية",
    contactTitle: "Marine & Land Fleets General Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=31.4312,31.7612"
  },
  {
    id: "eg_titan_820",
    nameAr: "الشركة المصرية لإنتاج الإيثيلين ومشتقاته (إيثيدكو - مجمع الإسكندرية)",
    nameEn: "Egyptian Ethylene & Derivatives Co. (ETHYDCO Petrochemicals)",
    sector: "manufacturing",
    subSector: "إنتاج البولي إيثيلين عالي ومنخفض الكثافة والبوتادين وخامات البلاستيك القومية",
    city: "alexandria",
    governorate: "الإسكندرية",
    address: "النهضة، العامرية، الإسكندرية",
    phone1: "034770100",
    mobile: "01005577994",
    hotline: "19311",
    website: "https://www.ethydco-eg.com",
    latitude: 31.0189,
    longitude: 29.8345,
    fleetSize: 145,
    fleetType: "تريلات نقل حبيبات بوليمر في سيلوهات وتريلات حاويات، صهاريج غازات، وأتوبيسات نقل ورديات",
    fleetTires: "315/80R22.5 • 385/65R22.5 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "أحدث وأكبر مجمع للبتروكيماويات والبولي إيثيلين في مصر لتغذية صناعات البلاستيك والكابلات الوطنية",
    contactPerson: "مدير عام الخدمات العامة والأسطول",
    contactTitle: "General Services & Fleet General Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=31.0189,29.8345"
  },
  {
    id: "eg_titan_821",
    nameAr: "شركة البتروكيماويات المصرية (EPC - مصانع الـ PVC والصودا الكاوية)",
    nameEn: "Egyptian Petrochemicals Company (EPC Amreya Complex)",
    sector: "manufacturing",
    subSector: "إنتاج خام بولي فينيل كلوريد (PVC) والصودا الكاوية السائلة وقشور وغاز الكلور المسال",
    city: "alexandria",
    governorate: "الإسكندرية",
    address: "طريق النهضة، العامرية، الكيلو 36 طريق الإسكندرية القاهرة الصحراوي",
    phone1: "034770500",
    mobile: "01007711336",
    hotline: "19472",
    website: "https://www.petrochem.com.eg",
    latitude: 31.0245,
    longitude: 29.8289,
    fleetSize: 150,
    fleetType: "صهاريج نقل صودا كاوية وكلور سائل مبطنة تيتانيوم، تريلات شحن حبيبات PVC، وسيارات طوارئ",
    fleetTires: "315/80R22.5 • 12.00R20 • 385/65R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "قلعة تصنيع خام البلاستيك والمواسير والكيماويات التابعة للهيئة العامة للبترول المصرية",
    contactPerson: "مساعد رئيس الشركة للشؤون الإدارية والخدمات الميدانية",
    contactTitle: "Assistant Chairman for Field Services & Fleets",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=31.0245,29.8289"
  },
  {
    id: "eg_titan_822",
    nameAr: "شركة سيدي كرير للبتروكيماويات (سيدبك - Sidpec Mega Plants)",
    nameEn: "Sidi Kerir Petrochemicals Co. (Sidpec Complex)",
    sector: "manufacturing",
    subSector: "تكسير غاز الإيثان وإنتاج البولي إيثيلين ومشتقاته للتطبيقات الصناعية والطبية",
    city: "alexandria",
    governorate: "الإسكندرية",
    address: "الكيلو 36 طريق الإسكندرية - مطروح الساحلي، سيدي كرير، الإسكندرية",
    phone1: "034770000",
    mobile: "01009933552",
    hotline: "19211",
    website: "https://www.sidpec.com",
    latitude: 31.0589,
    longitude: 29.6891,
    fleetSize: 135,
    fleetType: "تريلات شحن حبيبات بوليمر، صهاريج غاز الإيثان المسال، وأساطيل نقل العاملين والمهندسين",
    fleetTires: "315/80R22.5 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "من أهم قلاع قطاع البتروكيماويات المصرية المقيدة بالبورصة والمورد الاستراتيجي لمصانع البلاستيك",
    contactPerson: "مدير عام النقل والمهمات البتروكيماوية",
    contactTitle: "Transport & Petrochemical Missions Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=31.0589,29.6891"
  },
  {
    id: "eg_titan_823",
    nameAr: "شركة مصر للهيدروجين الأخضر والأمونيا الخضراء (Green Hydrogen Egypt)",
    nameEn: "Egypt Green Hydrogen & Ammonia Mega Complex (Sokhna)",
    sector: "manufacturing",
    subSector: "أول مجمع صناعي لإنتاج الهيدروجين الأخضر والأمونيا الخضراء باستخدام الطاقة المتجددة بالشرق الأوسط",
    city: "suez",
    governorate: "السويس",
    address: "المنطقة الاقتصادية لقناة السويس، العين السخنة، السويس",
    phone1: "0623985100",
    mobile: "01001188229",
    hotline: "19830",
    website: "https://www.greenhydrogen-eg.com",
    latitude: 29.6456,
    longitude: 32.3124,
    fleetSize: 85,
    fleetType: "تريلات صهاريج نقل هيدروجين مضغوط فائق الأمان، صهاريج أمونيا خضراء، وسيارات مسح بيئي",
    fleetTires: "315/80R22.5 • 385/65R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "المشروع القومي الرائد الذي تم تشغيله خلال قمة المناخ COP27 كأول منشأة هيدروجين أخضر متكاملة بإفريقيا",
    contactPerson: "مدير عام اللوجستيات وسلاسل إمداد الطاقة الخضراء",
    contactTitle: "Green Energy Supply Chain & Logistics Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.6456,32.3124"
  },
  {
    id: "eg_titan_824",
    nameAr: "شركة شينت إلكتريك مصر لصناعة القواطع والمحولات (Chint Electric Egypt)",
    nameEn: "Chint Electric Egypt Industrial Manufacturing",
    sector: "manufacturing",
    subSector: "تصنيع مهمات الجهد المتوسط والمنخفض، محطات المحولات المدمجة، وقواطع الدوائر الكهربائية",
    city: "cairo",
    governorate: "القاهرة",
    address: "المنطقة الصناعية بمدينة بدر، طريق السويس، القاهرة",
    phone1: "0228649000",
    mobile: "01003355118",
    hotline: "19766",
    website: "https://www.chint.com/eg",
    latitude: 30.1345,
    longitude: 31.7245,
    fleetSize: 80,
    fleetType: "شاحنات نقل محولات ولوحات توزيع، أوناش شوكية، وسيارات دعم فني واختبارات كهروميكانيكية",
    fleetTires: "315/80R22.5 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "المصنع المتطور للعملاق العالمي شينت المنفذ لأكبر شبكات الكهرباء ومحطات الطاقة الشمسية بنبان",
    contactPerson: "مدير العمليات اللوجستية والمعدات",
    contactTitle: "Logistics Operations & Fleets Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.1345,31.7245"
  },
  {
    id: "eg_titan_825",
    nameAr: "شركة النصر للكيماويات الوسيطة (مجمع كوم أوشيم بالفيوم)",
    nameEn: "El Nasr Co. for Intermediate Chemicals (Kom Oshim Complex)",
    sector: "manufacturing",
    subSector: "إنتاج الشبة السائلة والصلبة لتنقية مياه الشرب، حامض الكبريتيك المركز، والمبيدات الحشرية",
    city: "fayoum",
    governorate: "الفيوم",
    address: "المنطقة الصناعية بكوم أوشيم، طريق الفيوم - القاهرة الصحراوي، الفيوم",
    phone1: "0846219400",
    mobile: "01005577338",
    hotline: "19582",
    website: "https://www.ncic.com.eg",
    latitude: 29.5412,
    longitude: 30.9124,
    fleetSize: 180,
    fleetType: "صهاريج نقل شبة سائلة لمحطات مياه الشرب على مستوى الجمهورية، صهاريج حامض كبريتيك، وشاحنات شحن",
    fleetTires: "315/80R22.5 • 12.00R20 • 385/65R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الصرح الوطني الاستراتيجي الأكبر التابع لجهاز الخدمة الوطنية المسؤول عن تأمين الشبة لجميع محطات مياه مصر",
    contactPerson: "مدير عام النقل واللوجستيات الكيميائية القومية",
    contactTitle: "Chemical Fleets & Transport General Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.5412,30.9124"
  },
  {
    id: "eg_titan_826",
    nameAr: "شركة النصر للكيماويات الوسيطة (مجمع العين السخنة للأسمدة الفوسفاتية والمركبة)",
    nameEn: "NCIC Mega Phosphatic & Compound Fertilizers Complex (Sokhna)",
    sector: "manufacturing",
    subSector: "أضخم مجمع صناعي للأسمدة الفوسفاتية وحامض الفوسفوريك النقي والسماد المركب بإفريقيا",
    city: "suez",
    governorate: "السويس",
    address: "المنطقة الاقتصادية بالعين السخنة، طريق السويس - البحر الأحمر",
    phone1: "0623915500",
    mobile: "01007799552",
    hotline: "19582",
    website: "https://www.ncic.com.eg/sokhna",
    latitude: 29.6124,
    longitude: 32.3789,
    fleetSize: 220,
    fleetType: "تريلات تريلا فرش وتريلات صهاريج أحماض، تريلات نقل أسمدة داب وناب، وأساطيل نقل خام الفوسفات",
    fleetTires: "315/80R22.5 • 385/65R22.5 • 12.00R24",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "المجمع الرئاسي العملاق الذي يضم 9 مصانع كبرى لإنتاج وتصدير الأسمدة الفوسفاتية لأكثر من 55 دولة",
    contactPerson: "رئيس قطاعات الأسطول والنقل وشحن الموانئ",
    contactTitle: "Ports Shipping & Heavy Fleets Sector Head",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.6124,32.3789"
  },
  {
    id: "eg_titan_827",
    nameAr: "شركة البويات والصناعات الكيماوية ميدو (Mido Group - بويات السيارات والديكور)",
    nameEn: "Mido Coatings & Chemical Industries Mega Fleet",
    sector: "manufacturing",
    subSector: "إنتاج معاجين وبويات السيارات، الدهانات الخشبية، ومستلزمات الطلاء الصناعي",
    city: "alexandria",
    governorate: "الإسكندرية",
    address: "المنطقة الصناعية الثالثة، برج العرب الجديدة، الإسكندرية",
    phone1: "034598100",
    mobile: "01009911445",
    hotline: "19669",
    website: "https://www.midocoatings.com",
    latitude: 30.9245,
    longitude: 29.6891,
    fleetSize: 105,
    fleetType: "شاحنات شحن دهانات مبردة، سيارات توزيع فروع، وتريلات نقل خامات صناعية",
    fleetTires: "315/80R22.5 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "من كبرى العلامات المصرية المصدرة لمعجون ودهانات السيارات لإفريقيا والدول العربية",
    contactPerson: "مدير عام إدارة الحركة واللوجستيات",
    contactTitle: "Logistics & Transport Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.9245,29.6891"
  },
  {
    id: "eg_titan_828",
    nameAr: "شركة يونيليفر مشرق للصناعات والمنظفات المنزلية (Unilever Mashreq)",
    nameEn: "Unilever Mashreq Industrial Plants (6th of October)",
    sector: "manufacturing",
    subSector: "تصنيع المنظفات الصناعية والشامبو ومستحضرات العناية الشخصية (أومو، صن سيلك، دوف، ريكسونا)",
    city: "giza",
    governorate: "الجيزة",
    address: "المنطقة الصناعية الثالثة، السادس من أكتوبر، الجيزة",
    phone1: "0238289000",
    mobile: "01001133994",
    hotline: "16111",
    website: "https://www.unilever.com.eg",
    latitude: 29.9456,
    longitude: 30.9124,
    fleetSize: 145,
    fleetType: "شاحنات نقل منتجات استهلاكية سريعة الدوران (FMCG)، تريلات شحن للمحافظات، وفانات توزيع",
    fleetTires: "315/80R22.5 • 295/80R22.5 • 225/75R17.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الصرح الاستهلاكي والكيماوي العالمي المغذي لملايين الأسر المصرية والمصدر لإفريقيا والشرق الأوسط",
    contactPerson: "مدير عام سلاسل الإمداد والأسطول الإقليمي",
    contactTitle: "Regional Supply Chain & Fleet Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.9456,30.9124"
  },
  {
    id: "eg_titan_829",
    nameAr: "شركة بروكتر آند جامبل مصر (Procter & Gamble Egypt - P&G 6th of October)",
    nameEn: "Procter & Gamble Egypt (P&G Mega Plant 6th of October)",
    sector: "manufacturing",
    subSector: "مجمع تصنيع مساحيق الغسيل والعناية بالأقمشة (إريال، تايد، بونكس، بامبرز، هيد آند شولدرز)",
    city: "giza",
    governorate: "الجيزة",
    address: "المنطقة الصناعية الرابعة، السادس من أكتوبر، الجيزة",
    phone1: "0238201100",
    mobile: "01003355887",
    hotline: "19330",
    website: "https://www.pg.com",
    latitude: 29.9389,
    longitude: 30.8989,
    fleetSize: 165,
    fleetType: "تريلات شحن منتجات كرتونية مغلقة، شاحنات توزيع لوجستي للمراكز الإقليمية، وتريلات صهاريج سلفونيك",
    fleetTires: "315/80R22.5 • 295/80R22.5 • 385/65R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "أكبر مركز تصديري لشركة P&G الأمريكية في الشرق الأوسط وإفريقيا بأسطول شحن فائق الكفاءة",
    contactPerson: "رئيس قطاع العمليات اللوجستية والنقل الدولي والمحلي",
    contactTitle: "Logistics Operations & Fleet Head",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.9389,30.8989"
  },
  {
    id: "eg_titan_830",
    nameAr: "شركة هينكل مصر للمنظفات الصناعية (Henkel Egypt - مجمع مصانع بورسعيد)",
    nameEn: "Henkel Egypt Detergents Mega Complex (Port Said)",
    sector: "manufacturing",
    subSector: "تصنيع مساحيق الغسيل والمنظفات السائلة ومواد اللصق التكنولوجية (برسيل، بريل، أوكي)",
    city: "port_said",
    governorate: "بورسعيد",
    address: "المنطقة الصناعية C6، جنوب بورسعيد",
    phone1: "0663789100",
    mobile: "01005577228",
    hotline: "19055",
    website: "https://www.henkel.eg",
    latitude: 31.2189,
    longitude: 32.2845,
    fleetSize: 135,
    fleetType: "شاحنات شحن مساحيق ومنظفات، تريلات نقل حاويات تصدير للميناء، وشاحنات توزيع محافظات الدلتا",
    fleetTires: "315/80R22.5 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الصرح الألماني الرائد في المنظفات الصناعية ومواد اللصق الهندسية بحجم إنتاج وتوزيع استثنائي",
    contactPerson: "مدير النقل وسلاسل الإمداد المركزية",
    contactTitle: "Central Supply Chain & Transport Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=31.2189,32.2845"
  },
  {
    id: "eg_titan_831",
    nameAr: "مجموعة لورد لصناعة شفرات الحلاقة والصناعات الدقيقة (Lord International Group)",
    nameEn: "Lord International Precision Manufacturing Mega Fleet",
    sector: "manufacturing",
    subSector: "تصنيع شفرات وماكينات الحلاقة الدقيقة والتصدير لأكثر من 85 دولة حول العالم",
    city: "alexandria",
    governorate: "الإسكندرية",
    address: "المنطقة الحرة العامة بالعامرية، الإسكندرية",
    phone1: "034500100",
    mobile: "01007799441",
    hotline: "19424",
    website: "https://www.lordshave.com",
    latitude: 31.0456,
    longitude: 29.8456,
    fleetSize: 95,
    fleetType: "شاحنات نقل منتجات دقيقة مبردة ومجهزة، تريلات شحن حاويات موانئ، وسيارات توزيع محلية",
    fleetTires: "315/80R22.5 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "من كبرى القلاع التصديرية المصرية المصنفة عالمياً ضمن كبار مصنعي شفرات الصلب المقاوم للصدأ",
    contactPerson: "مدير الشحن والنقل اللوجستي الدولي",
    contactTitle: "International Shipping & Transport Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=31.0456,29.8456"
  },
  {
    id: "eg_titan_832",
    nameAr: "شركة مصر لصناعة الكيماويات (MCH - المكس بالإسكندرية)",
    nameEn: "Misr Chemical Industries Co. (MCH Alexandria)",
    sector: "manufacturing",
    subSector: "إنتاج الصودا الكاوية، غاز الكلور المسال، حامض الهيدروكلوريك، وهيبوكلوريت الصوديوم",
    city: "alexandria",
    governorate: "الإسكندرية",
    address: "شارع السد العالي، المكس، الإسكندرية",
    phone1: "034481500",
    mobile: "01009911337",
    hotline: "19733",
    website: "https://www.misrchem.gov.eg",
    latitude: 31.1412,
    longitude: 29.8389,
    fleetSize: 125,
    fleetType: "صهاريج كيميائية متخصصة لنقل الصودا الكاوية السائلة، شاحنات نقل أسطوانات وحاويات الكلور المسال",
    fleetTires: "315/80R22.5 • 12.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الصرح الوطني الأقدم التابع للشركة القابضة للصناعات الكيماوية المؤمّن لاحتياجات محطات مياه الشرب من الكلور",
    contactPerson: "مدير عام إدارة النقل والورش التخصصية",
    contactTitle: "Specialized Workshops & Transport Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=31.1412,29.8389"
  },
  {
    id: "eg_titan_833",
    nameAr: "شركة قنا لصناعة الورق (Qena Paper Industry Mega Plant)",
    nameEn: "Qena Paper Industry (Sugar Cane Bagasse Paper Complex)",
    sector: "manufacturing",
    subSector: "إنتاج ورق الكتابة والطباعة عالي الجودة من مصاص القصب وتغذية المطابع القومية",
    city: "qena",
    governorate: "قنا",
    address: "مدينة قوص، جنوب محافظة قنا",
    phone1: "0966814100",
    mobile: "01001144662",
    hotline: "19815",
    website: "https://www.qenapaper.com",
    latitude: 25.9124,
    longitude: 32.7589,
    fleetSize: 110,
    fleetType: "تريلات تريلا فرش شحن بكر ولفائف ورق طباعة، شاحنات نقل مصاص قصب السكر، وأتوبيسات",
    fleetTires: "315/80R22.5 • 12.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الصرح الصناعي البيئي الأضخم في صعيد مصر لتحويل مخلفات السكر إلى ورق كتابة وطباعة فاخر",
    contactPerson: "مدير عام النقل والخدمات الميدانية بالمصانع",
    contactTitle: "Plants Transport & Field Services Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=25.9124,32.7589"
  },
  {
    id: "eg_titan_834",
    nameAr: "شركة مصر إدفو للب الورق وكتابة وطباعة (Edfu Paper Mills)",
    nameEn: "Misr Edfu Paper Mills (Pulp & Writing Paper)",
    sector: "manufacturing",
    subSector: "إنتاج لب الورق الكيميائي والورق الأبيض لطباعة الكتب المدرسية والجرائد القومية",
    city: "aswan",
    governorate: "أسوان",
    address: "مدينة إدفو، شمال محافظة أسوان",
    phone1: "0974712500",
    mobile: "01003366992",
    hotline: "19644",
    website: "https://www.edfu-paper.gov.eg",
    latitude: 24.9789,
    longitude: 32.8712,
    fleetSize: 100,
    fleetType: "تريلات شحن ورق مسافات طويلة للقاهرة والدلتا، شاحنات قلاب نقل مخلفات عضوية، ولوادر",
    fleetTires: "315/80R22.5 • 12.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "القلعة الصناعية القومية التابعة للقابضة الكيماوية الموردة لورق الكتب المدرسية لوزارة التربية والتعليم",
    contactPerson: "رئيس قطاع الحركة والنقل الثقيل بأسوان",
    contactTitle: "Aswan Heavy Fleet & Transport Head",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=24.9789,32.8712"
  },
  {
    id: "eg_titan_835",
    nameAr: "شركة الشروق للكرتون المضلع ومواد التغليف (El Shorouk Packaging)",
    nameEn: "El Shorouk Corrugated Cardboard & Packaging Mega Fleet",
    sector: "manufacturing",
    subSector: "تصنيع الكرتون المضلع والعبوات الكرتونية الفاخرة لكبرى شركات الأغذية والأدوية والأجهزة",
    city: "sharqia",
    governorate: "الشرقية",
    address: "المنطقة الصناعية A4، العاشر من رمضان، الشرقية",
    phone1: "015414500",
    mobile: "01005588331",
    hotline: "19755",
    website: "https://www.shoroukpack.com",
    latitude: 30.3124,
    longitude: 31.7689,
    fleetSize: 120,
    fleetType: "شاحنات نقل كرتون صناديق مغلقة ذات سعة حجمية عملاقة (Jumbo Boxes)، تريلات نقل رولات كرافت",
    fleetTires: "315/80R22.5 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "رائدة صناعة الكرتون المضلع والتغليف الذكي الموردة لمصانع الحاصلات الزراعية التصديرية والأجهزة المنزلية",
    contactPerson: "مدير عام النقل والأسطول اللوجستي",
    contactTitle: "Logistics Fleet & Transport General Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.3124,31.7689"
  },
  {
    id: "eg_titan_836",
    nameAr: "شركة إيجيباك لتصنيع العبوات المعدنية والغذائية (Egypac Metal Packaging)",
    nameEn: "Egypac Metal Cans & Packaging Mega Industrial Plants",
    sector: "manufacturing",
    subSector: "تصنيع عبوات الصفيح للأغذية، عبوات الدهانات، وعلب المشروبات المعدنية ومصانع الأيروسول",
    city: "qalyubia",
    governorate: "القليوبية",
    address: "المنطقة الصناعية بقليوب، طريق مصر إسكندرية الزراعي، القليوبية",
    phone1: "0132145800",
    mobile: "01007711448",
    hotline: "19832",
    website: "https://www.egypac.com",
    latitude: 30.1891,
    longitude: 31.2124,
    fleetSize: 85,
    fleetType: "شاحنات شحن عبوات معدنية مجهزة لحماية الطلاء والطباعة، تريلات نقل لفائف صفيح مقصدر",
    fleetTires: "315/80R22.5 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "المورد الاستراتيجي للعبوات المعدنية لكبرى شركات الصلصة والزيوت النباتية ومصانع الدهانات بمصر",
    contactPerson: "مدير الحركة والنقل الخارجي",
    contactTitle: "Outbound Logistics & Transport Head",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.1891,31.2124"
  },
  {
    id: "eg_titan_837",
    nameAr: "شركة فليكس بي فيلمز مصر للبلاستيك والبوليمر (Flex P Films Egypt)",
    nameEn: "Flex P Films Egypt Mega BOPET & BOPP Complex",
    sector: "manufacturing",
    subSector: "إنتاج أفلام البولي بروبيلين والبولي إستر ثنائية التوجيه (BOPET & BOPP) لتغليف الأغذية والأدوية",
    city: "giza",
    governorate: "الجيزة",
    address: "المنطقة الصناعية الهندسية، السادس من أكتوبر، الجيزة",
    phone1: "0238249000",
    mobile: "01009933117",
    hotline: "19677",
    website: "https://www.flexfilm.com",
    latitude: 29.9312,
    longitude: 30.8891,
    fleetSize: 110,
    fleetType: "شاحنات شحن رولات بوليمر حساسة، تريلات نقل حاويات تصدير، وتريلات صهاريج خامات بلاستيك",
    fleetTires: "315/80R22.5 • 385/65R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الفرع المصري لأكبر منتج ومصدر لأفلام التغليف البوليمرية المرنة ذات التكنولوجيا الهندية العالمية",
    contactPerson: "مدير عام اللوجستيات وسلاسل الإمداد",
    contactTitle: "Supply Chain & Logistics Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.9312,30.8891"
  },
  {
    id: "eg_titan_838",
    nameAr: "شركة يونيفرسال لصناعة الأجهزة المنزلية والبوتاجازات (Universal Group)",
    nameEn: "Universal Group for Home Appliances & Gas Cookers",
    sector: "manufacturing",
    subSector: "مجمعات تصنيع البوتاجازات، سخانات الغاز والكهرباء، والغسالات الأوتوماتيكية والتصدير",
    city: "giza",
    governorate: "الجيزة",
    address: "المنطقة الصناعية الرابعة، السادس من أكتوبر، الجيزة",
    phone1: "0238202500",
    mobile: "01001155883",
    hotline: "19600",
    website: "https://www.universal-group.org",
    latitude: 29.9512,
    longitude: 30.9189,
    fleetSize: 170,
    fleetType: "أساطيل شاحنات نقل أجهزة منزلية مغلقة، سيارات صيانة منزلية سريعة، وتريلات نقل صاج مدرفل",
    fleetTires: "315/80R22.5 • 295/80R22.5 • 225/75R16",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "من أضخم مجمعات الأجهزة المنزلية في مصر بأسطول صيانة وتوزيع يخدم ملايين المنازل بالمحافظات",
    contactPerson: "رئيس قطاع الأسطول والصيانة المنزلية الميدانية",
    contactTitle: "Field Service Fleet & Operations Head",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.9512,30.9189"
  },
  {
    id: "eg_titan_839",
    nameAr: "شركة يونيون إير لصناعة أجهزة التكييف والشاشات (Unionaire Group)",
    nameEn: "Unionaire Group for Air Conditioners & Electronics",
    sector: "manufacturing",
    subSector: "مجمعات تصنيع أجهزة التكييف الاسبليت والكونسيلد والشاشات الذكية والأجهزة المنزلية",
    city: "giza",
    governorate: "الجيزة",
    address: "المنطقة الصناعية الثالثة، السادس من أكتوبر، الجيزة",
    phone1: "0238338100",
    mobile: "01003377449",
    hotline: "19012",
    website: "https://www.unionaire.com",
    latitude: 29.9612,
    longitude: 30.9312,
    fleetSize: 185,
    fleetType: "شاحنات شحن أجهزة تكييف، فانات صيانة وتركيبات مجهزة، تريلات شحن شاشات وثلاجات",
    fleetTires: "315/80R22.5 • 295/80R22.5 • 225/75R16",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "رائدة تصنيع أجهزة التكييف والتبريد في مصر والشرق الأوسط بطاقة إنتاجية وتصديرية ضخمة",
    contactPerson: "مدير عام إدارة الحركة والخدمات اللوجستية",
    contactTitle: "Logistics & Fleet Operations General Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.9612,30.9312"
  },
  {
    id: "eg_titan_840",
    nameAr: "مجموعة فريش إليكتريك للأجهزة المنزلية (Fresh Electric - مجمعات العاشر)",
    nameEn: "Fresh Electric for Home Appliances Mega Complex (10th of Ramadan)",
    sector: "manufacturing",
    subSector: "تصنيع الثلاجات، الديب فريزر، البوتاجازات، والتكييفات والمراوح والتصدير لأكثر من 60 دولة",
    city: "sharqia",
    governorate: "الشرقية",
    address: "المنطقة الصناعية الثالثة A3، العاشر من رمضان، الشرقية",
    phone1: "015418100",
    mobile: "01005599332",
    hotline: "19059",
    website: "https://www.fresh.com.eg",
    latitude: 30.3045,
    longitude: 31.7512,
    fleetSize: 240,
    fleetType: "أضخم أسطول شاحنات توزيع أجهزة منزلية مغلقة، سيارات صيانة متنقلة، وتريلات شحن صادرات للموانئ",
    fleetTires: "315/80R22.5 • 295/80R22.5 • 225/75R17.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "القلعة الصناعية الوطنية الأبرز والأوسع انتشاراً للأجهزة المنزلية بأسطول دعم فني ومبيعات متكامل",
    contactPerson: "نائب رئيس مجلس الإدارة لقطاعات الأسطول واللوجستيات",
    contactTitle: "Vice President - Fleet & Logistics Operations",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.3045,31.7512"
  },
  {
    id: "eg_titan_841",
    nameAr: "شركة بافاريا مصر لمعدات وأنظمة الإطفاء والسلامة (Bavaria Egypt)",
    nameEn: "Bavaria Egypt Fire Fighting Equipment & Trucks Manufacturing",
    sector: "manufacturing",
    subSector: "تصنيع أجهزة إطفاء الحريق، تجهيز سيارات الإطفاء للمطارات والمصانع، وشبكات الإنذار الآلي",
    city: "giza",
    governorate: "الجيزة",
    address: "مجمع بافاريا الصناعي، جسر السويس، عين شمس، القاهرة",
    phone1: "0221808000",
    mobile: "01007722119",
    hotline: "19997",
    website: "https://www.bavaria-firefighting.com",
    latitude: 30.1345,
    longitude: 31.3589,
    fleetSize: 110,
    fleetType: "شاحنات نقل وتوزيع أجهزة إطفاء، سيارات اختبار وفحص شبكات إطفاء، وتريلات صهاريج رغوي إطفاء",
    fleetTires: "315/80R22.5 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الصرح الألماني المصري المشترك الرائد في تجهيز سيارات الإطفاء ومعدات السلامة للمنشآت الحيوية والنفطية",
    contactPerson: "مدير عام الخدمات اللوجستية والأسطول الفني",
    contactTitle: "Technical Fleets & Logistics General Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.1345,31.3589"
  },
  {
    id: "eg_titan_842",
    nameAr: "شركة كابلات مصر (Egypt Cables - مجمع مجموعة البابطين الصناعي)",
    nameEn: "Egypt Cables (Al Babtain Industrial Group)",
    sector: "manufacturing",
    subSector: "تصنيع كابلات الجهد العالي والفائق وكابلات التليفونات والألياف الضوئية",
    city: "cairo",
    governorate: "القاهرة",
    address: "المنطقة الصناعية بأبو زعبل، الخانكة، القليوبية",
    phone1: "0133241100",
    mobile: "01009944662",
    hotline: "19839",
    website: "https://www.egypt-cables.com",
    latitude: 30.2489,
    longitude: 31.3612,
    fleetSize: 130,
    fleetType: "تريلات تريلا فرش حاملات بكر كابلات ثقيلة حمولة حتى 40 طن، أوناش هيدروليكية، وشاحنات سحب كابلات",
    fleetTires: "315/80R22.5 • 385/65R22.5 • 12.00R24",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "المورد المعتمد للمشروعات القومية لوزارة الكهرباء وشبكات الطاقة الشمسية بمصر والدول العربية",
    contactPerson: "مدير عام النقل الثقيل والمهمات الكهربائية",
    contactTitle: "Heavy Cargo & Electrical Fleets Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.2489,31.3612"
  },
  {
    id: "eg_titan_843",
    nameAr: "شركة الكابلات الكهربائية المصرية (ECE - مجمع مصانع مسطرد)",
    nameEn: "Egyptian Electric Cables Co. (ECE Mostorod Mega Complex)",
    sector: "manufacturing",
    subSector: "أقدم صرح لتصنيع كابلات الطاقة المعزولة، كابلات التحكم، والموصلات الهوائية غير المعزولة",
    city: "qalyubia",
    governorate: "القليوبية",
    address: "شارع ترعة الإسماعيلية، مسطرد، شبرا الخيمة، القليوبية",
    phone1: "0242200500",
    mobile: "01001166334",
    hotline: "19322",
    website: "https://www.ececables.com",
    latitude: 30.1389,
    longitude: 31.3089,
    fleetSize: 125,
    fleetType: "تريلات شحن كابلات بكر حديدي وخشب، شاحنات نقل خامات نحاس وألومنيوم وبوليمرات، وأوناش شوكية",
    fleetTires: "315/80R22.5 • 12.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الصرح الوطني التاريخي المؤسس لشبكات الكهرباء في مصر والشرق الأوسط منذ عام 1954",
    contactPerson: "رئيس قطاعات النقل والورش المركزية",
    contactTitle: "Central Workshops & Fleets Sector Head",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.1389,31.3089"
  },
  {
    id: "eg_titan_844",
    nameAr: "شركة السويدي للمحولات الكهربائية العملاقة (Elsewedy Power Transformers)",
    nameEn: "Elsewedy Power Transformers Mega Industrial Plants",
    sector: "manufacturing",
    subSector: "تصنيع محولات الطاقة الكهربائية العملاقة حتى جهد 500 ك.ف وقدرات 175 ميجافولت أمبير",
    city: "sharqia",
    governorate: "الشرقية",
    address: "المنطقة الصناعية الثالثة A3، العاشر من رمضان، الشرقية",
    phone1: "015419000",
    mobile: "01003388117",
    hotline: "16274",
    website: "https://www.elsewedyelectric.com/transformers",
    latitude: 30.3012,
    longitude: 31.7645,
    fleetSize: 140,
    fleetType: "مقطورات هيدروليكية ذات محاور متعددة (Multi-Axles) لنقل المحولات فائقة الوزن، أوناش عملاقة",
    fleetTires: "385/65R22.5 • 315/80R22.5 • 12.00R24",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "المصنع الأضخم في إفريقيا والشرق الأوسط المصدر لمحولات الربط الكهربائي بين مصر والسعودية وإفريقيا",
    contactPerson: "مدير عام النقل الثقيل والأحمال الاستثنائية",
    contactTitle: "Heavy Lift & Abnormal Loads General Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.3012,31.7645"
  },
  {
    id: "eg_titan_845",
    nameAr: "شركة إسكرا إميكو مصر لإنتاج العدادات الذكية (Iskraemeco Elsewedy)",
    nameEn: "Iskraemeco Egypt Smart Energy Meters (Elsewedy)",
    sector: "manufacturing",
    subSector: "تصنيع عدادات الكهرباء والمياه والغاز الذكية مسبوقة الدفع وأنظمة إدارة الشبكات",
    city: "giza",
    governorate: "الجيزة",
    address: "المنطقة الصناعية الرابعة، السادس من أكتوبر، الجيزة",
    phone1: "0238204500",
    mobile: "01005522776",
    hotline: "19448",
    website: "https://www.iskraemeco.com/eg",
    latitude: 29.9456,
    longitude: 30.9245,
    fleetSize: 90,
    fleetType: "شاحنات شحن إلكترونيات دقيقة مبردة ومجهزة، سيارات دعم فني واختبارات شبكات توزيع الكهرباء",
    fleetTires: "295/80R22.5 • 225/75R17.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "المورد القومي لملايين العدادات الذكية المطبقة بالمدن الجديدة وشركات توزيع الكهرباء المصرية",
    contactPerson: "مدير اللوجستيات والمستودعات المركزية",
    contactTitle: "Logistics & Central Stores Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.9456,30.9245"
  },
  {
    id: "eg_titan_846",
    nameAr: "شركة جنرال موتورز مصر لتجميع وتصنيع المركبات (GM Egypt)",
    nameEn: "General Motors Egypt (Chevrolet Mega Assembly Plant)",
    sector: "manufacturing",
    subSector: "أكبر مصنع لتجميع وتصنيع سيارات النقل التجاري والدبابة والجامبو والملاكي بمصر",
    city: "giza",
    governorate: "الجيزة",
    address: "المنطقة الصناعية الرابعة، السادس من أكتوبر، الجيزة",
    phone1: "0238280000",
    mobile: "01007744115",
    hotline: "19444",
    website: "https://www.gm.com/egypt",
    latitude: 29.9389,
    longitude: 30.9124,
    fleetSize: 220,
    fleetType: "تريلات حاملات سيارات لنقل الشاحنات المصنعة، تريلات نقل أجزاء هياكل ومحركات، وسيارات اختبار",
    fleetTires: "315/80R22.5 • 385/65R22.5 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الصرح الأول في صناعة وتجميع شاحنات النقل التجاري (شيفروليه الدبابة والجامبو) المتصدرة للسوق المصري",
    contactPerson: "مدير عام سلاسل الإمداد وشحن المركبات المصنعة",
    contactTitle: "Supply Chain & Vehicle Shipping Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.9389,30.9124"
  },
  {
    id: "eg_titan_847",
    nameAr: "شركة نيسان موتور إيجيبت لتصنيع السيارات (Nissan Motor Egypt)",
    nameEn: "Nissan Motor Egypt Assembly Plants (6th of October)",
    sector: "manufacturing",
    subSector: "مجمعات تجميع سيارات الركاب والشاحنات ونظم الطلاء والمعالجة الكهروستاتيكية",
    city: "giza",
    governorate: "الجيزة",
    address: "المنطقة الصناعية الأولى، السادس من أكتوبر، الجيزة",
    phone1: "0238285500",
    mobile: "01009966332",
    hotline: "16860",
    website: "https://www.nissan.com.eg",
    latitude: 29.9689,
    longitude: 30.9389,
    fleetSize: 150,
    fleetType: "تريلات حاملات سيارات حديثة ذات طابقين، شاحنات نقل مكونات إنتاج، وأساطيل نقل كوادر فنية",
    fleetTires: "315/80R22.5 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الاستثمار الياباني المباشر الأكبر في قطاع تصنيع وتجميع السيارات بجمهورية مصر العربية",
    contactPerson: "مدير الخدمات اللوجستية والشحن الميداني",
    contactTitle: "Logistics & Field Shipping Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.9689,30.9389"
  },
  {
    id: "eg_titan_848",
    nameAr: "مجموعة الأمل لتصنيع وتجميع السيارات (لادا وبي واي دي وكينج لونج)",
    nameEn: "Al Amal Auto Assembly & Manufacturing Group (BYD, Lada, King Long)",
    sector: "manufacturing",
    subSector: "مجمعات تجميع سيارات التاكسي القومي، الميكروباص، والسيارات الصديقة للبيئة بالغاز الطبيعي",
    city: "sharqia",
    governorate: "الشرقية",
    address: "المنطقة الصناعية B3، العاشر من رمضان، الشرقية",
    phone1: "015411700",
    mobile: "01002288554",
    hotline: "19633",
    website: "https://www.alamalauto.com",
    latitude: 30.3124,
    longitude: 31.7541,
    fleetSize: 160,
    fleetType: "تريلات حاملات سيارات وميكروباصات، شاحنات نقل هياكل ومحركات، وسيارات اختبار أداء",
    fleetTires: "315/80R22.5 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الشريك الرئيسي في المبادرة الرئاسية لإحلال وتجديد السيارات للعمل بالغاز الطبيعي في مصر",
    contactPerson: "رئيس قطاع التوزيع والشحن التجاري",
    contactTitle: "Commercial Shipping & Distribution Head",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.3124,31.7541"
  },
  {
    id: "eg_titan_849",
    nameAr: "شركة هاير مصر للإلكترونيات والأجهزة الكهربائية (Haier Egypt Eco-Park)",
    nameEn: "Haier Egypt Eco-Park Mega Industrial Complex (10th of Ramadan)",
    sector: "manufacturing",
    subSector: "المجمع الصناعي البيئي الذكي لتصنيع الشاشات، التكييفات، الغسالات، والثلاجات باستثمارات عملاقة",
    city: "sharqia",
    governorate: "الشرقية",
    address: "مجمع هاير إيكو بارك، المنطقة الصناعية الجنوبية، العاشر من رمضان",
    phone1: "015419800",
    mobile: "01004411776",
    hotline: "19016",
    website: "https://www.haier.com/eg",
    latitude: 30.2891,
    longitude: 31.7456,
    fleetSize: 175,
    fleetType: "شاحنات نقل أجهزة ذكية مغلقة، تريلات شحن صادرات للموانئ، وفانات صيانة وتوزيع متطورة",
    fleetTires: "315/80R22.5 • 295/80R22.5 • 225/75R17.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "أحدث وأضخم استثمار تكنولوجي صيني في مصر الحاصل على الرخصة الذهبية لتصنيع الأجهزة المنزلية والذكية",
    contactPerson: "مدير عام سلاسل الإمداد والخدمات اللوجستية الإقليمية",
    contactTitle: "Regional Supply Chain & Logistics General Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.2891,31.7456"
  },
  {
    id: "eg_titan_850",
    nameAr: "شركة ميديا مصر للأجهزة المنزلية والكهربائية (Midea Electric Egypt)",
    nameEn: "Midea Electric Egypt Mega Manufacturing Plants",
    sector: "manufacturing",
    subSector: "مجمعات تصنيع غسالات الأطباق وغسالات الملابس وأجهزة التكييف الموفرة للطاقة (إنفرتر)",
    city: "giza",
    governorate: "الجيزة",
    address: "المنطقة الصناعية بمجمع تيدا، السادس من أكتوبر، الجيزة",
    phone1: "0238241500",
    mobile: "01006633882",
    hotline: "19024",
    website: "https://www.midea.com/eg",
    latitude: 29.9345,
    longitude: 30.9124,
    fleetSize: 140,
    fleetType: "شاحنات شحن أجهزة كهربائية، تريلات نقل حاويات تصدير، وفانات دعم فني للمستهلكين",
    fleetTires: "315/80R22.5 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "المجمع الصناعي التكنولوجي الأول لمجموعة ميديا العالمية لتصدير الأجهزة المنزلية لإفريقيا وأوروبا",
    contactPerson: "رئيس قطاع النقل والمستودعات الإقليمية",
    contactTitle: "Regional Warehouses & Transport Head",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.9345,30.9124"
  }
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { wave7Part3 };
}
