/**
 * scripts/wave6_data_part5.js
 * Part 5 of Wave 6 Titans (eg_titan_631 to eg_titan_665) - 35 Industrial Titans.
 * Sectors: Sanitaryware, Machinery, Military Factories, Automotive Assembly & Shipyards & Contracting.
 */

const wave6Part5 = [
  // 7. Sanitaryware, Pipes, Machinery & Automotive Assembly (20)
  {
    id: "eg_titan_631",
    nameAr: "شركة ليسيكو للصناعات الخزفية والسباكة والبورسلين (خورشيد وبرج العرب)",
    nameEn: "Lecico Egypt for Ceramic Sanitaryware & Tiles (Alexandria)",
    sector: "building_materials",
    subSector: "أكبر مصنع ومصدر للأطقم الصحية الخزفية وخلاطات المياه وبلاط السيراميك في الشرق الأوسط وأوروبا",
    city: "alexandria",
    governorate: "الإسكندرية",
    address: "منطقة خورشيد، كرموز، الإسكندرية / مجمع مصانع برج العرب الجديدة",
    phone1: "035170000",
    mobile: "01001188339",
    hotline: "16231",
    website: "https://www.lecico.com",
    latitude: 31.1512,
    longitude: 30.0145,
    fleetSize: 130,
    fleetType: "تريلات تريلا لنقل الخامات الطينية والفلسبار، شاحنات شحن أطقم صحية للموانئ، وفانات توزيع",
    fleetTires: "315/80R22.5 • 385/65R22.5 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "عملاق الصناعات الخزفية المصري الرائد المصدر لأكثر من 50 دولة بأسطول شحن ثقيل مباشر للموانئ والمعارض",
    contactPerson: "مدير عام النقل والخدمات اللوجستية المركزية",
    contactTitle: "Central Logistics & Fleet Transport Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=31.1512,30.0145"
  },
  {
    id: "eg_titan_632",
    nameAr: "شركة إيديال ستاندرد مصر للأدوات الصحية وخلاطات المياه (العاشر من رمضان)",
    nameEn: "Ideal Standard International Egypt (10th of Ramadan)",
    sector: "manufacturing",
    subSector: "تصنيع أطقم الحمامات الفاخرة وخلاطات المياه النحاسية والبانيوهات الأكريليك وفق تكنولوجيا ألمانية",
    city: "sharqia",
    governorate: "الشرقية",
    address: "المنطقة الصناعية A1، مدينة العاشر من رمضان، محافظة الشرقية",
    phone1: "015411000",
    mobile: "01224488117",
    hotline: "16232",
    website: "https://www.idealstandard.com.eg",
    latitude: 30.3045,
    longitude: 31.7412,
    fleetSize: 90,
    fleetType: "شاحنات نقل مغلقة، تريلات شحن كراتين، فانات توزيع معارض، وأسطول حافلات ركاب",
    fleetTires: "315/80R22.5 • 295/80R22.5 • 225/75R17.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الصرح العالمي لتصنيع الأدوات الصحية بالعاشر من رمضان بأسطول شحن وتوزيع نشط في جميع محافظات مصر",
    contactPerson: "مدير العمليات اللوجستية والنقل",
    contactTitle: "Logistics Operations & Transport Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.3045,31.7412"
  },
  {
    id: "eg_titan_633",
    nameAr: "الشركة المصرية لصناعة مواسير الفخار والحراريات (التبين - حلوان)",
    nameEn: "Egyptian Clay Pipes & Refractories Manufacturing Co. (Helwan)",
    sector: "building_materials",
    subSector: "تصنيع مواسير الفخار المزجج لشبكات الصرف الصحي والحراريات لمصانع الصلب والأسمنت",
    city: "helwan",
    governorate: "القاهرة",
    address: "طريق كورنيش النيل، التبين، حلوان، القاهرة",
    phone1: "0225011400",
    mobile: "01115544118",
    hotline: "16233",
    website: "https://www.claypipes.com.eg",
    latitude: 29.7712,
    longitude: 31.3089,
    fleetSize: 75,
    fleetType: "تريلات تريلا مسطحة لنقل المواسير الضخمة، شاحنات حراريات، لوادر، وأتوبيسات ركاب",
    fleetTires: "12.00R24 • 315/80R22.5 • 12.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "المورد المعتمد لمواسير الفخار المقاومة للأحماض لمشروعات حياة كريمة والصرف الصحي القومي",
    contactPerson: "مدير حركة الأسطول والمشروعات الميدانية",
    contactTitle: "Fleet Movement & Field Projects Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.7712,31.3089"
  },
  {
    id: "eg_titan_634",
    nameAr: "شركة مصر لصناعة الزجاج الدوائي وزجاج العبوات (العاشر من رمضان)",
    nameEn: "Misr for Pharmaceutical Glass & Container Manufacturing (MEG)",
    sector: "manufacturing",
    subSector: "تصنيع زجاجات الأدوية والأمبولات المعقمة والعبوات الزجاجية للصناعات الغذائية والمشروبات",
    city: "sharqia",
    governorate: "الشرقية",
    address: "المنطقة الصناعية B1، مدينة العاشر من رمضان، الشرقية",
    phone1: "015412100",
    mobile: "01007744338",
    hotline: "16234",
    website: "https://www.meg-glass.com",
    latitude: 30.2912,
    longitude: 31.7612,
    fleetSize: 80,
    fleetType: "تريلات نقل رمال بيضاء وصودا، شاحنات نقل عبوات زجاجية لمصانع الأدوية، وحافلات ركاب",
    fleetTires: "315/80R22.5 • 295/80R22.5 • 12.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "أكبر منتج للزجاج الدوائي والغذائي في مصر التابع لمجموعة مصر لصناعة الزجاج بأسطول شحن ضخم",
    contactPerson: "مدير عام النقل واللوجستيات",
    contactTitle: "General Transport & Logistics Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.2912,31.7612"
  },
  {
    id: "eg_titan_635",
    nameAr: "شركة قها للصناعات الكيماوية وتجهيز العبوات (مصنع 270 الحربي)",
    nameEn: "Qaha Chemicals & Industrial Packaging (Military Factory 270)",
    sector: "manufacturing",
    subSector: "تصنيع العبوات المعدنية والبراميل والكيماويات وبطاريات السيارات والأجهزة الكهربائية",
    city: "qalyubia",
    governorate: "القليوبية",
    address: "طريق مصر إسكندرية الزراعي، قها، محافظة القليوبية",
    phone1: "0132561200",
    mobile: "01228811335",
    hotline: "16235",
    website: "https://www.fact270.momp.gov.eg",
    latitude: 30.2812,
    longitude: 31.2045,
    fleetSize: 70,
    fleetType: "شاحنات نقل منتجات معدنية، تريلات براميل صلب، شاحنات شحن، وأتوبيسات ركاب",
    fleetTires: "315/80R22.5 • 295/80R22.5 • 11.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "مصنع حربي متطور بمدينة قها بالقليوبية ينتج العبوات المعدنية وبطاريات السيارات المعتمدة",
    contactPerson: "مدير إدارة النقل والورش",
    contactTitle: "Transport & Workshops Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.2812,31.2045"
  },
  {
    id: "eg_titan_636",
    nameAr: "شركة حلوان للمسبوكات ومسبوكات الزهر الثقيل (مصنع 9 الحربي)",
    nameEn: "Helwan Castings & Heavy Foundry Co. (Military Factory 9)",
    sector: "manufacturing",
    subSector: "مسبوكات الزهر الرمادي والمرن والصلب، قواعد الماكينات، وأغطية بالوعات الصرف الصحي المعتمدة",
    city: "helwan",
    governorate: "القاهرة",
    address: "طريق كورنيش النيل، حلوان، محافظة القاهرة",
    phone1: "0225561400",
    mobile: "01114488339",
    hotline: "16236",
    website: "https://www.fact9.momp.gov.eg",
    latitude: 29.8412,
    longitude: 31.3012,
    fleetSize: 85,
    fleetType: "شاحنات نقل مسبوكات ثقيلة، تريلات خردة صلب، روافع شوكية عملاقة، وأتوبيسات ركاب",
    fleetTires: "12.00R24 • 315/80R22.5 • 12.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "قلعة مسبوكات الزهر والحديد الكبرى في الشرق الأوسط الموردة لمشروعات البنية التحتية القومية",
    contactPerson: "مدير الحركة والنقل الميكانيكي",
    contactTitle: "Mechanical Transport Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.8412,31.3012"
  },
  {
    id: "eg_titan_637",
    nameAr: "شركة شبرا للصناعات الهندسية والمحركات (مصنع 27 الحربي)",
    nameEn: "Shoubra Engineering Industries & Electric Motors (Military Factory 27)",
    sector: "manufacturing",
    subSector: "تصنيع المحركات الكهربائية الصناعية، المراوح، الطلمبات، والسباكة الدقيقة للسبائك النحاسية",
    city: "qalyubia",
    governorate: "القليوبية",
    address: "شبرا الخيمة، محافظة القليوبية",
    phone1: "0242204100",
    mobile: "01003366995",
    hotline: "16237",
    website: "https://www.fact27.momp.gov.eg",
    latitude: 30.1212,
    longitude: 31.2589,
    fleetSize: 65,
    fleetType: "شاحنات شحن محركات ومعدات، فانات صيانة، وأتوبيسات نقل مهندسين وعمال",
    fleetTires: "295/80R22.5 • 225/75R17.5 • 11.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الصرح الرائد في تصنيع المحركات الكهربائية المعتمدة للمصانع والورش والري الزراعي",
    contactPerson: "مدير النقل والمهمات",
    contactTitle: "Transport & Logistics Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.1212,31.2589"
  },
  {
    id: "eg_titan_638",
    nameAr: "شركة المعادي للصناعات الهندسية وتصنيع المعدات (مصنع 54 الحربي)",
    nameEn: "Maadi Engineering Industries & Medical Equipment (Military Factory 54)",
    sector: "manufacturing",
    subSector: "تصنيع الآلات والمعدات الميكانيكية، التجهيزات الطبية والعيادات المتنقلة، وقطع غيار المصانع",
    city: "cairo",
    governorate: "القاهرة",
    address: "شارع كورنيش النيل، المعادي، القاهرة",
    phone1: "0223581200",
    mobile: "01227711448",
    hotline: "16238",
    website: "https://www.fact54.momp.gov.eg",
    latitude: 29.9612,
    longitude: 31.2512,
    fleetSize: 60,
    fleetType: "شاحنات شحن تجهيزات ومعدات طبية، فانات صيانة، وأتوبيسات ركاب",
    fleetTires: "295/80R22.5 • 225/75R17.5 • 8.25R16",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "مصنع هندسي وتكنولوجي عريق بالمعادي يقوم بتجهيز المستشفيات الميدانية والسيارات الطبية",
    contactPerson: "مدير إدارة الحركة والسيارات",
    contactTitle: "Automotive & Transport Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.9612,31.2512"
  },
  {
    id: "eg_titan_639",
    nameAr: "شركة أبو زعبل للكيماويات المتخصصة وإنتاج الصودا (مصنع 18 الحربي)",
    nameEn: "Abu Zaabal Specialized Chemicals & Acids (Military Factory 18)",
    sector: "manufacturing",
    subSector: "إنتاج النيتروسيليلوز، البارود الصناعي، الأحماض الكيماوية المركزة، والمواد الرابطة للدهانات",
    city: "qalyubia",
    governorate: "القليوبية",
    address: "منطقة أبو زعبل الصناعية، الخانكة، محافظة القليوبية",
    phone1: "0246201200",
    mobile: "01118833559",
    hotline: "16239",
    website: "https://www.fact18.momp.gov.eg",
    latitude: 30.2412,
    longitude: 31.3612,
    fleetSize: 85,
    fleetType: "شاحنات نقل مواد خطرة مجهزة ومصفحة، صهاريج أحماض ستانلس ستيل، وأتوبيسات عمال",
    fleetTires: "315/80R22.5 • 295/80R22.5 • 12.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "القلعة الكيماوية العسكرية والصناعية بأبو زعبل بأسطول نقل معتمد بأعلى معايير السلامة والأمان لنقل الكيماويات",
    contactPerson: "رئيس قطاع النقل والسلامة الكيماوية",
    contactTitle: "Safety & Chemical Fleet Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.2412,31.3612"
  },
  {
    id: "eg_titan_640",
    nameAr: "شركة أبو قير للصناعات الهندسية والمهمات (طابية رشيد - الإسكندرية)",
    nameEn: "Abu Qir Engineering Industries & Can-Making (Military Factory 10)",
    sector: "manufacturing",
    subSector: "تصنيع عبوات الصفيح والألومنيوم للأغذية والزيوت وعلب الأيروسول والمهمات الميكانيكية",
    city: "alexandria",
    governorate: "الإسكندرية",
    address: "منطقة طابية رشيد، خليج أبو قير، الإسكندرية",
    phone1: "035612100",
    mobile: "01004499881",
    hotline: "16240",
    website: "https://www.fact10.momp.gov.eg",
    latitude: 31.3212,
    longitude: 30.0789,
    fleetSize: 70,
    fleetType: "شاحنات نقل عبوات معدنية مجهزة، تريلات صفيح، وأتوبيسات نقل عاملين",
    fleetTires: "315/80R22.5 • 295/80R22.5 • 11.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الصرح المتخصص في تصنيع عبوات الصفيح التصديرية والأيروسول لشركات الأغذية والدهانات في مصر",
    contactPerson: "مدير حركة النقل والتوزيع",
    contactTitle: "Transport Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=31.3212,30.0789"
  },
  {
    id: "eg_titan_641",
    nameAr: "الشركة المصرية للصهاريج وخزانات الوقود الضخمة (العاشر من رمضان)",
    nameEn: "Egyptian Tanks & Heavy Pressure Vessels Co. (10th of Ramadan)",
    sector: "manufacturing",
    subSector: "تصنيع صهاريج نقل الوقود والغاز المسال والمواد الكيماوية وخزانات المستودعات البترولية العملاقة",
    city: "sharqia",
    governorate: "الشرقية",
    address: "المنطقة الصناعية A3، العاشر من رمضان، محافظة الشرقية",
    phone1: "015413100",
    mobile: "01223377114",
    hotline: "16241",
    website: "https://www.egyptiantanks.com",
    latitude: 30.3189,
    longitude: 31.7345,
    fleetSize: 60,
    fleetType: "تريلات تريلا لوابد نقل صهاريج وخزانات عملاقة، شاحنات أوناش، وأتوبيسات ركاب",
    fleetTires: "12.00R24 • 315/80R22.5 • 385/65R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "المصنع الرائد في تزويد شركات البترول بشاحنات الصهاريج والخزانات المطابقة لمواصفات ADR العالمية",
    contactPerson: "مدير الشحن والتركيبات الخارجية",
    contactTitle: "Outbound Logistics & Heavy Transport Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.3189,31.7345"
  },
  {
    id: "eg_titan_642",
    nameAr: "شركة إيماك لتصنيع مواسير الخرسانة سابقة الإجهاد لخطوط المياه (6 أكتوبر)",
    nameEn: "EMAC Pre-stressed Concrete Pipes & Water Transmission (6th of October)",
    sector: "construction",
    subSector: "تصنيع مواسير الخرسانة سابقة الإجهاد ذات الأسطوانة الصلبة (PCCP) لخطوط نقل مياه الشرب والري القومية",
    city: "giza",
    governorate: "الجيزة",
    address: "المنطقة الصناعية السادسة، مدينة السادس من أكتوبر، الجيزة",
    phone1: "0238312500",
    mobile: "01115599338",
    hotline: "16242",
    website: "https://www.emacpipes.com",
    latitude: 29.8912,
    longitude: 30.8789,
    fleetSize: 85,
    fleetType: "تريلات تريلا لوابد نقل مواسير أقطار عملاقة (تصل 3000 مم)، أوناش هيدروليكية، وحافلات ركاب",
    fleetTires: "12.00R24 • 315/80R22.5 • 385/65R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الشركة الرائدة في تزويد المشروعات القومية بمواسير نقل المياه العملاقة لسيناء والدلتا الجديدة",
    contactPerson: "مدير عام النقل الثقيل واللوجستيات الهندسية",
    contactTitle: "Heavy Logistics & Engineering Transport Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.8912,30.8789"
  },
  {
    id: "eg_titan_643",
    nameAr: "مصانع الراجحي لتصنيع الهياكل الحديدية والخزانات (مدينة السادات)",
    nameEn: "Al Rajhi Heavy Steel Structures & Storage Tanks (Sadat City)",
    sector: "manufacturing",
    subSector: "تصنيع الجمالونات، الكباري الفولاذية، الهياكل المعدنية لمصانع الأسمنت، وصوامع الحبوب",
    city: "menofia",
    governorate: "المنوفية",
    address: "المنطقة الصناعية السابعة، مدينة السادات، المنوفية",
    phone1: "0482617200",
    mobile: "01008822117",
    hotline: "16243",
    website: "https://www.alrajhisteel.com.eg",
    latitude: 30.3712,
    longitude: 30.5212,
    fleetSize: 75,
    fleetType: "تريلات تريلا لوابد تلسكوبية لنقل الكمرات الفولاذية الطويلة، أوناش شوكية، وحافلات ورديات",
    fleetTires: "12.00R24 • 315/80R22.5 • 385/65R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "مجمع صناعي رائد في الهياكل المعدنية الثقيلة بمدينة السادات يمتلك أسطول شاحنات لوابد نقل أطوال غير قياسية",
    contactPerson: "مدير إدارة الحركة والشحن الهندسي",
    contactTitle: "Project Haulage & Logistics Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.3712,30.5212"
  },
  {
    id: "eg_titan_644",
    nameAr: "شركة أكوا فليكس لتصنيع لوازم المواسير والبولي إيثيلين (مدينة بدر الصناعية)",
    nameEn: "Aqua Flex for HDPE Pipes & Industrial Fittings (Badr City)",
    sector: "manufacturing",
    subSector: "تصنيع مواسير البولي إيثيلين عالي الكثافة (HDPE) لخطوط الغاز ومياه الشرب والري الحديث",
    city: "cairo",
    governorate: "القاهرة",
    address: "المنطقة الصناعية الثالثة، مدينة بدر، محافظة القاهرة",
    phone1: "0228609100",
    mobile: "01229944773",
    hotline: "16244",
    website: "https://www.aquaflexegypt.com",
    latitude: 30.1289,
    longitude: 31.7289,
    fleetSize: 60,
    fleetType: "تريلات شحن رولات ومواسير بلاستيك، شاحنات بضائع، وأتوبيسات ركاب",
    fleetTires: "315/80R22.5 • 295/80R22.5 • 11.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "مصنع معتمد من الهيئة القومية لمياه الشرب لتوريد شبكات البولي إيثيلين بالمدن الجديدة",
    contactPerson: "مدير حركة النقل",
    contactTitle: "Transport Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.1289,31.7289"
  },
  {
    id: "eg_titan_645",
    nameAr: "مجموعة ميكار للصناعات المعدنية وهياكل الشاحنات (العاشر من رمضان)",
    nameEn: "Mecar Heavy Metal Industries & Truck Bodyworks (10th of Ramadan)",
    sector: "manufacturing",
    subSector: "تصنيع وتجميع مقطورات التريلات، القلابات، الصهاريج، وهياكل الشاحنات التجارية المتطورة",
    city: "sharqia",
    governorate: "الشرقية",
    address: "المنطقة الصناعية A4، مدينة العاشر من رمضان، الشرقية",
    phone1: "015414500",
    mobile: "01113388226",
    hotline: "16245",
    website: "https://www.mecargroup.com",
    latitude: 30.3012,
    longitude: 31.7589,
    fleetSize: 70,
    fleetType: "تريلات سحب واختبار شاسيهات مقطورات، شاحنات صيانة، وأتوبيسات نقل فنيين ومهندسين",
    fleetTires: "385/65R22.5 • 315/80R22.5 • 12.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الصرح الرائد في تصنيع مقطورات النقل الثقيل والقلابات التجارية بمصر ويعد مركزاً رئيسياً لاستهلاك الإطارات",
    contactPerson: "مدير الإنتاج والتشغيل والاختبارات",
    contactTitle: "Production & Fleet Testing Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.3012,31.7589"
  },
  {
    id: "eg_titan_646",
    nameAr: "الشركة المصرية لتصنيع طلمبات المياه والمحركات الكبرى (حلوان)",
    nameEn: "Egyptian Water Pumps & Heavy Motors Manufacturing (Helwan)",
    sector: "manufacturing",
    subSector: "تصنيع طلمبات الرفع العملاقة لمحطات معالجة مياه الصرف ومحطات الري وترع توشكى ومستقبل مصر",
    city: "helwan",
    governorate: "القاهرة",
    address: "طريق حلوان الزراعي، التبين، القاهرة",
    phone1: "0225562100",
    mobile: "01007711994",
    hotline: "16246",
    website: "https://www.egyptpumps.com",
    latitude: 29.8212,
    longitude: 31.3145,
    fleetSize: 65,
    fleetType: "شاحنات نقل طلمبات ومحركات ثقيلة، تريلات لوابد، وسيارات خدمة محطات المياه الميدانية",
    fleetTires: "315/80R22.5 • 295/80R22.5 • 12.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الشركة المتخصصة في توريد محطات الطلمبات العملاقة لمشروعات الري واستصلاح الأراضي القومية",
    contactPerson: "مدير الحركة والنقل الميداني للمشروعات",
    contactTitle: "Project Fleet & Field Haulage Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.8212,31.3145"
  },
  {
    id: "eg_titan_647",
    nameAr: "شركة مصر لتجفيف الحاصلات والمجففات الصناعية (سوهاج والإسكندرية)",
    nameEn: "Misr for Crops Dehydration & Industrial Dryers (Sohag & Alex)",
    sector: "food",
    subSector: "تجفيف البصل والثوم والخضروات العطرية وتصديرها لمصانع الشوربة والتوابل في أوروبا وأمريكا",
    city: "sohag",
    governorate: "سوهاج",
    address: "المنطقة الصناعية بالكوثر، سوهاج / مكاتب الإسكندرية والقاهرة",
    phone1: "0932281200",
    mobile: "01224433992",
    hotline: "16247",
    website: "https://www.misrdehydration.com",
    latitude: 26.5412,
    longitude: 31.7889,
    fleetSize: 60,
    fleetType: "شاحنات نقل بصل وثوم من الحقول، تريلات حاويات تصدير لميناء الإسكندرية، وأتوبيسات ركاب",
    fleetTires: "315/80R22.5 • 295/80R22.5 • 11.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "أكبر مصدر للبصل والثوم المجفف في صعيد مصر بأسطول شحن مباشر لموانئ البحر المتوسط",
    contactPerson: "مدير النقل والتشغيل الزراعي",
    contactTitle: "Agro-Logistics Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=26.5412,31.7889"
  },
  {
    id: "eg_titan_648",
    nameAr: "شركة سيكو للصناعات الإلكترونية وتجميع الأجهزة (أسيوط الجديدة)",
    nameEn: "SICO Technology - Smartphone & Electronics Mega Complex (New Assiut)",
    sector: "manufacturing",
    subSector: "أول مصنع في مصر والشرق الأوسط لإنتاج الهواتف الذكية وأجهزة التابلت والشاشات الذكية",
    city: "assiut",
    governorate: "أسيوط",
    address: "المنطقة التكنولوجية (واحات السيليكون)، مدينة أسيوط الجديدة، أسيوط",
    phone1: "0882391500",
    mobile: "01112277884",
    hotline: "16248",
    website: "https://www.sico.com.eg",
    latitude: 27.2112,
    longitude: 31.3112,
    fleetSize: 55,
    fleetType: "فانات شحن إلكترونيات مؤمنة، سيارات نقل بضائع مغلقة، وحافلات ركاب مكيفة لنقل المهندسين",
    fleetTires: "225/75R17.5 • 295/80R22.5 • 8.25R16",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "مجمع الإلكترونيات والتكنولوجيا الرائد بالصعيد بأسطول توزيع يغطي كافة معارض ومراكز صيانة المحافظات",
    contactPerson: "مدير العمليات اللوجستية والتوزيع",
    contactTitle: "Logistics & Distribution Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=27.2112,31.3112"
  },
  {
    id: "eg_titan_649",
    nameAr: "شركة الأمل لتصنيع وتجميع سيارات BYD ولادا (العاشر من رمضان والخانكة)",
    nameEn: "Al Amal Auto Manufacturing (BYD & Lada Assembly Plants)",
    sector: "manufacturing",
    subSector: "تجميع وتصنيع سيارات الركوب وسيارات التاكسي والغاز الطبيعي والميكروباصات بمصر",
    city: "sharqia",
    governorate: "الشرقية",
    address: "المنطقة الصناعية B4، العاشر من رمضان / مجمع مصانع أبو زعبل بالخانكة",
    phone1: "015411800",
    mobile: "01002288447",
    hotline: "16249",
    website: "https://www.alamalauto.com",
    latitude: 30.2889,
    longitude: 31.7512,
    fleetSize: 85,
    fleetType: "تريلات لوابد شحن سيارات (كاريير سيارات متعدد الطوابق)، شاحنات نقل شاسيهات ومكونات، وحافلات عمال",
    fleetTires: "315/80R22.5 • 295/80R22.5 • 245/70R19.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "المصنع الرائد لسيارات التاكسي والغاز الطبيعي بمصر مع أسطول ناقلات سيارات متطور لتسليم المعارض",
    contactPerson: "مدير عام النقل وناقلات السيارات",
    contactTitle: "Vehicle Carrier Fleet & Transport Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.2889,31.7512"
  },
  {
    id: "eg_titan_650",
    nameAr: "شركة فريش إليكتريك لمسبوكات الأفران والأجهزة (العاشر من رمضان)",
    nameEn: "Fresh Electric - Castings & Heavy Cooking Appliances Mega Plant",
    sector: "manufacturing",
    subSector: "مسبوكات أفران البوتاجاز ومحابس الغاز والمكونات المعدنية للأجهزة المنزلية",
    city: "sharqia",
    governorate: "الشرقية",
    address: "المنطقة الصناعية A2، مدينة العاشر من رمضان، الشرقية",
    phone1: "015412800",
    mobile: "01221199338",
    hotline: "16250",
    website: "https://www.fresh.com.eg",
    latitude: 30.3112,
    longitude: 31.7412,
    fleetSize: 95,
    fleetType: "تريلات شحن أجهزة بوتاجاز وغسالات، شاحنات توزيع معارض، وأسطول حافلات ورديات",
    fleetTires: "315/80R22.5 • 295/80R22.5 • 225/75R17.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "أكبر مصنع متخصص في تصنيع البوتاجازات والأجهزة المنزلية الموجهة للأسواق الإفريقية والعربية",
    contactPerson: "مدير عام الأسطول وسلاسل الإمداد",
    contactTitle: "Supply Chain & Fleet Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.3112,31.7412"
  },

  // 8. Shipyards, Dredging & Mega Contracting (15)
  {
    id: "eg_titan_651",
    nameAr: "شركة ترسانة الإسكندرية البحرية (بناء وصيانة السفن وأحواض الترسانة الكبرى)",
    nameEn: "Alexandria Shipyard (ASY - Mega Drydocks & Shipbuilding)",
    sector: "construction",
    subSector: "بناء وإصلاح السفن الحربية والتجارية، ناقلات النفط، الحفارات البحرية، والأحواض العائمة والجافة",
    city: "alexandria",
    governorate: "الإسكندرية",
    address: "باب 36، ميناء الإسكندرية الغربي، رأس التين، الإسكندرية",
    phone1: "034453090",
    mobile: "01115588226",
    hotline: "16251",
    website: "https://www.alexshipyard.com.eg",
    latitude: 31.1912,
    longitude: 29.8645,
    fleetSize: 120,
    fleetType: "أوناش رصيف عملاقة حمولات 300 طن، لوابد نقل ألواح الصلب البحري، شاحنات صيانة، وأتوبيسات مهندسين",
    fleetTires: "12.00R24 • 14.00R24 • 315/80R22.5 • 18.00R25",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "أكبر ترسانة بناء وإصلاح سفن في جنوب المتوسط تمتلك أحواضاً جافة تتسع لسفن حتى 85,000 طن بأسطول معدات ثقيل ضخم",
    contactPerson: "رئيس قطاع النقل والمهمات الثقيلة والأوناش",
    contactTitle: "Head of Heavy Haulage, Cranes & Shipyard Fleet",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=31.1912,29.8645"
  },
  {
    id: "eg_titan_652",
    nameAr: "شركة التمساح لبناء السفن والقاطرات البحرية (الإسماعيلية وبورسعيد)",
    nameEn: "Timsah Shipbuilding Co. (SCA Subsidiary - Ismailia & Port Said)",
    sector: "construction",
    subSector: "بناء قاطرات الإنقاذ البحري، سفن الإمداد والتموين لمنصات البترول، ولنشات الإرشاد بقناة السويس",
    city: "ismailia",
    governorate: "الإسماعيلية",
    address: "شارع الورش البحرية، الإسماعيلية / ترسانة بورسعيد",
    phone1: "0643912100",
    mobile: "01003399115",
    hotline: "16252",
    website: "https://www.timsahship.com",
    latitude: 30.5912,
    longitude: 32.2789,
    fleetSize: 85,
    fleetType: "روافع شوكية وأوناش هيدروليكية، شاحنات نقل معدات بحرية، لوابد نقل قطع، وأتوبيسات ركاب",
    fleetTires: "12.00R24 • 315/80R22.5 • 11.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "إحدى كبرى شركات هيئة قناة السويس المتخصصة في بناء وتجهيز أساطيل القاطرات البحرية المتطورة",
    contactPerson: "مدير عام الورش والحركة الميكانيكية",
    contactTitle: "Workshops & Mechanical Fleet Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.5912,32.2789"
  },
  {
    id: "eg_titan_653",
    nameAr: "شركة القناة للموانئ والمشاريع الكبرى والإنشاءات البحرية (السويس)",
    nameEn: "Canal Harbour Works Co. (SCA Subsidiary - Suez)",
    sector: "construction",
    subSector: "إنشاء الأرصفة البحرية، حواجز الأمواج، مآخذ مياه التبريد لمحطات الكهرباء، والكباري العائمة",
    city: "suez",
    governorate: "السويس",
    address: "شارع بورسعيد، السويس / مكاتب الإسماعيلية والإسكندرية",
    phone1: "0623334100",
    mobile: "01227788993",
    hotline: "16253",
    website: "https://www.canalharbour.com",
    latitude: 29.9712,
    longitude: 32.5512,
    fleetSize: 105,
    fleetType: "أوناش بحرية وبرية عملاقة، قلابات نقل صخور الحواجز، خفارات، تريلات نقل معدات، وأتوبيسات",
    fleetTires: "12.00R24 • 315/80R22.5 • 14.00R24",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الذراع الهندسي البحري الرائد لهيئة قناة السويس لتطوير موانئ مصر وإنشاء الأرصفة البحرية الاستراتيجية",
    contactPerson: "مدير عام المعدات البحرية والأسطول البري",
    contactTitle: "Marine Equipment & Land Fleet Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.9712,32.5512"
  },
  {
    id: "eg_titan_654",
    nameAr: "شركة القناة لأعمال الموانئ والتكريك البحري (الإسماعيلية)",
    nameEn: "Canal Marine Dredging & Port Services Co. (Ismailia)",
    sector: "construction",
    subSector: "تكريك وتعميق الممرات الملاحية وأحواض الموانئ وتطهير البحيرات المصرية بالشرقية والإسكندرية",
    city: "ismailia",
    governorate: "الإسماعيلية",
    address: "شارع النجدة، الإسماعيلية / محطات التكريك ببحيرة البردويل وبحيرة قارون",
    phone1: "0643921500",
    mobile: "01114477112",
    hotline: "16254",
    website: "https://www.canaldredging.com",
    latitude: 30.6012,
    longitude: 32.2689,
    fleetSize: 90,
    fleetType: "كراكات ماصة طاردة، خطوط أنابيب تكريك صلب، شاحنات دعم ونقل مهمات، وسيارات 4x4",
    fleetTires: "12.00R24 • 315/80R22.5 • 245/75R16",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الصرح الوطني المتخصص في التكريك وتعميق الموانئ والمشاريع المائية الكبرى",
    contactPerson: "مدير العمليات البحرية والأسطول",
    contactTitle: "Marine Operations & Fleet Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.6012,32.2689"
  },
  {
    id: "eg_titan_655",
    nameAr: "شركة الترسانة النهرية ومصانع تجميع الصنادل (مصر القديمة وحلوان)",
    nameEn: "Nile Shipyard & River Barge Fabrication (Old Cairo & Helwan)",
    sector: "construction",
    subSector: "بناء وصيانة صنادل النقل النهري، العائمات السياحية الفاخرة، ومعديات نقل الركاب والسيارات عبر النيل",
    city: "cairo",
    governorate: "القاهرة",
    address: "أثر النبي، مصر القديمة، القاهرة / ورش كفر العلو بحلوان",
    phone1: "0223651200",
    mobile: "01002244883",
    hotline: "16255",
    website: "https://www.nileshipyard.com.eg",
    latitude: 29.9889,
    longitude: 31.2312,
    fleetSize: 65,
    fleetType: "أوناش سحب عائمات، شاحنات نقل صاج ومعدات تقطيع، فانات صيانة، وأتوبيسات نقل مهندسين",
    fleetTires: "12.00R20 • 315/80R22.5 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "أكبر ترسانة لبناء وصيانة الصنادل النهرية والفنادق العائمة على نهر النيل بأسطول معدات ورش ثقيل",
    contactPerson: "مدير الورش والأسطول الميكانيكي",
    contactTitle: "Mechanical Fleet & Shipyard Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.9889,31.2312"
  },
  {
    id: "eg_titan_656",
    nameAr: "مجموعة الغرابلي للأعمال الهندسية المتكاملة والموانئ (الإسكندرية)",
    nameEn: "El Ghorabely Integrated Engineering & Marine Contracting (Alexandria)",
    sector: "construction",
    subSector: "المقاول الرئيسي لمشروعات توسعات ميناء الإسكندرية الكبير، ميناء أبو قير الجديد، ومحطات الحاويات",
    city: "alexandria",
    governorate: "الإسكندرية",
    address: "طريق الجيش، جليم، الإسكندرية / مواقع ميناء أبو قير والدخيلة",
    phone1: "035841200",
    mobile: "01228833114",
    hotline: "16256",
    website: "https://www.ghorabely.com",
    latitude: 31.2412,
    longitude: 29.9689,
    fleetSize: 160,
    fleetType: "أوناش بحرية وبرية ضخمة، قلابات نقل صخور ردم الموانئ (مان وفولفو 4 أكسات)، حفارات عملاقة، وأتوبيسات",
    fleetTires: "12.00R24 • 14.00R24 • 315/80R22.5 • 13R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "العملاق الهندسي المنفذ لأضخم توسعات بحرية وموانئ على البحر المتوسط في ميناء أبو قير وميناء الإسكندرية الكبير",
    contactPerson: "نائب رئيس مجلس الإدارة للأسطول والمعدات الثقيلة",
    contactTitle: "VP of Heavy Plant & Fleet Machinery",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=31.2412,29.9689"
  },
  {
    id: "eg_titan_657",
    nameAr: "شركة الحاذق للإنشاءات والمقاولات المتخصصة (القاهرة الكبرى)",
    nameEn: "Al Hazek Construction - Mega Commercial & Infrastructure Projects",
    sector: "construction",
    subSector: "إنشاء الأبراج السكنية والتجارية الكبرى، المستشفيات، ومجمعات الجامعات بالعاصمة الإدارية والتجمع",
    city: "cairo",
    governorate: "القاهرة",
    address: "التجمع الخامس، القاهرة الجديدة / مواقع العاصمة الإدارية الجديدة",
    phone1: "0228109100",
    mobile: "01117744338",
    hotline: "16257",
    website: "https://www.alhazek.com",
    latitude: 30.0189,
    longitude: 31.4289,
    fleetSize: 95,
    fleetType: "مضخات خرسانة عملاقة، خلاطات خرسانية ريدي ميكس، أوناش برجية، تريلات نقل مواد، وحافلات ركاب",
    fleetTires: "315/80R22.5 • 385/65R22.5 • 12.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "شركة مقاولات فئة أولى متميزة في تنفيذ المشروعات العقارية الفاخرة والأبراج بالعاصمة الإدارية",
    contactPerson: "مدير المعدات والأسطول الميكانيكي",
    contactTitle: "Plant & Heavy Equipment Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.0189,31.4289"
  },
  {
    id: "eg_titan_658",
    nameAr: "شركة تبارك للأبنية والمقاولات الخرسانية الكبرى (القاهرة)",
    nameEn: "Tabarak Developments & Heavy Concrete Construction",
    sector: "construction",
    subSector: "تطوير المدن والمجتمعات العمرانية المتكاملة وأعمال الهياكل الخرسانية والبنية التحتية",
    city: "cairo",
    governorate: "القاهرة",
    address: "شارع مصطفى النحاس، مدينة نصر، القاهرة",
    phone1: "0222741500",
    mobile: "01004488226",
    hotline: "16258",
    website: "https://www.tabarak.com",
    latitude: 30.0589,
    longitude: 31.3489,
    fleetSize: 80,
    fleetType: "شاحنات نقل مواد بناء، تريلات حديد تسليح، خلاطات خرسانة، وأتوبيسات مهندسين ومواقع",
    fleetTires: "315/80R22.5 • 12.00R20 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "مجموعة تطوير وإنشاءات عقارية كبرى تدير أسطول معدات وشاحنات في القاهرة والشروق والساحل الشمالي",
    contactPerson: "مدير حركة المعدات واللوجستيات",
    contactTitle: "Equipment & Logistics Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.0589,31.3489"
  },
  {
    id: "eg_titan_659",
    nameAr: "مجموعة درة للإنشاءات والمقاولات العمرانية الكبرى (الشيخ زايد وأكتوبر)",
    nameEn: "Dorra Group - Construction, Contracting & Real Estate Mega Projects",
    sector: "construction",
    subSector: "إنشاء المجمعات السكنية الفاخرة والأبراج، مشروعات الكباري والبنية التحتية والمباني الذكية",
    city: "giza",
    governorate: "الجيزة",
    address: "محور 26 يوليو، الشيخ زايد، محافظة الجيزة",
    phone1: "0238519100",
    mobile: "01223388449",
    hotline: "16259",
    website: "https://www.dorra.com",
    latitude: 30.0412,
    longitude: 30.9889,
    fleetSize: 110,
    fleetType: "مضخات خرسانة شوينج، خلاطات مرسيدس أكتروس، لوابد نقل حفارات، وأسطول حافلات ورديات",
    fleetTires: "315/80R22.5 • 385/65R22.5 • 12.00R24",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "إحدى كبرى وأعرق شركات المقاولات العامة والإنشاءات في مصر بأسطول معدات ومركبات فائق الضخامة",
    contactPerson: "مدير عام المعدات والأسطول المركزي للمجموعة",
    contactTitle: "Corporate Fleet & Plant Machinery Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.0412,30.9889"
  },
  {
    id: "eg_titan_660",
    nameAr: "شركة سياك للمعدات والشدات المعدنية والخرسانة الجاهزة (6 أكتوبر)",
    nameEn: "SIAC Industrial Construction & Plant Equipment (6th of October)",
    sector: "construction",
    subSector: "تنفيذ المصانع الكبرى، المحطات الحرارية للكهرباء، وأبراج مدينة العلمين والعاصمة الإدارية",
    city: "giza",
    governorate: "الجيزة",
    address: "المنطقة الصناعية الخامسة، مدينة السادس من أكتوبر، الجيزة",
    phone1: "0238335400",
    mobile: "01112299557",
    hotline: "16260",
    website: "https://www.siac.com.eg",
    latitude: 29.9112,
    longitude: 30.9012,
    fleetSize: 115,
    fleetType: "شاحنات نقل شدات معدنية، أوناش هيدروليكية تلسكوبية، خلاطات خرسانة، وأتوبيسات نقل مواقع",
    fleetTires: "315/80R22.5 • 385/65R22.5 • 12.00R24",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "شركة المقاولات الصناعية الرائدة في مصر المنفذة لكبرى مشروعات المحطات الصناعية والأبراج ناطحات السحاب",
    contactPerson: "مدير إدارة المعدات الثقيلة والنقل",
    contactTitle: "Heavy Equipment & Transport Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.9112,30.9012"
  },
  {
    id: "eg_titan_661",
    nameAr: "شركة أركان للإنشاءات الخرسانية الكبرى والبنية التحتية (القاهرة الجديدة)",
    nameEn: "Arkan Mega Infrastructure & Concrete Construction",
    sector: "construction",
    subSector: "تنفيذ خطوط المونوريل، القطار الكهربائي الخفيف LRT، ومحطات الكهرباء والمحاور المرورية",
    city: "cairo",
    governorate: "القاهرة",
    address: "محور المشير طنطاوي، التجمع الخامس، القاهرة الجديدة",
    phone1: "0226171400",
    mobile: "01007733881",
    hotline: "16261",
    website: "https://www.arkan-construction.com",
    latitude: 30.0145,
    longitude: 31.4112,
    fleetSize: 90,
    fleetType: "تريلات نقل كمرات خرسانية سابقة الصب، خلاطات، لوادر، حفارات، وأتوبيسات ركاب",
    fleetTires: "315/80R22.5 • 12.00R24 • 12.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "شركة مقاولات وإنشاءات بنية تحتية عملاقة تشارك في محاور العاصمة الإدارية الجديدة",
    contactPerson: "مدير حركة النقل والمعدات الميدانية",
    contactTitle: "Fleet Movement & Field Equipment Supervisor",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.0145,31.4112"
  },
  {
    id: "eg_titan_662",
    nameAr: "شركة النصر للإسكان والتعمير (المقطم - القاهرة)",
    nameEn: "El Nasr Housing & Development Mega Co. (Mokattam - Cairo)",
    sector: "construction",
    subSector: "تطوير هضبة المقطم، إنشاء المشروعات السكنية القومية، وتجهيز البنية التحتية العمرانية",
    city: "cairo",
    governorate: "القاهرة",
    address: "ميدان النافورة، المقطم، محافظة القاهرة",
    phone1: "0225081200",
    mobile: "01224411993",
    hotline: "16262",
    website: "https://www.nasr-housing.com",
    latitude: 30.0112,
    longitude: 31.2989,
    fleetSize: 70,
    fleetType: "شاحنات نقل وتسوية أراضي، لوادر، تريلات نقل مواد بناء، وسيارات صيانة وإشراف",
    fleetTires: "315/80R22.5 • 12.00R20 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "إحدى كبرى شركات الإسكان التابعة للشركة القابضة للتشييد والتعمير التابعة للدولة",
    contactPerson: "مدير إدارة الحركة والمركبات",
    contactTitle: "Transport & Vehicles Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.0112,31.2989"
  },
  {
    id: "eg_titan_663",
    nameAr: "شركة مصر الجديدة للإسكان والتعمير (مصر الجديدة وهليوبوليس)",
    nameEn: "Heliopolis Housing & Development Mega Co. (HHD)",
    sector: "construction",
    subSector: "تخطيط وتطوير مدينة هليوبوليس الجديدة ومدينة نيو هليوبوليس وأصول الأراضي الكبرى",
    city: "cairo",
    governorate: "القاهرة",
    address: "شارع إبراهيم اللقاني، روكسي، مصر الجديدة، القاهرة",
    phone1: "0224521400",
    mobile: "01113355887",
    hotline: "16263",
    website: "https://www.hhdco.com",
    latitude: 30.0945,
    longitude: 31.3189,
    fleetSize: 75,
    fleetType: "شاحنات نقل مخلفات وتسوية، لوادر، تريلات نقل مواد إنشائية، وسيارات متابعة مشروعات",
    fleetTires: "315/80R22.5 • 12.00R20 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الشركة العريقة المالكة لآلاف الأفدنة بهليوبوليس الجديدة والشروق بأسطول معدات وخدمات ممتد",
    contactPerson: "مدير عام النقل والحركة",
    contactTitle: "General Transport Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.0945,31.3189"
  },
  {
    id: "eg_titan_664",
    nameAr: "شركة المعادي للتنمية والتعمير ومشاريع الإسكان (المعادي)",
    nameEn: "Maadi for Development & Construction Co. (Cairo)",
    sector: "construction",
    subSector: "تطوير مشروعات دجلة والمعادي الجديدة والشروق والمجمعات الإدارية الحديثة",
    city: "cairo",
    governorate: "القاهرة",
    address: "شارع كورنيش النيل، المعادي، القاهرة",
    phone1: "0223591400",
    mobile: "01008833441",
    hotline: "16264",
    website: "https://www.maadico.com.eg",
    latitude: 29.9612,
    longitude: 31.2589,
    fleetSize: 65,
    fleetType: "شاحنات مقاولات، لوادر كاتربيلر، سيارات إشراف، وأتوبيسات نقل موظفين وعمال",
    fleetTires: "315/80R22.5 • 295/80R22.5 • 11.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "شركة تطوير وتشييد حكومية رائدة تابعة للقطاع العام تدير أسطول معدات مشروعات مستمر",
    contactPerson: "مدير حركة السيارات والمعدات",
    contactTitle: "Vehicles & Equipment Supervisor",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.9612,31.2589"
  },
  {
    id: "eg_titan_665",
    nameAr: "شركة طلعت مصطفى للمعدات والتشييد والخرسانات (مدينتي والرحاب)",
    nameEn: "Talaat Moustafa Group Construction & Heavy Equipment (TMG)",
    sector: "construction",
    subSector: "أضخم مطور عمراني بمصر والعالم العربي لتشييد المدن المليونية المتكاملة (مدينتي، الرحاب، نور)",
    city: "cairo",
    governorate: "القاهرة",
    address: "مجمع الإدارة والتشغيل، مدينتي، طريق السويس، القاهرة",
    phone1: "0224131000",
    mobile: "01229988225",
    hotline: "16265",
    website: "https://www.talaatmoustafa.com",
    latitude: 30.1112,
    longitude: 31.6212,
    fleetSize: 180,
    fleetType: "أساطيل خلاطات خرسانة مركزية، مضخات خرسانة عملاقة، تريلات قلاب سن ورمل، لوادر، وأتوبيسات نقل ركاب",
    fleetTires: "315/80R22.5 • 385/65R22.5 • 12.00R24 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "العملاق العقاري والإنشائي الأكبر في مصر مع أسطول معدات ومركبات خرسانية ونقل ثقيل يخدم مدن مدينتي ونور والرحاب",
    contactPerson: "نائب الرئيس للمعدات الثقيلة والأسطول الميكانيكي",
    contactTitle: "VP of Heavy Plant, Ready Mix & Fleet Logistics",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.1112,31.6212"
  }
];

module.exports = { wave6Part5 };
