/**
 * scripts/wave6_data_part2.js
 * Part 2 of Wave 6 Titans (eg_titan_526 to eg_titan_555) - 30 Industrial Titans.
 * Sectors: Paper, Pulp, Cardboard & Packaging (20) and Mining, Minerals & Quarries (10).
 */

const wave6Part2 = [
  // 2. Paper, Pulp, Printing & Corrugated Packaging (20)
  {
    id: "eg_titan_526",
    nameAr: "شركة مصر إدفو لصناعة لب الورق والورق الأبيض (إدفو - أسوان)",
    nameEn: "Misr Edfu Paper Pulp & White Paper Manufacturing Co. (Aswan)",
    sector: "manufacturing",
    subSector: "تحويل مصاص القصب (الباجاس) إلى لب ورق نقي وإنتاج ورق الطباعة والكتابة الأبيض",
    city: "aswan",
    governorate: "أسوان",
    address: "طريق الكورنيش، مجمع مصانع الورق، إدفو، محافظة أسوان",
    phone1: "0974701200",
    mobile: "01002288334",
    hotline: "16126",
    website: "https://www.misredfupaper.com",
    latitude: 24.9789,
    longitude: 32.8712,
    fleetSize: 85,
    fleetType: "تريلات تيبار لنقل الباجاس من مصانع السكر، شاحنات نقل رولات الورق، وحافلات ركاب",
    fleetTires: "315/80R22.5 • 12.00R24 • 12.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الصرح القومي الاستراتيجي بصعيد مصر لإنتاج الورق من مخلفات القصب بأسطول شحن ونقل ثقيل ضخم",
    contactPerson: "مدير عام النقل والمهمات الثقيلة",
    contactTitle: "Heavy Transport & Fleet Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=24.9789,32.8712"
  },
  {
    id: "eg_titan_527",
    nameAr: "شركة قنا لصناعة الورق وكتابة وطباعة الأوفست (نجع حمادي - قنا)",
    nameEn: "Qena Paper Industry Co. - Offset Printing & Writing Paper (Qena)",
    sector: "manufacturing",
    subSector: "أكبر منتج لورق الكتابة والطباعة الأوفست وورق الصحف والكرتون عالي النقاء في مصر",
    city: "qena",
    governorate: "قنا",
    address: "طريق مصر أسوان الزراعي، نجع حمادي، محافظة قنا",
    phone1: "0966581400",
    mobile: "01224488991",
    hotline: "16127",
    website: "https://www.qenapaper.com",
    latitude: 26.0412,
    longitude: 32.2412,
    fleetSize: 90,
    fleetType: "تريلات رولات ورق الأوفست الكبرى، شاحنات نقل الباجاس، وأتوبيسات ركاب",
    fleetTires: "315/80R22.5 • 385/65R22.5 • 12.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "شركة مساهمة كبرى تغذي قطاع التعليم والمطابع الصحفية بأسطول تريلات نقل ممتد لكافة محافظات الجمهورية",
    contactPerson: "رئيس قطاع الحركة والنقل البري",
    contactTitle: "Head of Land Logistics & Fleet Movement",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=26.0412,32.2412"
  },
  {
    id: "eg_titan_528",
    nameAr: "مطابع الأهرام المركزية الحديثة ومجمع الصحافة (قليوب و6 أكتوبر)",
    nameEn: "Al-Ahram Commercial & Newspaper Mega Printing Presses (Qalyub & 6th of October)",
    sector: "manufacturing",
    subSector: "طباعة الصحف القومية والكتب المدرسية والتغليف والمطبوعات التجارية الملونة الكبرى",
    city: "qalyubia",
    governorate: "القليوبية",
    address: "طريق القاهرة الإسكندرية الزراعي، قليوب / مجمع المنطقة الصناعية بأكتوبر",
    phone1: "0242151200",
    mobile: "01115588332",
    hotline: "16128",
    website: "https://www.ahrampress.com.eg",
    latitude: 30.1812,
    longitude: 31.2189,
    fleetSize: 95,
    fleetType: "شاحنات نقل وتوزيع صحف وكتب مجهزة، تريلات نقل رولات الورق المستورد، وفانات توزيع",
    fleetTires: "295/80R22.5 • 225/75R17.5 • 11.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "أضخم مؤسسة طباعة وصحافة في الشرق الأوسط بأسطول توزيع يومي يقطع آلاف الكيلومترات فجر كل يوم لجميع محافظات مصر",
    contactPerson: "مدير عام أسطول النقل والتوزيع المركزي",
    contactTitle: "General Manager of Fleet Distribution",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.1812,31.2189"
  },
  {
    id: "eg_titan_529",
    nameAr: "مؤسسة أخبار اليوم للصحافة والطباعة والتوزيع (مجمع 6 أكتوبر)",
    nameEn: "Akhbar El Yom Printing, Publishing & Distribution Mega Complex",
    sector: "manufacturing",
    subSector: "مجمع مطابع صحفية وتجارية متطور لطباعة الإصدارات القومية وتغليف المنتجات والمناهج التعليمية",
    city: "giza",
    governorate: "الجيزة",
    address: "المنطقة الصناعية الرابعة، مدينة السادس من أكتوبر، الجيزة",
    phone1: "0238334500",
    mobile: "01007733441",
    hotline: "16129",
    website: "https://www.akhbarelyom.com",
    latitude: 29.9389,
    longitude: 30.9245,
    fleetSize: 80,
    fleetType: "سيارات توزيع فانات، شاحنات صندوقية مغلقة، تريلات ورق، وحافلات ركاب",
    fleetTires: "225/75R17.5 • 295/80R22.5 • 8.25R16",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "أسطول سيارات توزيع وشاحنات نشط يعمل على مدار 24 ساعة لتغطية شبكة التوزيع القومية",
    contactPerson: "مدير إدارة الحركة والتوزيع المركزي",
    contactTitle: "Central Transport & Distribution Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.9389,30.9245"
  },
  {
    id: "eg_titan_530",
    nameAr: "مؤسسة دار التحرير للطباعة والنشر (الجمهورية - أكتوبر)",
    nameEn: "Dar Al Tahrir Printing & Publishing (Al Gomhuria - 6th of October)",
    sector: "manufacturing",
    subSector: "طباعة المطبوعات الحكومية والصحف اليومية ومستلزمات التعبئة والتغليف",
    city: "giza",
    governorate: "الجيزة",
    address: "المنطقة الصناعية الثالثة، مدينة 6 أكتوبر، الجيزة",
    phone1: "0238341200",
    mobile: "01228811443",
    hotline: "16130",
    website: "https://www.algomhuria.com.eg",
    latitude: 29.9245,
    longitude: 30.9389,
    fleetSize: 60,
    fleetType: "شاحنات توزيع بضائع، فانات وسيارات شحن، وأتوبيسات ركاب",
    fleetTires: "225/75R17.5 • 295/80R22.5 • 7.50R16",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "مجمع مطابع صحفية قومية كبرى بأكتوبر بأسطول سيارات شحن سريع",
    contactPerson: "مدير الشؤون الإدارية والحركة",
    contactTitle: "Administration & Transport Officer",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.9245,30.9389"
  },
  {
    id: "eg_titan_531",
    nameAr: "شركة الشروق الحديثة للطباعة والتغليف (مدينة العبور)",
    nameEn: "Shorouk Modern Printing & Packaging Mega Plants (Obour City)",
    sector: "manufacturing",
    subSector: "طباعة علب الكرتون الفاخرة، طباعة عبوات الأدوية والأغذية، والكتب المصورة والتجليد الفاخر",
    city: "qalyubia",
    governorate: "القليوبية",
    address: "المنطقة الصناعية الأولى، مدينة العبور، محافظة القليوبية",
    phone1: "0244814100",
    mobile: "01118833112",
    hotline: "16131",
    website: "https://www.shoroukprinting.com",
    latitude: 30.2289,
    longitude: 31.4645,
    fleetSize: 70,
    fleetType: "شاحنات نقل مغلقة، تريلات نقل رولات الكرتون، وفانات شحن سريعة لشركات الأدوية",
    fleetTires: "295/80R22.5 • 225/75R17.5 • 8.25R16",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "أكبر شركة طباعة وتغليف حديثة متخصصة في عبوات الأدوية والأغذية بالشرق الأوسط بأسطول لوجستي عالي التجهيز",
    contactPerson: "مدير اللوجستيات وسلاسل الإمداد",
    contactTitle: "Supply Chain & Logistics Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.2289,31.4645"
  },
  {
    id: "eg_titan_532",
    nameAr: "مجموعة برينت باك لتصنيع الكرتون المضلع (العاشر من رمضان)",
    nameEn: "Print Pack Corrugated Packaging Industries (10th of Ramadan)",
    sector: "manufacturing",
    subSector: "صناعة كراتين التعبئة المضلعة (Corrugated Boxes) لمصانع الأغذية والأجهزة والفاكهة التصديرية",
    city: "sharqia",
    governorate: "الشرقية",
    address: "المنطقة الصناعية A4، مدينة العاشر من رمضان، محافظة الشرقية",
    phone1: "015414200",
    mobile: "01006611884",
    hotline: "16132",
    website: "https://www.printpackegypt.com",
    latitude: 30.3089,
    longitude: 31.7512,
    fleetSize: 85,
    fleetType: "تريلات جامبو لنقل الكراتين المضلعة، شاحنات صندوقية، وحافلات ركاب",
    fleetTires: "315/80R22.5 • 295/80R22.5 • 385/65R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "مورد رئيسي لكراتين التصدير لكبرى مزارع الفاكهة ومصانع الأجهزة الكهربائية بأسطول شحن فائق الحجم",
    contactPerson: "مدير الحركة والنقل الخارجي",
    contactTitle: "Outbound Logistics & Fleet Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.3089,31.7512"
  },
  {
    id: "eg_titan_533",
    nameAr: "الشركة القومية للورق والكرتون (العامرية - الإسكندرية)",
    nameEn: "National Paper & Board Co. (Amreya - Alexandria)",
    sector: "manufacturing",
    subSector: "إعادة تدوير المخلفات الورقية وإنتاج ورق الكرتون، ورق الفلوتنج، والتست لاينر",
    city: "alexandria",
    governorate: "الإسكندرية",
    address: "الكيلو 28 طريق مصر إسكندرية الصحراوي، العامرية، الإسكندرية",
    phone1: "034481200",
    mobile: "01225577991",
    hotline: "16133",
    website: "https://www.nationalpaper.com.eg",
    latitude: 31.0312,
    longitude: 29.8145,
    fleetSize: 65,
    fleetType: "تريلات قلاب ونقل مخلفات ورقية، شاحنات نقل رولات كرتون، وأتوبيسات ركاب",
    fleetTires: "315/80R22.5 • 12.00R20 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "صرح رائد في إعادة تدوير الورق وتصنيع ورق الكرتون بالعامرية بأسطول شحن ثقيل نشط",
    contactPerson: "مدير الأسطول والخدمات اللوجستية",
    contactTitle: "Fleet & Logistics Operations Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=31.0312,29.8145"
  },
  {
    id: "eg_titan_534",
    nameAr: "شركة الورق الأهلية لصناعة ورق التعبئة والكرتون (محرم بك - الإسكندرية)",
    nameEn: "El Ahleia Paper Manufacturing Co. (Moharam Bek - Alexandria)",
    sector: "manufacturing",
    subSector: "تصنيع ورق الكرافت، أكياس الورق الصناعية، ورق التغليف والكرتون الدوبلكس",
    city: "alexandria",
    governorate: "الإسكندرية",
    address: "شارع قنال المحمودية، محرم بك، الإسكندرية",
    phone1: "034951200",
    mobile: "01114477885",
    hotline: "16134",
    website: "https://www.ahleiapaper.com",
    latitude: 31.1889,
    longitude: 29.9145,
    fleetSize: 55,
    fleetType: "شاحنات نقل ورق كرافت، تريلات نقل خام، وأتوبيسات ركاب",
    fleetTires: "315/80R22.5 • 295/80R22.5 • 11.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "شركة عريقة في تصنيع الورق والكرتون بالإسكندرية تابعة لقطاع الأعمال العام",
    contactPerson: "مدير الحركة والنقل",
    contactTitle: "Transport Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=31.1889,29.9145"
  },
  {
    id: "eg_titan_535",
    nameAr: "الشركة المصرية لصناعة الكرتون والتغليف (إيجيباك - العاشر من رمضان)",
    nameEn: "Egyptian Packaging & Corrugated Board (Egypack - 10th of Ramadan)",
    sector: "manufacturing",
    subSector: "تصنيع الكرتون المضلع والعلب الصندوقية المقواة لمصانع السيراميك والمواد الكيماوية",
    city: "sharqia",
    governorate: "الشرقية",
    address: "المنطقة الصناعية B1، مدينة العاشر من رمضان، الشرقية",
    phone1: "015415100",
    mobile: "01009944332",
    hotline: "16135",
    website: "https://www.egypack.com.eg",
    latitude: 30.2989,
    longitude: 31.7612,
    fleetSize: 75,
    fleetType: "تريلات شحن كرتون جامبو، شاحنات مقفلة، وحافلات نقل عمال",
    fleetTires: "315/80R22.5 • 295/80R22.5 • 8.25R16",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "قلعة تصنيع الكرتون المضلع عالي التحمل بالعاشر من رمضان",
    contactPerson: "مدير حركة النقل والتوريدات",
    contactTitle: "Supply & Fleet Movement Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.2989,31.7612"
  },
  {
    id: "eg_titan_536",
    nameAr: "مصانع النيل لصناعة الكرتون المضلع والتعبئة (مدينة بدر الصناعية)",
    nameEn: "Nile Corrugated Packaging Industries (Badr City)",
    sector: "manufacturing",
    subSector: "إنتاج عبوات الشحن الكرتونية والكرتون متعدد الطبقات لكبرى شركات الصناعات الغذائية",
    city: "cairo",
    governorate: "القاهرة",
    address: "المنطقة الصناعية الثانية، مدينة بدر، محافظة القاهرة",
    phone1: "0228608200",
    mobile: "01227744118",
    hotline: "16136",
    website: "https://www.nilecarton.com",
    latitude: 30.1345,
    longitude: 31.7145,
    fleetSize: 60,
    fleetType: "تريلات صندوقية، شاحنات مرسيدس أكتروس، وفانات وسيارات بيك آب",
    fleetTires: "315/80R22.5 • 295/80R22.5 • 225/75R17.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "مصنع كرتون رئيسي يغذي مصانع العاصمة الإدارية وبدر والعاشر من رمضان",
    contactPerson: "مدير الصيانة والحركة الميدانية",
    contactTitle: "Maintenance & Transport Supervisor",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.1345,31.7145"
  },
  {
    id: "eg_titan_537",
    nameAr: "الشركة المتحدة لصناعة الورق والكرتون (يونيباك - مدينة السادات)",
    nameEn: "United Paper & Board Industries (Unipack - Sadat City)",
    sector: "manufacturing",
    subSector: "إنتاج ورق الدوبلكس والكرتون الرمادي والمبيض لمصانع التعبئة والطباعة",
    city: "menofia",
    governorate: "المنوفية",
    address: "المنطقة الصناعية السابعة، مدينة السادات، محافظة المنوفية",
    phone1: "0482613100",
    mobile: "01112255774",
    hotline: "16137",
    website: "https://www.unipackegypt.com",
    latitude: 30.3789,
    longitude: 30.5112,
    fleetSize: 70,
    fleetType: "تريلات رولات الكرتون، شاحنات نقل خامات، وأتوبيسات ركاب",
    fleetTires: "315/80R22.5 • 385/65R22.5 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "أكبر مصنع إنتاج كرتون دوبلكس بمدينة السادات بأسطول شحن يغطي مصانع الدلتا والقاهرة",
    contactPerson: "مدير عام النقل والأسطول",
    contactTitle: "General Fleet Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.3789,30.5112"
  },
  {
    id: "eg_titan_538",
    nameAr: "شركة روتو باك لتغليف وطباعة المواد الغذائية (مدينة 6 أكتوبر)",
    nameEn: "Roto Pack Flexible Packaging & Printing (6th of October)",
    sector: "manufacturing",
    subSector: "طباعة وتصنيع مواد التغليف المرنة (Flexible Packaging) لرقائق الشيبسي والبسكويت والحلويات",
    city: "giza",
    governorate: "الجيزة",
    address: "المنطقة الصناعية الثانية، مدينة السادس من أكتوبر، الجيزة",
    phone1: "0238206100",
    mobile: "01003344119",
    hotline: "16138",
    website: "https://www.rotopack.com.eg",
    latitude: 29.9145,
    longitude: 30.9112,
    fleetSize: 55,
    fleetType: "شاحنات شحن رولات التغليف المعقمة، سيارات نقل مغلقة، وحافلات ركاب",
    fleetTires: "295/80R22.5 • 225/75R17.5 • 8.25R16",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الشركة الرائدة في تزويد شركات الأغذية بأفلام التغليف متعددة الطبقات بأكتوبر",
    contactPerson: "مدير اللوجستيات والحركة",
    contactTitle: "Logistics Officer",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.9145,30.9112"
  },
  {
    id: "eg_titan_539",
    nameAr: "الشركة الأهلية للطباعة والتغليف الفاخر (العاشر من رمضان)",
    nameEn: "El Ahleia Modern Printing & Luxury Packaging (10th of Ramadan)",
    sector: "manufacturing",
    subSector: "صناعة علب العطور والحلويات الشرقية وعبوات الهدايا الفاخرة والتجليد الآلي",
    city: "sharqia",
    governorate: "الشرقية",
    address: "المنطقة الصناعية C1، مدينة العاشر من رمضان، الشرقية",
    phone1: "015416200",
    mobile: "01221144883",
    hotline: "16139",
    website: "https://www.ahleiaprinting.com",
    latitude: 30.3212,
    longitude: 31.7489,
    fleetSize: 45,
    fleetType: "شاحنات نقل بضائع مغلقة، فانات توزيع سريعة، وأتوبيسات ركاب",
    fleetTires: "225/75R17.5 • 295/80R22.5 • 7.50R16",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "صرح متخصص في التغليف الكرتوني الفاخر لشركات الأغذية والعطور والتصدير",
    contactPerson: "مدير الحركة والنقل",
    contactTitle: "Transport Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.3212,31.7489"
  },
  {
    id: "eg_titan_540",
    nameAr: "شركة الشرق الأوسط لصناعة الورق (سيمو - مسطرد - القليوبية)",
    nameEn: "Middle East Paper Co. (SIMO - Mostorod)",
    sector: "manufacturing",
    subSector: "صناعة ورق اللف والتغليف وورق الكرتون وإعادة تدوير الدشت الصناعي",
    city: "qalyubia",
    governorate: "القليوبية",
    address: "طريق ترعة الإسماعيلية، مسطرد، محافظة القليوبية",
    phone1: "0242201500",
    mobile: "01115599221",
    hotline: "16140",
    website: "https://www.simopaper.com",
    latitude: 30.1289,
    longitude: 31.3112,
    fleetSize: 50,
    fleetType: "تريلات نقل مخلفات ورقية، شاحنات رولات ورق، وأتوبيسات نقل ورديات",
    fleetTires: "315/80R22.5 • 295/80R22.5 • 11.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "مصنع ورقي عريق بمسطرد بأسطول شاحنات مخصص لتجميع الدشت ونقل المنتجات",
    contactPerson: "مدير إدارة الحركة",
    contactTitle: "Fleet Movement Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.1289,31.3112"
  },
  {
    id: "eg_titan_541",
    nameAr: "شركة فليكس بي فيلمز إيجيبت لتصنيع أفلام التغليف البلاستيكية (مدينة 6 أكتوبر)",
    nameEn: "Flex P Films Egypt - BOPP & Packaging Films (6th of October)",
    sector: "manufacturing",
    subSector: "أكبر منتج لأفلام البولي بروبيلين ثنائية المحور (BOPP) وأفلام البوليستر للتغليف الصناعي",
    city: "giza",
    governorate: "الجيزة",
    address: "المنطقة الهندسية، مجمع المطورين، مدينة السادس من أكتوبر، الجيزة",
    phone1: "0238243100",
    mobile: "01004488221",
    hotline: "16141",
    website: "https://www.flexfilm.com",
    latitude: 29.9012,
    longitude: 30.8989,
    fleetSize: 65,
    fleetType: "تريلات شحن رولات البلاستيك، شاحنات تصدير للموانئ، وحافلات ركاب حديثة",
    fleetTires: "315/80R22.5 • 385/65R22.5 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "استثمار هندي دولي عملاق في 6 أكتوبر لتصنيع أفلام التغليف وتصديرها لمختلف دول العالم",
    contactPerson: "مدير العمليات اللوجستية والشحن الدولي",
    contactTitle: "Logistics Operations & International Freight Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.9012,30.8989"
  },
  {
    id: "eg_titan_542",
    nameAr: "مصانع تكنوباك لصناعة أكياس الأسمنت والكرتون المتعدد (مدينة السادات)",
    nameEn: "Technopack Heavy Duty Bags & Multiwall Paper Sacks (Sadat City)",
    sector: "manufacturing",
    subSector: "صناعة أكياس الورق متعددة الطبقات لتعبئة الأسمنت والجبس والكيماويات ومساحيق الأغذية",
    city: "menofia",
    governorate: "المنوفية",
    address: "المنطقة الصناعية الرابعة، مدينة السادات، محافظة المنوفية",
    phone1: "0482614200",
    mobile: "01223399115",
    hotline: "16142",
    website: "https://www.technopackegypt.com",
    latitude: 30.3645,
    longitude: 30.5289,
    fleetSize: 50,
    fleetType: "تريلات شحن أكياس لمصانع الأسمنت، شاحنات صندوقية، وأتوبيسات ركاب",
    fleetTires: "315/80R22.5 • 295/80R22.5 • 11.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "مورد معتمد لأكياس الأسمنت والكيماويات لكبرى شركات مواد البناء في مصر",
    contactPerson: "مدير حركة النقل",
    contactTitle: "Transport Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.3645,30.5289"
  },
  {
    id: "eg_titan_543",
    nameAr: "شركة بريميير لتصنيع الكرتون ومواد الشحن اللوجستي (برج العرب - الإسكندرية)",
    nameEn: "Premier Packaging & Logistics Shipping Materials (Borg El Arab)",
    sector: "manufacturing",
    subSector: "تصنيع باليتات الكرتون المضغوط وأركان الحماية وحلول التعبئة للشحن الخارجي",
    city: "alexandria",
    governorate: "الإسكندرية",
    address: "المنطقة الصناعية الثالثة، برج العرب الجديدة، الإسكندرية",
    phone1: "034592400",
    mobile: "01117788442",
    hotline: "16143",
    website: "https://www.premierpack.com.eg",
    latitude: 30.9212,
    longitude: 29.6345,
    fleetSize: 45,
    fleetType: "شاحنات جامبو شحن، فانات نقل، وحافلات نقل ورديات",
    fleetTires: "295/80R22.5 • 225/75R17.5 • 8.25R16",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "مصنع متخصص في حلول التغليف والحماية لمصانع برج العرب وميناء الإسكندرية",
    contactPerson: "مدير الشؤون اللوجستية",
    contactTitle: "Logistics Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.9212,29.6345"
  },
  {
    id: "eg_titan_544",
    nameAr: "الشركة العالمية لورق الكرتون والتغليف والتصدير (العاشر من رمضان)",
    nameEn: "Universal Paper Board & Export Packaging Co. (10th of Ramadan)",
    sector: "manufacturing",
    subSector: "تصنيع كرتون الحاصلات الزراعية وشيتات الكرتون وورق التعبئة المخصص لغرف التبريد",
    city: "sharqia",
    governorate: "الشرقية",
    address: "المنطقة الصناعية B3، مدينة العاشر من رمضان، الشرقية",
    phone1: "015417500",
    mobile: "01005511773",
    hotline: "16144",
    website: "https://www.universalcardboard.com",
    latitude: 30.2945,
    longitude: 31.7689,
    fleetSize: 60,
    fleetType: "تريلات شحن كرتون لمزارع الموالح، شاحنات نقل ثقيل، وأتوبيسات عمال",
    fleetTires: "315/80R22.5 • 295/80R22.5 • 385/65R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "قلعة تصنيع كراتين الموالح المقاومة للرطوبة لحاويات التصدير",
    contactPerson: "مدير عام الأسطول والمتابعة",
    contactTitle: "Fleet Operations Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.2945,31.7689"
  },
  {
    id: "eg_titan_545",
    nameAr: "مطابع روزاليوسف للصحافة والطباعة الحديثة (مدينة 6 أكتوبر)",
    nameEn: "Rose El Youssef Press & Commercial Printing Center (6th of October)",
    sector: "manufacturing",
    subSector: "طباعة المجلات الدورية والكتب والصحف والمطبوعات الإعلانية والتجارية الضخمة",
    city: "giza",
    governorate: "الجيزة",
    address: "المنطقة الصناعية الرابعة، مدينة 6 أكتوبر، الجيزة",
    phone1: "0238338100",
    mobile: "01229933661",
    hotline: "16145",
    website: "https://www.rosadaily.com",
    latitude: 29.9345,
    longitude: 30.9312,
    fleetSize: 45,
    fleetType: "فانات وسيارات توزيع سريعة، شاحنات صندوقية، وأتوبيسات ركاب",
    fleetTires: "225/75R17.5 • 295/80R22.5 • 7.50R16",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "مجمع مطابع صحفي وتجاري قومي حديث بمدينة 6 أكتوبر",
    contactPerson: "مدير حركة التوزيع والنقل",
    contactTitle: "Distribution & Transport Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.9345,30.9312"
  },

  // 3. Mining, Phosphate, Minerals & Raw Materials (10)
  {
    id: "eg_titan_546",
    nameAr: "شركة سيناء للمنجنيز (أبو زنيمة - جنوب سيناء)",
    nameEn: "Sinai Manganese Co. - Mining & Metallurgy (Abu Zenima - South Sinai)",
    sector: "manufacturing",
    subSector: "تعدين واستخراج خام المنجنيز والجبس والرمال البيضاء وإنتاج سبائك السيليكون منجنيز",
    city: "south_sinai",
    governorate: "جنوب سيناء",
    address: "منطقة أم بجمة، أبو زنيمة، محافظة جنوب سيناء / ميناء أبو زنيمة التعديني",
    phone1: "0693520100",
    mobile: "01001188442",
    hotline: "16146",
    website: "https://www.sinaisalt.com",
    latitude: 29.0412,
    longitude: 33.1112,
    fleetSize: 95,
    fleetType: "قلابات تعدين عملاقة (دنابر كوماتسو وكاتربيلر)، تريلات نقل خامات لميناء التصدير، وأتوبيسات عمال دفع رباعي",
    fleetTires: "12.00R24 • 14.00R24 • 315/80R22.5 • 24R20.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "أقدم وأكبر صرح لتعدين المنجنيز والجبس بجنوب سيناء يمتلك ميناء تعديني خاص وأسطول معدات مناجم ثقيل",
    contactPerson: "مدير عام المناجم والنقل الميداني الثقيل",
    contactTitle: "General Manager of Mines & Heavy Equipment Transport",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.0412,33.1112"
  },
  {
    id: "eg_titan_547",
    nameAr: "شركة النصر للتعدين واستخراج الفوسفات (المحاميد - إدفو وأسوان)",
    nameEn: "El Nasr Mining Co. - Phosphate & Mineral Extraction (Aswan)",
    sector: "manufacturing",
    subSector: "تعدين واستخراج الفوسفات، التلك، البارايت، والكوارتز من مناجم أسوان والبحر الأحمر",
    city: "aswan",
    governorate: "أسوان",
    address: "المحاميد قبلي، إدفو، محافظة أسوان / مكاتب القاهرة وسفاجا",
    phone1: "0974712300",
    mobile: "01224411883",
    hotline: "16147",
    website: "https://www.nasrmining.com",
    latitude: 25.0212,
    longitude: 32.8412,
    fleetSize: 130,
    fleetType: "شاحنات قلاب تعدين ثقيل، لوادر وحفارات كاتربيلر، تريلات صب جاف لنقل الفوسفات لسفاجا، وأتوبيسات مهندسين",
    fleetTires: "12.00R24 • 315/80R22.5 • 14.00R24 • 385/65R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "عملاق التعدين المصري التابع لوزارة قطاع الأعمال العام وأكبر مصدر للفوسفات الصخري في الشرق الأوسط",
    contactPerson: "رئيس قطاع الحركة والنقل الثقيل بالمناجم",
    contactTitle: "Head of Mine Transport & Heavy Equipment Fleet",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=25.0212,32.8412"
  },
  {
    id: "eg_titan_548",
    nameAr: "شركة فوسفات مصر بمشروع هضبة أبو طرطور (الوادي الجديد والبحر الأحمر)",
    nameEn: "Phosphate Misr Co. - Abu Tartur Mega Phosphate Plateau",
    sector: "manufacturing",
    subSector: "استخراج خام الفوسفات ومعالجته وتوريده لمصانع الأسمدة المحلية وموانئ التصدير العالمية",
    city: "new_valley",
    governorate: "الوادي الجديد",
    address: "مشروع منجم هضبة أبو طرطور، الخارجة، محافظة الوادي الجديد / ميناء سفاجا التعديني",
    phone1: "0927921500",
    mobile: "01113399442",
    hotline: "16148",
    website: "https://www.phosphatemisr.com",
    latitude: 25.4312,
    longitude: 30.0145,
    fleetSize: 150,
    fleetType: "شاحنات تعدين عملاقة، دنابر ثقيلة، تريلات نقل خام لسفاجا وقنا، أساطيل لوادر وتجهيزات حفر",
    fleetTires: "14.00R24 • 12.00R24 • 315/80R22.5 • 18.00R33",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "أضخم احتياطي فوسفات في إفريقيا والشرق الأوسط بأسطول معدات تعدين ونقل صحراوي استثنائي الحجم",
    contactPerson: "مدير عام الأسطول البري ومعدات التعدين",
    contactTitle: "General Manager of Surface Mining Fleet & Logistics",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=25.4312,30.0145"
  },
  {
    id: "eg_titan_549",
    nameAr: "الشركة المصرية للثروات التعدينية (مرسى علم والقصير والواحات)",
    nameEn: "Egyptian Mineral Resources Co. (EMRA - Red Sea & Oases)",
    sector: "manufacturing",
    subSector: "استكشاف واستغلال خامات الذهب، الفلسبار، التلك، الألكاب، والرمال الكاولينية بالصحراء",
    city: "red_sea",
    governorate: "البحر الأحمر",
    address: "طريق القصير - مرسى علم، محافظة البحر الأحمر / المقر التعديني بالمعادي",
    phone1: "0653312400",
    mobile: "01007744118",
    hotline: "16149",
    website: "https://www.emra-egypt.com",
    latitude: 25.8212,
    longitude: 34.1889,
    fleetSize: 85,
    fleetType: "شاحنات صحراوية دفع رباعي 6x6، حفارات تعدين، تريلات شحن، وأتوبيسات فرق الجيولوجيين",
    fleetTires: "14.00R20 • 12.00R24 • 315/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الذراع الاستثماري لهيئة الثروة المعدنية في تشغيل وإدارة المناجم المصرية بأسطول شاحنات صحراوية ثقيلة",
    contactPerson: "مدير عام الخدمات واللوجستيات الصحراوية",
    contactTitle: "Desert Logistics & Exploration Transport Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=25.8212,34.1889"
  },
  {
    id: "eg_titan_550",
    nameAr: "شركة شلاتين للثروات المعدنية واستخراج الذهب والمعادن (حلايب وشلاتين)",
    nameEn: "Shalateen Mineral Resources Co. (Halayeb & Shalateen)",
    sector: "manufacturing",
    subSector: "تقنين واستخراج خام الذهب والمعادن المصاحبة بالصحراء الشرقية ومثلث حلايب وشلاتين وأسوان",
    city: "red_sea",
    governorate: "البحر الأحمر",
    address: "مدينة شلاتين، محافظة البحر الأحمر / فروع أسوان والقاهرة",
    phone1: "0653560200",
    mobile: "01228833994",
    hotline: "16150",
    website: "https://www.shalateen-mining.com",
    latitude: 23.1345,
    longitude: 35.5889,
    fleetSize: 90,
    fleetType: "شاحنات نقل صخور خام الذهب، شاحنات مجهزة للصحراء الوعرة، كاسحات، وأتوبيسات دفع رباعي",
    fleetTires: "14.00R20 • 12.00R24 • 315/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الشركة القومية المكلفة بإدارة واستغلال مناطق الذهب بالصحراء الشرقية بأسطول مركبات ومعدات ثقيلة ذات مواصفات خاصة",
    contactPerson: "مدير العمليات اللوجستية والحركة الميدانية",
    contactTitle: "Field Operations & Fleet Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=23.1345,35.5889"
  },
  {
    id: "eg_titan_551",
    nameAr: "شركة الوادي الجديد للطفلة والتعدين (الخارجة والداخلة)",
    nameEn: "New Valley Clay & Mining Industries (Kharga & Dakhla)",
    sector: "building_materials",
    subSector: "استخراج الطفلة الأسمنتية، الحجر الجيري النقي، والجبس التعديني لتغذية مصانع الصعيد والدلتا",
    city: "new_valley",
    governorate: "الوادي الجديد",
    address: "المنطقة الصناعية، الخارجة، محافظة الوادي الجديد",
    phone1: "0927931200",
    mobile: "01116644229",
    hotline: "16151",
    website: "https://www.newvalleymining.com",
    latitude: 25.4412,
    longitude: 30.5412,
    fleetSize: 65,
    fleetType: "قلابات نقل طفلة وحجر جيري، لوادر محاجر، تريلات نقل ثقيل، وأتوبيسات ركاب",
    fleetTires: "12.00R24 • 315/80R22.5 • 12.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "شركة تعدين كبرى تغذي مصانع الأسمنت والسيراميك بخامات الطفلة من صحراء الوادي الجديد",
    contactPerson: "مدير الحركة والمحاجر",
    contactTitle: "Quarry Operations & Transport Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=25.4412,30.5412"
  },
  {
    id: "eg_titan_552",
    nameAr: "شركة كيروزي للجرانيت والرخام ومحاجر أسوان التعدينية",
    nameEn: "Kirozi Granite, Marble & Aswan Quarry Mining Co.",
    sector: "building_materials",
    subSector: "استخراج كتل الجرانيت الأسواني الأحمر والأسود والرمادي وتقطيعها وتصديرها عالمياً",
    city: "aswan",
    governorate: "أسوان",
    address: "طريق السد العالي، المنطقة الصناعية بالشلال، أسوان",
    phone1: "0972391400",
    mobile: "01008811554",
    hotline: "16152",
    website: "https://www.kiroziaswangranite.com",
    latitude: 24.0112,
    longitude: 32.8889,
    fleetSize: 70,
    fleetType: "تريلات تريلا مسطحة لنقل كتل الجرانيت الصخرية (بلوكات)، أوناش رفع هيدروليكية، وحفارات",
    fleetTires: "12.00R24 • 315/80R22.5 • 385/65R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "أكبر مصدري ومستخرجي الجرانيت الطبيعي في أسوان بأسطول شاحنات نقل ثقيل لنقل البلوكات لموانئ العين السخنة والإسكندرية",
    contactPerson: "مدير حركة الشحن والمحاجر",
    contactTitle: "Heavy Haulage & Quarry Transport Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=24.0112,32.8889"
  },
  {
    id: "eg_titan_553",
    nameAr: "الشركة العامة للأبحاث والمياه الجوفية (ريجوا - أساطيل الحفارات والشاحنات الثقيلة)",
    nameEn: "REGWA - General Research & Ground Water Mega Drilling Co.",
    sector: "construction",
    subSector: "حفر آبار المياه الجوفية العميقة، استصلاح الأراضي، وأعمال البنية التحتية المائية القومية",
    city: "cairo",
    governorate: "القاهرة",
    address: "شارع الجمهورية، وسط البلد، القاهرة / ورش الصيانة المركزية بمسطرد",
    phone1: "0225914200",
    mobile: "01223311776",
    hotline: "16153",
    website: "https://www.regwa.com.eg",
    latitude: 30.0545,
    longitude: 31.2489,
    fleetSize: 110,
    fleetType: "أبراج حفارات مياه عملاقة محمولة على شاحنات، تريلات نقل مواسير ومهمات، سيارات خدمة سريعة 4x4",
    fleetTires: "12.00R24 • 14.00R20 • 315/80R22.5 • 11.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الشركة القومية الأولى في مصر لحفر الآبار العميقة لمشروعات الدلتا الجديدة وتوشكى والريف المصري بأسطول شاحنات صحراوي عملاق",
    contactPerson: "مدير عام الورش المركزية وأسطول الحفارات",
    contactTitle: "General Director of Heavy Rigs & Mobile Fleet",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.0545,31.2489"
  },
  {
    id: "eg_titan_554",
    nameAr: "شركة هيديلبرج ماتيريالز للمحاجر والمواد الخام الجافة (السويس والقاهرة)",
    nameEn: "Heidelberg Materials Aggregates & Quarry Operations (Suez & Cairo)",
    sector: "building_materials",
    subSector: "استخراج وتكسير الركام، سن البناء النقي، ورمل المحاجر لأعمال الخرسانة الجاهزة والطرق السريعة",
    city: "suez",
    governorate: "السويس",
    address: "طريق السويس - العين السخنة، جبل عتاقة، محافظة السويس",
    phone1: "0623391800",
    mobile: "01002244991",
    hotline: "16154",
    website: "https://www.heidelbergmaterials.com.eg",
    latitude: 29.8812,
    longitude: 32.3489,
    fleetSize: 90,
    fleetType: "قلابات سن 4 أكسات، لوادر كاتربيلر عملاقة، تريلات قلاب، وسيارات صيانة محجرية",
    fleetTires: "315/80R22.5 • 12.00R24 • 13R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "إحدى كبرى شركات المحاجر والسن في مصر التابعة لمجموعة هيديلبرج العالمية بأسطول نقل ركام ثقيل متواصل",
    contactPerson: "مدير حركة أسطول المحاجر والخدمات اللوجستية",
    contactTitle: "Aggregates Fleet & Quarry Logistics Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.8812,32.3489"
  },
  {
    id: "eg_titan_555",
    nameAr: "مجموعة تبارك لمحاجر الجبس وخامات البناء (رأس ملعب - جنوب سيناء)",
    nameEn: "Tabarak Gypsum & Mineral Extraction Group (Ras Malaab - South Sinai)",
    sector: "building_materials",
    subSector: "تعدين واستخراج خام الجبس الأبيض النقي وتصنيع الجبس الطبيعي والمصيص والمواد العازلة",
    city: "south_sinai",
    governorate: "جنوب سيناء",
    address: "منطقة رأس ملعب، أبو زنيمة، محافظة جنوب سيناء / مكاتب السويس والقاهرة",
    phone1: "0693510400",
    mobile: "01118844119",
    hotline: "16155",
    website: "https://www.tabarakgypsum.com",
    latitude: 29.1812,
    longitude: 32.9912,
    fleetSize: 75,
    fleetType: "قلابات محاجر صخور جبسية، تريلات نقل بودرة جبس سائبة، وتريلات شحن أكياس",
    fleetTires: "12.00R24 • 315/80R22.5 • 385/65R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "أكبر مصانع ومحاجر استخراج الجبس الطبيعي في سيناء بأسطول شحن وتوزيع لكافة المحافظات وموانئ التصدير",
    contactPerson: "مدير النقل البري والمحاجر",
    contactTitle: "Land Haulage & Quarry Transport Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.1812,32.9912"
  }
];

module.exports = { wave6Part2 };
