/**
 * Wave 7 Titans - Part 5 (Titans 901 to 950)
 * Sector Focus: Engineering, Mega Home Appliances, Electronics, Automotive & Commercial Vehicle Assembly, Power Equipment
 */

const wave7Part5 = [
  {
    id: "eg_titan_901",
    nameAr: "شركة بيكو مصر للأجهزة المنزلية (Beko Egypt Mega Eco-Park - العاشر من رمضان)",
    nameEn: "Beko Egypt Mega Home Appliances Complex (Arçelik Group)",
    sector: "manufacturing",
    subSector: "المجمع الصناعي الذكي الأكبر لمجموعة أرتشيليك العالمية لتصنيع الثلاجات والأفران الموفرة للطاقة والتصدير",
    city: "sharqia",
    governorate: "الشرقية",
    address: "المنطقة الصناعية الاستثمارية، العاشر من رمضان، الشرقية",
    phone1: "015418800",
    mobile: "01001144226",
    hotline: "16616",
    website: "https://www.beko.com/eg-ar",
    latitude: 30.2945,
    longitude: 31.7589,
    fleetSize: 210,
    fleetType: "شاحنات نقل أجهزة منزلية مبطنة، تريلات شحن صادرات لموانئ بورسعيد والسخنة، وفانات خدمة وصيانة منزلية",
    fleetTires: "315/80R22.5 • 295/80R22.5 • 225/75R17.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الصرح الحاصل على الرخصة الذهبية باستثمارات تتجاوز 100 مليون دولار لإنتاج 1.5 مليون جهاز سنوياً وتصدير 60%",
    contactPerson: "مدير عام اللوجستيات وسلاسل الإمداد الإقليمية",
    contactTitle: "Regional Supply Chain & Logistics General Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.2945,31.7589"
  },
  {
    id: "eg_titan_902",
    nameAr: "شركة سامسونج إلكترونيكس مصر (Samsung Electronics Egypt - مجمع مصانع بني سويف)",
    nameEn: "Samsung Electronics Egypt Mega Tech Complex (Beni Suef)",
    sector: "manufacturing",
    subSector: "أول وأكبر مصنع لسامسونج بالشرق الأوسط وإفريقيا لإنتاج الشاشات التلفزيونية الذكية والتابلت التعليمي",
    city: "beni_suef",
    governorate: "بني سويف",
    address: "المنطقة الصناعية بكوم أبو راضي، الواسطى، بني سويف",
    phone1: "0822450000",
    mobile: "01003366448",
    hotline: "16580",
    website: "https://www.samsung.com/eg",
    latitude: 29.3124,
    longitude: 31.1891,
    fleetSize: 260,
    fleetType: "شاحنات تريلات صندوقية مجهزة بنظم امتصاص اهتزازات لشحن الشاشات الحساسة، تريلات نقل حاويات موانئ، وفانات",
    fleetTires: "315/80R22.5 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "القلعة التكنولوجية الأولى في الصعيد المصدرة لشاشات سامسونج لأكثر من 50 دولة أوروبية وعربية وأفريقية",
    contactPerson: "نائب رئيس مجلس الإدارة لقطاعات اللوجستيات والشحن الدولي",
    contactTitle: "Vice President - Logistics & Global Shipping",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.3124,31.1891"
  },
  {
    id: "eg_titan_903",
    nameAr: "شركة إل جي إلكترونيكس مصر (LG Electronics Egypt - مجمع العاشر من رمضان)",
    nameEn: "LG Electronics Egypt Mega Industrial Plants (10th of Ramadan)",
    sector: "manufacturing",
    subSector: "تصنيع شاشات OLED وLED والغسالات الأوتوماتيكية الحديثة بنظم الذكاء الاصطناعي والتصدير الإقليمي",
    city: "sharqia",
    governorate: "الشرقية",
    address: "مجمع LG الصناعي، المنطقة الصناعية B4، العاشر من رمضان، الشرقية",
    phone1: "015417000",
    mobile: "01005588661",
    hotline: "19960",
    website: "https://www.lg.com/eg_ar",
    latitude: 30.3156,
    longitude: 31.7645,
    fleetSize: 230,
    fleetType: "شاحنات نقل أجهزة إلكترونية وغسالات، تريلات شحن صادرات للموانئ البحرية، وأساطيل صيانة ودعم فني",
    fleetTires: "315/80R22.5 • 295/80R22.5 • 225/75R17.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "قاعدة الإنتاج التصديرية الرئيسية لمجموعة إل جي الكورية في شمال إفريقيا والشرق الأوسط",
    contactPerson: "مدير عام النقل والأسطول المركزي",
    contactTitle: "Central Transport & Logistics Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.3156,31.7645"
  },
  {
    id: "eg_titan_904",
    nameAr: "شركة وايت ويل إيجيبت لتصنيع الأجهزة المنزلية (White Whale Egypt)",
    nameEn: "White Whale Egypt Mega Home Appliances Manufacturing",
    sector: "manufacturing",
    subSector: "تصنيع الثلاجات الكورية المزدوجة، الديب فريزر الرأسي، التكييفات الإسبليت، وميكروويف المطابخ",
    city: "giza",
    governorate: "الجيزة",
    address: "المنطقة الصناعية الثالثة، السادس من أكتوبر، الجيزة",
    phone1: "0238339000",
    mobile: "01007711883",
    hotline: "19086",
    website: "https://www.whitewhale.com.eg",
    latitude: 29.9612,
    longitude: 30.9289,
    fleetSize: 160,
    fleetType: "شاحنات صندوقية لنقل الثلاجات والفريزر، سيارات خدمة وتركيبات سريعة، وتريلات نقل خامات صاج وبلاستيك",
    fleetTires: "295/80R22.5 • 225/75R17.5 • 315/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "العلامة الكورية المرموقة للأجهزة المنزلية بأسطول دعم وتوزيع يغطي معارض الأجهزة والموزعين المعتمدين",
    contactPerson: "مدير عام الحركة والخدمات الميدانية",
    contactTitle: "Field Services & Movement Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.9612,30.9289"
  },
  {
    id: "eg_titan_905",
    nameAr: "مجموعة مصانع كريازي للصناعات الهندسية (Kiriazi Group - مجمع مصانع العاشر من رمضان)",
    nameEn: "Kiriazi Group for Home Appliances Mega Complex (10th of Ramadan)",
    sector: "manufacturing",
    subSector: "أكبر مصانع لتصنيع الثلاجات المنزلية، الديب فريزر الأفقي والرأسي، الغسالات، والبوتاجازات الفولاذية",
    city: "sharqia",
    governorate: "الشرقية",
    address: "المنطقة الصناعية A1، العاشر من رمضان، الشرقية",
    phone1: "015410100",
    mobile: "01009933225",
    hotline: "19082",
    website: "https://www.kiriazi.com",
    latitude: 30.3012,
    longitude: 31.7456,
    fleetSize: 270,
    fleetType: "أضخم أسطول شاحنات توزيع أجهزة منزلية مغلقة، تريلات شحن معارض ومستودعات إقليمية، وسيارات صيانة فورية",
    fleetTires: "315/80R22.5 • 295/80R22.5 • 225/75R17.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "أحد أقدم وأعرق قلاع تصنيع الثلاجات والأجهزة المنزلية الوطنية ذات الشعبية الواسعة والاعتمادية الفائقة",
    contactPerson: "رئيس قطاعات الأسطول والنقل المركزي",
    contactTitle: "Central Fleets & Movement Sector Head",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.3012,31.7456"
  },
  {
    id: "eg_titan_906",
    nameAr: "شركة إليكترولوكس مصر للأجهزة المنزلية (Electrolux Egypt - زانوسي وإيديال وأوليمبيك)",
    nameEn: "Electrolux Egypt Mega Plants (Zanussi, Olympic Electric, Ideal)",
    sector: "manufacturing",
    subSector: "مجمعات تصنيع غسالات زانوسي، سخانات أوليمبيك إلكتريك، ثلاجات إيديال، والبوتاجازات الحديثة",
    city: "sharqia",
    governorate: "الشرقية",
    address: "المنطقة الصناعية الثالثة، العاشر من رمضان، الشرقية",
    phone1: "015411200",
    mobile: "01001155447",
    hotline: "19999",
    website: "https://www.electrolux.com.eg",
    latitude: 30.3078,
    longitude: 31.7589,
    fleetSize: 290,
    fleetType: "أساطيل شاحنات شحن وتوزيع أجهزة منزلية، فانات صيانة زانوسي المعتمدة، وتريلات تصدير منتجات للشرق الأوسط",
    fleetTires: "315/80R22.5 • 295/80R22.5 • 225/75R17.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "العملاق السويدي المالك للعلامات التاريخية زانوسي وأوليمبيك وإيديال بأكبر أسطول صيانة منزلية في مصر",
    contactPerson: "مدير عام النقل والأسطول الميداني",
    contactTitle: "Fleet Operations & Logistics Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.3078,31.7589"
  },
  {
    id: "eg_titan_907",
    nameAr: "مجموعة العربي للصناعات الهندسية والتجارية (Elaraby Group - مجمع مصانع قويسنا وبنها)",
    nameEn: "Elaraby Group Mega Industrial Complex (Toshiba, Sharp, Tornado)",
    sector: "manufacturing",
    subSector: "أكبر مجمع صناعي للأجهزة المنزلية والإلكترونية في الشرق الأوسط (توشيبا، شارب، تورنيدو، هوفر، وسوني)",
    city: "monufia",
    governorate: "المنوفية",
    address: "المنطقة الصناعية بقويسنا، الكيلو 60 طريق القاهرة - الإسكندرية الزراعي، المنوفية",
    phone1: "0482570000",
    mobile: "01003377669",
    hotline: "19319",
    website: "https://www.elarabygroup.com",
    latitude: 30.5289,
    longitude: 31.1412,
    fleetSize: 520,
    fleetType: "أضخم أسطول شاحنات توزيع، تريلات نقل ثقيل، سيارات صيانة منزلية فورية مجهزة، وفانات توزيع قطع غيار",
    fleetTires: "315/80R22.5 • 295/80R22.5 • 225/75R17.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "قلعة الصناعة الوطنية الأولى في الأجهزة المنزلية والإلكترونيات والشاشات ومحركات الغسالات والمراوح في إفريقيا",
    contactPerson: "رئيس قطاعات النقل والأسطول المركزي وخدمة ما بعد البيع",
    contactTitle: "Central Fleet & Post-Sales Logistics Sector Head",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.5289,31.1412"
  },
  {
    id: "eg_titan_908",
    nameAr: "شركة صناعة وسائل النقل إم سي في (MCV - مصانع أتوبيسات وشاحنات مرسيدس بالصالحية)",
    nameEn: "Manufacturing Commercial Vehicles (MCV Mega Plants - Salheya)",
    sector: "manufacturing",
    subSector: "أكبر مصنع لتصنيع وتصدير أتوبيسات النقل الجماعي والسياحي، أتوبيسات لندن الكهربائية، وشاحنات مرسيدس-بنز",
    city: "sharqia",
    governorate: "الشرقية",
    address: "المنطقة الصناعية بمدينة الصالحية الجديدة، الشرقية",
    phone1: "0553201000",
    mobile: "01005599882",
    hotline: "19628",
    website: "https://www.mcv-eg.com",
    latitude: 30.6541,
    longitude: 31.8912,
    fleetSize: 310,
    fleetType: "حاملات شاحنات وأتوبيسات هيدروليكية، شاحنات نقل هياكل ومحركات مرسيدس-بنز ثقيلة، وسيارات خدمة طرق",
    fleetTires: "315/80R22.5 • 385/65R22.5 • 12.00R24",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "فخر الصناعة الهندسية المصرية المصدر الأكبر للأتوبيسات الفاخرة لبريطانيا وألمانيا ودول الخليج وأفريقيا",
    contactPerson: "نائب رئيس مجلس الإدارة للإنتاج والشحن الدولي",
    contactTitle: "Vice President - Plant Logistics & Global Shipping",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.6541,31.8912"
  },
  {
    id: "eg_titan_909",
    nameAr: "مجموعة جي بي كورب للسيارات التجارية ومعدات النقل (GB Corp Commercial Mega Plants - مدينة السادات)",
    nameEn: "GB Corp Commercial Vehicles & Heavy Equipment (Sadat City)",
    sector: "manufacturing",
    subSector: "مجمعات تجميع وتصنيع شاحنات النقل الثقيل فولفو، شاحنات ميتسوبيشي فوزو، أتوبيسات وهيئات النقل العام",
    city: "monufia",
    governorate: "المنوفية",
    address: "المنطقة الصناعية السابعة، مدينة السادات، المنوفية",
    phone1: "0482603000",
    mobile: "01007722446",
    hotline: "16611",
    website: "https://www.gb-corporation.com",
    latitude: 30.3712,
    longitude: 30.5189,
    fleetSize: 280,
    fleetType: "تريلات حاملات شاحنات، سيارات صيانة متنقلة لخدمة أساطيل النقل الثقيل، وتريلات نقل شاسيهات ومحركات",
    fleetTires: "315/80R22.5 • 385/65R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "العملاق التجاري الأكبر في مصر في قطاع الشاحنات التجارية والحافلات والمعدات الثقيلة وخدمات ما بعد البيع",
    contactPerson: "رئيس قطاعات الأسطول التجاري واللوجستيات الميدانية",
    contactTitle: "Commercial Fleet & Field Logistics Sector Head",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.3712,30.5189"
  },
  {
    id: "eg_titan_910",
    nameAr: "شركة سوزوكي إيجيبت لتصنيع وتجميع المركبات (Suzuki Egypt Assembly Plants)",
    nameEn: "Suzuki Egypt Mega Vehicle Assembly Complex (6th of October)",
    sector: "manufacturing",
    subSector: "مجمعات تجميع سيارات الفان التجارية، الميكروباص 7 راكب، الشاحنات الخفيفة، والسيارات الملاكي",
    city: "giza",
    governorate: "الجيزة",
    address: "المنطقة الصناعية الثالثة، السادس من أكتوبر، الجيزة",
    phone1: "0238330500",
    mobile: "01009944118",
    hotline: "16838",
    website: "https://www.suzukiegypt.com",
    latitude: 29.9578,
    longitude: 30.9345,
    fleetSize: 175,
    fleetType: "تريلات حاملات سيارات لنقل مركبات سوزوكي للمعارض، شاحنات قطع غيار، وسيارات دعم فني ميداني",
    fleetTires: "315/80R22.5 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "رائدة مركبات النقل الخفيف والفان التجارية في مصر الأكثر استخداماً في التوزيع الداخلي والمشروعات الصغيرة",
    contactPerson: "مدير عام النقل والتوزيع للمعارض",
    contactTitle: "Showroom Distribution & Logistics Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.9578,30.9345"
  },
  {
    id: "eg_titan_911",
    nameAr: "شركة مانتراك مصر للمعدات الثقيلة ومولدات كاتربيلر (Mantrac Egypt - كاتربيلر)",
    nameEn: "Mantrac Egypt (Caterpillar Mega Heavy Equipment & Fleets Hub)",
    sector: "manufacturing",
    subSector: "تجميع وتوزيع معدات التشييد الثقيلة كاتربيلر، الحفارات واللوادر، مولدات الكهرباء العملاقة، ومحركات الديزل",
    city: "giza",
    governorate: "الجيزة",
    address: "الكيلو 28، طريق مصر - إسكندرية الصحراوي، القرية الذكية / السادس من أكتوبر",
    phone1: "0235390000",
    mobile: "01001166885",
    hotline: "19266",
    website: "https://www.mantracegypt.com",
    latitude: 30.0712,
    longitude: 31.0189,
    fleetSize: 260,
    fleetType: "تريلات لوابد هيدروليكية لنقل الحفارات والبلدوزرات العملاقة، سيارات ورش صيانة ميدانية لشركات المقاولات والنفط",
    fleetTires: "385/65R22.5 • 315/80R22.5 • 12.00R24",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الوكيل الحصري لكاتربيلر بمصر وإحدى أكبر شركات توزيع المعدات الثقيلة والمولدات عالمياً التابعة لمجموعة منصور",
    contactPerson: "مدير عام أسطول النقل الثقيل واللوابد الميدانية",
    contactTitle: "Heavy Lowbed Fleet & Field Support Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.0712,31.0189"
  },
  {
    id: "eg_titan_912",
    nameAr: "شركة إس إم جي الهندسية للسيارات (SMG Engineering - أساطيل سكانيا وبورش وبوش)",
    nameEn: "SMG Engineering Automotive Co. (Scania Mega Trucks & Bus Hub)",
    sector: "manufacturing",
    subSector: "تجميع شاحنات سكانيا السويدية الثقيلة، محطات صيانة أساطيل النقل الثقيل، وتوزيع بطاريات ومعدات بوش الألمانية",
    city: "cairo",
    governorate: "القاهرة",
    address: "طريق مصر - الإسماعيلية الصحراوي، الكيلو 26، القاهرة",
    phone1: "0226561000",
    mobile: "01003388229",
    hotline: "19544",
    website: "https://www.smg.com.eg",
    latitude: 30.1789,
    longitude: 31.4512,
    fleetSize: 190,
    fleetType: "تريلات صيانة وإنقاذ شاحنات سكانيا على الطرق السريعة، حاملات سيارات، وشاحنات توزيع قطع غيار بوش",
    fleetTires: "315/80R22.5 • 385/65R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الوكيل التاريخي لشاحنات سكانيا ومعدات بوش ومقدم حلول الأساطيل الموثوقة لكبرى شركات النقل بمصر",
    contactPerson: "مدير عام الدعم الفني للأساطيل والشحن",
    contactTitle: "Fleet Solutions & Technical Support General Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.1789,31.4512"
  },
  {
    id: "eg_titan_913",
    nameAr: "شركة شنايدر إليكتريك مصر الإقليمية (Schneider Electric Egypt Mega Switchgear Plant - بدر)",
    nameEn: "Schneider Electric Egypt Regional Mega Switchgear Hub (Badr City)",
    sector: "manufacturing",
    subSector: "أكبر مصنع إقليمي لتصنيع لوحات الجهد المتوسط والمنخفض الذكية، محطات المحولات المدمجة، وأنظمة إدارة الطاقة",
    city: "cairo",
    governorate: "القاهرة",
    address: "المنطقة الصناعية الأولى، مدينة بدر، طريق القاهرة - السويس، القاهرة",
    phone1: "0228795000",
    mobile: "01005511773",
    hotline: "19733",
    website: "https://www.se.com/eg",
    latitude: 30.1412,
    longitude: 31.7124,
    fleetSize: 185,
    fleetType: "شاحنات شحن مهمات كهربائية ولوحات ذكية معزولة، سيارات اختبار شبكات ومهمات، وتريلات تصدير للموانئ",
    fleetTires: "315/80R22.5 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "المركز الإقليمي لتصنيع اللوحات الكهربائية الذكية للشرق الأوسط وإفريقيا والمورد لكافة المشروعات القومية المصرية",
    contactPerson: "مدير عام العمليات اللوجستية والنقل التصديري",
    contactTitle: "Regional Logistics & Outbound Transport Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.1412,31.7124"
  },
  {
    id: "eg_titan_914",
    nameAr: "شركة إيه بي بي مصر للصناعات الكهربائية (ABB Egypt Mega Transformer & Automation Plants)",
    nameEn: "ABB Egypt Mega Electrification & Automation Plants (10th of Ramadan)",
    sector: "manufacturing",
    subSector: "مجمعات تصنيع محولات التوزيع، خلايا الجهد العالي والمتوسط، ومحطات الشحن السريع للمركبات الكهربائية",
    city: "sharqia",
    governorate: "الشرقية",
    address: "المنطقة الصناعية B1، العاشر من رمضان، الشرقية",
    phone1: "015414500",
    mobile: "01007733994",
    hotline: "19722",
    website: "https://new.abb.com/eg",
    latitude: 30.3089,
    longitude: 31.7545,
    fleetSize: 170,
    fleetType: "تريلات نقل محولات ثقيلة، شاحنات مجهزة بنظم تثبيت هيدروليكية للوحات المفاتيح الحساسة، وسيارات دعم مشاريع",
    fleetTires: "315/80R22.5 • 385/65R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "رائدة التكنولوجيا السويسرية السويدية في قطاع الطاقة الكهربائية والتحكم الآلي ومورد محطات العاصمة الإدارية",
    contactPerson: "مدير عام سلاسل الإمداد والشحن للمشروعات",
    contactTitle: "Project Freight & Supply Chain General Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.3089,31.7545"
  },
  {
    id: "eg_titan_915",
    nameAr: "شركة سيمنس إينرجي مصر للمهمات التوربينية ومحطات الطاقة (Siemens Energy Egypt)",
    nameEn: "Siemens Energy Egypt Mega Service & Heavy Equipment Center (Ain Sokhna)",
    sector: "manufacturing",
    subSector: "مركز الصيانة والخدمات التكنولوجية المتطور لتوربينات الغاز والرياح وتصنيع المكونات الدقيقة لمحطات الطاقة",
    city: "suez",
    governorate: "السويس",
    address: "المنطقة الاقتصادية لقناة السويس، العين السخنة، السويس",
    phone1: "0623395000",
    mobile: "01009955331",
    hotline: "19788",
    website: "https://www.siemens-energy.com/eg",
    latitude: 29.6245,
    longitude: 32.3412,
    fleetSize: 140,
    fleetType: "مقطورات هيدروليكية ذات محاور متعددة (Goldhofer) لنقل ريش التوربينات والمولدات العملاقة، وشاحنات صيانة",
    fleetTires: "385/65R22.5 • 315/80R22.5 • 12.00R24",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الشريك التكنولوجي الاستراتيجي لبناء محطات الكهرباء العملاقة (بني سويف، البرلس، والعاصمة) ومشاريع الهيدروجين الأخضر",
    contactPerson: "رئيس قطاعات النقل الثقيل والأحمال التوربينية الفائقة",
    contactTitle: "Heavy Lift & Turbine Transport Sector Head",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.6245,32.3412"
  },
  {
    id: "eg_titan_916",
    nameAr: "شركة ليجراند مصر للأجهزة والمفاتيح الكهربائية (Legrand Egypt - مصانع مدينة السادات)",
    nameEn: "Legrand Egypt Mega Low Voltage Wiring Devices Plants (Sadat City)",
    sector: "manufacturing",
    subSector: "تصنيع مفاتيح ومآخذ الكهرباء الفاخرة، القواطع الأوتوماتيكية، لوحات التوزيع السكنية، وحلول المنازل الذكية",
    city: "monufia",
    governorate: "المنوفية",
    address: "المنطقة الصناعية الثانية، مدينة السادات، المنوفية",
    phone1: "0482601700",
    mobile: "01001188553",
    hotline: "19972",
    website: "https://www.legrand.eg",
    latitude: 30.3789,
    longitude: 30.5124,
    fleetSize: 135,
    fleetType: "شاحنات شحن منتجات كهربائية، فانات توزيع لمعارض الكهرباء والمشروعات السكنية الفاخرة، وتريلات تصدير",
    fleetTires: "295/80R22.5 • 225/75R17.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الفرع المصري لمجموعة ليجراند الفرنسية العالمية والرائدة في التجهيزات الكهربائية للمباني والكومباوندات",
    contactPerson: "مدير عام التوزيع والأسطول التجاري",
    contactTitle: "Commercial Distribution & Fleets Lead",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.3789,30.5124"
  },
  {
    id: "eg_titan_917",
    nameAr: "شركة السويدي لتصنيع أبراج طاقة الرياح (Elsewedy Wind Energy Towers - السخنة)",
    nameEn: "Elsewedy Wind Energy Towers Mega Facility (SWEG Ain Sokhna)",
    sector: "manufacturing",
    subSector: "تصنيع أبراج طاقة الرياح الفولاذية العملاقة والهياكل الثقيلة لمزارع الطاقة المتجددة في خليج السويس وغارب",
    city: "suez",
    governorate: "السويس",
    address: "المنطقة الاقتصادية الخاصة، شمال غرب خليج السويس، العين السخنة",
    phone1: "0623396500",
    mobile: "01003311776",
    hotline: "16274",
    website: "https://www.elsewedyelectric.com/wind-towers",
    latitude: 29.6512,
    longitude: 32.3214,
    fleetSize: 150,
    fleetType: "مقطورات نقل أبراج تلسكوبية فائقة الطول (Telescopic Semi-Trailers) حتى طول 60 متراً، وتريلات معدات ثقيلة",
    fleetTires: "385/65R22.5 • 315/80R22.5 • 12.00R24",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "المصنع الأول والأضخم في إفريقيا والشرق الأوسط لتصنيع أبراج الرياح الضخمة المصدرة للمشروعات القومية وأوروبا",
    contactPerson: "مدير عام النقل التخصصي والأطوال الفائقة",
    contactTitle: "Oversized Wind Towers Transport General Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.6512,32.3214"
  },
  {
    id: "eg_titan_918",
    nameAr: "مجموعة بنية للاتصالات وتصنيع كابلات الألياف الضوئية (Benya Group Mega Fiber Optic Plant)",
    nameEn: "Benya Cables Mega Factory (Suez Canal Economic Zone)",
    sector: "manufacturing",
    subSector: "أضخم مصنع في إفريقيا والشرق الأوسط لإنتاج كابلات الألياف الضوئية (الفايبر) لتغطية التحول الرقمي المصري",
    city: "suez",
    governorate: "السويس",
    address: "المنطقة الاقتصادية لقناة السويس، تيدا السخنة، السويس",
    phone1: "0623397000",
    mobile: "01005533998",
    hotline: "19827",
    website: "https://www.benyagroup.com",
    latitude: 29.6845,
    longitude: 32.3389,
    fleetSize: 140,
    fleetType: "شاحنات شحن بكر فايبر مجهزة، سيارات لحام واختبار كابلات ضوئية ميدانية، وتريلات تصدير للموانئ الإفريقية",
    fleetTires: "315/80R22.5 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الصرح التكنولوجي القومي الاستراتيجي بالشراكة مع الهيئة العربية للتصنيع لتوطين صناعة كابلات الإنترنت والاتصالات",
    contactPerson: "رئيس قطاعات اللوجستيات والمشروعات الميدانية",
    contactTitle: "Projects Logistics & Supply Chain Sector Head",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.6845,32.3389"
  },
  {
    id: "eg_titan_919",
    nameAr: "شركة كولدير مصر لأجهزة التكييف والتبريد الصناعي (Koldair Egypt - مجمعات العاشر من رمضان)",
    nameEn: "Koldair Egypt for Air Conditioning & Industrial Refrigeration",
    sector: "manufacturing",
    subSector: "تصنيع كولديرات المياه العامة، التكييفات المركزية والصحراوية، ومبردات المياه للمساجد والمدارس والمصانع",
    city: "sharqia",
    governorate: "الشرقية",
    address: "المنطقة الصناعية B2، العاشر من رمضان، الشرقية",
    phone1: "015413300",
    mobile: "01007755223",
    hotline: "19772",
    website: "https://www.koldair.com.eg",
    latitude: 30.3045,
    longitude: 31.7512,
    fleetSize: 125,
    fleetType: "شاحنات شحن مبردات وكولديرات مياه، سيارات تركيبات وصيانة ميدانية، وتريلات نقل صاج مدرفل وخامات فوم",
    fleetTires: "295/80R22.5 • 225/75R17.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "العلامة التراثية الرائدة والاسم المرادف لمبردات المياه في مصر والعالم العربي منذ أكثر من 70 عاماً",
    contactPerson: "مدير عام النقل والأسطول الداخلي",
    contactTitle: "Inbound & Outbound Transport Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.3045,31.7512"
  },
  {
    id: "eg_titan_920",
    nameAr: "شركة ميراكو كارير لأنظمة التكييف والتبريد (Miraco Carrier Mega HVAC Complex)",
    nameEn: "Miraco Carrier Mega HVAC & Industrial Chillers Complex",
    sector: "manufacturing",
    subSector: "تصنيع أجهزة التكييف كاريير وميراكو، وحدات التبريد المركزية (Chillers)، وأنظمة التبريد التجاري للمولات",
    city: "giza",
    governorate: "الجيزة",
    address: "المنطقة الصناعية بمدينة أبو رواش، طريق مصر - إسكندرية الصحراوي، الجيزة",
    phone1: "0235391200",
    mobile: "01009977445",
    hotline: "19111",
    website: "https://www.miraco.com.eg",
    latitude: 30.0512,
    longitude: 31.0678,
    fleetSize: 220,
    fleetType: "شاحنات شحن أجهزة تكييف، تريلات نقل شيللرات مركزية ثقيلة، وأساطيل فانات مهندسي وفنيي الصيانة الدورية",
    fleetTires: "315/80R22.5 • 295/80R22.5 • 225/75R16",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "القلعة الصناعية الأولى لأنظمة التكييف والتبريد المركزي في مصر والمورد المعتمد للمستشفيات والمدن الذكية والمطارات",
    contactPerson: "رئيس قطاعات الأسطول والدعم الميداني القومي",
    contactTitle: "National Fleets & Field Service Sector Head",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.0512,31.0678"
  },
  {
    id: "eg_titan_921",
    nameAr: "الشركة العربية الأمريكية للسيارات (AAV - مصانع جيب وتويوتا التابعة للهيئة العربية للتصنيع)",
    nameEn: "Arab American Vehicles (AAV Jeep & Toyota Mega Assembly Plant)",
    sector: "manufacturing",
    subSector: "مجمعات تجميع سيارات الدفع الرباعي جيب ورانجلر وجراند شيروكي، وتويوتا فورتشنر، والشاحنات العسكرية والمدنية",
    city: "cairo",
    governorate: "القاهرة",
    address: "طريق مصر السويس الصحراوي، الكيلو 4.5، ألماظة، القاهرة",
    phone1: "0222915000",
    mobile: "01001133996",
    hotline: "19842",
    website: "https://www.aav.com.eg",
    latitude: 30.0989,
    longitude: 31.3789,
    fleetSize: 180,
    fleetType: "تريلات حاملات سيارات دفع رباعي، شاحنات نقل هياكل ومحركات، وسيارات اختبار أداء وتجهيزات عسكرية",
    fleetTires: "315/80R22.5 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الصرح الصناعي التاريخي المشترك بين الهيئة العربية للتصنيع وكرايسلر العالمية المجمع المعتمد لسيارات جيب بمصر",
    contactPerson: "مدير عام الشحن والأسطول التنسيقي",
    contactTitle: "Vehicle Shipping & Fleet Operations Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.0989,31.3789"
  },
  {
    id: "eg_titan_922",
    nameAr: "مجموعة بهجت للصناعات الهندسية والإلكترونيات (Bahgat Group - مصانع جولدي بالسادس من أكتوبر)",
    nameEn: "Bahgat Group Mega Industrial Complex (Goldi Electronics)",
    sector: "manufacturing",
    subSector: "تصنيع شاشات التلفزيون جولدي، الأجهزة المنزلية، الثلاجات، المكونات البلاستيكية، والأثاث المكتبي المتطور",
    city: "giza",
    governorate: "الجيزة",
    address: "مدينة دريم لاند، السادس من أكتوبر، طريق الواحات، الجيزة",
    phone1: "0238555000",
    mobile: "01003355118",
    hotline: "19455",
    website: "https://www.bahgat.com",
    latitude: 29.9745,
    longitude: 31.0289,
    fleetSize: 150,
    fleetType: "شاحنات نقل أجهزة إلكترونية، تريلات شحن ثلاجات، وسيارات فنية لخدمة المشروعات العقارية والتجارية",
    fleetTires: "295/80R22.5 • 225/75R17.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "المجموعة الوطنية الرائدة المؤسسة لصناعة الإلكترونيات والشاشات الوطنية في مصر (جولدي)",
    contactPerson: "مدير عام الخدمات اللوجستية والأسطول",
    contactTitle: "Logistics Operations & Fleets Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.9745,31.0289"
  },
  {
    id: "eg_titan_923",
    nameAr: "شركة إليكتراستار لتصنيع الثلاجات والديب فريزر (Electrostar Mega Industrial Complex)",
    nameEn: "Electrostar for Refrigerators & Freezers Mega Complex (6th of October)",
    sector: "manufacturing",
    subSector: "تصنيع أجهزة الديب فريزر الأفقي والرأسي نوفروست، الثلاجات المنزلية، والبوتاجازات الفاخرة",
    city: "giza",
    governorate: "الجيزة",
    address: "المنطقة الصناعية الرابعة، السادس من أكتوبر، الجيزة",
    phone1: "0238203500",
    mobile: "01005577334",
    hotline: "19056",
    website: "https://www.electrostar.com.eg",
    latitude: 29.9456,
    longitude: 30.9167,
    fleetSize: 165,
    fleetType: "شاحنات شحن ديب فريزر وثلاجات للموزعين، سيارات صيانة منزلية فورية، وتريلات نقل خامات صاج وبلاستيك",
    fleetTires: "295/80R22.5 • 225/75R17.5 • 315/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "رائدة صناعة أجهزة الديب فريزر في مصر بأسطول توزيع يغطي كل محافظات وقرى ونجوع الوجهين البحري والقبلي",
    contactPerson: "رئيس قطاعات الأسطول والخدمات اللوجستية",
    contactTitle: "Fleet & Logistics Sector Head",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.9456,30.9167"
  },
  {
    id: "eg_titan_924",
    nameAr: "مجموعة القصراوي لتجميع وتوزيع السيارات والشاحنات (Kasrawy Group - جاك وإيفيكو وسيتروين)",
    nameEn: "Kasrawy Group Mega Automotive & Heavy Commercial Complex",
    sector: "manufacturing",
    subSector: "تجميع وتوزيع شاحنات جاك التجارية، سيارات إيفيكو للنقل الثقيل، شبكات الصيانة المركزية ومستودعات التوزيع",
    city: "giza",
    governorate: "الجيزة",
    address: "الكيلو 28، طريق مصر - إسكندرية الصحراوي، أبو رواش، الجيزة",
    phone1: "0235393000",
    mobile: "01007799557",
    hotline: "19299",
    website: "https://www.kasrawygroup.com",
    latitude: 30.0612,
    longitude: 31.0545,
    fleetSize: 190,
    fleetType: "تريلات حاملات شاحنات وسيارات، سيارات ورش صيانة طرق سريعة، وشاحنات توزيع قطع غيار معتمدة",
    fleetTires: "315/80R22.5 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "المجموعة الحائزة على جوائز التميز في خدمات ما بعد البيع لقطاعات الشاحنات التجارية والسيارات بمصر",
    contactPerson: "مدير عام أسطول الشحن والدعم اللوجستي",
    contactTitle: "Fleet Dispatch & Logistic Support Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.0612,31.0545"
  },
  {
    id: "eg_titan_925",
    nameAr: "الشركة المصرية الألمانية للسيارات إيجا (EGA Mercedes-Benz Mega Assembly Plant)",
    nameEn: "Egyptian German Automotive (EGA Mercedes-Benz 6th of October Plant)",
    sector: "manufacturing",
    subSector: "مجمعات التجميع الفاخر لسيارات مرسيدس-بنز الركاب والشاحنات، معالجة وتصنيع أقراص المكابح للتصدير لألمانيا",
    city: "giza",
    governorate: "الجيزة",
    address: "المنطقة الصناعية الرابعة، السادس من أكتوبر، الجيزة",
    phone1: "0238201100",
    mobile: "01009911779",
    hotline: "16362",
    website: "https://www.ega-auto.com",
    latitude: 29.9389,
    longitude: 30.9245,
    fleetSize: 130,
    fleetType: "حاملات سيارات مغلقة ومحمية لشحن السيارات الفاخرة، تريلات شحن صادرات أقراص المكابح للموانئ البحرية",
    fleetTires: "315/80R22.5 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الصرح الوطني فائق الدقة المعتمد من دايملر مرسيدس-بنز العالمية لتجميع السيارات الفاخرة وتصدير مكونات المكابح لشتوتغارت",
    contactPerson: "مدير عام النقل وسلاسل الإمداد الدولية",
    contactTitle: "International Supply Chain & Fleets Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.9389,30.9245"
  },
  {
    id: "eg_titan_926",
    nameAr: "المجموعة البافارية لتصنيع وتجميع سيارات بي إم دبليو (BMW Bavarian Auto Group - مصانع أكتوبر)",
    nameEn: "Bavarian Auto Group (BMW & MINI Mega Assembly Plants - 6th of October)",
    sector: "manufacturing",
    subSector: "مجمع تجميع سيارات بي إم دبليو الفئة السابعة والخامسة والثالثة وسيارات X الدفع الرباعي الفاخرة",
    city: "giza",
    governorate: "الجيزة",
    address: "المنطقة الصناعية الرابعة، السادس من أكتوبر، الجيزة",
    phone1: "0238205000",
    mobile: "01002244883",
    hotline: "19269",
    website: "https://www.bmw-egypt.com",
    latitude: 29.9412,
    longitude: 30.9212,
    fleetSize: 145,
    fleetType: "حاملات سيارات متطورة لنقل السيارات الفاخرة، شاحنات نقل مكونات إنتاج، وأساطيل فانات خدمة بي إم دبليو المتنقلة",
    fleetTires: "315/80R22.5 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الصرح التكنولوجي الأول لتجميع سيارات BMW الألمانية في إفريقيا وفقاً لأعلى معايير الجودة لمجموعة BMW العالمية",
    contactPerson: "مدير عام اللوجستيات والشحن المعتمد",
    contactTitle: "Logistics & Certified Shipping General Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.9412,30.9212"
  },
  {
    id: "eg_titan_927",
    nameAr: "شركة فوتون إيجيبت لتصنيع الشاحنات والمركبات الكهربائية (Foton Egypt Mega Assembly Plants)",
    nameEn: "Foton Egypt Commercial & Electric Vehicles Assembly Plants",
    sector: "manufacturing",
    subSector: "تجميع الأتوبيسات الكهربائية الصديقة للبيئة، المينى باص، والشاحنات الثقيلة بالشراكة مع وزارة الإنتاج الحربي",
    city: "cairo",
    governorate: "القاهرة",
    address: "مجمع مصانع حلوان العسكرية، حلوان، القاهرة",
    phone1: "0225581500",
    mobile: "01004466992",
    hotline: "19834",
    website: "https://www.foton-global.com/egypt",
    latitude: 29.8312,
    longitude: 31.3124,
    fleetSize: 160,
    fleetType: "تريلات حاملات حافلات وشاحنات، سيارات دعم فني وشحن بطاريات متنقلة، وشاحنات شحن هياكل",
    fleetTires: "315/80R22.5 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "المصنع القومي المعتمد لإنتاج وتجميع الأتوبيسات الكهربائية لخدمة العاصمة الإدارية وشبكات النقل الحضري النظيف",
    contactPerson: "رئيس قطاعات الأسطول والتشغيل الميداني",
    contactTitle: "Operations & Fleet Sector Head",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.8312,31.3124"
  },
  {
    id: "eg_titan_928",
    nameAr: "شركة سينوتراك هوو مصر لتجميع شاحنات النقل الثقيل (Sinotruk HOWO Egypt)",
    nameEn: "Sinotruk HOWO Egypt Mega Heavy Duty Trucks Assembly Plant",
    sector: "manufacturing",
    subSector: "تجميع وتصنيع شاحنات النقل الثقيل HOWO، قلابات المحاجر، خلاطات الخرسانة، ورؤوس التريلات العملاقة",
    city: "suez",
    governorate: "السويس",
    address: "المنطقة الاقتصادية شمال غرب خليج السويس، العين السخنة، السويس",
    phone1: "0623398000",
    mobile: "01006688114",
    hotline: "19741",
    website: "https://www.howoegypt.com",
    latitude: 29.6912,
    longitude: 32.3245,
    fleetSize: 175,
    fleetType: "تريلات لوابد لنقل القلابات والخلاطات، سيارات ورش صيانة لشركات المحاجر والإنشاءات، وشاحنات قطع غيار",
    fleetTires: "315/80R22.5 • 12.00R24 • 385/65R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "العلامة الأكثر انتشاراً في قطاع قلابات التعدين والخلاطات والشاحنات الثقيلة في المشروعات القومية المصرية",
    contactPerson: "مدير عام النقل والأسطول الهندسي",
    contactTitle: "Engineering Fleets & Transport Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.6912,32.3245"
  },
  {
    id: "eg_titan_929",
    nameAr: "شركة شاكمان إيجيبت لتجميع الشاحنات والمعدات الثقيلة (Shacman Egypt Heavy Trucks)",
    nameEn: "Shacman Egypt Mega Heavy Trucks & Dumpers Assembly Plant",
    sector: "manufacturing",
    subSector: "تجميع شاحنات شاكمان F3000 وX3000، سيارات ضخ ونقل الخرسانة، وشاحنات صهاريج المواد البترولية",
    city: "giza",
    governorate: "الجيزة",
    address: "المنطقة الصناعية الخامسة، السادس من أكتوبر، الجيزة",
    phone1: "0238206000",
    mobile: "01008811335",
    hotline: "19877",
    website: "https://www.shacmanegypt.com",
    latitude: 29.9312,
    longitude: 30.9012,
    fleetSize: 165,
    fleetType: "تريلات حاملات رؤوس جرارات، سيارات صيانة محاجر ميدانية، وشاحنات توزيع محركات وشاسيهات",
    fleetTires: "315/80R22.5 • 12.00R24 • 385/65R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الشريك المعتمد لشركات المقاولات الكبرى في توريد وصيانة أساطيل النقل الثقيل وقلابات الطرق الوعرة",
    contactPerson: "مدير عام خدمات ما بعد البيع وأساطيل الشاحنات",
    contactTitle: "Fleet Services & Heavy Trucks General Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.9312,30.9012"
  },
  {
    id: "eg_titan_930",
    nameAr: "مجموعة غبور أوتو لسيارات الركوب والتجميع المحلي (GB Auto Passenger Cars - مصانع بريما بأبو رواش)",
    nameEn: "GB Auto Passenger Cars Mega Assembly Plants (Prima Abu Rawash)",
    sector: "manufacturing",
    subSector: "تجميع سيارات هيونداي فيرنا وأكسنت وإلنترا، وشيري تيجو وأريزو، وشانجان بالسوق المصري",
    city: "giza",
    governorate: "الجيزة",
    address: "الكيلو 28، طريق مصر - إسكندرية الصحراوي، المنطقة الصناعية بأبو رواش، الجيزة",
    phone1: "0235392000",
    mobile: "01001144773",
    hotline: "16661",
    website: "https://www.ghabbourauto.com",
    latitude: 30.0645,
    longitude: 31.0612,
    fleetSize: 310,
    fleetType: "أضخم أسطول تريلات حاملات سيارات ذات طابقين لنقل السيارات المنتجة لشبكة الموزعين بكافة المحافظات",
    fleetTires: "315/80R22.5 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "رائد صناعة وتجميع وتوزيع سيارات الركاب في مصر والشرق الأوسط بحصة سوقية تاريخية لا تضاهى",
    contactPerson: "رئيس قطاعات الأسطول وحركة النقل اللوجستي",
    contactTitle: "Vehicle Logistics & Fleets Sector Head",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.0645,31.0612"
  },
  {
    id: "eg_titan_931",
    nameAr: "شركة كينج لونج مصر لتجميع الميكروباص ومركبات الركاب (King Long Egypt Mega Assembly Plant)",
    nameEn: "King Long Egypt Mega Microbus & Van Assembly Plants (6th of October)",
    sector: "manufacturing",
    subSector: "أكبر مصنع لتجميع وتوريد سيارات الميكروباص 14 راكب وسيارات الإسعاف ونقل الركاب بالغاز الطبيعي",
    city: "giza",
    governorate: "الجيزة",
    address: "المنطقة الصناعية الرابعة، السادس من أكتوبر، الجيزة",
    phone1: "0238207500",
    mobile: "01003366887",
    hotline: "19634",
    website: "https://www.kinglongegypt.com",
    latitude: 29.9378,
    longitude: 30.9156,
    fleetSize: 180,
    fleetType: "تريلات حاملات ميكروباصات، شاحنات نقل مكونات هياكل ومحركات، وسيارات صيانة متنقلة لخطوط السير",
    fleetTires: "315/80R22.5 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الميكروباص الأكثر مبيعاً وشعبية في مصر والمشارك الأكبر في خطة الإحلال والعمل بالغاز الطبيعي",
    contactPerson: "مدير عام النقل والتوزيع الميداني",
    contactTitle: "Commercial Fleets & Distribution Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.9378,30.9156"
  },
  {
    id: "eg_titan_932",
    nameAr: "شركة فاو مصر لتجميع الشاحنات وسيارات النقل الخفيف (FAW Trucks Egypt)",
    nameEn: "FAW Trucks Egypt Commercial Vehicles Assembly Plants",
    sector: "manufacturing",
    subSector: "تجميع شاحنات النقل الخفيف والمتوسط، تريلات النقل الثقيل، وسيارات النصف نقل بالمنطقة الحرة",
    city: "alexandria",
    governorate: "الإسكندرية",
    address: "المنطقة الحرة العامة بالعامرية، الإسكندرية",
    phone1: "034500500",
    mobile: "01005588119",
    hotline: "19839",
    website: "https://www.faw-egypt.com",
    latitude: 31.0214,
    longitude: 29.8124,
    fleetSize: 145,
    fleetType: "تريلات حاملات شاحنات، سيارات صيانة متنقلة، وشاحنات شحن قطع غيار للمحافظات",
    fleetTires: "315/80R22.5 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الفرع المصري لأقدم وأكبر صانع شاحنات صيني بأسطول دعم فني ومبيعات منتشر بمحافظات الدلتا والإسكندرية",
    contactPerson: "مدير عام المبيعات اللوجستية والأسطول",
    contactTitle: "Logistics Sales & Fleet General Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=31.0214,29.8124"
  },
  {
    id: "eg_titan_933",
    nameAr: "مجموعة منصور للسيارات (Mansour Automotive - شيفروليه وإم جي وأوبل وبيجو)",
    nameEn: "Mansour Automotive Mega Distribution & Logistics Complex",
    sector: "manufacturing",
    subSector: "أكبر موزع ومجمع لسيارات شيفروليه النقل والملاكي، إم جي، أوبل، وبيجو، ومراكز الخدمات المتكاملة",
    city: "giza",
    governorate: "الجيزة",
    address: "طريق مصر - إسكندرية الصحراوي، الكيلو 28، أبو رواش، الجيزة",
    phone1: "0235394000",
    mobile: "01007711332",
    hotline: "16424",
    website: "https://www.mansourtransport.com",
    latitude: 30.0689,
    longitude: 31.0589,
    fleetSize: 380,
    fleetType: "أساطيل تريلات حاملات سيارات، شاحنات توزيع قطع غيار سريعة، وسيارات إنقاذ وطوارئ على الطرق السريعة",
    fleetTires: "315/80R22.5 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الموزع رقم 1 لجنرال موتورز وشيفروليه في العالم وأكبر كيان لتجارة وتوزيع السيارات في الشرق الأوسط",
    contactPerson: "رئيس قطاعات اللوجستيات وحركة الأساطيل المركزية",
    contactTitle: "Central Fleets & Logistics Sector Head",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.0689,31.0589"
  },
  {
    id: "eg_titan_934",
    nameAr: "شركة تويوتا إيجيبت لتوزيع وتجهيز المركبات (Toyota Egypt Mega Logistics & Distribution Hub)",
    nameEn: "Toyota Egypt Mega Logistics, Body Building & Fleets Hub",
    sector: "manufacturing",
    subSector: "تجهيز وتوزيع شاحنات تويوتا هايلوكس، ميكروباص هاي إيس، سيارات النقل التجاري، ومراكز الصيانة المركزية",
    city: "cairo",
    governorate: "القاهرة",
    address: "المنطقة الصناعية بالعباسية، طريق صلاح سالم، القاهرة / مدينة السادات",
    phone1: "0223420000",
    mobile: "01009933556",
    hotline: "16550",
    website: "https://www.toyota.com.eg",
    latitude: 30.0678,
    longitude: 31.2891,
    fleetSize: 220,
    fleetType: "حاملات سيارات تويوتا، شاحنات شحن قطع غيار معتمدة، وسيارات خدمة أعطال متنقلة لشركات البترول والسفارات",
    fleetTires: "315/80R22.5 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الممثل الحصري لشركة تويوتا العالمية ومورد أساطيل المركبات لقطاعات البترول والمقاولات والسياحة في مصر",
    contactPerson: "مدير عام اللوجستيات والأسطول التجاري",
    contactTitle: "Commercial Fleet & Logistics General Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.0678,31.2891"
  },
  {
    id: "eg_titan_935",
    nameAr: "الشركة المصرية لتصنيع وسائل النقل إيتامكو (Ghabbour Commercial - مصانع باجاج والتوك توك)",
    nameEn: "Egyptian Transport Manufacturing Co. (ETAMCO Ghabbour)",
    sector: "manufacturing",
    subSector: "تصنيع وتجميع مركبات التوك توك باجاج، الدراجات النارية، سيارات الفان لنقل البضائع، ومعدات النقل الخفيف",
    city: "qalyubia",
    governorate: "القليوبية",
    address: "طريق مصر - الإسكندرية الزراعي، قليوب، القليوبية",
    phone1: "0132147000",
    mobile: "01001166224",
    hotline: "16611",
    website: "https://www.etamco.com.eg",
    latitude: 30.1945,
    longitude: 31.2089,
    fleetSize: 180,
    fleetType: "تريلات تريلا ذات طوابق لنقل مركبات التوك توك والدراجات النارية، شاحنات قطع غيار، وتريلات شحن معارض",
    fleetTires: "315/80R22.5 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "المصنع الأكبر لمركبات النقل الخفيف والتنقل الحضري في مصر التابع لمجموعة جي بي أوتو كورب",
    contactPerson: "مدير عام النقل وسلاسل الإمداد",
    contactTitle: "Supply Chain & Transport Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.1945,31.2089"
  },
  {
    id: "eg_titan_936",
    nameAr: "شركة النصر لصناعة السيارات (NASCO - مصانع وادي حوف التاريخية)",
    nameEn: "El Nasr Automotive Manufacturing Co. (NASCO Historic Plants)",
    sector: "manufacturing",
    subSector: "إعادة إحياء وتطوير مصانع تجميع الأتوبيسات السياحية والنقل العام، ميني باص الغاز، والسيارات الكهربائية",
    city: "cairo",
    governorate: "القاهرة",
    address: "وادي حوف، حلوان، القاهرة",
    phone1: "0223690000",
    mobile: "01003388445",
    hotline: "19846",
    website: "https://www.nasr.eg",
    latitude: 29.8678,
    longitude: 31.3124,
    fleetSize: 195,
    fleetType: "تريلات حاملات أتوبيسات وشاحنات، شاحنات نقل هياكل ومحركات، وسيارات صيانة واختبار خطوط إنتاج",
    fleetTires: "315/80R22.5 • 12.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "عميد صناعة السيارات الوطنية في مصر والشرق الأوسط العائد بقوة لتصنيع الأتوبيسات الحديثة وتوطين المركبات الكهربائية",
    contactPerson: "رئيس قطاعات النقل والتشغيل والورش المركزية",
    contactTitle: "Central Fleets & Plant Operations Sector Head",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.8678,31.3124"
  },
  {
    id: "eg_titan_937",
    nameAr: "الشركة الهندسية لصناعة السيارات (EAMCO - وادي حوف حلوان)",
    nameEn: "Engineering Automotive Manufacturing Co. (EAMCO Wadi Hof)",
    sector: "manufacturing",
    subSector: "تصنيع شاسيهات الشاحنات الثقيلة، تصنيع مقطورات النقل وتنك البترول، وأتوبيسات نقل الركاب والعمال",
    city: "cairo",
    governorate: "القاهرة",
    address: "وادي حوف، حلوان، جنوب القاهرة",
    phone1: "0223692500",
    mobile: "01005511887",
    hotline: "19847",
    website: "https://www.eamco.com.eg",
    latitude: 29.8612,
    longitude: 31.3089,
    fleetSize: 160,
    fleetType: "شاحنات شحن شاسيهات وهياكل حديدية، مقطورات هيدروليكية، وسيارات صيانة أساطيل نقل الركاب",
    fleetTires: "315/80R22.5 • 12.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "القلعة التابعة للشركة القابضة للصناعات المعدنية المتخصصة في بناء وتجهيز شاحنات ومقطورات النقل الثقيل",
    contactPerson: "مدير عام النقل والورش الميكانيكية",
    contactTitle: "Mechanical Workshops & Fleet Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.8612,31.3089"
  },
  {
    id: "eg_titan_938",
    nameAr: "مجموعة راية القابضة لحلول اللوجستيات وتجميع المركبات الخفيفة (Raya Auto & Logistics Hub)",
    nameEn: "Raya Auto & Mega Logistics Hub (6th of October)",
    sector: "manufacturing",
    subSector: "تجميع المركبات الكهربائية الخفيفة (سكوتر ومركبات جولف)، وإدارة أضخم شبكات المستودعات والأسطول الذكي بمصر",
    city: "giza",
    governorate: "الجيزة",
    address: "مجمع راية الصناعي، المنطقة الصناعية السادسة، السادس من أكتوبر، الجيزة",
    phone1: "0238276000",
    mobile: "01007733116",
    hotline: "19977",
    website: "https://www.rayacorp.com",
    latitude: 29.9124,
    longitude: 30.8945,
    fleetSize: 240,
    fleetType: "شاحنات شحن بضائع إلكترونية مزودة بتتبع GPS دقيق، فانات توزيع سريع، وتريلات نقل حاويات موانئ",
    fleetTires: "295/80R22.5 • 225/75R17.5 • 315/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "رائدة حلول التجارة الإلكترونية، اللوجستيات المتطورة، وتجميع المركبات الكهربائية الحديثة",
    contactPerson: "رئيس قطاعات النقل والأسطول الذكي",
    contactTitle: "Smart Fleet & Logistics Operations Head",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.9124,30.8945"
  },
  {
    id: "eg_titan_939",
    nameAr: "شركة فريش إليكتريك - مجمع سخانات الغاز والأجهزة الصغيرة (Fresh Badr Mega Industrial Complex)",
    nameEn: "Fresh Electric Mega Water Heaters & Small Appliances Complex (Badr)",
    sector: "manufacturing",
    subSector: "مجمع مصانع سخانات المياه الفورية بالغاز والكهرباء، الخلاطات، المراوح السقفية، والمكانس الكهربائية",
    city: "cairo",
    governorate: "القاهرة",
    address: "المنطقة الصناعية الثانية، مدينة بدر، طريق القاهرة - السويس، القاهرة",
    phone1: "0228794000",
    mobile: "01009955228",
    hotline: "19059",
    website: "https://www.fresh.com.eg/badr",
    latitude: 30.1389,
    longitude: 31.7212,
    fleetSize: 170,
    fleetType: "شاحنات توزيع سخانات وأجهزة صغيرة، سيارات صيانة منزلية فورية مجهزة بقطع غيار، وتريلات تصدير",
    fleetTires: "295/80R22.5 • 225/75R17.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "المجمع التخصصي الأكبر لإنتاج سخانات الغاز الطبيعي والكهرباء الآمنة وتجهيزات المطابخ العصرية بمصر",
    contactPerson: "مدير عام النقل والتوزيع الميداني",
    contactTitle: "Field Distribution & Fleets Lead",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.1389,31.7212"
  },
  {
    id: "eg_titan_940",
    nameAr: "مجموعة العربي - مجمع مصانع بنها للإلكترونيات والشاشات (Elaraby Banha Mega Industrial Complex)",
    nameEn: "Elaraby Banha Mega Technology & Electronics Plants",
    sector: "manufacturing",
    subSector: "تصنيع وتجميع شاشات التلفزيون الذكية، أجهزة الريسيفر، لوحات الدوائر الإلكترونية المطبوعة (PCB)، واللمبات الليد",
    city: "qalyubia",
    governorate: "القليوبية",
    address: "طريق بنها - الزقازيق، بنها، القليوبية",
    phone1: "0133228000",
    mobile: "01001177443",
    hotline: "19319",
    website: "https://www.elarabygroup.com/banha",
    latitude: 30.4612,
    longitude: 31.1891,
    fleetSize: 210,
    fleetType: "شاحنات تريلات مجهزة بنظم أمان فائقة لنقل الشاشات والإلكترونيات، فانات توزيع تجزئة، وتريلات تصدير",
    fleetTires: "315/80R22.5 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "صرح التكنولوجيا الأول لمجموعة العربي في الدلتا المورد الأكبر للشاشات الذكية بالسوق المصري والعربي",
    contactPerson: "مدير عام اللوجستيات والنقل الآمن",
    contactTitle: "Secure Transport & Logistics General Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.4612,31.1891"
  },
  {
    id: "eg_titan_941",
    nameAr: "الشركة المصرية لخدمات التتبع وإدارة الأساطيل إيتراك (ETRAC Fleet Telematics & IoT)",
    nameEn: "ETRAC Egypt Fleet Telematics, IoT & Smart Logistics",
    sector: "transport",
    subSector: "تجهيز الشاحنات بأجهزة التتبع عبر الأقمار الصناعية (AVL & GPS)، إدارة الأساطيل الميدانية، ومستشعرات الوقود",
    city: "cairo",
    governorate: "القاهرة",
    address: "شارع مصطفى النحاس، المنطقة الثامنة، مدينة نصر، القاهرة",
    phone1: "0222718000",
    mobile: "01003399661",
    hotline: "19838",
    website: "https://www.etrac.com.eg",
    latitude: 30.0456,
    longitude: 31.3512,
    fleetSize: 110,
    fleetType: "سيارات ورش فنية متنقلة لتركيب وصيانة أجهزة التتبع على الشاحنات والمعدات الثقيلة بمواقع العملاء",
    fleetTires: "225/75R16 • 205/65R15",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "المشغل الأمني والتكنولوجي المعتمد لربط آلاف الشاحنات التجارية بمنظومات التتبع القومية وإدارة استهلاك الوقود",
    contactPerson: "رئيس قطاعات العمليات الميدانية والتركيبات",
    contactTitle: "Field Operations & Fleet Tech Sector Head",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.0456,31.3512"
  },
  {
    id: "eg_titan_942",
    nameAr: "شركة جيزة سيستمز لحلول البنية التحتية والشبكات الذكية (Giza Systems Mega Fleet Operations)",
    nameEn: "Giza Systems Mega Field Engineering & Infrastructure Fleets",
    sector: "construction",
    subSector: "تنفيذ مشروعات البنية التحتية الذكية، خطوط الأنابيب، شبكات الكهرباء والتحكم الآلي (SCADA)، ومحطات الطاقة",
    city: "cairo",
    governorate: "القاهرة",
    address: "القطاع الثاني، التجمع الخامس، القاهرة الجديدة",
    phone1: "0226146000",
    mobile: "01005522448",
    hotline: "19754",
    website: "https://www.gizasystems.com",
    latitude: 30.0189,
    longitude: 31.4289,
    fleetSize: 190,
    fleetType: "سيارات مهندسين ومختبرات متنقلة، شاحنات نقل مهمات ومعدات اتصالات وكابلات فايبر، وتريلات مشروعات",
    fleetTires: "295/80R22.5 • 225/75R16 • 315/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "المقاول والمنفذ التكنولوجي الإقليمي الأول لمشروعات الرقمنة والشبكات الذكية والمرافق الحيوية بالشرق الأوسط",
    contactPerson: "مدير عام العمليات الميدانية والأسطول",
    contactTitle: "Field Operations & Fleet Support Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.0189,31.4289"
  },
  {
    id: "eg_titan_943",
    nameAr: "الشركة المصرية للاتصالات وي - أسطول البنية التحتية القومية (Telecom Egypt WE Field Fleets)",
    nameEn: "Telecom Egypt WE Mega Infrastructure & Fiber Fleet Network",
    sector: "transport",
    subSector: "أضخم أسطول دعم فني وميداني لمد شبكات الألياف الضوئية، صيانة السنترالات، وتوصيل الإنترنت للمنازل والمصانع",
    city: "giza",
    governorate: "الجيزة",
    address: "القرية الذكية، طريق مصر - إسكندرية الصحراوي، الكيلو 28، الجيزة",
    phone1: "0235340000",
    mobile: "01007744882",
    hotline: "111",
    website: "https://www.te.eg",
    latitude: 30.0789,
    longitude: 31.0212,
    fleetSize: 680,
    fleetType: "أضخم أسطول سيارات فانات خدمة سريعة مجهزة بسلالم وأجهزة لحام ألياف، شاحنات نقل بكر كابلات ثقيل، وأوناش",
    fleetTires: "225/75R16 • 295/80R22.5 • 315/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "المشغل الوطني التاريخي للاتصالات في مصر والمالك لأكبر شبكة كابلات اتصالات بحرية وأرضية في المنطقة",
    contactPerson: "رئيس قطاعات النقل والتشغيل الميداني القومي",
    contactTitle: "National Field Fleet & Transport Sector Head",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.0789,31.0212"
  },
  {
    id: "eg_titan_944",
    nameAr: "شركة تشنت إيجيبت لتصنيع اللوحات والمعدات الكهربائية (CHINT Egypt Low Voltage)",
    nameEn: "CHINT Electrics Egypt Mega Manufacturing Plants (Sadat City)",
    sector: "manufacturing",
    subSector: "تصنيع وتجميع القواطع الهوائية، لوحات التوزيع الذكية، محولات الطاقة المدمجة، وحلول الطاقة الشمسية",
    city: "monufia",
    governorate: "المنوفية",
    address: "المنطقة الصناعية الرابعة، مدينة السادات، المنوفية",
    phone1: "0482605500",
    mobile: "01009966115",
    hotline: "19836",
    website: "https://www.chint.com/eg",
    latitude: 30.3712,
    longitude: 30.5045,
    fleetSize: 130,
    fleetType: "شاحنات شحن قواطع ولوحات، تريلات نقل محطات محولات مدمجة، وفانات دعم فني للمشروعات الكبرى",
    fleetTires: "295/80R22.5 • 315/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الصرح التصنيعي الصيني المتطور والشريك في توريد مهمات الكهرباء للعديد من محطات ومشروعات الدولة الكبرى",
    contactPerson: "مدير عام اللوجستيات والشحن",
    contactTitle: "Logistics & Freight General Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.3712,30.5045"
  },
  {
    id: "eg_titan_945",
    nameAr: "مجموعة هاجر مصر للأنظمة الكهربائية والتحكم (Hager Egypt Building Automation)",
    nameEn: "Hager Egypt Low Voltage Enclosures & Smart Automation Hub",
    sector: "manufacturing",
    subSector: "تجميع لوحات التحكم وتوزيع الطاقة السكنية والتجارية، أنظمة إدارة المباني الذكية (KNX)، والحماية الكهربائية",
    city: "cairo",
    governorate: "القاهرة",
    address: "المنطقة الصناعية بمدينة العبور، القليوبية / التجمع الخامس",
    phone1: "0244814500",
    mobile: "01002288337",
    hotline: "19835",
    website: "https://www.hager.eg",
    latitude: 30.2289,
    longitude: 31.4745,
    fleetSize: 115,
    fleetType: "شاحنات توزيع لوحات كهربائية، فانات دعم تقني وتركيبات متطورة، وتريلات شحن خامات معدنية وبوليمرية",
    fleetTires: "225/75R17.5 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "رائدة التكنولوجيا الألمانية الفرنسية في لوحات التحكم الذكي والمورد المفضل لمشروعات العاصمة الإدارية والعلمين",
    contactPerson: "مدير العمليات وسلاسل الإمداد الميدانية",
    contactTitle: "Supply Chain & Operations Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.2289,31.4745"
  },
  {
    id: "eg_titan_946",
    nameAr: "شركة سوناي مصر للأجهزة الكهربائية والمنزلية (Sonai Egypt - مجمع العاشر من رمضان)",
    nameEn: "Sonai Egypt for Modern Home Appliances Mega Plants",
    sector: "manufacturing",
    subSector: "تصنيع الأجهزة المنزلية الصغيرة، القلايات الهوائية، محضرات الطعام، أجهزة التدفئة، والمكاوي البخارية",
    city: "sharqia",
    governorate: "الشرقية",
    address: "المنطقة الصناعية A4، العاشر من رمضان، الشرقية",
    phone1: "015417800",
    mobile: "01004411559",
    hotline: "19034",
    website: "https://www.sonai.com.eg",
    latitude: 30.3189,
    longitude: 31.7589,
    fleetSize: 140,
    fleetType: "شاحنات توزيع كراتين أجهزة مغلقة، فانات صيانة فورية، وتريلات شحن مراكز تجارية وهايبر ماركت",
    fleetTires: "295/80R22.5 • 225/75R17.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "العلامة المصرية السريعة النمو التي أثبتت جدارتها في منافسة الأجهزة العالمية في السوق المحلي والتصدير العربي",
    contactPerson: "مدير عام النقل والمبيعات المركزية",
    contactTitle: "Central Transport & Sales Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.3189,31.7589"
  },
  {
    id: "eg_titan_947",
    nameAr: "شركة يونيفرسال لصناعة سخانات المياه وأفران الغاز (Universal Heating & Gas Appliances)",
    nameEn: "Universal Mega Plants for Gas Water Heaters & Built-in Ovens",
    sector: "manufacturing",
    subSector: "مجمعات تصنيع سخانات المياه الفورية بالغاز والكهرباء، المسطحات البلت إن، وأفران المطابخ الفاخرة",
    city: "giza",
    governorate: "الجيزة",
    address: "المنطقة الصناعية الثالثة، السادس من أكتوبر، الجيزة",
    phone1: "0238202800",
    mobile: "01006633774",
    hotline: "19600",
    website: "https://www.universal-group.org/heating",
    latitude: 29.9545,
    longitude: 30.9212,
    fleetSize: 155,
    fleetType: "شاحنات نقل وتوزيع سخانات، سيارات فنيي صيانة منزلية فورية مجهزة، وتريلات تصدير منتجات للشرق الأوسط",
    fleetTires: "295/80R22.5 • 225/75R16",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الاسم الأبرز في صناعة سخانات الغاز الطبيعي بمصر بأسطول دعم فني وصيانة يغطي كافة محافظات الجمهورية",
    contactPerson: "مدير عام الأسطول وخدمات ما بعد البيع",
    contactTitle: "After-Sales Fleets & Operations Lead",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.9545,30.9212"
  },
  {
    id: "eg_titan_948",
    nameAr: "شركة دايو باص مصر لتجميع وتصنيع الأتوبيسات (Daewoo Bus Egypt Assembly Complex)",
    nameEn: "Daewoo Bus Egypt Mega Public & Tourism Buses Assembly Plant",
    sector: "manufacturing",
    subSector: "تجميع أتوبيسات النقل العام الكبيرة، حافلات السياحة الفاخرة، وميني باص المدارس والمصانع بالمنطقة الصناعية",
    city: "giza",
    governorate: "الجيزة",
    address: "المنطقة الصناعية بأبو رواش، طريق القاهرة - الإسكندرية الصحراوي، الجيزة",
    phone1: "0235395500",
    mobile: "01008855993",
    hotline: "19833",
    website: "https://www.daewoobus.com.eg",
    latitude: 30.0578,
    longitude: 31.0645,
    fleetSize: 150,
    fleetType: "حاملات أتوبيسات، سيارات صيانة وتدخل سريع لخدمة خطوط هيئات النقل، وشاحنات شحن محركات ديزل",
    fleetTires: "315/80R22.5 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "المورد المعتمد لهيئات النقل العام بالقاهرة والإسكندرية وشركات النقل الجماعي والسياحة الكبرى بمصر",
    contactPerson: "مدير عام الحركة والأسطول الفني",
    contactTitle: "Technical Fleets & Transport General Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.0578,31.0645"
  },
  {
    id: "eg_titan_949",
    nameAr: "مجموعة السويدي إليكتريك - مصنع كابلات الجهد الفائق بالعين السخنة (Elsewedy Extra High Voltage Cables)",
    nameEn: "Elsewedy Extra High Voltage Cables Mega Plant (EHV Ain Sokhna)",
    sector: "manufacturing",
    subSector: "تصنيع كابلات الجهد فائق العلو حتى 500 ك.ف والربط الكهربائي الدولي تحت سطح الأرض والأعماق البحرية",
    city: "suez",
    governorate: "السويس",
    address: "المنطقة الاقتصادية الخاصة، العين السخنة، السويس",
    phone1: "0623399000",
    mobile: "01001199335",
    hotline: "16274",
    website: "https://www.elsewedyelectric.com/ehv",
    latitude: 29.6412,
    longitude: 32.3312,
    fleetSize: 180,
    fleetType: "تريلات تريلا ذات مقطورات محورية فائقة القدرة لنقل بكر كابلات عملاقة حتى 50 طن للبكرة الواحدة، وأوناش",
    fleetTires: "385/65R22.5 • 315/80R22.5 • 12.00R24",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "المصنع الأكثر تقدماً في إفريقيا والشرق الأوسط المصنع لكابلات مشروعات الربط الكهربائي القومي مع السعودية واليونان",
    contactPerson: "نائب رئيس مجلس الإدارة لقطاعات النقل الثقيل والمشاريع الكبرى",
    contactTitle: "Mega Projects & Heavy Cargo Transport Vice President",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.6412,32.3312"
  },
  {
    id: "eg_titan_950",
    nameAr: "الشركة المصرية لتجارة وتوكيلات الشاحنات والمعدات الثقيلة (EIT Iveco - توكيلات إيفيكو إيجيبت)",
    nameEn: "Egyptian International Motors (EIM Heavy Trucks & Equipment - Iveco)",
    sector: "manufacturing",
    subSector: "تجميع وتوزيع شاحنات إيفيكو ستراليس وتراكر للنقل الثقيل والمحاجر، معدات الحفر كوماتسو، ومحركات بحرية",
    city: "giza",
    governorate: "الجيزة",
    address: "الكيلو 26، طريق مصر - إسكندرية الصحراوي، أبو رواش، الجيزة",
    phone1: "0235396000",
    mobile: "01003311558",
    hotline: "19830",
    website: "https://www.eim-eg.com",
    latitude: 30.0745,
    longitude: 31.0512,
    fleetSize: 190,
    fleetType: "تريلات لوابد نقل معدات ثقيلة، سيارات صيانة متنقلة مجهزة بأجهزة تشخيص أعطال كمبيوترية، وشاحنات قطع غيار",
    fleetTires: "315/80R22.5 • 385/65R22.5 • 12.00R24",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الوكيل الحصري لشاحنات إيفيكو ومعدات كوماتسو العالمية المعتمدة لدى كبرى شركات النقل والمقاولات في مصر",
    contactPerson: "مدير عام النقل الثقيل والخدمات اللوجستية",
    contactTitle: "Heavy Equipment Fleets & Logistics Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.0745,31.0512"
  }
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { wave7Part5 };
}
