/**
 * scripts/wave7_data_part2.js
 * Part 2 of Wave 7 Titans (eg_titan_751 to eg_titan_800) - 50 Industrial Titans.
 * Sectors: Tier-1 General Contractors, Infrastructure, Bridges, Deep Piling, Water Plants & Smart Cities.
 */

const wave7Part2 = [
  {
    id: "eg_titan_751",
    nameAr: "شركة ريدكون للتعمير (Redcon Construction Mega Projects)",
    nameEn: "Redcon Construction Mega Engineering Fleet",
    sector: "construction",
    subSector: "المقاولات العامة للأبراج الشاهقة والمباني الخضراء والمستدامة بمصر",
    city: "cairo",
    governorate: "القاهرة",
    address: "التجمع الخامس، شارع التسعين الجنوبي، القاهرة الجديدة",
    phone1: "0228109000",
    mobile: "01007733445",
    hotline: "19721",
    website: "https://www.redconcon.com",
    latitude: 30.0245,
    longitude: 31.4789,
    fleetSize: 180,
    fleetType: "أوناش برجية عملاقة، تريلات نقل حديد وصلب، لوادر، ومقطورات نقل ثقيل",
    fleetTires: "315/80R22.5 • 385/65R22.5 • 12.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "رائدة التشييد الأخضر والمستدام والمنفذة لمشروع أطول برج خشبي صديق للبيئة وأبراج العلمين",
    contactPerson: "نائب رئيس مجلس الإدارة للعمليات الهندسية والأسطول",
    contactTitle: "Engineering Operations & Fleet Vice President",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.0245,31.4789"
  },
  {
    id: "eg_titan_752",
    nameAr: "الشركة القابضة لمياه الشرب والصرف الصحي (أسطول الطوارئ والأزمات المركزي)",
    nameEn: "Holding Company for Water & Wastewater (Emergency Fleet)",
    sector: "construction",
    subSector: "أسطول سيارات الكسح والشفاطات المدمجة وسيارات السيول ومعدات إصلاح الكسور لشبكات المياه القومية",
    city: "cairo",
    governorate: "القاهرة",
    address: "طريق النصر، تقاطع شارع يوسف عباس، مدينة نصر، القاهرة",
    phone1: "0223841500",
    mobile: "01001199882",
    hotline: "125",
    website: "https://www.hcww.com.eg",
    latitude: 30.0612,
    longitude: 31.3125,
    fleetSize: 450,
    fleetType: "سيارات شفاط نافوري كومبي، سيارات بدالات نزح سيول، تريلات نقل مواسير صلب، وروافع كسور",
    fleetTires: "315/80R22.5 • 12.00R20 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الأسطول القومي الخدمي الأكبر المعني بإدارة الأزمات والطوارئ وشبكات مياه الشرب على مستوى كافة المحافظات",
    contactPerson: "رئيس قطاع الأزمات والطوارئ والحركة المركزية",
    contactTitle: "Crises, Emergencies & Fleet Sector Head",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.0612,31.3125"
  },
  {
    id: "eg_titan_753",
    nameAr: "شركة الحاذق للإنشاءات (El Hazek Construction Mega Fleet)",
    nameEn: "El Hazek Construction & Contracting",
    sector: "construction",
    subSector: "المقاولات الكبرى للأندية الرياضية العالمية والمستشفيات والكمبوندات الفاخرة",
    city: "cairo",
    governorate: "القاهرة",
    address: "شارع التسعين الشمالي، التجمع الخامس، القاهرة الجديدة",
    phone1: "0225648900",
    mobile: "01003355991",
    hotline: "19672",
    website: "https://www.elhazek.com",
    latitude: 30.0389,
    longitude: 31.4712,
    fleetSize: 140,
    fleetType: "شاحنات نقل مواد بناء، أوناش هيدروليكية، خلاطات خرسانة، وسيارات نقل مهندسين",
    fleetTires: "315/80R22.5 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "من أكبر شركات المقاولات المصرية المصنفة فئة أولى والمنفذة لكبرى مشروعات العاصمة والساحل الشمالي",
    contactPerson: "مدير المعدات والآليات الثقيلة",
    contactTitle: "Heavy Machinery & Equipment Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.0389,31.4712"
  },
  {
    id: "eg_titan_754",
    nameAr: "شركة الشروق للمقاولات العامة وأعمال الكهرباء والشبكات",
    nameEn: "Al Shorouk Contracting & Power Networks",
    sector: "construction",
    subSector: "مد شبكات كابلات الجهد العالي والمتوسط ومحطات الإنارة للمدن الجديدة",
    city: "cairo",
    governorate: "القاهرة",
    address: "شارع مكرم عبيد، مدينة نصر، القاهرة",
    phone1: "0222741500",
    mobile: "01005577334",
    hotline: "19438",
    website: "https://www.shorouk-contracting.com",
    latitude: 30.0612,
    longitude: 31.3389,
    fleetSize: 115,
    fleetType: "تريلات حاملات بكر كابلات عملاقة، أوناش سلكية، سيارات باسكت إنارة هيدروليكية، وحفارات",
    fleetTires: "315/80R22.5 • 12.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "شريك رئيسي مع الشركة المصرية لنقل الكهرباء في توصيل شبكات العاصمة الإدارية ومستقبل مصر",
    contactPerson: "مدير عام النقل والمهمات الكهربائية الثقيلة",
    contactTitle: "Electrical Heavy Missions & Fleet Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.0612,31.3389"
  },
  {
    id: "eg_titan_755",
    nameAr: "شركة دورا للإنشاءات الهندسية (Dorra Construction)",
    nameEn: "Dorra Construction & Infrastructure",
    sector: "construction",
    subSector: "المقاولات المتكاملة والمراكز التجارية الكبرى والأبراج السكنية بغرب القاهرة",
    city: "giza",
    governorate: "الجيزة",
    address: "محور 26 يوليو، مدخل زايد 1، الشيخ زايد، الجيزة",
    phone1: "0238501200",
    mobile: "01008833441",
    hotline: "19789",
    website: "https://www.dorraconstruction.com",
    latitude: 30.0389,
    longitude: 30.9789,
    fleetSize: 155,
    fleetType: "شاحنات نقل ثقيل، أوناش، معدات حفر وردم، وأساطيل نقل طواقم عمل",
    fleetTires: "315/80R22.5 • 295/80R22.5 • 12.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الصرح الإنشائي الأبرز لعلامة درة المنفذة لأكبر المولات والكمبوندات السكنية المرموقة",
    contactPerson: "رئيس قطاع التشغيل والمعدات الهندسية",
    contactTitle: "Engineering Fleets & Machinery Head",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.0389,30.9789"
  },
  {
    id: "eg_titan_756",
    nameAr: "شركة بتروجت للإنشاءات البحرية والمنصات البترولية (ترسانة المعدية)",
    nameEn: "Petrojet Marine Fabrication Yard (El Maadya)",
    sector: "construction",
    subSector: "تصنيع وتركيب منصات البترول والغاز البحرية وخطوط الأنابيب البحرية العميقة",
    city: "beheira",
    governorate: "البحيرة",
    address: "ترسانة تصنيع المنشآت البحرية، ميناء المعدية، إدكو، البحيرة",
    phone1: "0452981400",
    mobile: "01002299881",
    hotline: "19400",
    website: "https://www.petrojet.com.eg",
    latitude: 31.3124,
    longitude: 30.2245,
    fleetSize: 190,
    fleetType: "بارجات بحرية لمد الأنابيب، روافع هيدروليكية عملاقة حتى 500 طن، وتريلات شحن أجزاء منصات",
    fleetTires: "315/80R22.5 • 385/65R22.5 • 12.00R24",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الترسانة القومية العملاقة التابعة لقطاع البترول المصري المسؤولة عن بناء وتثبيت منصات حقول الغاز بالبحر المتوسط",
    contactPerson: "مدير عام الخدمات البحرية ومعدات الترسانة",
    contactTitle: "Marine Fleets & Yard Equipment General Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=31.3124,30.2245"
  },
  {
    id: "eg_titan_757",
    nameAr: "شركة إنبي للخدمات الهندسية والإشراف على المشروعات (ENPPI)",
    nameEn: "Engineering for the Petroleum & Process Industries (ENPPI)",
    sector: "construction",
    subSector: "الإشراف والتنفيذ الهندسي لمجمعات التكرير ومحطات البتروكيماويات والغاز القومية",
    city: "cairo",
    governorate: "القاهرة",
    address: "شارع أنور المفتي، المنطقة الأولى، مدينة نصر، القاهرة",
    phone1: "0222762000",
    mobile: "01004411883",
    hotline: "19331",
    website: "https://www.enppi.com",
    latitude: 30.0612,
    longitude: 31.3345,
    fleetSize: 130,
    fleetType: "سيارات فحص ومسح هندسي مجهزة بأحدث الرادارات، أساطيل نقل خبراء ومهندسين للمواقع البترولية",
    fleetTires: "245/75R16 • 265/65R17 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الذراع الهندسي الاستشاري الأول في الشرق الأوسط التابع لوزارة البترول المصرية برصيد مشروعات دولي",
    contactPerson: "مدير عام إدارة الحركة والخدمات الميدانية",
    contactTitle: "Transport & Field Operations General Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.0612,31.3345"
  },
  {
    id: "eg_titan_758",
    nameAr: "شركة أبناء عبد السلام فياض للمقاولات العامة (A.S. Fayad Contracting)",
    nameEn: "Abnaa A.S. Fayad General Contracting",
    sector: "construction",
    subSector: "إنشاء شبكات مياه الشرب والصرف ومحطات الرفع بمحافظات الدلتا",
    city: "damietta",
    governorate: "دمياط",
    address: "طريق رأس البر الغربي، دمياط",
    phone1: "0572341900",
    mobile: "01006699331",
    hotline: "19739",
    website: "https://www.asfayad.com",
    latitude: 31.4124,
    longitude: 31.8124,
    fleetSize: 105,
    fleetType: "حفارات هيدروليكية، شاحنات نقل مواسير ومهمات، لوادر، وتريلات قلاب",
    fleetTires: "315/80R22.5 • 12.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "من كبرى شركات مقاولات البنية التحتية المنفذة لمشروعات الصرف الصحي بدمياط والدقهلية وبورسعيد",
    contactPerson: "مدير الحركة والمعدات الثقيلة",
    contactTitle: "Heavy Equipment & Fleets Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=31.4124,31.8124"
  },
  {
    id: "eg_titan_759",
    nameAr: "شركة الأهرام لنظم الأمان والمقاولات الكهروميكانيكية (Al Ahram Security Systems)",
    nameEn: "Al Ahram Security Systems & Electromechanical Contracting",
    sector: "construction",
    subSector: "تنفيذ شبكات مكافحة الحريق، إنذار المباني الذكية، والمحطات الكهروميكانيكية الكبرى",
    city: "sharqia",
    governorate: "الشرقية",
    address: "المنطقة الصناعية الثالثة A3، العاشر من رمضان، الشرقية",
    phone1: "015412800",
    mobile: "01009944118",
    hotline: "19128",
    website: "https://www.ahram.org.eg/security",
    latitude: 30.2981,
    longitude: 31.7612,
    fleetSize: 95,
    fleetType: "سيارات فحص شبكات إطفاء، شاحنات نقل مضخات حريق وتجهيزات هيدروليكية، وأساطيل صيانة دورية",
    fleetTires: "295/80R22.5 • 225/75R16",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الرائدة في تأمين وحماية أكبر المجمعات الصناعية والمطارات والمؤسسات السيادية من أخطار الحريق",
    contactPerson: "مدير إدارة الصيانة والأسطول الخدمي",
    contactTitle: "Service Fleet & Maintenance Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.2981,31.7612"
  },
  {
    id: "eg_titan_760",
    nameAr: "شركة الخرافي ناشيونال للمشروعات والبنية التحتية (Kharafi National Egypt)",
    nameEn: "Kharafi National for Mega Infrastructure & Electro-Mechanical Projects",
    sector: "construction",
    subSector: "مشروعات محطات توليد الكهرباء، معالجة مياه الصرف العملاقة (بحر البقر ومحسمة)، والبنية التحتية المتكاملة",
    city: "cairo",
    governorate: "القاهرة",
    address: "مجمع الخرافي، القطاع الأول، التجمع الخامس، القاهرة الجديدة",
    phone1: "0228135000",
    mobile: "01002244991",
    hotline: "19891",
    website: "https://www.kharafinational.com",
    latitude: 30.0212,
    longitude: 31.4389,
    fleetSize: 220,
    fleetType: "تريلات نقل معدات ثقيلة، أوناش هيدروليكية عملاقة حمولة حتى 250 طن، وشاحنات ورش المشروعات الميدانية",
    fleetTires: "315/80R22.5 • 385/65R22.5 • 12.00R24",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "العملاق الإقليمي المنفذ لأضخم محطات معالجة المياه ومحطات الطاقة التوربينية وشبكات البنية التحتية بمصر",
    contactPerson: "رئيس قطاعات الأسطول الثقيل والمعدات المركزية",
    contactTitle: "Central Heavy Fleets & Equipment Sector Head",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.0212,31.4389"
  },
  {
    id: "eg_titan_761",
    nameAr: "شركة سياك لصناعة الهياكل المعدنية والجمالونات (SIAC Steel Fabrication)",
    nameEn: "SIAC Industrial Steel Structures & Cranes",
    sector: "construction",
    subSector: "تصنيع الهياكل الفولاذية والجمالونات العملاقة للمصانع والمستودعات والمطارات",
    city: "giza",
    governorate: "الجيزة",
    address: "المنطقة الصناعية بأبو رواش، طريق القاهرة الإسكندرية الصحراوي، الجيزة",
    phone1: "0235390800",
    mobile: "01007799221",
    hotline: "19655",
    website: "https://www.siac.com.eg/steel",
    latitude: 30.0541,
    longitude: 31.0789,
    fleetSize: 110,
    fleetType: "تريلات تريلا فرش نقل كمرات صلب عملاقة تصل حتى 40 متراً، أوناش رفع ثقيل تادانو",
    fleetTires: "315/80R22.5 • 385/65R22.5 • 12.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الصرح الوطني الأبرز لتصنيع وتشييد الهياكل المعدنية لأكبر صالات العرض ومصانع المركبات والمطارات",
    contactPerson: "مدير عام النقل الثقيل وتصاريح الحمولات الخاصة",
    contactTitle: "Special Cargoes & Heavy Transport General Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.0541,31.0789"
  },
  {
    id: "eg_titan_762",
    nameAr: "شركة النصر للمباني والإنشاءات (إيجيكو - قطاع الأعمال العام)",
    nameEn: "El Nasr for Buildings & Construction (EGYCO)",
    sector: "construction",
    subSector: "إنشاء الكباري الخرسانية، المستشفيات العامة، ومحطات تنقية المياه الكبرى",
    city: "cairo",
    governorate: "القاهرة",
    address: "شارع 26 يوليو، وسط البلد، القاهرة",
    phone1: "0225752100",
    mobile: "01001144229",
    hotline: "19533",
    website: "https://www.egyco.gov.eg",
    latitude: 30.0589,
    longitude: 31.2412,
    fleetSize: 175,
    fleetType: "شاحنات نقل ثقيل، حفارات كوماتسو، لوادر، تريلات قلابات، وسيارات ورش متنقلة",
    fleetTires: "315/80R22.5 • 12.00R20 • 385/65R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "إحدى أقدم وأعرق قلاع المقاولات المصرية التابعة للقابضة للتشييد والتعمير",
    contactPerson: "رئيس قطاعات الآليات والمعدات الميكانيكية",
    contactTitle: "Mechanical Fleets & Machinery Sector Head",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.0589,31.2412"
  },
  {
    id: "eg_titan_763",
    nameAr: "شركة أبناء حسن علام للإنشاءات التخصصية والأساسات الميكانيكية",
    nameEn: "Hassan Allam Special Construction & Mechanical Piling",
    sector: "construction",
    subSector: "تنفيذ الستائر الخرسانية، الخوازيق المستمرة (CFA)، والحوائط اللوحية (Diaphragm Walls)",
    city: "cairo",
    governorate: "القاهرة",
    address: "مجمع حسن علام، شارع الثورة، الكيلو 4.5 طريق السويس، القاهرة",
    phone1: "0222915800",
    mobile: "01005522998",
    hotline: "16541",
    website: "https://www.hassanallam.com/foundations",
    latitude: 30.0891,
    longitude: 31.3541,
    fleetSize: 185,
    fleetType: "ماكينات حفر حوائط لوحية باور وبويل، أوناش هيدروليكية، ماكينات خلط بنتونايت، وتريلات صهاريج",
    fleetTires: "315/80R22.5 • 12.00R24 • 385/65R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "المتخصصة في أصعب أعمال الأساسات العميقة والستائر المانعة لنفاذية المياه حول أنفاق المترو ومجرى النيل",
    contactPerson: "مدير عام أسطول الأساسات العميقة",
    contactTitle: "Deep Foundations Fleet General Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.0891,31.3541"
  },
  {
    id: "eg_titan_764",
    nameAr: "الشركة الوطنية للتشييد والتنمية (التابعة لجهاز الخدمة الوطنية)",
    nameEn: "National Construction & Development Company (NSPO)",
    sector: "construction",
    subSector: "المشروعات الزراعية والصناعية القومية الكبرى، إنشاء الصوامع، واستصلاح الأراضي",
    city: "cairo",
    governorate: "القاهرة",
    address: "محور المشير طنطاوي، التجمع الخامس، القاهرة",
    phone1: "0224058100",
    mobile: "01008899552",
    hotline: "19900",
    website: "https://www.nspo.com.eg",
    latitude: 30.0212,
    longitude: 31.3891,
    fleetSize: 320,
    fleetType: "لوادر، بلدوزرات كتربيلر D9 و D10، تريلات قلاب جبلية، حفارات هيدروليكية، وأساطيل نقل ثقيل",
    fleetTires: "315/80R22.5 • 12.00R24 • 14.00R24 • 385/65R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الصرح الوطني الاستراتيجي المنفذ لأكبر مشروعات الاستصلاح بمستقبل مصر وجنوب الوادي وتوشكى الخير",
    contactPerson: "مدير قطاع الآليات والمعدات الهندسية الثقيلة",
    contactTitle: "Heavy Engineering Machinery Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.0212,31.3891"
  },
  {
    id: "eg_titan_765",
    nameAr: "شركة الخرافي للإنشاءات والمرافق (Kharafi Construction Egypt)",
    nameEn: "Kharafi Construction & Infrastructure Fleets",
    sector: "construction",
    subSector: "إنشاء الموانئ الجافة، المطارات الدولية، ومحطات معالجة مياه مصرف بحر البقر ومحطة الدلتا الجديدة",
    city: "giza",
    governorate: "الجيزة",
    address: "القرية الذكية، طريق مصر الإسكندرية الصحراوي، الجيزة",
    phone1: "0235378900",
    mobile: "01002211993",
    hotline: "19234",
    website: "https://www.kharafi.com",
    latitude: 30.0812,
    longitude: 31.0245,
    fleetSize: 190,
    fleetType: "معدات حفر محطات معالجة، أوناش عملاقة، تريلات نقل معدات كهروميكانيكية، وشاحنات خرسانة",
    fleetTires: "315/80R22.5 • 385/65R22.5 • 12.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "المشاركة في تنفيذ أضخم محطات معالجة مياه في العالم (بحر البقر والدلتا الجديدة) المسجلة بموسوعة جينيس",
    contactPerson: "نائب رئيس مجلس الإدارة للخدمات اللوجستية للمشروعات",
    contactTitle: "Projects Logistics Vice President",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.0812,31.0245"
  },
  {
    id: "eg_titan_766",
    nameAr: "شركة الصرح للمقاولات العامة والإنشاءات المتكاملة",
    nameEn: "Al Sarh General Contracting & Engineering",
    sector: "construction",
    subSector: "إنشاء المجمعات الصناعية والمستودعات اللوجستية ومصانع الأدوية بالعاشر والسادات",
    city: "sharqia",
    governorate: "الشرقية",
    address: "المنطقة الصناعية الثالثة، العاشر من رمضان، الشرقية",
    phone1: "015418900",
    mobile: "01004455112",
    hotline: "19837",
    website: "https://www.alsarh-contracting.com",
    latitude: 30.3012,
    longitude: 31.7589,
    fleetSize: 90,
    fleetType: "شاحنات نقل ثقيل، أوناش شوكية وتلسكوبية، لوادر، وسيارات خدمات فنية",
    fleetTires: "315/80R22.5 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "متخصصة في بناء هناجر المصانع العملاقة والأرضيات الخرسانية عالية التحمل بمصانع الشرقية",
    contactPerson: "مدير تشغيل وصيانة الأسطول",
    contactTitle: "Fleet Operations & Maintenance Head",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.3012,31.7589"
  },
  {
    id: "eg_titan_767",
    nameAr: "شركة كير للمقاولات العامة والتنمية العمرانية",
    nameEn: "Care for Contracting & Urban Development",
    sector: "construction",
    subSector: "تطوير البنية التحتية، شبكات الري الحديث، ومحطات معالجة مياه الصرف الصحي الزراعي",
    city: "giza",
    governorate: "الجيزة",
    address: "شارع مصدق، الدقي، الجيزة",
    phone1: "0237624100",
    mobile: "01007788339",
    hotline: "19561",
    website: "https://www.care-contracting.com",
    latitude: 30.0412,
    longitude: 31.2089,
    fleetSize: 100,
    fleetType: "حفارات هيدروليكية، شاحنات قلاب، ماكينات لحام أنابيب بولي إيثيلين، وتريلات شحن",
    fleetTires: "315/80R22.5 • 12.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "رائدة تنفيذ مشروعات الري الحديث ومد خطوط أنابيب نقل مياه الاستصلاح الزراعي بغرب مصر",
    contactPerson: "مدير المعدات الميدانية والنقل",
    contactTitle: "Field Equipment & Fleet Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.0412,31.2089"
  },
  {
    id: "eg_titan_768",
    nameAr: "شركة بترومنت للإنشاءات الهندسية والمقاولات البترولية (Petromaint)",
    nameEn: "Alexandria Petroleum Maintenance Co. (Petromaint)",
    sector: "construction",
    subSector: "المقاولات الإنشائية المتخصصة وصيانة مصافي التكرير ومستودعات التخزين الاستراتيجية للوقود",
    city: "alexandria",
    governorate: "الإسكندرية",
    address: "طريق مصر الإسكندرية الصحراوي، مرغم، الإسكندرية",
    phone1: "034700800",
    mobile: "01009911883",
    hotline: "19741",
    website: "https://www.petromaint.com.eg",
    latitude: 31.0541,
    longitude: 29.8312,
    fleetSize: 145,
    fleetType: "أوناش تادانو هيدروليكية، سيارات فحص وتطهير مستودعات بترول، تريلات نقل معدات ثقيلة، وشاحنات ورش",
    fleetTires: "315/80R22.5 • 295/80R22.5 • 12.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "إحدى كبرى شركات قطاع البترول المصري المسؤولة عن الصيانة والإنشاءات بالموانئ ومصافي التكرير",
    contactPerson: "مدير عام النقل والمعدات الميكانيكية",
    contactTitle: "Transport & Mechanical Fleets General Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=31.0541,29.8312"
  },
  {
    id: "eg_titan_769",
    nameAr: "شركة صان مصر للمقاولات والخدمات الهندسية (EMC - Egyptian Maintenance Company)",
    nameEn: "Egyptian Maintenance Company (EMC Mega Fleet)",
    sector: "construction",
    subSector: "المقاولات الكهروميكانيكية، تصنيع المعدات الاستاتيكية ومجمعات الغاز الطبيعي المسال",
    city: "cairo",
    governorate: "القاهرة",
    address: "شارع التسعين الجنوبي، التجمع الخامس، القاهرة الجديدة",
    phone1: "0228104500",
    mobile: "01003344117",
    hotline: "16522",
    website: "https://www.emc-egypt.net",
    latitude: 30.0212,
    longitude: 31.4456,
    fleetSize: 160,
    fleetType: "أوناش رفع هيدروليكية، تريلات شحن فائق الحجم للمبادلات الحرارية، وأساطيل نقل فرق هندسية",
    fleetTires: "315/80R22.5 • 385/65R22.5 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الشريك الاستراتيجي لقطاع الطاقة المصري في تنفيذ مشروعات إدكو ودمياط لإسالة الغاز والمستودعات الاستراتيجية",
    contactPerson: "مساعد رئيس الشركة للعمليات والأسطول",
    contactTitle: "Assistant Chairman for Operations & Fleet",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.0212,31.4456"
  },
  {
    id: "eg_titan_770",
    nameAr: "شركة أبناء سوهاج للمقاولات العامة ورصف الطرق",
    nameEn: "Abnaa Sohag General Contracting & Road Paving",
    sector: "construction",
    subSector: "مشروعات تطوير محاور الصعيد، الكباري العلوية على النيل، وازدواج الطرق الصحراوية",
    city: "sohag",
    governorate: "سوهاج",
    address: "المنطقة الصناعية بالكوثر، سوهاج",
    phone1: "0932281500",
    mobile: "01006622558",
    hotline: "19854",
    website: "https://www.abnaasohag.com",
    latitude: 26.5412,
    longitude: 31.7891,
    fleetSize: 120,
    fleetType: "هراسات أسفلت، لوادر كتربيلر، تريلات قلابات صخور، وفينيشرات رصف طرق حرة",
    fleetTires: "315/80R22.5 • 12.00R24 • 385/65R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "من مقاولي الفئة الأولى المشاركين في ربط محافظات سوهاج وأسيوط وقنا بالطرق الصحراوية الشرقية والغربية",
    contactPerson: "رئيس قطاع المعدات والورش المركزية بسوهاج",
    contactTitle: "Machinery & Central Workshops Head",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=26.5412,31.7891"
  },
  {
    id: "eg_titan_771",
    nameAr: "شركة أسوان العامة للمقاولات والإنشاءات النهرية",
    nameEn: "Aswan General Contracting & River Works",
    sector: "construction",
    subSector: "أعمال التكريك وتطوير المجرى الملاحي لنهر النيل بين الأقصر وأسوان ومحطات الرفع",
    city: "aswan",
    governorate: "أسوان",
    address: "طريق السادات، كورنيش النيل، أسوان",
    phone1: "0972418500",
    mobile: "01008844221",
    hotline: "19381",
    website: "https://www.aswan-contracting.com",
    latitude: 24.0891,
    longitude: 32.8989,
    fleetSize: 95,
    fleetType: "صنادل نهرية بمعدات حفر، كراكات طمي، تريلات شحن كتل جرانيتية، ولوادر ثقيلة",
    fleetTires: "315/80R22.5 • 12.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "المتخصصة في حماية وتعميق المجرى الملاحي للفنادق العائمة وتطوير مآخذ محطات مياه الشرب بأسوان",
    contactPerson: "مدير العمليات النهرية والمعدات الميدانية",
    contactTitle: "River Operations & Equipment Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=24.0891,32.8989"
  },
  {
    id: "eg_titan_772",
    nameAr: "شركة قنا العامة للمقاولات والبنية الأساسية",
    nameEn: "Qena General Contracting & Infrastructure",
    sector: "construction",
    subSector: "محطات الرفع وشبكات الصرف الصحي لمبادرة حياة كريمة بمحافظات قنا والأقصر",
    city: "qena",
    governorate: "قنا",
    address: "المنطقة الصناعية بنجع حمادي، قنا",
    phone1: "0966581400",
    mobile: "01001177445",
    hotline: "19467",
    website: "https://www.qena-contracting.com",
    latitude: 26.0456,
    longitude: 32.2412,
    fleetSize: 85,
    fleetType: "حفارات هيدروليكية، تريلات نقل مواسير زهر مرن، لوادر، وتريلات قلاب",
    fleetTires: "315/80R22.5 • 12.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "المنفذ الرئيسي لخطوط وشبكات مياه الشرب العملاقة لقرى الظهير الصحراوي بمحافظة قنا",
    contactPerson: "مدير إدارة الحركة والسيارات الثقيلة",
    contactTitle: "Heavy Fleets & Movement Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=26.0456,32.2412"
  },
  {
    id: "eg_titan_773",
    nameAr: "شركة الإسكندرية للأعمال الهندسية المتطورة (AEC)",
    nameEn: "Alexandria Advanced Engineering Contracting (AEC)",
    sector: "construction",
    subSector: "الإنشاءات الصناعية وتجهيز خطوط الإنتاج لمصانع الورق والحديد والبتروكيماويات",
    city: "alexandria",
    governorate: "الإسكندرية",
    address: "شارع الفردوس، سموحة، الإسكندرية",
    phone1: "034258900",
    mobile: "01005511884",
    hotline: "19681",
    website: "https://www.aec-alex.com",
    latitude: 31.2089,
    longitude: 29.9389,
    fleetSize: 90,
    fleetType: "أوناش شوكية ثقيلة، أوناش ذراع متحرك، تريلات نقل ماكينات صناعية، وشاحنات صيانة",
    fleetTires: "315/80R22.5 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "رائدة تركيب خطوط الإنتاج والآلات الصناعية الثقيلة بمصانع الدلتا والإسكندرية",
    contactPerson: "رئيس قسم التركيبات والمعدات الثقيلة",
    contactTitle: "Installations & Heavy Fleets Chief",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=31.2089,29.9389"
  },
  {
    id: "eg_titan_774",
    nameAr: "شركة بورسعيد للمقاولات العامة والإنشاءات البحرية",
    nameEn: "Port Said General Contracting & Marine Works",
    sector: "construction",
    subSector: "تطوير أرصفة الحاويات والساحات اللوجستية بميناء شرق وغرب بورسعيد",
    city: "port_said",
    governorate: "بورسعيد",
    address: "المنطقة الصناعية جنوب بورسعيد، طريق المعاهدة، بورسعيد",
    phone1: "0663781200",
    mobile: "01003377551",
    hotline: "19711",
    website: "https://www.portsaid-contracting.com",
    latitude: 31.2245,
    longitude: 32.2891,
    fleetSize: 110,
    fleetType: "أوناش رصيف، تريلات نقل كتل صخرية وخرسانية، ماكينات دك أرضيات الساحات، وشاحنات دعم",
    fleetTires: "315/80R22.5 • 12.00R24 • 385/65R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "المقاول المحلي الأبرز في تجهيز البنية التحتية لميناء شرق بورسعيد المحوري العالمي",
    contactPerson: "مدير الحركة والمعدات البحرية والبرية",
    contactTitle: "Marine & Land Equipment Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=31.2245,32.2891"
  },
  {
    id: "eg_titan_775",
    nameAr: "شركة سيناء للمقاولات العامة وأعمال الطرق الصحراوية",
    nameEn: "Sinai Contracting & Desert Roads Construction",
    sector: "construction",
    subSector: "إنشاء ورفع كفاءة شبكة المحاور الاستراتيجية بشمال ووسط سيناء ونفق الشهيد أحمد حمدي",
    city: "north_sinai",
    governorate: "شمال سيناء",
    address: "شارع الفاتح، العريش، شمال سيناء",
    phone1: "0683321500",
    mobile: "01007744882",
    hotline: "19829",
    website: "https://www.sinai-contracting.com",
    latitude: 31.1345,
    longitude: 33.7989,
    fleetSize: 105,
    fleetType: "لوادر كتربيلر جبلية، تريلات قلابات صخور، ماكينات رصف أسفلت، وخلاطات أسمنت",
    fleetTires: "315/80R22.5 • 12.00R24 • 14.00R24",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الصرح الوطني العامل في شق وتأهيل شبكة الطرق الدولية والتجمعات التنموية بسيناء",
    contactPerson: "مدير قطاع المعدات الميدانية بسيناء",
    contactTitle: "Sinai Field Fleets Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=31.1345,33.7989"
  },
  {
    id: "eg_titan_776",
    nameAr: "شركة مصر لأعمال الري والصرف والمشروعات المدنية",
    nameEn: "Misr for Irrigation & Drainage Works",
    sector: "construction",
    subSector: "تبطين وتأهيل الترع والمصارف القومية ومخرات السيول وسدود الحماية بمصر",
    city: "giza",
    governorate: "الجيزة",
    address: "شارع مراد، الجيزة",
    phone1: "0235721400",
    mobile: "01009955331",
    hotline: "19522",
    website: "https://www.misr-irrigation.gov.eg",
    latitude: 30.0189,
    longitude: 31.2089,
    fleetSize: 150,
    fleetType: "حفارات هيدروليكية ذات ذراع مفصلي طويل، لوادر، تريلات نقل أحجار الدبش، وماكينات صب خرسانة مبطنة",
    fleetTires: "315/80R22.5 • 12.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الشركة التابعة للقابضة للري والصرف المنفذة للمشروع القومي لتبطين الترع وتحديث نظم الري",
    contactPerson: "مدير عام الصيانة الميكانيكية والسيارات",
    contactTitle: "Mechanical Maintenance & Vehicles Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.0189,31.2089"
  },
  {
    id: "eg_titan_777",
    nameAr: "شركة طيبة للمقاولات العامة والتوريدات الهندسية (Tiba Contracting)",
    nameEn: "Tiba General Contracting & Engineering Supplies",
    sector: "construction",
    subSector: "إنشاء محطات محولات الكهرباء وتمديد خطوط الربط الكهربائي القومي",
    city: "cairo",
    governorate: "القاهرة",
    address: "شارع عباس العقاد، مدينة نصر، القاهرة",
    phone1: "0222719200",
    mobile: "01002288337",
    hotline: "19661",
    website: "https://www.tiba-contracting.com",
    latitude: 30.0541,
    longitude: 31.3389,
    fleetSize: 85,
    fleetType: "تريلات تريلا فرش شحن كابلات ومحولات، أوناش هيدروليكية، وحفارات مد شبكات",
    fleetTires: "315/80R22.5 • 12.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "شريك رئيسي مع قطاع الكهرباء في تنفيذ محطات محولات الجهد الفائق بالمدن الجديدة",
    contactPerson: "مدير الحركة والنقل الخارجي",
    contactTitle: "Transport & Logistics Head",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.0541,31.3389"
  },
  {
    id: "eg_titan_778",
    nameAr: "شركة الفرسان للمقاولات والتجارة العامة (Al Fursan Contracting)",
    nameEn: "Al Fursan Contracting & Mega Infrastructure",
    sector: "construction",
    subSector: "إنشاء شبكات الغاز الطبيعي وخطوط الأنابيب المغذية للمدن الصناعية",
    city: "qalyubia",
    governorate: "القليوبية",
    address: "طريق مصر الإسكندرية الزراعي، قليوب، القليوبية",
    phone1: "0132158900",
    mobile: "01004499113",
    hotline: "19749",
    website: "https://www.alfursan-eg.com",
    latitude: 30.1789,
    longitude: 31.2056,
    fleetSize: 95,
    fleetType: "شاحنات مد أنابيب غاز، أوناش شوكية وتلسكوبية، حفارات، وسيارات طوارئ مجهزة",
    fleetTires: "315/80R22.5 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "المقاول المعتمد لمشروعات توصيل الغاز الطبيعي لمناطق العبور وقها وبنها وشبرا الخيمة",
    contactPerson: "مدير صيانة الأسطول والمعدات",
    contactTitle: "Equipment & Fleet Maintenance Head",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.1789,31.2056"
  },
  {
    id: "eg_titan_779",
    nameAr: "شركة العمار العامة للمقاولات والاستثمار العقاري",
    nameEn: "Al Ammar General Contracting & Real Estate",
    sector: "construction",
    subSector: "تنفيذ الأبراج الفندقية والمجمعات التجارية والقرى السياحية بالساحل الشمالي",
    city: "matrouh",
    governorate: "مطروح",
    address: "طريق الإسكندرية - مطروح الساحلي، مارينا، العلمين، مطروح",
    phone1: "0464061200",
    mobile: "01006611885",
    hotline: "19419",
    website: "https://www.alammar-group.com",
    latitude: 30.8245,
    longitude: 28.9456,
    fleetSize: 110,
    fleetType: "شاحنات نقل مواد بناء، أوناش برجية، لوادر، وتريلات شحن معدات ميكانيكية",
    fleetTires: "315/80R22.5 • 12.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "رائدة التشييد السياحي والساحلي بالعلمين الجديدة وسيدي عبد الرحمن ورأس الحكمة",
    contactPerson: "مدير إدارة المعدات والأسطول الساحلي",
    contactTitle: "Coastal Fleet & Equipment Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.8245,28.9456"
  },
  {
    id: "eg_titan_780",
    nameAr: "شركة التعمير الهندسية للأعمال المتكاملة (Taamir Integrated Engineering)",
    nameEn: "Taamir Integrated Engineering Contracting",
    sector: "construction",
    subSector: "المقاولات الكهروميكانيكية المتكاملة لمحطات مترو الأنفاق والمونوريل والقطار الخفيف",
    city: "cairo",
    governorate: "القاهرة",
    address: "شارع الطيران، مدينة نصر، القاهرة",
    phone1: "0222621800",
    mobile: "01008855119",
    hotline: "19632",
    website: "https://www.taamir-integrated.com",
    latitude: 30.0541,
    longitude: 31.3189,
    fleetSize: 105,
    fleetType: "شاحنات نقل معدات إلكتروميكانيكية، أوناش هيدروليكية، وسيارات صيانة طوارئ على مدار 24 ساعة",
    fleetTires: "315/80R22.5 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "المقاول المتخصص في تركيب نظم التكييف المركزي والتهوية ومكافحة الحريق بأنفاق المترو",
    contactPerson: "رئيس قطاع الدعم اللوجستي للمشروعات",
    contactTitle: "Projects Logistics Support Head",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.0541,31.3189"
  },
  {
    id: "eg_titan_781",
    nameAr: "شركة الإسراء للمقاولات العامة وتشييد الجسور والأنفاق",
    nameEn: "Al Esraa Contracting & Bridges Construction",
    sector: "construction",
    subSector: "إنشاء الكباري الخرسانية والمعدنية والتقاطعات المرورية الحرة بالقاهرة الكبرى",
    city: "cairo",
    governorate: "القاهرة",
    address: "محور المشير، مدينة نصر، القاهرة",
    phone1: "0224019200",
    mobile: "01001166442",
    hotline: "19782",
    website: "https://www.alesraa-contracting.com",
    latitude: 30.0412,
    longitude: 31.3289,
    fleetSize: 125,
    fleetType: "أوناش رفع كمرات كباري عملاقة، تريلات هيدروليكية خاصة، خلاطات خرسانة، وماكينات رصف",
    fleetTires: "315/80R22.5 • 385/65R22.5 • 12.00R24",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "المنفذة لعدد من أهم كباري ومحاور شرق القاهرة ومصر الجديدة وتطوير الطرق الدائرية",
    contactPerson: "مدير عام الأسطول والمهمات الخاصة",
    contactTitle: "Special Missions & Fleets Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.0412,31.3289"
  },
  {
    id: "eg_titan_782",
    nameAr: "شركة النور للمقاولات العامة وأعمال الخرسانة سابقة الإجهاد",
    nameEn: "Al Noor Contracting & Post-Tension Concrete",
    sector: "construction",
    subSector: "تنفيذ الخرسانات سابقة الإجهاد والشد اللاحق للكباري والصوامع والأبراج الشاهقة",
    city: "giza",
    governorate: "الجيزة",
    address: "المنطقة الصناعية الثانية، السادس من أكتوبر، الجيزة",
    phone1: "0238341900",
    mobile: "01003322887",
    hotline: "19491",
    website: "https://www.alnoor-posttension.com",
    latitude: 29.9612,
    longitude: 30.9124,
    fleetSize: 85,
    fleetType: "ماكينات شد كابلات صلب هيدروليكية، شاحنات حقن أسمنتي، تريلات نقل مواد إنشائية، وروافع",
    fleetTires: "315/80R22.5 • 12.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "رائدة التكنولوجيا المتطورة في الشد اللاحق لكباري المونوريل والقطار الكهربائي السريع بمصر",
    contactPerson: "مدير العمليات الفنية والأسطول",
    contactTitle: "Technical Operations & Fleet Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.9612,30.9124"
  },
  {
    id: "eg_titan_783",
    nameAr: "شركة المعادي العامة للمقاولات والاستثمار العقاري",
    nameEn: "Maadi General Contracting & Real Estate",
    sector: "construction",
    subSector: "تطوير ضواحي المعادي، هضبة المقطم، وإنشاء المجمعات السكنية والإدارية الحديثة",
    city: "cairo",
    governorate: "القاهرة",
    address: "شارع النصر، المعادي الجديدة، القاهرة",
    phone1: "0225194100",
    mobile: "01005588114",
    hotline: "19318",
    website: "https://www.maadi-contracting.gov.eg",
    latitude: 29.9789,
    longitude: 31.2891,
    fleetSize: 115,
    fleetType: "شاحنات نقل قلاب، لوادر، أوناش هيدروليكية، وسيارات خدمات صيانة وإمداد",
    fleetTires: "315/80R22.5 • 12.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "إحدى قلاع قطاع الأعمال العام الرائدة في مشروعات الإسكان الفاخر والمتوسط بجنوب القاهرة",
    contactPerson: "مدير عام إدارة الحركة والورش",
    contactTitle: "Movement & Workshops General Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.9789,31.2891"
  },
  {
    id: "eg_titan_784",
    nameAr: "شركة المستقبل للمقاولات العامة والبنية التحتية (مستقبل سيتي)",
    nameEn: "Mostakbal Contracting & Mega Infrastructure",
    sector: "construction",
    subSector: "تطوير البنية التحتية والمرافق الذكية لمدينة المستقبل وطريق القاهرة السويس",
    city: "cairo",
    governorate: "القاهرة",
    address: "طريق القاهرة السويس الصحراوي، الكيلو 45، مستقبل سيتي، القاهرة",
    phone1: "0226891500",
    mobile: "01007711995",
    hotline: "19888",
    website: "https://www.mostakbal-contracting.com",
    latitude: 30.1124,
    longitude: 31.6789,
    fleetSize: 140,
    fleetType: "حفارات هيدروليكية، لوادر، تريلات نقل مواسير وكابلات فايبر وألياف ضوئية، ومعدات تسوية",
    fleetTires: "315/80R22.5 • 12.00R20 • 385/65R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "المسؤولة عن مد وتطوير شرايين المرافق الذكية ومحطات المعالجة والكهرباء بمستقبل سيتي",
    contactPerson: "مدير عام الخدمات اللوجستية والآليات",
    contactTitle: "Machinery & Logistics General Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.1124,31.6789"
  },
  {
    id: "eg_titan_785",
    nameAr: "شركة الفرسان للخرسانة والمقاولات البحرية بالبحر الأحمر",
    nameEn: "Al Fursan Marine Construction & Concrete",
    sector: "construction",
    subSector: "إنشاء المراسي السياحية واليخوت، كاسرات الأمواج، والمنشآت الفندقية البحرية",
    city: "red_sea",
    governorate: "البحر الأحمر",
    address: "طريق المطار، الغردقة، البحر الأحمر",
    phone1: "0653451900",
    mobile: "01009933886",
    hotline: "19726",
    website: "https://www.alfursan-marine.com",
    latitude: 27.1789,
    longitude: 33.8124,
    fleetSize: 85,
    fleetType: "صنادل وقاطرات بحرية، شاحنات نقل صخور بحرية، لوادر، ومضخات صب خرسانة شاطئية",
    fleetTires: "315/80R22.5 • 12.00R24",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "المتخصصة في تطوير مارينا اليخوت والإنشاءات الشاطئية بالجونة والغردقة وسهل حشيش ومكادي",
    contactPerson: "مدير الأسطول البحري والبري للمشروعات",
    contactTitle: "Marine & Land Fleet Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=27.1789,33.8124"
  },
  {
    id: "eg_titan_786",
    nameAr: "شركة حلوان لمحطات الطاقة والمقاولات الكهروميكانيكية",
    nameEn: "Helwan Power Plants & Electromechanical Contracting",
    sector: "construction",
    subSector: "إنشاء وصيانة التوربينات البخارية والغازية لمحطات توليد الكهرباء العملاقة",
    city: "cairo",
    governorate: "القاهرة",
    address: "المنطقة الصناعية بكفر العلو، حلوان، القاهرة",
    phone1: "0223691800",
    mobile: "01001188447",
    hotline: "19577",
    website: "https://www.helwan-power.com",
    latitude: 29.8456,
    longitude: 31.3124,
    fleetSize: 100,
    fleetType: "أوناش رفع ثقيل، شاحنات نقل توربينات ومحولات، وسيارات صيانة طوارئ متخصصة",
    fleetTires: "315/80R22.5 • 385/65R22.5 • 12.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الصرح الهندسي المتخصص في صيانة وإنشاء محطات توليد الكهرباء المركبة بحلوان والكريمات والعاصمة",
    contactPerson: "مدير عام الصيانة والورش المركزية",
    contactTitle: "Central Workshops & Maintenance General Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.8456,31.3124"
  },
  {
    id: "eg_titan_787",
    nameAr: "شركة الدلتا العامة للمقاولات والاستثمار الزراعي",
    nameEn: "Delta General Contracting & Agricultural Investment",
    sector: "construction",
    subSector: "استصلاح الأراضي الزراعية بالدلتا الجديدة، شق الترع الرئيسية، ومحطات الطلمبات",
    city: "beheira",
    governorate: "البحيرة",
    address: "طريق مصر الإسكندرية الصحراوي، وادي النطرون، البحيرة",
    phone1: "0453671200",
    mobile: "01004477881",
    hotline: "19648",
    website: "https://www.delta-agricon.com",
    latitude: 30.4124,
    longitude: 30.3456,
    fleetSize: 130,
    fleetType: "جرارات استصلاح ثقيلة، بلدوزرات كتربيلر، تريلات قلاب، وحفارات شق قنوات مائية",
    fleetTires: "315/80R22.5 • 12.00R24 • 14.00R24",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "من كبرى شركات المقاولات الزراعية العاملة في تسوية واستصلاح مساحات شاسعة بمشروع الدلتا الجديدة",
    contactPerson: "مدير قطاع الآليات والمعدات الزراعية الثقيلة",
    contactTitle: "Heavy Agricultural Fleets Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.4124,30.3456"
  },
  {
    id: "eg_titan_788",
    nameAr: "شركة السويس للإنشاءات المعدنية وأعمال اللحام التخصصية",
    nameEn: "Suez Steel Construction & Specialized Welding",
    sector: "construction",
    subSector: "تصنيع خزانات الوقود الكروية والأسطوانية للموانئ ومحطات البترول",
    city: "suez",
    governorate: "السويس",
    address: "المنطقة الحرة بعتاقة، السويس",
    phone1: "0623690500",
    mobile: "01006633994",
    hotline: "19407",
    website: "https://www.suez-steelcon.com",
    latitude: 29.9456,
    longitude: 32.4891,
    fleetSize: 95,
    fleetType: "تريلات تريلا فرش نقل ألواح صلب مدرفلة، أوناش هيدروليكية، وسيارات فحص إشعاعي للحامات",
    fleetTires: "315/80R22.5 • 12.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "متخصصة في بناء مستودعات التخزين الكبرى لصهاريج السولار والمازوت والغاز المسال بميناء السويس",
    contactPerson: "مدير إدارة النقل والمعدات الميدانية",
    contactTitle: "Field Equipment & Transport Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.9456,32.4891"
  },
  {
    id: "eg_titan_789",
    nameAr: "شركة الإسكندرية لأعمال العزل والترميم الإنشائي المتخصص",
    nameEn: "Alexandria Specialized Waterproofing & Structural Repair",
    sector: "construction",
    subSector: "حقن وترميم الكباري والأنفاق والمنشآت الخرسانية المتضررة من مياه البحر",
    city: "alexandria",
    governorate: "الإسكندرية",
    address: "شارع بورسعيد، الشاطبي، الإسكندرية",
    phone1: "035912400",
    mobile: "01008822446",
    hotline: "19731",
    website: "https://www.alex-repair.com",
    latitude: 31.2145,
    longitude: 29.9124,
    fleetSize: 80,
    fleetType: "شاحنات حقن خرساني بضغط عالي، سيارات عزل مائي وحراري، تريلات نقل مواد إيبوكسية، وأوناش صيانة",
    fleetTires: "315/80R22.5 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "رائدة حماية وترميم المنشآت الخرسانية الساحلية وكباري ستانلي ومحرم بك وتوسعات الكورنيش",
    contactPerson: "مدير المشروعات والأسطول الفني",
    contactTitle: "Technical Fleet & Projects Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=31.2145,29.9124"
  },
  {
    id: "eg_titan_790",
    nameAr: "شركة الصفا للمقاولات العامة والإنشاءات التعدينية (Al Safa Mining & Construction)",
    nameEn: "Al Safa Mining & General Contracting Mega Fleet",
    sector: "construction",
    subSector: "فتح وتطوير مناجم الفوسفات والذهب والجرانيت بالصحراء الشرقية وأسوان",
    city: "red_sea",
    governorate: "البحر الأحمر",
    address: "طريق القصير - سفاجا، البحر الأحمر",
    phone1: "0653331400",
    mobile: "01002277116",
    hotline: "19842",
    website: "https://www.alsafa-mining.com",
    latitude: 26.1124,
    longitude: 34.2891,
    fleetSize: 135,
    fleetType: "تريلات قلابات صخور تعدينية 60 طن، حفارات جبلية هيفي ديوتي، شاحنات وقود صحراوية، ولوادر",
    fleetTires: "12.00R24 • 14.00R24 • 315/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "المقاول المنجمي الأكبر المشارك في نقل وخدمة خامات الفوسفات بمناجم أبو طرطور والسباعية وسفاجا",
    contactPerson: "مدير عام النقل المنجمي والصحراوي",
    contactTitle: "Mining & Desert Fleets General Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=26.1124,34.2891"
  },
  {
    id: "eg_titan_791",
    nameAr: "شركة الفتح لتوريد وتأجير المعدات الثقيلة وأوناش الرفع العملاقة",
    nameEn: "Al Fateh Heavy Equipment & Mega Cranes Rental",
    sector: "construction",
    subSector: "تأجير وتشغيل أوناش الرفع الهيدروليكية والتلسكوبية حتى 800 طن للمشروعات البترولية والصناعية",
    city: "cairo",
    governorate: "القاهرة",
    address: "طريق الأوتوستراد، صقر قريش، المعادي، القاهرة",
    phone1: "0227051800",
    mobile: "01004433779",
    hotline: "19934",
    website: "https://www.alfateh-cranes.com",
    latitude: 29.9689,
    longitude: 31.3124,
    fleetSize: 110,
    fleetType: "أوناش مجنزرة ليهبر وتادانو حمولات 100 إلى 800 طن، تريلات هيدروليكية جولد هوفر لنقل التوربينات",
    fleetTires: "385/65R22.5 • 315/80R22.5 • 12.00R24",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الأسطول المعتمد لرفع كمرات الكباري العملاقة وتركيب توربينات الرياح بمزارع جبل الزيت والزعفرانة",
    contactPerson: "مدير عام إدارة الأوناش والحمولات الثقيلة",
    contactTitle: "Mega Cranes & Heavy Lift Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.9689,31.3124"
  },
  {
    id: "eg_titan_792",
    nameAr: "شركة النيل للطرق والكباري والمقاولات العامة (إحدى شركات القابضة للنقل)",
    nameEn: "Nile Roads & Bridges Construction (Holding Co. for Transport)",
    sector: "construction",
    subSector: "إنشاء وصيانة الطرق الحرة والكباري والأنفاق التابعة للهيئة العامة للطرق والكباري",
    city: "cairo",
    governorate: "القاهرة",
    address: "شارع القصر العيني، السيدة زينب، القاهرة",
    phone1: "0227941200",
    mobile: "01007755331",
    hotline: "19515",
    website: "https://www.nile-roads.gov.eg",
    latitude: 30.0389,
    longitude: 31.2345,
    fleetSize: 200,
    fleetType: "فينيشرات أسفلت، كاشطات أسفلت، تريلات قلاب نقل ركام ومواد بترولية، ومعدات صيانة طرق",
    fleetTires: "315/80R22.5 • 12.00R20 • 385/65R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الصرح الوطني التاريخي التابع لوزارة النقل المنفذ لآلاف الكيلومترات من الشبكة القومية للطرق بمصر",
    contactPerson: "رئيس قطاعات التشغيل الميكانيكي والأسطول",
    contactTitle: "Mechanical Fleets & Operations Sector Head",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.0389,31.2345"
  },
  {
    id: "eg_titan_793",
    nameAr: "شركة النيل للإنشاء والرصف (إحدى شركات وزارة النقل المصرية)",
    nameEn: "Nile Construction & Paving Co. (Ministry of Transport)",
    sector: "construction",
    subSector: "تنفيذ مشروعات ازدواج الطرق الصحراوية والكباري السطحية على الرياحات المائية",
    city: "cairo",
    governorate: "القاهرة",
    address: "شارع وزارة النقل، مدينة نصر، القاهرة",
    phone1: "0222601900",
    mobile: "01009988223",
    hotline: "19481",
    website: "https://www.nile-paving.gov.eg",
    latitude: 30.0612,
    longitude: 31.3189,
    fleetSize: 180,
    fleetType: "هراسات أسفلت وتربة، تريلات قلاب، خلاطات أسفلت عملاقة، وماكينات دهان وتخطيط طرق",
    fleetTires: "315/80R22.5 • 12.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "المشاركة في تنفيذ الطريق الدائري الإقليمي ومحاور ربط محافظات الدلتا بالطرق الحرة السريعة",
    contactPerson: "مدير عام المعدات والمستودعات المركزية",
    contactTitle: "Heavy Equipment & Central Stores Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.0612,31.3189"
  },
  {
    id: "eg_titan_794",
    nameAr: "شركة السويدي للحلول الرقمية والبنية التحتية الذكية (Elsewedy Digital Infrastructure)",
    nameEn: "Elsewedy Digital & Smart Infrastructure Fleets",
    sector: "construction",
    subSector: "مد شبكات الألياف الضوئية الذكية وربط مراكز البيانات القومية بالمدن الذكية",
    city: "cairo",
    governorate: "القاهرة",
    address: "مجمع السويدي، التجمع الخامس، شارع التسعين، القاهرة",
    phone1: "0227599700",
    mobile: "01001133557",
    hotline: "16274",
    website: "https://www.elsewedyelectric.com/digital",
    latitude: 30.0245,
    longitude: 31.4312,
    fleetSize: 110,
    fleetType: "شاحنات مد كابلات فايبر مجهزة بنظم الحفر النفقي الموجه (HDD)، سيارات اختبار ألياف ضوئية",
    fleetTires: "295/80R22.5 • 225/75R16",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "المنفذة للبنية التحتية الذكية ومراكز التحكم الموحدة للمدن الذكية بالعاصمة الإدارية والعلمين",
    contactPerson: "مدير الأسطول الميداني والعمليات الذكية",
    contactTitle: "Field Fleet & Smart Operations Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.0245,31.4312"
  },
  {
    id: "eg_titan_795",
    nameAr: "شركة مصر لأعمال الهيدروليك والأساسات المتقدمة (Misr Hydraulics & Piling)",
    nameEn: "Misr Advanced Hydraulics & Foundation Piling",
    sector: "construction",
    subSector: "تنفيذ خوازيق السند، تثبيت الميول الجبلية، ومكافحة انهيارات التربة بمشروعات الطرق الجبلية",
    city: "cairo",
    governorate: "القاهرة",
    address: "طريق النصر، تقاطع مكرم عبيد، مدينة نصر، القاهرة",
    phone1: "0222731800",
    mobile: "01003366114",
    hotline: "19608",
    website: "https://www.misr-hydraulics.com",
    latitude: 30.0645,
    longitude: 31.3312,
    fleetSize: 90,
    fleetType: "ماكينات حفر ميكانيكية متقدمة، ضواغط هواء عملاقة أطلس كوبكو، وتريلات شحن معدات ثقيلة",
    fleetTires: "315/80R22.5 • 12.00R24",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "رائدة تثبيت الصخور وتأمين الميول بمشروعات هضبة الجلالة وطريق السخنة وطريق شرم الشيخ الجديد",
    contactPerson: "مدير صيانة الآليات والأسطول",
    contactTitle: "Machinery Maintenance & Transport Head",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.0645,31.3312"
  },
  {
    id: "eg_titan_796",
    nameAr: "شركة الإسكندرية لتجارة وتأجير المعدات الثقيلة (Alex Heavy Machinery Fleets)",
    nameEn: "Alexandria Heavy Machinery & Cranes Rental Mega Fleet",
    sector: "construction",
    subSector: "تأجير أساطيل الحفارات واللوادر والأوناش البحرية لخدمة المشروعات الساحلية والصناعية",
    city: "alexandria",
    governorate: "الإسكندرية",
    address: "طريق المكس، القباري، الإسكندرية",
    phone1: "034401500",
    mobile: "01005599447",
    hotline: "19777",
    website: "https://www.alexheavy.com",
    latitude: 31.1589,
    longitude: 29.8541,
    fleetSize: 115,
    fleetType: "لوادر كتربيلر 966 و 980، حفارات 30 إلى 50 طن، أوناش بحرية وبرية، وتريلات لوابد لنقل المعدات",
    fleetTires: "315/80R22.5 • 12.00R24 • 14.00R24 • 23.5R25",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "أكبر أسطول تأجير معدات ثقيلة يخدم موانئ الإسكندرية والدخيلة وأبو قير ومحطة الضبعة النووية",
    contactPerson: "مدير عام حركة الآليات الثقيلة",
    contactTitle: "Heavy Equipment Movement Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=31.1589,29.8541"
  },
  {
    id: "eg_titan_797",
    nameAr: "شركة المقاولات المصرية (مختار إبراهيم - قطاع الأعمال العام)",
    nameEn: "Egyptian Contracting Co. (Mokhtar Ibrahim Mega Infrastructure)",
    sector: "construction",
    subSector: "المشروعات الكبرى لشبكات مياه الشرب والصرف الصحي ومحطات المعالجة بمصر والدول العربية",
    city: "cairo",
    governorate: "القاهرة",
    address: "شارع مصدق، الدقي، الجيزة",
    phone1: "0237604100",
    mobile: "01008811335",
    hotline: "19441",
    website: "https://www.mokhtar-ibrahim.com",
    latitude: 30.0412,
    longitude: 31.2056,
    fleetSize: 250,
    fleetType: "حفارات عملاقة، تريلات نقل مواسير زهر مرن وصلب، ماكينات خرق نفقي تحت السكك الحديدية، ولوادر",
    fleetTires: "315/80R22.5 • 12.00R20 • 385/65R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "القلعة التاريخية التابعة للشركة القابضة للتشييد والتعمير والمصنفة دولياً في مشروعات البنية التحتية والمياه",
    contactPerson: "رئيس قطاعات المعدات والتشغيل الميكانيكي",
    contactTitle: "Mechanical Equipment & Fleets Sector Head",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.0412,31.2056"
  },
  {
    id: "eg_titan_798",
    nameAr: "شركة النصر العامة للمرافق والتركيبات (ميتالكو - Metalco Infrastructure)",
    nameEn: "El Nasr for Steel Structures & Utilities (Metalco)",
    sector: "construction",
    subSector: "تصنيع كباري المشاة والسيارات المعدنية وخطوط الأنابيب الفولاذية الضخمة لمحطات المياه",
    city: "cairo",
    governorate: "القاهرة",
    address: "المنطقة الصناعية بمسطرد، شبرا الخيمة، القليوبية",
    phone1: "0242201900",
    mobile: "01002244883",
    hotline: "19329",
    website: "https://www.metalco.gov.eg",
    latitude: 30.1345,
    longitude: 31.3124,
    fleetSize: 130,
    fleetType: "تريلات تريلا فرش نقل كباري معدنية كاملة التجهيز، أوناش هيدروليكية، وشاحنات شحن ثقيل",
    fleetTires: "315/80R22.5 • 385/65R22.5 • 12.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الصرح الوطني التاريخي لتصنيع وتشييد الكباري المعدنية وأبراج الكهرباء والاتصالات بمصر",
    contactPerson: "مدير عام النقل والمهمات المعدنية",
    contactTitle: "Steel Missions & Transport General Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.1345,31.3124"
  },
  {
    id: "eg_titan_799",
    nameAr: "شركة التعمير للرصف والإنشاءات التخصصية (Taamir Paving & Specialized Works)",
    nameEn: "Taamir Paving & Specialized Construction Fleet",
    sector: "construction",
    subSector: "رصف ممرات ومواقف الطائرات بالمطارات الدولية وتطوير الطرق السريعة",
    city: "cairo",
    governorate: "القاهرة",
    address: "شارع النصر، مساكن شيراتون، مصر الجديدة، القاهرة",
    phone1: "0222681500",
    mobile: "01004488117",
    hotline: "19614",
    website: "https://www.taamir-paving.com",
    latitude: 30.1089,
    longitude: 31.3789,
    fleetSize: 110,
    fleetType: "فينيشرات أسفلت بمجسات ليزر عالية الدقة، هراسات أسفلت ثقيلة، وتريلات قلاب مجهزة للحفاظ على حرارة الخلطة",
    fleetTires: "315/80R22.5 • 12.00R20 • 385/65R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "المتخصصة في رصف ممرات مطار القاهرة الدولي ومطار سفنكس ومطار العاصمة الإدارية",
    contactPerson: "مدير قطاع الخلاطات الأسفلتية والمعدات",
    contactTitle: "Asphalt Plants & Heavy Fleets Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.1089,31.3789"
  },
  {
    id: "eg_titan_800",
    nameAr: "شركة المقاولات العامة واستصلاح الأراضي (العامة للاستصلاح - قطاع الأعمال)",
    nameEn: "General Land Reclamation & Contracting Co.",
    sector: "construction",
    subSector: "تسوية الأراضي الصحراوية بالليزر، حفر قنوات الري الكبرى، وإنشاء القرى النموذجية بالريف المصري",
    city: "cairo",
    governorate: "القاهرة",
    address: "شارع الجيزة، الدقي، الجيزة",
    phone1: "0237492100",
    mobile: "01007722449",
    hotline: "19548",
    website: "https://www.general-reclamation.gov.eg",
    latitude: 30.0345,
    longitude: 31.2112,
    fleetSize: 180,
    fleetType: "بلدوزرات كتربيلر D8 و D9، جرارات زراعية ثقيلة، كاشطات تربة، وتريلات لوابد لنقل الآليات",
    fleetTires: "12.00R24 • 14.00R24 • 315/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الصرح الوطني التاريخي التابع لقطاع الأعمال العام المنفذ لمليون ونصف المليون فدان ومشروعات استصلاح سيناء والصعيد",
    contactPerson: "رئيس قطاعات التشغيل الميكانيكي والآليات",
    contactTitle: "Mechanical Fleets & Operations Sector Head",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.0345,31.2112"
  }
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { wave7Part2 };
}
