/**
 * scripts/wave6_data_part6.js
 * Part 6 of Wave 6 Titans (eg_titan_666 to eg_titan_700) - 35 Industrial Titans.
 * Sectors: Engineering & Infrastructure, Dry Ports, Retail Logistics, Freight Fleets & Pharma & Tourism.
 */

const wave6Part6 = [
  // 8. Engineering & Infrastructure (5)
  {
    id: "eg_titan_666",
    nameAr: "شركة أوراسكوم للفنادق والتنمية والإنشاءات (الجونة والبحر الأحمر)",
    nameEn: "Orascom Development Egypt (El Gouna Mega Construction & Fleet)",
    sector: "construction",
    subSector: "تطوير وإدارة المدن السياحية الشاملة والمرافق والبنية التحتية المتكاملة بالجونة وطابا",
    city: "red_sea",
    governorate: "البحر الأحمر",
    address: "مدينة الجونة، شمال الغردقة، محافظة البحر الأحمر",
    phone1: "0653580100",
    mobile: "01001144229",
    hotline: "16266",
    website: "https://www.orascomde.com",
    latitude: 27.3912,
    longitude: 33.6812,
    fleetSize: 110,
    fleetType: "شاحنات خدمات مدن، لوادر صيانة طرق، أساطيل حافلات نقل موظفين وسائحين، وسيارات كهربائية",
    fleetTires: "315/80R22.5 • 295/80R22.5 • 11.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "المطور والمدير العام لمدينة الجونة بالبحر الأحمر بأسطول مركبات خدمية وحافلات نقل عمال ضخم",
    contactPerson: "مدير عام الخدمات اللوجستية والحركة بالجونة",
    contactTitle: "El Gouna Town Transport & Logistics Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=27.3912,33.6812"
  },
  {
    id: "eg_titan_667",
    nameAr: "شركة الشمس للإسكان والتعمير ومعدات المواقع (القاهرة)",
    nameEn: "El Shams Housing & Urban Development Co.",
    sector: "construction",
    subSector: "تنفيذ المشروعات السكنية والاستثمارية الكبرى وتجهيزات البنية التحتية بالقاهرة والسادس من أكتوبر",
    city: "cairo",
    governorate: "القاهرة",
    address: "شارع عبد الخالق ثروت، وسط البلد، القاهرة",
    phone1: "0223931200",
    mobile: "01227766113",
    hotline: "16267",
    website: "https://www.elshamshousing.com",
    latitude: 30.0512,
    longitude: 31.2412,
    fleetSize: 60,
    fleetType: "شاحنات نقل مواد ومهمات، لوادر تسوية، سيارات إشراف، وأتوبيسات ركاب",
    fleetTires: "315/80R22.5 • 295/80R22.5 • 11.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "شركة إسكان وتعمير قطاع عام كبرى تابعة للشركة القابضة للتشييد والتعمير",
    contactPerson: "مدير حركة السيارات والمعدات",
    contactTitle: "Fleet Movement Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.0512,31.2412"
  },
  {
    id: "eg_titan_668",
    nameAr: "شركة الجيزة للأنظمة الهندسية وتنفيذ مشاريع البنية الذكية (Giza Systems)",
    nameEn: "Giza Systems - Mega Infrastructure Engineering & Field Operations",
    sector: "construction",
    subSector: "تنفيذ مشروعات البنية التحتية الذكية، خطوط الألياف الضوئية، محطات التحكم الآلي في المياه والكهرباء والسكك الحديدية",
    city: "cairo",
    governorate: "القاهرة",
    address: "شارع التسعين الشمالي، التجمع الخامس، القاهرة الجديدة",
    phone1: "0226141000",
    mobile: "01118833446",
    hotline: "16268",
    website: "https://www.gizasystems.com",
    latitude: 30.0212,
    longitude: 31.4389,
    fleetSize: 95,
    fleetType: "سيارات فانات صيانة تكنولوجية مجهزة، شاحنات مد كابلات، سيارات خدمة سريعة 4x4، وأتوبيسات مهندسين",
    fleetTires: "225/75R17.5 • 245/75R16 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الرائد الإقليمي في تنفيذ البنية التحتية الذكية بمصر والشرق الأوسط بأسطول سيارات وفرق هندسية ميدانية يغطي كافة المحافظات",
    contactPerson: "مدير عام العمليات الميدانية والأسطول",
    contactTitle: "Field Operations & Fleet General Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.0212,31.4389"
  },
  {
    id: "eg_titan_669",
    nameAr: "شركة التعمير والاستشارات الهندسية الكبرى (الدقي والقاهرة)",
    nameEn: "Engineering Consulting & Mega Urban Development Co. (TAMEER)",
    sector: "construction",
    subSector: "تطوير وإشراف على تنفيذ المشروعات العقارية والصناعية الكبرى والبنية الأساسية",
    city: "giza",
    governorate: "الجيزة",
    address: "ميدان المساحة، الدقي، الجيزة",
    phone1: "0237612400",
    mobile: "01004499113",
    hotline: "16269",
    website: "https://www.tameer.com.eg",
    latitude: 30.0389,
    longitude: 31.2112,
    fleetSize: 55,
    fleetType: "سيارات إشراف هندسي، شاحنات نقل مهمات، وسيارات نقل مهندسين",
    fleetTires: "245/75R16 • 225/75R17.5 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "من أقدم بيوت الاستشارات والتطوير الهندسي في مصر",
    contactPerson: "مدير الخدمات المساندة والحركة",
    contactTitle: "Support Services & Transport Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.0389,31.2112"
  },
  {
    id: "eg_titan_670",
    nameAr: "شركة الأهرام للمقاولات العامة والإنشاءات الحديثة (المنصورة والقاهرة)",
    nameEn: "Al Ahram for General Contracting & Modern Construction",
    sector: "construction",
    subSector: "تنفيذ مشروعات الطرق والكباري والصرف الصحي ومحطات المعالجة بالوجه البحري",
    city: "dakahlia",
    governorate: "الدقهلية",
    address: "شارع الجيش، المنصورة، محافظة الدقهلية / فرع القاهرة",
    phone1: "0502314500",
    mobile: "01223366448",
    hotline: "16270",
    website: "https://www.ahramcontracting.com",
    latitude: 31.0412,
    longitude: 31.3812,
    fleetSize: 70,
    fleetType: "شاحنات قلاب، خلاطات أسمنت، لوادر، تريلات نقل معدات، وأتوبيسات مواقع",
    fleetTires: "315/80R22.5 • 12.00R24 • 12.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "شركة مقاولات فئة أولى رائدة في محافظات الدلتا",
    contactPerson: "مدير حركة المعدات",
    contactTitle: "Equipment & Transport Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=31.0412,31.3812"
  },

  // 9. Dry Ports, Central Logistics & Couriers (15)
  {
    id: "eg_titan_671",
    nameAr: "شركة السادس من أكتوبر للموانئ الجافة (ODP - الميناء الجاف بمدينة 6 أكتوبر)",
    nameEn: "October Dry Port (ODP - First Mega Dry Port in Egypt)",
    sector: "transport",
    subSector: "استقبال وتخليص وفحص الحاويات المشحونة بالسكة الحديد من موانئ الإسكندرية والدخيلة والسخنة",
    city: "giza",
    governorate: "الجيزة",
    address: "المنطقة الصناعية الامتداد الغربي، مدينة السادس من أكتوبر، الجيزة",
    phone1: "0238241200",
    mobile: "01115599228",
    hotline: "16271",
    website: "https://www.octoberdryport.com",
    latitude: 29.8812,
    longitude: 30.8412,
    fleetSize: 110,
    fleetType: "رافعات حاويات عملاقة (Reach Stackers)، جرارات موانئ (Yard Tractors)، تريلات نقل حاويات، وسيارات خدمة ساحات",
    fleetTires: "18.00R25 • 315/80R22.5 • 385/65R22.5 • 12.00R24",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الميناء الجاف القومي الأول في مصر الصديق للبيئة الذي يقلل تكدس موانئ البحر المتوسط بأسطول معدات أرصفة وتريلات",
    contactPerson: "مدير عام العمليات اللوجستية وساحات الحاويات",
    contactTitle: "Terminal Operations & Yard Fleet Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.8812,30.8412"
  },
  {
    id: "eg_titan_672",
    nameAr: "شركة ميناء العاشر من رمضان الجاف والمستودعات الجمركية (العاشر من رمضان)",
    nameEn: "10th of Ramadan Dry Port & Bonded Logistics Terminal",
    sector: "transport",
    subSector: "المركز اللوجستي التبادلي لحاويات البضائع والمستودعات الجمركية لمنطقة شرق القاهرة والقناة",
    city: "sharqia",
    governorate: "الشرقية",
    address: "طريق الروبيكي، المنطقة الصناعية اللوجستية، مدينة العاشر من رمضان",
    phone1: "015418900",
    mobile: "01007788114",
    hotline: "16272",
    website: "https://www.10thdryport.com",
    latitude: 30.2712,
    longitude: 31.7889,
    fleetSize: 90,
    fleetType: "رافعات حاويات ريتش ستاكر، تريلات نقل بضائع، شاحنات جمركية مجهزة، وأتوبيسات ركاب",
    fleetTires: "18.00R25 • 315/80R22.5 • 385/65R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الميناء الجاف المحوري لخدمة كبرى مصانع العاشر من رمضان وبدر والعبور ومربوط بموانئ بورسعيد والسويس",
    contactPerson: "مدير حركة المعدات والساحات الجمركية",
    contactTitle: "Terminal Logistics & Fleet Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.2712,31.7889"
  },
  {
    id: "eg_titan_673",
    nameAr: "ميناء السلوم البري ومحطة الشاحنات الدولية الكبرى (مطروح والسلوم)",
    nameEn: "Salloum Land Port & International Trucking Freight Terminal",
    sector: "transport",
    subSector: "أكبر منفذ وميناء بري تجاري دولي يربط مصر بليبيا ودول المغرب العربي لمرور شاحنات الترانزيت الدولية",
    city: "matrouh",
    governorate: "مطروح",
    address: "هضبة السلوم، المنفذ البري الدولي، محافظة مطروح",
    phone1: "0464401200",
    mobile: "01229933557",
    hotline: "16273",
    website: "https://www.salloumport.gov.eg",
    latitude: 31.5412,
    longitude: 25.1512,
    fleetSize: 95,
    fleetType: "شاحنات فحص جمركي وإشراف، ساحات انتظار تستوعب آلاف الشاحنات يومياً، سيارات سحب طوارئ، وأتوبيسات",
    fleetTires: "315/80R22.5 • 385/65R22.5 • 12.00R24",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الميناء البري الاستراتيجي المحدث بالكامل لاستيعاب التجارة البينية مع شمال إفريقيا وأكبر تجمع للشاحنات الدولية",
    contactPerson: "مدير عام التشغيل والخدمات الفنية للشاحنات",
    contactTitle: "Terminal Fleet & Cross-Border Logistics Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=31.5412,25.1512"
  },
  {
    id: "eg_titan_674",
    nameAr: "ميناء سفاجا التعديني ومحطة الصب الجاف والتصدير (سفاجا)",
    nameEn: "Safaga Industrial Mining Port & Bulk Cargo Terminals",
    sector: "transport",
    subSector: "محطات مناولة وتصدير المواد التعدينية السائبة (فوسفات، جبس، ملح) واستقبال فحم الكوك والقمح",
    city: "red_sea",
    governorate: "البحر الأحمر",
    address: "طريق القصير - سفاجا، ميناء سفاجا التعديني، البحر الأحمر",
    phone1: "0653252100",
    mobile: "01112244778",
    hotline: "16274",
    website: "https://www.safagabulk.com",
    latitude: 26.7345,
    longitude: 33.9345,
    fleetSize: 85,
    fleetType: "شاحنات تفريغ هيدروليكية، كباشات ولوادر عملاقة، قاطرات ساحات، وأتوبيسات نقل ورديات الميناء",
    fleetTires: "12.00R24 • 315/80R22.5 • 26.5R25",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "المنفذ البحري الرئيسي لصادرات التعدين في صعيد مصر والبحر الأحمر بأسطول معدات شحن ثقيل متخصص",
    contactPerson: "مدير عام محطات الشحن والتفريغ",
    contactTitle: "Bulk Handling & Terminal Fleet Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=26.7345,33.9345"
  },
  {
    id: "eg_titan_675",
    nameAr: "شركة بي تك (B.TECH) للوجستيات وسلاسل التوزيع المركزي (مستودعات 6 أكتوبر المركزية)",
    nameEn: "B.TECH Mega Central Logistics & Distribution Hub (6th of October)",
    sector: "transport",
    subSector: "أكبر شبكة توزيع وإمداد للأجهزة الكهربائية والإلكترونيات الاستهلاكية وسلاسل الفروع بمصر",
    city: "giza",
    governorate: "الجيزة",
    address: "المنطقة اللوجستية، امتداد 6 أكتوبر، محافظة الجيزة",
    phone1: "0238281000",
    mobile: "01004488339",
    hotline: "16275",
    website: "https://www.btech.com",
    latitude: 29.8945,
    longitude: 30.8612,
    fleetSize: 140,
    fleetType: "شاحنات مقفولة مجهزة بنظام تتبع GPS، سيارات جامبو وفانات توزيع، وتريلات شحن ثقيل للمحافظات",
    fleetTires: "225/75R17.5 • 295/80R22.5 • 315/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "رائد تجارة وتوزيع الأجهزة الكهربائية في مصر بأكبر أسطول توزيع بري يجوب محافظات الجمهورية من الإسكندرية لأسوان",
    contactPerson: "رئيس قطاع سلاسل الإمداد والأسطول الوطني",
    contactTitle: "Head of Supply Chain & National Fleet Operations",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.8945,30.8612"
  },
  {
    id: "eg_titan_676",
    nameAr: "مجموعة الفطيم مصر ومراكز التوزيع الكبرى (كايرو فستيفال سيتي)",
    nameEn: "Al-Futtaim Group Egypt - Retail & Central Logistics Hub",
    sector: "transport",
    subSector: "إدارة سلاسل الإمداد وتوزيع التجزئة لكبرى العلامات التجارية (إيكيا، تويز آر أص، ماركس آند سبنسر، زارا)",
    city: "cairo",
    governorate: "القاهرة",
    address: "مجمع كايرو فستيفال سيتي الإداري، الطريق الدائري، القاهرة الجديدة",
    phone1: "0226188000",
    mobile: "01228833991",
    hotline: "16276",
    website: "https://www.alfuttaim.com",
    latitude: 30.0312,
    longitude: 31.4089,
    fleetSize: 95,
    fleetType: "شاحنات شحن أثاث وبضائع مجهزة، فانات توصيل منازل، شاحنات جامبو، وسيارات خدمة",
    fleetTires: "225/75R17.5 • 295/80R22.5 • 315/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "المجموعة الإقليمية العملاقة للتجزئة واللوجستيات بأسطول شاحنات توصيل وتوزيع يغطي القاهرة الكبرى والإسكندرية",
    contactPerson: "مدير عام النقل واللوجستيات اللوجستية بمصر",
    contactTitle: "Country Fleet & Logistics Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.0312,31.4089"
  },
  {
    id: "eg_titan_677",
    nameAr: "مراكز توزيع كارفور ومستودعات التبريد المركزي الكبرى (العبور و6 أكتوبر)",
    nameEn: "Carrefour Egypt Central Distribution & Cold Logistics Mega Hubs",
    sector: "transport",
    subSector: "تغذية سلاسل الهايبرماركت والسوبرماركت بالبضائع الجافة والمبردة واللحوم والأسماك والخضروات الطازجة",
    city: "qalyubia",
    governorate: "القليوبية",
    address: "المنطقة اللوجستية، مدينة العبور / مجمع مستودعات 6 أكتوبر المركزية",
    phone1: "0244891200",
    mobile: "01115599441",
    hotline: "16277",
    website: "https://www.carrefouregypt.com",
    latitude: 30.2412,
    longitude: 31.4889,
    fleetSize: 120,
    fleetType: "تريلات برادات مبردة حديثة ثيرموكنج، شاحنات جامبو جافة، فانات توصيل سريع، وسيارات صيانة",
    fleetTires: "315/80R22.5 • 295/80R22.5 • 225/75R17.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "سلسلة التجزئة الأضخم بمصر (ماجد الفطيم) بأسطول شاحنات مبردة وجافة يعمل 24 ساعة لتزويد الفروع بالمنتجات",
    contactPerson: "مدير عام الحركة وأسطول النقل المبرد واللوجستيات",
    contactTitle: "National Cold Chain & Logistics Operations Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.2412,31.4889"
  },
  {
    id: "eg_titan_678",
    nameAr: "شركة رنين للتجارة والتوزيع المركزي وشبكات التوريد (أساطيل شاحنات البضائع)",
    nameEn: "Raneen Mega Retail, Warehousing & Central Logistics Fleet",
    sector: "transport",
    subSector: "شحن وتوزيع الأدوات المنزلية، الأجهزة الكهربائية، والمفروشات لشبكة فروع رنين بكافة محافظات مصر",
    city: "giza",
    governorate: "الجيزة",
    address: "المنطقة الصناعية الرابعة، مدينة 6 أكتوبر، محافظة الجيزة",
    phone1: "0238339500",
    mobile: "01002244993",
    hotline: "16278",
    website: "https://www.raneen.com",
    latitude: 29.9312,
    longitude: 30.9089,
    fleetSize: 100,
    fleetType: "شاحنات نقل مغلقة، تريلات شحن ثقيل، سيارات جامبو توزيع للمحافظات، وسيارات نقل عمال",
    fleetTires: "295/80R22.5 • 315/80R22.5 • 225/75R17.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "إحدى كبرى سلاسل التجزئة للأدوات المنزلية في مصر بأسطول شحن مركزي دائم الحركة",
    contactPerson: "مدير حركة الأسطول والنقل المركزي",
    contactTitle: "Central Transport & Fleet Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.9312,30.9089"
  },
  {
    id: "eg_titan_679",
    nameAr: "شركة أمان للتوزيع والخدمات الميدانية (شبكات التوزيع بالمحافظات)",
    nameEn: "Aman for E-Payments, Retail & Field Distribution Network (Raya Group)",
    sector: "transport",
    subSector: "توزيع مستلزمات الدفع الإلكتروني، تجارة السلع الاستهلاكية، وتزويد آلاف المتاجر والمنافذ بالجمهورية",
    city: "giza",
    governorate: "الجيزة",
    address: "المبنى الإداري لشركة راية، الحي المتميز، 6 أكتوبر، الجيزة",
    phone1: "0238271500",
    mobile: "01227744886",
    hotline: "16279",
    website: "https://www.aman.eg",
    latitude: 29.9789,
    longitude: 30.9512,
    fleetSize: 85,
    fleetType: "شاحنات جامبو توزيع بضائع، فانات توصيل سريعة، سيارات إشراف ودعم ميداني",
    fleetTires: "225/75R17.5 • 195/70R15C • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "شبكة التوزيع الميداني الاستهلاكي التابعة لمجموعة راية القابضة بأسطول شاحنات تجزئة سريع الانتشار",
    contactPerson: "مدير عام الخدمات اللوجستية والأسطول الميداني",
    contactTitle: "Field Fleet Operations & Logistics Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.9789,30.9512"
  },
  {
    id: "eg_titan_680",
    nameAr: "شركة البريد المصري لأسطول النقل والتوزيع المركزي السريع (1,400 سيارة توزيع)",
    nameEn: "Egypt Post - Central Express Mail & Parcel Distribution Mega Fleet",
    sector: "transport",
    subSector: "النقل والتوزيع القومي للطرود البريدية، التجارة الإلكترونية، والأموال، ونقل المطبوعات لآلاف المكاتب بالجمهورية",
    city: "cairo",
    governorate: "القاهرة",
    address: "ميدان العتبة، القاهرة / مراكز الفرز والتبادل بمطار القاهرة ومحطة مصر ورمسيس",
    phone1: "0223910000",
    mobile: "01114488335",
    hotline: "16280",
    website: "https://www.egyptpost.org",
    latitude: 30.0512,
    longitude: 31.2489,
    fleetSize: 260,
    fleetType: "شاحنات نقل طرود مؤمنة، شاحنات مصفحة لنقل الأموال، فانات نقل سريع إلكترونية، وأتوبيسات ركاب",
    fleetTires: "225/75R17.5 • 295/80R22.5 • 195/70R15C • 315/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "المؤسسة القومية الأعرق بالدولة المصرية التي تمتلك أضخم أسطول سيارات بريد وتوزيع طرود يغطي كل شبر في مصر",
    contactPerson: "رئيس قطاع الحركة والنقل والأسطول المركزي بالهيئة",
    contactTitle: "Head of Fleet Operations & Postal Transportation",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.0512,31.2489"
  },
  {
    id: "eg_titan_681",
    nameAr: "شركة فيدكس مصر (إيجيبت إكسبريس للشحن السريع واللوجستيات)",
    nameEn: "FedEx Express Egypt (Egypt Express - Mega Logistics & Courier Fleet)",
    sector: "transport",
    subSector: "الشحن السريع الدولي والداخلي، التخليص الجمركي، وحلول سلاسل الإمداد لقطاعات البنوك والتجارة",
    city: "cairo",
    governorate: "القاهرة",
    address: "مجمع خدمات البضائع، مطار القاهرة الدولي / فروع بكافة المحافظات",
    phone1: "0222681500",
    mobile: "01003311774",
    hotline: "16281",
    website: "https://www.fedex.com/eg",
    latitude: 30.1212,
    longitude: 31.3989,
    fleetSize: 110,
    fleetType: "شاحنات نقل طرود وبضائع مجهزة، فانات توزيع سريع حديثة، سيارات نقل مغلقة، وحافلات ركاب",
    fleetTires: "225/75R17.5 • 195/70R15C • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "عملاق الشحن السريع واللوجستيات الدولي بمصر مع أسطول سيارات شحن بري سريع",
    contactPerson: "مدير عام أسطول النقل والشحن البري",
    contactTitle: "Ground Operations & Fleet Senior Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.1212,31.3989"
  },
  {
    id: "eg_titan_682",
    nameAr: "شركة أرامكس مصر للشحن السريع والنقل البري بين المحافظات",
    nameEn: "Aramex Egypt - Domestic & International Express Freight Fleet",
    sector: "transport",
    subSector: "حلول الشحن السريع ونقل بضائع التجارة الإلكترونية وإدارة المستودعات الذكية بالسادس من أكتوبر",
    city: "giza",
    governorate: "الجيزة",
    address: "المنطقة الصناعية الثالثة، مدينة 6 أكتوبر، الجيزة",
    phone1: "0233388466",
    mobile: "01223311995",
    hotline: "16282",
    website: "https://www.aramex.com",
    latitude: 29.9345,
    longitude: 30.9212,
    fleetSize: 130,
    fleetType: "شاحنات نقل بضائع كبرى بين المحافظات، أساطيل فانات شحن سريع، وشاحنات مبردة للأدوية",
    fleetTires: "225/75R17.5 • 295/80R22.5 • 195/70R15C",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "رائد الشحن والتوصيل السريع لشركات التجارة الإلكترونية في مصر مع أسطول سيارات وشاحنات ضخم عالي الدقة",
    contactPerson: "مدير العمليات اللوجستية والأسطول الوطني",
    contactTitle: "National Fleet & Logistics Operations Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=29.9345,30.9212"
  },
  {
    id: "eg_titan_683",
    nameAr: "شركة دي إتش إل إكسبريس مصر (DHL Egypt - أساطيل الشحن البري والجوي)",
    nameEn: "DHL Express Egypt - Air & Ground Cargo Logistics Fleet",
    sector: "transport",
    subSector: "المركز اللوجستي الإقليمي لشحن الطرود والبضائع والمستندات الحساسة وسلاسل توريد الطيران",
    city: "cairo",
    governorate: "القاهرة",
    address: "قرية البضائع، مطار القاهرة الدولي / فروع المعادي ومدينة نصر والإسكندرية",
    phone1: "0222661200",
    mobile: "01118844229",
    hotline: "16283",
    website: "https://www.dhl.com.eg",
    latitude: 30.1189,
    longitude: 31.4045,
    fleetSize: 120,
    fleetType: "شاحنات صندوقية مجهزة بنظام تتبع متقدم، فانات كهربائية وهيدروجينية، شاحنات شحن مطارات، وحافلات",
    fleetTires: "225/75R17.5 • 295/80R22.5 • 195/75R16C",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الشركة العالمية الأولى في الشحن السريع واللوجستيات بمصر والشرق الأوسط بأسطول عالي الكفاءة",
    contactPerson: "مدير عام العمليات الأرضية والأسطول",
    contactTitle: "Ground Operations & Fleet Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.1189,31.4045"
  },
  {
    id: "eg_titan_684",
    nameAr: "شركة الشرق الأوسط لخدمات النقل البري والبضائع (METCO)",
    nameEn: "Middle East Transport & Contracting Co. (METCO)",
    sector: "transport",
    subSector: "نقل الحاويات والبضائع العامة والمهمات الثقيلة بين موانئ الإسكندرية ودمياط والسخنة والمحافظات",
    city: "alexandria",
    governorate: "الإسكندرية",
    address: "شارع المكس، القباري، الإسكندرية / فرع السويس وبورسعيد",
    phone1: "034441500",
    mobile: "01007722558",
    hotline: "16284",
    website: "https://www.metco-transport.com",
    latitude: 31.1712,
    longitude: 29.8689,
    fleetSize: 95,
    fleetType: "تريلات تريلا مرسيدس أكتروس لنقل الحاويات 20 و 40 قدم، لوابد نقل معدات ثقيلة، وشاحنات صيانة",
    fleetTires: "315/80R22.5 • 385/65R22.5 • 295/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "شركة نقل بري حاويات كبرى بالإسكندرية تخدم خطوط الملاحة العالمية",
    contactPerson: "مدير حركة الأسطول والنقل الخارجي",
    contactTitle: "Outbound Fleet Movement Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=31.1712,29.8689"
  },
  {
    id: "eg_titan_685",
    nameAr: "شركة الوطنية للنقل النهري والملاحة الداخلية (صنادل وشاحنات الحاويات)",
    nameEn: "National River Transport & Inland Navigation Co.",
    sector: "transport",
    subSector: "نقل خام الفحم والغلال والحديد والحاويات عبر نهر النيل والرياح البحيري بين الإسكندرية والقاهرة وأسوان",
    city: "cairo",
    governorate: "القاهرة",
    address: "كورنيش النيل، إمبابة، الجيزة / ميناء التبين النهري بحلوان",
    phone1: "0233112400",
    mobile: "01224488336",
    hotline: "16285",
    website: "https://www.nationalrivertransport.com",
    latitude: 30.0689,
    longitude: 31.2189,
    fleetSize: 90,
    fleetType: "شاحنات تريلات تفريغ موانئ نهرية، لوادر تفريغ صنادل، أوناش ساحات، وصنادل حاويات نيلية",
    fleetTires: "315/80R22.5 • 12.00R24 • 385/65R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الصرح الوطني الأكبر للنقل النهري متعدد الوسائط يربط موانئ البحر المتوسط بقلب القاهرة والصعيد",
    contactPerson: "مدير عام العمليات النهرية والأسطول البري المساعد",
    contactTitle: "River Operations & Land Support Fleet Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.0689,31.2189"
  },

  // 10. Pharma, Cold Distribution & Tourist/Field Operations (15)
  {
    id: "eg_titan_686",
    nameAr: "الشركة القابضة للمستحضرات الحيوية واللقاحات (فاكسيرا - العجوزة و6 أكتوبر)",
    nameEn: "VACSERA - Holding Co. for Biological Products & Vaccines",
    sector: "pharma",
    subSector: "أكبر صرح قومي في إفريقيا لإنتاج وتصنيع اللقاحات والأمصال البشرية والبيطرية ومستحضرات الدم",
    city: "giza",
    governorate: "الجيزة",
    address: "شارع البطل أحمد عبد العزيز، المهندسين - العجوزة / مجمع مصانع اللقاحات بمدينة 6 أكتوبر",
    phone1: "0237611111",
    mobile: "01115533119",
    hotline: "16286",
    website: "https://www.vacsera.com",
    latitude: 30.0545,
    longitude: 31.2089,
    fleetSize: 110,
    fleetType: "شاحنات برادات تبريد عميق (-80 و -20 مئوية) لنقل الأمصال واللقاحات، فانات توزيع معقمة، وأتوبيسات ركاب",
    fleetTires: "225/75R17.5 • 295/80R22.5 • 315/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الأمن الصحي القومي المصري الأول لإنتاج اللقاحات وتوزيعها محلياً وإفريقياً بأسطول برادات عالي الحساسية",
    contactPerson: "مدير عام اللوجستيات وسلسلة التبريد الدوائية",
    contactTitle: "Cold Chain Logistics & Fleet Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.0545,31.2089"
  },
  {
    id: "eg_titan_687",
    nameAr: "شركة أبيكس فارما للصناعات الدوائية ومستحضرات الرعاية (مدينة بدر الصناعية)",
    nameEn: "Apex Pharma - Pharmaceutical Manufacturing Mega Complex (Badr City)",
    sector: "pharma",
    subSector: "إنتاج الأدوية البشرية والمضادات الحيوية وأدوية القلب وضغط الدم وفق معايير منظمة الصحة العالمية",
    city: "cairo",
    governorate: "القاهرة",
    address: "المنطقة الصناعية الأولى، مدينة بدر، محافظة القاهرة",
    phone1: "0228609500",
    mobile: "01007744882",
    hotline: "16287",
    website: "https://www.apexpharma.com",
    latitude: 30.1389,
    longitude: 31.7345,
    fleetSize: 85,
    fleetType: "شاحنات نقل أدوية مبردة، فانات توزيع لصيدليات الجمهورية، وأسطول حافلات ورديات عمال ومهندسين",
    fleetTires: "225/75R17.5 • 295/80R22.5 • 8.25R16",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "إحدى أسرع شركات الأدوية نمواً في مصر بأسطول توزيع مبرد يغطي مستودعات وموزعي الأدوية",
    contactPerson: "مدير العمليات اللوجستية والأسطول",
    contactTitle: "Logistics Operations & Fleet Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.1389,31.7345"
  },
  {
    id: "eg_titan_688",
    nameAr: "شركة ماركيرل للصناعات الدوائية والمضادات الحيوية (مدينة العبور)",
    nameEn: "Marcyrl Pharmaceutical Industries (Obour City)",
    sector: "pharma",
    subSector: "تصنيع أدوية الفيروسات الكبدية، الأورام، الكبسولات، والأشربة المعقمة وتصديرها لإفريقيا وآسيا",
    city: "qalyubia",
    governorate: "القليوبية",
    address: "المنطقة الصناعية الأولى، مدينة العبور، محافظة القليوبية",
    phone1: "0244813500",
    mobile: "01228844337",
    hotline: "16288",
    website: "https://www.marcyrl.com",
    latitude: 30.2312,
    longitude: 31.4712,
    fleetSize: 80,
    fleetType: "شاحنات تبريد معتمدة من هيئة الدواء، فانات توزيع سريعة، وحافلات ركاب مكيفة لنقل العاملين",
    fleetTires: "225/75R17.5 • 295/80R22.5 • 7.50R16",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "صرح دوائي مصري رائد ساهم بفاعلية في مبادرة القضاء على فيروس سي بأسطول شحن وتوزيع نشط",
    contactPerson: "مدير حركة النقل والتوزيع الدوائي",
    contactTitle: "Pharma Transport & Distribution Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.2312,31.4712"
  },
  {
    id: "eg_titan_689",
    nameAr: "شركة أوركيديا للصناعات الدوائية ومستحضرات العيون (مدينة العبور)",
    nameEn: "Orchidia Pharmaceutical Industries - Ophthalmic Mega Plant (Obour)",
    sector: "pharma",
    subSector: "أكبر مصنع متخصص في قطرات ومراهم العيون المعقمة والمحاليل الطبية في الشرق الأوسط وإفريقيا",
    city: "qalyubia",
    governorate: "القليوبية",
    address: "المنطقة الصناعية الأولى، مدينة العبور، القليوبية",
    phone1: "0244814500",
    mobile: "01112288554",
    hotline: "16289",
    website: "https://www.orchidiaeu.com",
    latitude: 30.2345,
    longitude: 31.4689,
    fleetSize: 70,
    fleetType: "فانات وشاحنات تبريد مجهزة بأجهزة تسجيل حرارة دقيقة، سيارات شحن جوي، وأتوبيسات ركاب",
    fleetTires: "225/75R17.5 • 295/80R22.5 • 8.25R16",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "رائد قطرات ومستحضرات العيون في مصر بأسطول نقل مبرد معتمد من هيئات الدواء الدولية",
    contactPerson: "مدير اللوجستيات والشحن الجوي والتوزيع",
    contactTitle: "Logistics & Freight Operations Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.2345,31.4689"
  },
  {
    id: "eg_titan_690",
    nameAr: "شركة الدلتا جراند فارما لصناعة الأدوية الحديثة (العاشر من رمضان)",
    nameEn: "Delta Grand Pharma - Modern Pharmaceutical Mega Complex (10th of Ramadan)",
    sector: "pharma",
    subSector: "تصنيع الأدوية الحيوية، الفوارات، المحاليل الوريدية، والكبسولات الصلبة والرخوة",
    city: "sharqia",
    governorate: "الشرقية",
    address: "المنطقة الصناعية B1، مدينة العاشر من رمضان، الشرقية",
    phone1: "015415800",
    mobile: "01009933221",
    hotline: "16290",
    website: "https://www.deltagrandpharma.com",
    latitude: 30.2989,
    longitude: 31.7645,
    fleetSize: 75,
    fleetType: "شاحنات نقل محاليل وريدية معقمة، فانات أدوية مبردة، وحافلات نقل صيادلة ومهندسين",
    fleetTires: "295/80R22.5 • 225/75R17.5 • 8.25R16",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "مصنع أدوية عملاق بالعاشر من رمضان يمتلك خطوط إنتاج وتوزيع محاليل طبية ضخمة",
    contactPerson: "مدير الحركة والأسطول",
    contactTitle: "Transport & Fleet Supervisor",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.2989,31.7645"
  },
  {
    id: "eg_titan_691",
    nameAr: "شركة كوباد فارما للمستحضرات الصيدلية والطبية (مدينة العبور)",
    nameEn: "Copad Pharma - Pharmaceutical & Healthcare Industries (Obour)",
    sector: "pharma",
    subSector: "إنتاج الأدوية المسكنة، أدوية الجهاز الهضمي، والمكملات الغذائية الطبية المتطورة",
    city: "qalyubia",
    governorate: "القليوبية",
    address: "المنطقة الصناعية B، مدينة العبور، محافظة القليوبية",
    phone1: "0244815200",
    mobile: "01224411779",
    hotline: "16291",
    website: "https://www.copadpharma.com",
    latitude: 30.2289,
    longitude: 31.4745,
    fleetSize: 60,
    fleetType: "فانات شحن دوائي، سيارات نقل مغلقة، وأتوبيسات ركاب لنقل العاملين",
    fleetTires: "225/75R17.5 • 295/80R22.5 • 7.50R16",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "مجمع دوائي متطور بمدينة العبور بأسطول توزيع يخدم سلاسل الصيدليات الكبرى",
    contactPerson: "مدير إدارة الحركة",
    contactTitle: "Fleet Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.2289,31.4745"
  },
  {
    id: "eg_titan_692",
    nameAr: "شركة يوتوبيا للأدوية والمكملات الغذائية العلاجية (مدينة بدر الصناعية)",
    nameEn: "Utopia Pharmaceuticals & Clinical Nutrition (Badr City)",
    sector: "pharma",
    subSector: "صناعة أدوية العظام والمفاصل والمخ والأعصاب والمكملات الغذائية العلاجية",
    city: "cairo",
    governorate: "القاهرة",
    address: "المنطقة الصناعية الثالثة، مدينة بدر، محافظة القاهرة",
    phone1: "0228608800",
    mobile: "01117733442",
    hotline: "16292",
    website: "https://www.utopiapharm.com",
    latitude: 30.1312,
    longitude: 31.7245,
    fleetSize: 65,
    fleetType: "شاحنات توزيع دوائي مجهزة، فانات شحن، وأتوبيسات ركاب",
    fleetTires: "225/75R17.5 • 295/80R22.5 • 8.25R16",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "شركة دوائية متميزة بمدينة بدر تدير شبكة توزيع نشطة في جميع المحافظات",
    contactPerson: "مدير اللوجستيات",
    contactTitle: "Logistics Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.1312,31.7245"
  },
  {
    id: "eg_titan_693",
    nameAr: "شركة هاي فارم للأدوية والمستحضرات الطبية (مدينة العبور)",
    nameEn: "HiPharm for Specialized Pharmaceuticals (Obour City)",
    sector: "pharma",
    subSector: "تصنيع الأدوية البيولوجية، الفيتامينات، ومضادات الالتهاب وفق أحدث المعايير الأمريكية والأوروبية",
    city: "qalyubia",
    governorate: "القليوبية",
    address: "المنطقة الصناعية الأولى، مدينة العبور، محافظة القليوبية",
    phone1: "0244812800",
    mobile: "01002288116",
    hotline: "16293",
    website: "https://www.hipharm.com",
    latitude: 30.2245,
    longitude: 31.4612,
    fleetSize: 55,
    fleetType: "شاحنات تبريد دوائي، فانات شحن، وأتوبيسات ركاب",
    fleetTires: "225/75R17.5 • 295/80R22.5 • 7.50R16",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "مصنع أدوية رائد بمدينة العبور",
    contactPerson: "مدير الحركة والنقل",
    contactTitle: "Transport Director",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.2245,31.4612"
  },
  {
    id: "eg_titan_694",
    nameAr: "شركة الفتح للأدوية ومستحضرات التجميل العلاجية (FIPCO - برج العرب)",
    nameEn: "FIPCO - Fath Industrial Pharmaceutical Co. (Borg El Arab)",
    sector: "pharma",
    subSector: "إنتاج المستحضرات الدوائية والجلدية والمطهرات الطبية ومستحضرات الرعاية الصحية",
    city: "alexandria",
    governorate: "الإسكندرية",
    address: "المنطقة الصناعية الأولى، برج العرب الجديدة، الإسكندرية",
    phone1: "034591800",
    mobile: "01223399447",
    hotline: "16294",
    website: "https://www.fipco-egypt.com",
    latitude: 30.9189,
    longitude: 29.6289,
    fleetSize: 60,
    fleetType: "شاحنات نقل مبردة، فانات توزيع، وأتوبيسات نقل ورديات العاملين",
    fleetTires: "225/75R17.5 • 295/80R22.5 • 8.25R16",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "مجمع دوائي وعلاجي رائد في برج العرب يغذي صيدليات الإسكندرية ومطروح والبحيرة",
    contactPerson: "مدير العمليات والحركة",
    contactTitle: "Operations & Fleet Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.9189,29.6289"
  },
  {
    id: "eg_titan_695",
    nameAr: "شركة إيجيفار للأدوية والمضادات الحيوية الفموية (مدينة العبور)",
    nameEn: "Egyphar - Egyptian Pharmaceutical Industries (Obour City)",
    sector: "pharma",
    subSector: "إنتاج الأدوية الجنيسة عالية الجودة ومضادات الحيوية واسعة المجال والمراهم الطبية",
    city: "qalyubia",
    governorate: "القليوبية",
    address: "المنطقة الصناعية الثانية، مدينة العبور، محافظة القليوبية",
    phone1: "0244816100",
    mobile: "01115588334",
    hotline: "16295",
    website: "https://www.egyphar.com",
    latitude: 30.2389,
    longitude: 31.4789,
    fleetSize: 55,
    fleetType: "شاحنات نقل أدوية، فانات توزيع، وأتوبيسات ركاب",
    fleetTires: "225/75R17.5 • 295/80R22.5 • 7.50R16",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "صرح تصنيعي دوائي معتمد بالعبور",
    contactPerson: "مدير حركة النقل",
    contactTitle: "Transport Supervisor",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.2389,31.4789"
  },
  {
    id: "eg_titan_696",
    nameAr: "شركة النصر للكيماويات الدوائية وإنتاج المواد الفعالة (أبو زعبل - القليوبية)",
    nameEn: "El Nasr Co. for Intermediate Pharmaceuticals & Active Ingredients",
    sector: "pharma",
    subSector: "المصنع الوحيد في مصر والشرق الأوسط لتخليق المواد الفعالة (APIs) لصناعة المضادات الحيوية والمسكنات",
    city: "qalyubia",
    governorate: "القليوبية",
    address: "طريق أبو زعبل، الخانكة، محافظة القليوبية",
    phone1: "0246202100",
    mobile: "01004411885",
    hotline: "16296",
    website: "https://www.nasr-pharma.com",
    latitude: 30.2489,
    longitude: 31.3545,
    fleetSize: 75,
    fleetType: "صهاريج كحول ومذيبات، شاحنات نقل مواد فعالة معقمة، وأسطول حافلات ركاب",
    fleetTires: "315/80R22.5 • 295/80R22.5 • 11.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الصرح الاستراتيجي القومي لتأمين المواد الخام الدوائية الفعالة لمصانع الأدوية في مصر",
    contactPerson: "مدير عام النقل والمهمات",
    contactTitle: "General Transport & Logistics Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.2489,31.3545"
  },
  {
    id: "eg_titan_697",
    nameAr: "الشركة المصرية لتجارة وتوزيع الأدوية (أكبر أسطول توزيع حكومي مبرد - 600 سيارة)",
    nameEn: "Egyptian Drug Trading Co. - National Pharma Cold Distribution Fleet",
    sector: "pharma",
    subSector: "توزيع الأدوية والألبان المدعمة وأدوية الأورام لجميع المستشفيات الحكومية والتأمين الصحي والصيدليات بمصر",
    city: "cairo",
    governorate: "القاهرة",
    address: "شارع الجلاء، رمسيس، القاهرة / مستودعات مركزية بجميع عواصم المحافظات",
    phone1: "0225751200",
    mobile: "01228833221",
    hotline: "16297",
    website: "https://www.egyptiandrug.com.eg",
    latitude: 30.0589,
    longitude: 31.2445,
    fleetSize: 190,
    fleetType: "سيارات برادات مبردة حديثة لنقل الأدوية، شاحنات شحن مستودعات، وفانات توزيع طوارئ مستشفيات",
    fleetTires: "225/75R17.5 • 295/80R22.5 • 195/70R15C • 315/80R22.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "أضخم أسطول توزيع أدوية مبرد تابع للدولة المصرية يضمن وصول الدواء والأمصال الحيوية لكل مستشفى ووحدة صحية",
    contactPerson: "رئيس قطاع الحركة والنقل المركزي بالجمهورية",
    contactTitle: "Head of National Pharmaceutical Transport & Fleet",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.0589,31.2445"
  },
  {
    id: "eg_titan_698",
    nameAr: "شركة مصر للسياحة (أسطول 320 حافلة سياحية كبرى بين المحافظات)",
    nameEn: "Misr Travel - National Tourism Mega Coach Fleet (320 Coaches)",
    sector: "rental",
    subSector: "النقل السياحي الدولي، رحلات الحج والعمرة، تشغيل الحافلات السياحية الفاخرة لكبرى الفنادق والمزارات الأثرية",
    city: "cairo",
    governorate: "القاهرة",
    address: "ميدان التحرير، القاهرة / جراجات السياحة الكبرى بألماظة والغردقة وشرم الشيخ والأقصر وأسوان",
    phone1: "0223930010",
    mobile: "01115599882",
    hotline: "16298",
    website: "https://www.misrtravel.net",
    latitude: 30.0445,
    longitude: 31.2389,
    fleetSize: 180,
    fleetType: "حافلات سياحية مرسيدس ترافيلو وإم سي في VIP، حافلات هايجر، وسيارات ليموزين فاخرة",
    fleetTires: "295/80R22.5 • 315/80R22.5 • 225/75R17.5",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الشركة الوطنية القومية الأولى للسياحة في مصر (تأسست 1934) بأحدث أسطول حافلات سياحية عملاق يجوب كل محافظات مصر",
    contactPerson: "مدير عام النقل السياحي والأسطول المركزي",
    contactTitle: "General Director of Tourism Fleet & Transport",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.0445,31.2389"
  },
  {
    id: "eg_titan_699",
    nameAr: "مجموعة ترافكو للنقل السياحي والحافلات الكبرى (أسطول 750 حافلة سياحية)",
    nameEn: "Travco Group - Mega Tourism Coach & Fleet Operations (750 Coaches)",
    sector: "rental",
    subSector: "أكبر أسطول نقل سياحي خاص في الشرق الأوسط يخدم ملايين السائحين بشرم الشيخ والغردقة ومرسى علم والأقصر والقاهرة",
    city: "giza",
    governorate: "الجيزة",
    address: "مجمع ترافكو الإداري، الشيخ زايد، محافظة الجيزة / جراجات الغردقة وشرم الشيخ",
    phone1: "0238541000",
    mobile: "01007711332",
    hotline: "16299",
    website: "https://www.travcogroup.com",
    latitude: 30.0289,
    longitude: 30.9812,
    fleetSize: 240,
    fleetType: "حافلات مرسيدس بنز MCV 600 سياحية فاخرة، ميني باصات، ميكروباصات تويوتا هاي إيس، وسيارات ليموزين",
    fleetTires: "295/80R22.5 • 315/80R22.5 • 225/75R17.5 • 195R15C",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الإمبراطورية السياحية الأكبر بالشرق الأوسط مع أضخم أسطول حافلات سياحية خاصة وأعلى معدل استهلاك لإطارات الحافلات",
    contactPerson: "نائب الرئيس التنفيذي للأسطول والنقل السياحي",
    contactTitle: "Executive VP of Fleet Operations & Transport",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.0289,30.9812"
  },
  {
    id: "eg_titan_700",
    nameAr: "شركة خدمات البترول الجوية (PAS - أساطيل الدعم الأرضي والنقل الميداني للحقول)",
    nameEn: "Petroleum Air Services (PAS - Ground Support & Field Logistics Fleet)",
    sector: "transport",
    subSector: "النقل والدعم الأرضي لشركات البترول، عمليات المطارات البترولية، وأساطيل نقل أطقم منصات النفط والغاز",
    city: "cairo",
    governorate: "القاهرة",
    address: "طريق النصر، تقاطع شارع النزهة، مدينة نصر، القاهرة / مطار رأس شقير ومطار الجميل",
    phone1: "0224032100",
    mobile: "01229955118",
    hotline: "16300",
    website: "https://www.pas.com.eg",
    latitude: 30.0712,
    longitude: 31.3345,
    fleetSize: 95,
    fleetType: "شاحنات تموين طائرات هليكوبتر بالوقود، سيارات إطفاء مطارات، أوتوبيسات نقل ركاب مكيفة، وسيارات دفع رباعي",
    fleetTires: "315/80R22.5 • 295/80R22.5 • 245/75R16 • 12.00R20",
    priority: "A+",
    status: "new",
    verified: true,
    isTitan: true,
    notes: "الصرح الوطني المتخصص في خدمات النقل والدعم الجوي والأرضي لقطاع البترول المصري بأسطول دعم لوجستي فائق التجهيز",
    contactPerson: "مدير عام النقل والخدمات الأرضية المساندة",
    contactTitle: "Ground Support & Fleet Operations General Manager",
    createdAt: "2026-09-21",
    google_maps_url: "https://www.google.com/maps?q=30.0712,31.3345"
  }
];

module.exports = { wave6Part6 };
